### ISSUE TITLE
[BUG/ISSUE] tray icon results of found packages are being trimmed after scrolling them

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#1001]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
When using the current latest version (v1.7.1) it looks like the results of the `x packages found` from the tray icon are being changed and trimmed after scrolling of the original list for some reason.

Bug reproduction:
![Recording #2](https://user-images.githubusercontent.com/8223772/236068904-87e69b2e-3fd6-42fe-86cc-9d2828f05b7e.gif)

## To Reproduce
Steps to reproduce the behaviour:
1. Right click on the tray icon
2. Hover over the `x packages found`
3. Hover over the down error to scroll down some time
4. Close the results by loosing focus of the results
5. Do the same as step 2
6. The list that is shown now is the currently installed packages and is being trimmed.

## Expected behaviour
The same results/packages should be shown in this list after scrolling it.

**Comment by Mikey1993** [comment]
@marticliment 
This bug has not been fixed, the menu still opens differently after scrolling the list and opening it again like in the gif above..
Please reopen.

**Comment by marticliment** [comment]
Hello,

I haven't been able to recreate this issue anymore. 
Since Context menus are handled by Qt, this issue was likely a Qt but and has already been fixed by them.
