### ISSUE TITLE
[FEATURE REQUEST] download the next package in the queue during installation

### ISSUE THREAD

**Issue by reaseno** [marticliment/WingetUI#1012]
During the installation of a package with winget, the downloads of other updates in the queue are paused. Only after the installation is complete, the next package is loaded. However, if the downloads were done without waiting, it would speed up the whole update process.

**Comment by Mikey1993** [comment]
@marticliment , I think that he wants to do the installations async and download independent of the installation, but this is not possible as of now with winget.exe executable.
But maybe it's possible to invoke multiple winget.exe instances to install multiple packages at the same time?

@reaseno - You should open an issue with a request to make this possible via winget natively here:
https://github.com/microsoft/winget-cli/issues

**Comment by reaseno** [comment]
But this seems NOT RECOMMENDED 😅

**Comment by marticliment** [comment]
yes, because sometimes installers conflict with each other, especially those based on msi or windows installer.
