### ISSUE TITLE
关于程序更新的目录变更

### ISSUE THREAD

**Issue by acolasialiuliu** [marticliment/WingetUI#1017]
更新后程序位置都去了c盘，应该是winget的问题。顺便问问有啥解决办法。 不能保持原目录的话，是个大问题

**Comment by marticliment** [comment]
and please, try posting in English

**Comment by acolasialiuliu** [comment]
I used wingetui yesterday, updated some of my programs, and found that the updated program directory was changed to another disk. Inconsistent with the previous program directory. Is this a known issue and is there any fix

**Comment by marticliment** [comment]
Did you change the installation path throught he installer or you manually moved the binaries folder?

**Comment by acolasialiuliu** [comment]
no

**Comment by marticliment** [comment]
Which was the original paht and which is the new path?
