### ISSUE TITLE
Non ASCII characters are missing from error messages.

### ISSUE THREAD

**Issue by radimous** [marticliment/WingetUI#1018]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Non ASCII characters are missing from error messages.
 
Example: 
Access denied in czech shows this:
`Pstup k cest C:\ProgramData\chocolatey\lib\rufus\.chocolateyPending byl odepen.`
instead of this:
`Přístup k cestě C:\ProgramData\chocolatey\lib\rufus\.chocolateyPending byl odepřen.`

## To Reproduce
Steps to reproduce the behaviour:
1. Try to install some package with language that reports errors with non ASCII characters and fail

## Expected behaviour
Error message should have non ASCII characters

**Comment by marticliment** [comment]
Hello,

Does this issue still happen in the latest beta? (https://github.com/marticliment/WingetUI/releases/tag/2.0.0-beta3)

**Comment by radimous** [comment]
Still issue in 2.0.1
![image](https://github.com/marticliment/WingetUI/assets/56518192/952cb1a8-3cf5-4e4c-8b85-fce837494f59)
