### ISSUE TITLE
Inquiry about the path

### ISSUE THREAD

**Issue by magic1996** [marticliment/WingetUI#1019]
As title, I want to adjust the path when I setup a soft with winget or scoop, would it be solved?

**Comment by marticliment** [comment]
Scoop and chocolatey don't allow that, and winget does support this only sometimes, without a regular criteria.
You can do that by adding custom parameters when installing a package (assmung the package is available from winget):
![image](https://github.com/marticliment/WingetUI/assets/53119851/709a7df3-c906-4903-be72-d79ed0ff7fbc)
