### ISSUE TITLE
Sorting by version sorts alphabetically instead of numerically

### ISSUE THREAD

**Issue by Dr-Otter** [marticliment/WingetUI#1020]
Currently, when sorting by version it seems to sort alphabetically instead of numerically.

For example:
![image](https://github.com/marticliment/WingetUI/assets/61125419/db1873f1-e221-453e-8cfd-48af5f3c12e6)
 
It thinks 3.12 is less than 3.2

**Comment by marticliment** [comment]
duplicate of #844
