### ISSUE TITLE
[BUG/ISSUE] beta 2.0 version

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1024]
- [x] Non capitalized Winget package source appear as Android

- [x] Discovery section false packages

<img width="960" alt="Screenshot 2023-05-11 121658" src="https://github.com/marticliment/WingetUI/assets/73800734/a2ed2254-04cd-4d73-8028-e1141cca60ad">

- [x] Install section false package

<img width="959" alt="Screenshot 2023-05-11 121959" src="https://github.com/marticliment/WingetUI/assets/73800734/b872f5d2-bb9a-45e5-829d-83a7bedcd3b6">

- [x] uninstall/update info menu buttons show install instead of their correct names

<img width="554" alt="Screenshot 2023-05-11 122244" src="https://github.com/marticliment/WingetUI/assets/73800734/1542fea4-0f47-47da-ae7d-c9c4a2517093">

- [x] Chocolatey packages don't show up in the discovery section (but they do in the install section), even after clicking reset, reenabling and restarting WingetUI (I am using built in Chocolatey)

<img width="952" alt="Screenshot 2023-05-11 123555" src="https://github.com/marticliment/WingetUI/assets/73800734/803a4daa-d6a8-4e24-b29f-2c3723d7a348">

[log.txt](https://github.com/marticliment/WingetUI/files/11451127/log.txt)

[ChocolateyCachedPackages.txt](https://github.com/marticliment/WingetUI/files/11451223/ChocolateyCachedPackages.txt)

- [x] also, the Chocolatey packages in the uninstall section take some time to load without giving any sign to the user. I needed to refresh or wait for it to automatically refresh for them to be shown.

- [x] clicking refresh button on discovery section make WingetUI briefly unresponsive

- [x] same happens when clicking the list titles
<img width="941" alt="Screenshot 2023-05-19 225225" src="https://github.com/marticliment/WingetUI/assets/73800734/131e8a9e-e6e5-48d7-816b-43a9d5a399e1">

**Comment by marticliment** [comment]
> * Chocolatey package don't show up in the discovery section, even after clicking reset, reenabling and restarting WingetUI (I am using built in Chocolatey)

Coud you please post your log?

**Comment by ppvnf** [comment]
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.02599930763244629 to load all language files
🟢 checkQueue Thread started!
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🟡 Chocolatey has no source update procedure (yet)
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1683800111.045954]
{'wingetFound': False, 'scoopFound': False, 'chocoFound': False, 'sudoFound': True, 'wingetVersion': 'Unknown', 'scoopVersion': 'Unknown', 'chocoVersion': 'Unknown', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'WingetFound': True, 'WingetVersion': 'v1.4.10173\r', 'ChocolateyFound': True, 'ChocolateyVersion': '1.2.1\r', 'ScoopFound': True, 'ScoopVersion': 'v0.3.1 - Released at 2022-11-15'}
🔵 Reached main ui load milestone
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🔵 Starting Scoop search for available packages
🟢 Found valid, non-empty cache file for Winget!
🔵 Starting Chocolatey search for available packages
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 4448 result(s)
🟢 Found valid, non-empty cache file for Scoop!
🔵 Starting Scoop package caching
🟢 Found valid, non-empty cache file for Chocolatey!
🟢 Scoop search for installed packages finished with 3920 result(s)
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 2 result(s)
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for updates
🔵 Starting Scoop search for updates
🔵 Starting Chocolatey search for updates
🟢 Searching for string ""
Can't disconnect
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🟢 Chocolatey packages cached successfuly
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
Win32Mica Error: win32 version 19045 is not supported
50
🟢 Total packages: 39
🟢 Chocolatey search for installed packages finished with 26 result(s)
🟢 Total packages: 7630
🟢 Total packages: 8370
🟢 Searching for string ""
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 126 result(s)
🟡 Package VMware.WorkstationPro is ignored
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 89 result(s)
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 11 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 126
🟢 Scoop search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Winget packages cached successfuly
🟢 Scoop packages cached successfuly
Win32Mica Error: win32 version 19045 is not supported
50
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 26 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 89 result(s)
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 11 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 126
🟢 Starting scoop search...
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟢 Scoop bucket search finished
🟢 Starting scoop search...
Win32Mica Error: win32 version 19045 is not supported
50
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟢 Chocolatey search for installed packages finished with 26 result(s)
🟢 Searching for string ""
🟢 Scoop bucket search finished
🟢 Winget search for installed packages finished with 89 result(s)
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 11 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 126
Win32Mica Error: win32 version 19045 is not supported
50
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 26 result(s)
🟢 Searching for string ""
🟢 Starting scoop search...
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟢 Winget search for installed packages finished with 89 result(s)
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 11 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 126
🟢 Scoop bucket search finished
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
Win32Mica Error: win32 version 19045 is not supported
50
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟢 Chocolatey search for installed packages finished with 26 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 89 result(s)
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 11 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 126
🔵 Copying log to the clipboard...

**Comment by marticliment** [comment]
Can you please check the chocolatey cache file?

.wingetui -> cacheddata -> ChocolateyCachedPackages

**Comment by ppvnf** [comment]
> Can you please check the chocolatey cache file?
> 
> .wingetui -> cacheddata -> ChocolateyCachedPackages

[ChocolateyCachedPackages.txt](https://github.com/marticliment/WingetUI/files/11451223/ChocolateyCachedPackages.txt)

**Comment by ppvnf** [comment]
I have added this to the list:
also, the Chocolatey packages in the uninstall section take some time to load without giving any sign to the user

**Comment by marticliment** [comment]
@ppvnf, can you test the latest commit for the choco packages?

Thanks!

**Comment by ppvnf** [comment]
[ChocolateyCachedPackages.txt](https://github.com/marticliment/WingetUI/files/11466959/ChocolateyCachedPackages.txt)
Those packages were loaded, but no matter how long I wait it is still missing some.

Also: 
<img width="953" alt="Screenshot 2023-05-12 203555" src="https://github.com/marticliment/WingetUI/assets/73800734/d3153551-d3b4-4fd6-9413-d212ce15d269">

**Comment by ppvnf** [comment]
There is also chocolateypackages, and other duplicates for winget and scoop. I deleted [ChocolateyCachedPackages](https://github.com/marticliment/WingetUI/files/11466959/ChocolateyCachedPackages.txt) while keeping the lowercase, but it didn't seem to help

**Comment by ppvnf** [comment]
Also, clicking refresh button on discovery section make it briefly unresponsive

**Comment by marticliment** [comment]
> There is also chocolateypackages, and other duplicates for winget and scoop. I deleted [ChocolateyCachedPackages](https://github.com/marticliment/WingetUI/files/11466959/ChocolateyCachedPackages.txt) while keeping the lowercase, but it didn't seem to help. When closing/reopening it should continue to load packages, right?

the lowercase is the old one

**Comment by marticliment** [comment]
> Also, clicking refresh button on discovery section make it briefly unresponsive

I'm aware of it. Can you add it to the list please?

**Comment by marticliment** [comment]
> There is also chocolateypackages, and other duplicates for winget and scoop. I deleted [ChocolateyCachedPackages](https://github.com/marticliment/WingetUI/files/11466959/ChocolateyCachedPackages.txt) while keeping the lowercase, but it didn't seem to help. When closing/reopening it should continue to load packages, right?

I am also facing this issue. I am investigating it, but i'm afraid id the ssame issue as always, and we'll need to leave it a day or two to load all packages

**Comment by ppvnf** [comment]
> [ChocolateyCachedPackages.txt](https://github.com/marticliment/WingetUI/files/11466959/ChocolateyCachedPackages.txt) Those packages were loaded, but no matter how long I wait it is still missing some.
> 
> Also: <img alt="Screenshot 2023-05-12 203555" width="953" src="https://user-images.githubusercontent.com/73800734/238055990-d3153551-d3b4-4fd6-9413-d212ce15d269.png">

What about this one?

**Comment by marticliment** [comment]
That's because it has shown in lowercase

**Comment by marticliment** [comment]
In theory, winget packages should have a capitalized letter

**Comment by marticliment** [comment]
I'll try to improve the parsind

**Comment by ppvnf** [comment]
> I'll try to improve the parsing

Thanks, that seems to be fixed!

**Comment by ppvnf** [comment]
> * clicking refresh button on discovery section make WingetUI briefly unresponsive

same happens when clicking the list titles
<img width="941" alt="Screenshot 2023-05-19 225225" src="https://github.com/marticliment/WingetUI/assets/73800734/131e8a9e-e6e5-48d7-816b-43a9d5a399e1">

**Comment by marticliment** [comment]
> * [ ]  also, the Chocolatey packages in the uninstall section take some time to load without giving any sign to the user. I needed to refresh or wait for it to automatically refresh for them to be shown.
> *

Is this issue still happening?

**Comment by ppvnf** [comment]
> > * [ ]   also, the Chocolatey packages in the uninstall section take some time to load without giving any sign to the user. I needed to refresh or wait for it to automatically refresh for them to be shown.
> 
> Is this issue still happening?

I don't think so

**Comment by ppvnf** [comment]
I have moved the remaining task from this issue to https://github.com/marticliment/WingetUI/issues/1056, in order to not have 2 issues about the same thing
