### ISSUE TITLE
[BUG/ISSUE] refresh "Installed Packages" tab silently

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1028]
https://github.com/marticliment/WingetUI/issues/811
Can this refreshing be done silently (like verifying if anything was changed and only then reload the package list)? It is a little bit annoying to have all packages disappear when you briefly close WingetUI
Also, could this be done on the update section as well?

**Comment by Mikey1993** [comment]
@ppvnf I don't understand why to open a new issue instead of just commenting there?
Why the clutter?

**Comment by ppvnf** [comment]
You might be right. I wouldn't mind reopening that issue and closing this one.

**Comment by marticliment** [comment]
Honestly, I think it is better to leave this issue here, since this is an extension of a completed issue. There's not any problem or misbehaviour with the original feature, but rather the proposal of an extension.

**Comment by ppvnf** [comment]
Also, it's not that important, but could this be done similarly  on the update section as well?

**Comment by marticliment** [comment]
To be honest, I think that _showing_ to the user that packages disappear and reappear again just assures that the reloading function actually works. I get why you would want this on the installed packages section (for automatic reloads), but I wouldn't add it on manual reloads

**Comment by ppvnf** [comment]
> To be honest, I think that _showing_ to the user that packages disappear and reappear again just assures that the reloading function actually works. I get why you would want this on the installed packages section (for automatic reloads), but I wouldn't add it on manual reloads

I agree appearing/disappearing is important, what I meant when I said in the update section is the automatic update every x minutes, but it is really not a big deal

**Comment by ppvnf** [comment]
regarding the auto update, I have been thinking that if you reload manually it should reset the automatic timer so you don't get WingetUI trying to update the same package twice (maybe there is another issue for that)

**Comment by marticliment** [comment]
I don't think I understand what you mean

**Comment by ppvnf** [comment]
For example,  auto update every 30m check happened at 20:15, but you click the manual refresh update button at 20:25, so the next automatic update check will happen at 20:55 instead of 20:45. Does it make sense?

**Comment by marticliment** [comment]
On the Installed Section packages are not reloaded on a timer, but rather when WingetUI is shown.

On the Updates tab, this is already done

**Comment by ppvnf** [comment]
I guess this was fixed, I just installed WingetUI after a long time away from Windows and it looks great!
