### ISSUE TITLE
[BUG/ISSUE] Defender Blocked Install of 2.0: Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by mbiracree** [marticliment/WingetUI#1029]
After installing the 2.0 beta on Windows 11, Windows Defender blocked the program showing it's infected with Trojan:Win32/Wacatac.H!ml

## To Reproduce
Steps to reproduce the behaviour:
1. Go to Github, download 2.0 Beta Installer
2. Run from Elevated Command Prompt

## Screenshots
![image](https://github.com/marticliment/WingetUI/assets/78425295/03c7747b-a53a-4b5b-a3d7-95269b59cc9e)

## The Log

Can't get log, program won't start.

**Comment by marticliment** [comment]
yes, I got this prompt also

**Comment by marticliment** [comment]
please report is as a false positive on ms defender.
Thanks.

Il will contact Microsoft so they can white-list WingetUI

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/113affab-77c2-4339-adf6-0c818158c00b)

**Comment by Skylancer187** [comment]
Defender also catches the beta installer as a trojan. This application may be used frequently to install some of the shader files in the repos. I read an article that there are some chatgpt clones in the repos that contain malware, and Wingetui might have been the file during Defender investigations as the source application that installs the malware.

As others have suggested, the application developer may need to report this to Microsoft. Until then, anyone downloading the application on Win10/11 with Defender active will continue to be alerted it's a virus.

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide#part-4-submit-a-file-for-analysis

![2023-05-13 07_00_14-Window](https://github.com/marticliment/WingetUI/assets/8769907/48a09638-6bd8-44f3-b674-b8bcd3d73645)

**Comment by marticliment** [comment]
I have submitted again the installer. The wingetui.exe executable shouldn't be banned anymore

**Comment by marticliment** [comment]
in theory wingetui shouldn't be banned anymore

**Comment by marticliment** [comment]
I have submitted false-positive reports

**Comment by marticliment** [comment]
> Once it's being "cleaned" - please update and I'll reinstall.

WingetUI does not have virus, but it has been built with the same toolkit some virus are built (python/pyinstaller, you can google it). Then, it sometimes gets false-positive flagged.

I will update you when I have further details about the reports
