### ISSUE TITLE
[FEATURE REQUEST] Install / Update MS Store Apps

### ISSUE THREAD

**Issue by MajorTomDE** [marticliment/WingetUI#1032]
I‘m not sure if it’s technical possible? It would be great to install and update apps from MS Store.

For me, update is more important than install to have only one tool to update all my apps.

**Comment by marticliment** [comment]
Maybe yes, this could be done

**Comment by candrapersada** [comment]
how to Upgrade Microsoft Store apps with `WingetUI`?
