### ISSUE TITLE
[BUG/ISSUE] (2.0 Beta 2) Command line appears during automatic update

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1034]
I was watching a YT video when this appeared
<img width="960" alt="Screenshot 2023-05-16 221032" src="https://github.com/marticliment/WingetUI/assets/73800734/d7714a97-b88d-4954-a262-33257bc6abac">

**Comment by marticliment** [comment]
Whoops...

**Comment by marticliment** [comment]
The latest commit should have this fixed now!
