### ISSUE TITLE
[FEATURE REQUEST]choosable Installation Location/path

### ISSUE THREAD

**Issue by Nawi915** [marticliment/WingetUI#1036]
It would be nice to be able to specify a Location for the package (C:\Programms\package name for example)
Like in Winget itself it would be used as follows:

winget install --name="WingetUi" --exact --location "C:\RandomFolderName\Wingetui

- Default path in settings 
- "Install at" as a option in the drop-down of the package manager itself

For convince with a Folder Browse Dialog if that's hard to implement just use a text box and plain text.

**Comment by marticliment** [comment]
For the moment, you can pass the arguments `--location "C:\RandomFolderName\Wingetui'` through the "custom command-line parameters" textbox on the info window.

However, I am aware this is not ideal, and once winget gets this feature improved I will implement a better way to do that.

**Comment by Nawi915** [comment]
Thank you very much for the fast answers and awesome support!

Keep up the good work dude as I said I discovered it some time ago and it's
an essential easy to use and versatile Programm for me now.

Best regards Jüegen

Martí Climent ***@***.***> schrieb am Mi., 17. Mai 2023,
22:54:
