### ISSUE TITLE
[SCOOP] (Enter your description here) remove permanent data not working in WingetUI 2.0.0 beta 2 

### ISSUE THREAD

**Issue by candrapersada** [marticliment/WingetUI#1040]
![gambar](https://github.com/marticliment/WingetUI/assets/36833664/6ba22d11-e72b-4677-8f1e-0acd19232b94)

**Comment by marticliment** [comment]
Hello,

Does the latest beta also have this issue? https://github.com/marticliment/WingetUI/releases/tag/2.0.0-beta3
