### ISSUE TITLE
[BUG/ISSUE] Cannot find the entry

### ISSUE THREAD

**Issue by Dragon1573** [marticliment/WingetUI#1044]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug

When launching WingetUI with Windows startup, an error with "Cannot find the entry" may pop up.

## To Reproduce

1. Download and install WingetUI `v2.0.0-beta2`
2. Go to "WingetUI Settings", unfold "Startup options" and check "Autostart WingetUI in the notification area"
   > ![image](https://github.com/marticliment/WingetUI/assets/49941141/fb353f6c-8ae1-4162-9d68-fb1350295bec)
   > ![image](https://github.com/marticliment/WingetUI/assets/49941141/73790700-0a95-440b-acc8-7b4d5215d9c2)
3. Restart the system.
4. Errors will occur with certain probabilities.

## Expected behaviour

No errors with WingetUI.

## Screenshots

![Snipaste_2023-05-21_11-12-42](https://github.com/marticliment/WingetUI/assets/49941141/59791529-ba6d-41c6-94ef-2a09a277843b)

## The Log

**Lost**. Will be attached as soon as possible.

</details>

## Additional context

Only occurs when WingetUI autostart with the operating system. Unable to reproduce with restart WingetUI only.

- Microsoft Windows 11 Professional 22H2 (22621.1702)
- WingetUI v2.0.0-beta2
- Gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)
- Winget v1.4.10173
- Scoop & Chocolatey are disabled.

**Comment by marticliment** [comment]
Hello,

Could you please try:
1. Installing WingetUI on the C: drive (or on your main volume)
2. Running WingetUI from the command-line with the `--daemon` parameter

**Comment by Dragon1573** [comment]
## Reproduce steps

1. Uninstall WingetUI from disk.
2. Reinstall WingetUI v2.0.0-beta2 to `$HOME/AppData/Local/Programs/WingetUI`, also create shortcuts in startup menu.
3. Launch WingetUI in `pwsh.exe` using following command
   ```powershell
   $HOME\AppData\Local\Programs\WingetUI\wingetui.exe --daemon
   ```

## Status

It seems that nothing happened.

**Comment by marticliment** [comment]
Try uninstalling and then manually deleting all the contents under $HOME/AppData/Local/Programs/WingetUI

**Comment by Dragon1573** [comment]
Manually uninstall and reinstall WingetUI does solve the problem. No errors occur after the operation.

Thanks! :heart:
