### ISSUE TITLE
Untranslated text strings in v2.0.0 beta 2

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#1046]
Version 2.0.0 beta 2

Upon first run the notification "Packages are being loaded for the first time..." is being displayed.
This string is not translated in Dutch language and does not exist on Tolgee.

![image](https://github.com/marticliment/WingetUI/assets/10008599/270afce4-1b41-4ffa-bbbf-a242429bca16)

**Comment by Stephan-P** [comment]
Let me add to this that more translations are missing.
- Set GUI language to Dutch (or another non-English language)
- In all three tabs, move the mouse over the icon bar
- Notice that quite a few of the mouse over help texts are shown in English

**Comment by Stephan-P** [comment]
In Disvover packages:
- Install selected packages ...
- Skip hash check...
- Do interactive install...

In tab Software updates:
- The same three icons

In tab Installed packages:
- Uninstall selected...
- Do interactive ...
- Select all packages 
- Clear package selection

All display a mouse over text in English language instead of the GUI language.

**Comment by Stephan-P** [comment]
More untranslated in Settings:
- Reset Chocolatey cache
- Reset Scoop cache
- Reset Winget cache

Possibly these are stray pointers

**Comment by marticliment** [comment]
Yes, I am aware of missing strings.

I am going to publish them all on Tolgee soon

**Comment by Stephan-P** [comment]
Please leave a message here so that i can take care of these translations in a timely manner before the release. Tolgee still does not over a notification feature.

**Comment by marticliment** [comment]
Added!
