### ISSUE TITLE
[BUG/ISSUE] Version 2.0 Final

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1056]
**Remaining:**

- [ ] #1194

still seems to happen (I reported it in https://github.com/marticliment/WingetUI/issues/1024)
[log.txt](https://github.com/marticliment/WingetUI/files/11771848/log.txt)

fixed after 2.0.1:

 <details>

- [x] besides their labels being untranslated, the reset buttons should IMO trigger an alert so the user has some feedback

<img width="157" alt="Screenshot 2023-05-11 122037" src="https://github.com/marticliment/WingetUI/assets/73800734/854537f1-0a0d-4616-8c00-c763ad74c7bb">

- [x] on the uninstall section I think the source should be only Winget (maybe on update section as well)

<img width="100" alt="Screenshot 2023-05-27 180142" src="https://github.com/marticliment/WingetUI/assets/73800734/1fe63053-c2cc-48d3-8330-0ed869759bb4">

- [x] The cancel update button seems to be doing nothing

[cancel signal not working winget.txt](https://github.com/marticliment/WingetUI/files/11771860/cancel.signal.not.working.winget.txt)

- [x]  tooltip color mismatch

<img width="958" alt="Screenshot 2023-06-16 171216" src="https://github.com/marticliment/WingetUI/assets/73800734/e34e6a9e-67bc-4fa9-b8e4-ca56c8152dca">

</details>

fixed in 2.0 final release:
 <details>

- [x] a line that looks like a horizontal scrolling bar appears after I open and close the info menu
<img width="960" alt="Screenshot 2023-05-27 182643" src="https://github.com/marticliment/WingetUI/assets/73800734/f46bb1b5-3eca-449c-ba28-543017041f93">

- [x] <s>I am unable to click OK on</s> the last element of the install queue is buggy

<img width="960" alt="Screenshot 2023-05-25 124108" src="https://github.com/marticliment/WingetUI/assets/73800734/178b2d93-70b2-4fed-91b1-7476c48285d0">

</details>

fixed during beta 1: https://github.com/marticliment/WingetUI/issues/1024

fixed during beta 2:
 <details>

- [x] MS is incorrectly identified on the install section (not sure about the upgrade section)

<img width="960" alt="Screenshot 2023-05-25 124303" src="https://github.com/marticliment/WingetUI/assets/73800734/032a7d71-28be-4751-8688-c859c7e374e4">

- [x] I think I should not see messages of success with my configuration:

<img width="710" alt="Screenshot 2023-05-25 123706" src="https://github.com/marticliment/WingetUI/assets/73800734/1f75e28c-dc48-44d0-8ff3-0794d1172b1c">

- [x]  Some pip updates needed to be manually elevated:

<img width="563" alt="Screenshot 2023-05-25 123950" src="https://github.com/marticliment/WingetUI/assets/73800734/a4b1d6d5-c32b-4841-9f57-c70637bb7a2d">

- [x] Manifest's link for Chocolatey packages(not sure about Winget and Scoop) that have hyfens is broken:

<img width="464" alt="Screenshot 2023-05-25 124557" src="https://github.com/marticliment/WingetUI/assets/73800734/fb7fc931-3102-457b-a9a4-53e0fe1b9fa4">

- [x] Updating the Chocolatey package Anki from 2.1.63 to 2.1.64 required manual elevation 
</details>

**Comment by marticliment** [comment]
> * MS is incorrectly identified on the install section (not sure about the upgrade section)

This is actually intended. At the end they work as Winget packages, so I preferred to leave them as Winget

**Comment by marticliment** [comment]
> * [ ]  I think I should not see messages of success with my configuration:

Have you tried resetting WingetUI after changing this settings. Revising the code, a restat might be required in order to get this function actually working

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/e7aef7e8-0278-4e39-8b04-40332cb6dcf6)
I will do the same as I did with scoop, which is to show `Manager: origin`

**Comment by marticliment** [comment]
I will try to reload the variables in a live environment.

P.D. Pip packages should autoelevate now

**Comment by ppvnf** [comment]
on the install section I think the source should be only Winget

**Comment by ppvnf** [comment]
a line that looks like a horizontal scrolling bar appears after I open and close the info menu
<img width="960" alt="Screenshot 2023-05-27 182643" src="https://github.com/marticliment/WingetUI/assets/73800734/f46bb1b5-3eca-449c-ba28-543017041f93">

**Comment by ppvnf** [comment]
> * I am unable to click OK on the last element of the install queue

I think this has been fixed, however the queue is behaving strangely in this latest beta sometimes:
<img width="960" alt="Screenshot 2023-05-27 225913" src="https://github.com/marticliment/WingetUI/assets/73800734/0951fc43-3c82-44ae-87e1-c7e5d5e7a5dc">
<img width="958" alt="Screenshot 2023-05-27 225902" src="https://github.com/marticliment/WingetUI/assets/73800734/3d8eaecd-a749-40bf-ad46-ddb06d118f7c">

**Comment by marticliment** [comment]
> > * I am unable to click OK on the last element of the install queue
> 
> I think this has been fixed, however the queue is behaving strangely in this latest beta sometimes: <img alt="Screenshot 2023-05-27 225913" width="960" src="https://user-images.githubusercontent.com/73800734/241432031-0951fc43-3c82-44ae-87e1-c7e5d5e7a5dc.png"> <img alt="Screenshot 2023-05-27 225902" width="958" src="https://user-images.githubusercontent.com/73800734/241432033-3d8eaecd-a749-40bf-ad46-ddb06d118f7c.png">

Yes, I am aware that the last element gets bugged. If you actually resize the window, you will see the widget's progressbar actually update, but for whatever the reason it does not update itself as the rest of the UI does

**Comment by ppvnf** [comment]
I am gonna try updating this issue. 

I have added:

> * Chocolatey packages in the uninstall section take some time to load without giving any sign to the user. I needed to refresh or wait for it to automatically refresh for them to be shown.

still seems to happen (I reported it in https://github.com/marticliment/WingetUI/issues/1024)
[log.txt](https://github.com/marticliment/WingetUI/files/11771848/log.txt)

> *  The cancel update button seems to be doing nothing

[cancel signal not working winget.txt](https://github.com/marticliment/WingetUI/files/11771860/cancel.signal.not.working.winget.txt)

> *  tooltip color mismatch

<img width="958" alt="Screenshot 2023-06-16 171216" src="https://github.com/marticliment/WingetUI/assets/73800734/e34e6a9e-67bc-4fa9-b8e4-ca56c8152dca">

**Comment by ppvnf** [comment]
I have updated this issue: I have added 3 more bugs, 2 bugs from latest beta remained and 2 were fixed

**Comment by marticliment** [comment]
> **New bugs in 2.0 final:**
> 
> **Bugs from 2.0 beta 3 that remained:**
> 
> * [ ]  on the uninstall section I think the source should be only Winget (maybe on update section as well)
> 
> <img alt="Screenshot 2023-05-27 180142" width="100" src="https://user-images.githubusercontent.com/73800734/241408774-1fe63053-c2cc-48d3-8330-0ed869759bb4.png">
> * [ ]  besides their labels being untranslated the reset buttons should IMO trigger an alert so the user has some feedback
> 
> <img alt="Screenshot 2023-05-11 122037" width="157" src="https://user-images.githubusercontent.com/73800734/237654761-854537f1-0a0d-4616-8c00-c763ad74c7bb.png">
> fixed in 2.0 final release:
> 
> fixed during beta 1: #1024
> 
> fixed during beta 2:

Scoop packages are also separated. This aims for a near future where winget sources will be able to be handled in the same way as scoop buckets are

**Comment by marticliment** [comment]
> * [ ]  besides their labels being untranslated, the reset buttons should IMO trigger an alert so the user has some feedback

Small, android-like notifications will be shown
![image](https://github.com/marticliment/WingetUI/assets/53119851/f4f11a0b-9093-4fb6-af05-da8eb61da1c2)

**Comment by ppvnf** [comment]
> * Chocolatey packages in the uninstall section take some time to load without giving any sign to the user. I had to manually refresh or wait for it to automatically refresh for them to be shown.

Nice. Only this remains unfixed I guess

**Comment by marticliment** [comment]
I have migrated the remaining issue
