### ISSUE TITLE
[FEATURE REQUEST] Use the same menu for discover and update/installed tabs

### ISSUE THREAD

**Issue by ThePhaseless** [marticliment/WingetUI#1057]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

If packet is installed, these's no need or even shoudn't be an option to install package if searching in discover tab. 
Same goes for packet details.

## Describe the solution you'd like

Instead right click would open the same menu as in other tabs. (Also reinstall button could be a good idea)
Same goes for packet details.

**Comment by marticliment** [comment]
> Also reinstall button could be a good idea

That's why it is listed on the install section

**Comment by marticliment** [comment]
Hello,

I am afraid this will not be part of WingetUI in the near future.

I am sorry
