### ISSUE TITLE
[FEATURE REQUEST] List all packages toggle

### ISSUE THREAD

**Issue by JAK1047** [marticliment/WingetUI#1062]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
After upgrading from Beta 2 to Beta 3 the Discover Tab is blank. The packages however are still cached it appears the table is just not built.

![image](https://github.com/marticliment/WingetUI/assets/29665481/f5e4d336-0125-4392-8cd5-b12a314d9305)

The installed packages tab does however still load correctly.

## The Log

<details>

```
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0015072822570800781 to load all language files
🟢 checkQueue Thread started!
🔵 Starting main application...
🔵 Looking for alive instances...
🔵 Language file up-to-date
🟡 Found lock file(s), reactivating...
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1685200792.3566115]
🔵 Reached main ui load milestone
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', 'WingetFound': True, 'WingetVersion': 'v1.4.10173\r', 'ScoopFound': True, 'ScoopVersion': 'v0.3.1 - Released at 2022-11-15', 'ChocolateyFound': True, 'ChocolateyVersion': '1.4.0\r'}
🔵 Is Dark
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🔵 Starting Scoop search for available packages
🟢 Found valid, non-empty cache file for Winget!
🔵 Starting Chocolatey search for available packages
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 4611 result(s)
🟢 Found valid, non-empty cache file for Scoop!
🔵 Starting Scoop package caching
🟢 Scoop search for installed packages finished with 3065 result(s)
🟢 Found valid, non-empty cache file for Chocolatey!
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 8854 result(s)
Can't disconnect
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for updates
🔵 Starting Scoop search for updates
🔵 Starting Chocolatey search for updates
🟢 Searching for string ""
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Total packages: 9033
🟢 Total packages: 12175
🟢 Winget search for updates finished with 0 result(s)
🟢 Total packages: 16530
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 65 result(s)
🟢 Searching for string ""
🟢 Scoop search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Scoop search for installed packages finished with 3 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 69
🟢 Winget packages cached successfuly
🟢 Scoop packages cached successfuly
🟢 Chocolatey packages cached successfuly
🔵 Starting Winget search for installed packages
🔵 Starting Scoop search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 1 result(s)
🟢 Searching for string ""
🟢 Scoop search for installed packages finished with 3 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 65 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 69
🔵 Starting Winget search for available packages
🔵 Starting Scoop search for available packages
🔵 Starting Chocolatey search for available packages
🟢 Found valid, non-empty cache file for Winget!
🟢 Found valid, non-empty cache file for Scoop!
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 4611 result(s)
🔵 Starting Scoop package caching
🟢 Scoop search for installed packages finished with 3065 result(s)
🟢 Found valid, non-empty cache file for Chocolatey!
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 9268 result(s)
🟢 Total packages: 16944
🔵 Starting Winget search for available packages
🔵 Starting Scoop search for available packages
🟢 Found valid, non-empty cache file for Winget!
🔵 Starting Chocolatey search for available packages
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 4611 result(s)
🟢 Found valid, non-empty cache file for Scoop!
🔵 Starting Scoop package caching
🟢 Scoop search for installed packages finished with 3065 result(s)
🟢 Found valid, non-empty cache file for Chocolatey!
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 9268 result(s)
🟢 Total packages: 16944
🟢 Winget packages cached successfuly
🟢 Winget packages cached successfuly
🟢 Scoop packages cached successfuly
🟢 Scoop packages cached successfuly
🟢 Chocolatey packages cached successfuly
🟢 Chocolatey packages cached successfuly
🔵 Copying log to the clipboard...

```

</details>

**Comment by marticliment** [comment]
yes, this is done in purpose.

try searching for packages to get results.

**Comment by marticliment** [comment]
at the end of the day, users won't scroll across a list with more than 17000 packages, they will just search the query they want. And since showing all of them lagged the interface, I decided to remove all package listing.

now users are required to type at least three characters in order to get results

**Comment by marticliment** [comment]
at the end of the day, users won't scroll across a list with more than 17000 packages, they will just search the query they want. And since showing all of them lagged the interface, I decided to remove all package listing.

now users are required to type at least three characters in order to get results

**Comment by ppvnf** [comment]
maybe this limit should be reduced to 2 as there are a few packages such as `np` on pip and npm that are 2 characters long

**Comment by JAK1047** [comment]
Is there a way to toggle that change or an option to display all\export a list? In our scenario maintaining images for VDI it was helpful to have the entire list to visually compare to what's installed on our golden image with Winget. Just 4k+ items so not difficult to scroll real quick. I can just make a script to dump that with Winget instead myself if there's no planned alternative for the functionality.

**Comment by JAK1047** [comment]
> maybe this limit should be reduced to 2 as there are a few packages such as `np` on pip and npm that are 2 characters long

I will say one of the apps I was just asked for was the Powershell Az module and had to guess if it was "Az Powershell", "Az.Powershell", or "AzPowershell". Got it on my third attempt so not a huge deal I suppose.

**Comment by marticliment** [comment]
Hello,

This feature is planned to be removed, but there is discussion about it. Chocolatey has deprecated all-package listing, and other package managers that are going to be added don't support this feature either (dotnet tool, nuget, etc.), and the operation of loading and processing so much packages is very resource-intensive.

For the moment, all package managers have been migrated from the PackageManager to the DynamicPackageManager class, enabling dynamic queries and removing all-listing support. While all-listing enabled faster searching, the resource usage when caching packages was notorious. Furthermore, packages wouldn't get updated regularly.

Moreover, I have in mind some kind of Welcome interface, showing some recommended packages and other useful shortcuts, an idea similar to the one behind the new Settings App homepage on Windows 11.

What do you think about this? Should I re-add all-listing packages for winget and scoop?

**Comment by JAK1047** [comment]
I guess Winget is a bit of the odd man out here since it only has 4k or so packages. Honestly at this point if everything else is removing the ability to do a full list it wouldn't make much sense not to just keep everything the same. It was nice to have but we can definitely just run list off Winget CLI ourselves and dump to a text file without much issue when the situation calls for it.

Side note excited to see Nuget added!

**Comment by neoOpus** [comment]
It would have been better to make this optional and enabled by default. However, those who prefer can simply toggle it in settings to be able to view all packages. This can be a pleasant way to discover new things by scrolling and unexpectedly coming across certain packages and reading their descriptions. We often don't know what to search for, and occasionally, we stumble upon something very useful in this manner, and some devs don't pick a representative name for their software packages...
