### ISSUE TITLE
[BUG/ISSUE] Unable to see package info of certain packages

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1063]
Maybe using an API it would be possible. On terminal it also fails
https://pypi.org/project/deluge/
<img width="535" alt="Screenshot 2023-05-27 182244" src="https://github.com/marticliment/WingetUI/assets/73800734/c4eb2ca4-9671-4a40-b16f-0b1ddb566ec0">
<img width="757" alt="Screenshot 2023-05-27 182152" src="https://github.com/marticliment/WingetUI/assets/73800734/82d675cb-5048-47ec-8b0f-473df920e209">

**Comment by ppvnf** [comment]
this one https://warehouse.pypa.io/api-reference/json.html?

**Comment by marticliment** [comment]
This api could provide better information for packages, thanks!
