### ISSUE TITLE
[BUG/ISSUE] (App not opening)

### ISSUE THREAD

**Issue by Jakeverse** [marticliment/WingetUI#1067]
App is not opening correctly, showing a line instead of app window. 

I don't know what causing this issue. Maybe lack of depenencies or it's bug from itself windows (windows 11 22000.9)

Please help me with this issue. 

Preview: https://drive.google.com/file/d/1Nv_UWa1T21SKZIy0tp0XSB3e6eipiNIb/view?usp=sharing

**Comment by marticliment** [comment]
Please try running the latest beta: https://github.com/marticliment/WingetUI/releases/tag/2.0.0-beta3

**Comment by Jakeverse** [comment]
Tried 2.0.0-beta, same issue. I think it's a bug from windows, not from your apps. Some other uwp apps open like this. Thanks for your time.

Another preview: https://drive.google.com/file/d/1W24mZi3gd22EpTacqt_zpll3gYPvtozB/view?usp=sharing

**Comment by marticliment** [comment]
The best I can say is to run a Health Check (https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image) on your pc; but if other UWP apps also fail, the issue is most likely to be your system
