### ISSUE TITLE
[ISSUE] Non-resizable columns

### ISSUE THREAD

**Issue by neslekkim** [marticliment/WingetUI#1069]
Columns are not resizable, and the text does not fill the column:
![image](https://github.com/marticliment/WingetUI/assets/281342/80af049e-d7b9-4bc5-bfe6-1597c5248656)
Would be nice to see a bit more of the Package name here.

**Comment by marticliment** [comment]
The missing text is an issue related with Winget, please see the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions)
