### ISSUE TITLE
[FEATURE REQUEST] location of local installation?

### ISSUE THREAD

**Issue by neslekkim** [marticliment/WingetUI#1071]
I would like to see where I have an certain package/app installed:
![image](https://github.com/marticliment/WingetUI/assets/281342/64789eb4-ca93-482e-a256-a43e76104662)
Only think I can get here is package detalis, which tells me info about the new package, not where I have the current one.

I just updates this package, tesseract:
![image](https://github.com/marticliment/WingetUI/assets/281342/3ecdc33d-0fdc-4496-9933-1003e84d15fc)
I used voidtools - everything to find it on disc first, and found it under programfilesx86, after updating, it was still located there, but I got the new one under programfiles, so now I have a duplicate of this program.
Not same issue, but if one install lot of updates, you can end up with duplicates like this, withouth knowing it?

**Comment by neslekkim** [comment]
I kinda like the idea of using winget for the packages that I install through winget, but winget takes over the whole computer, and wants to install everything, that I don't like (that is a winget problem, not wingetui problem ofcourse), I wonder why they did it like that, would be better that I could over time, migrate the apps I have installed separately over to winget (uninstall from appwiz.cpl, and reinstall using winget).
If it was possible to have a list of packages that winget should not touch, it would be better I think, and avoid this type of issue.

**Comment by marticliment** [comment]
You can ignore updates, both from the Updates tab and from the Installed Software Section.

Also, you can use other package managers with WingetUI, such as Chocolatey or Scoop, which tend to give less issues when upgrading packages

**Comment by Wosamarak** [comment]
I came here to report this as an error.
After installation of WingetUI I see three multiple lines of the same program beeing installed. Trying to install the update, one of the lines installs the update, while the other lines just report errors, that this program can't be updated.

So it would be really helpful to see, where the other versions should be located, to resolve this issue.

**Comment by marticliment** [comment]
could you please attach the actual output you are getting?

Thanks!

**Comment by Wosamarak** [comment]
Here two examples:
First a DotNet Runtime upgrade:
![2023-06-03 12_46_45-WingetUI](https://github.com/marticliment/WingetUI/assets/82721821/e4e12694-c751-4419-ab80-fb203e363bfd)
![2023-06-03 12_45_52-WingetUI](https://github.com/marticliment/WingetUI/assets/82721821/5bd66c5c-232e-4092-9c68-7516cd5a41db)
![2023-06-03 12_47_02-WingetUI](https://github.com/marticliment/WingetUI/assets/82721821/915821ba-ea60-444a-9eb3-25eddebf6976)

Second Incscape:
This is installed in the most recent version, however I receive messages, that two older versions should be installed and ready for update.

![2023-06-03 12_50_51-WingetUI](https://github.com/marticliment/WingetUI/assets/82721821/b759c7ed-f1ce-464d-b112-5abd632326b3)
![2023-06-03 12_49_53-WingetUI](https://github.com/marticliment/WingetUI/assets/82721821/d321e461-73f1-47c8-bf5b-0b345c527c65)
![2023-06-03 12_50_28-WingetUI](https://github.com/marticliment/WingetUI/assets/82721821/c8304d6b-5192-418c-8aa2-3c5ec113c45a)

**Comment by marticliment** [comment]
can you please share your  WingetUI log?

**Comment by Wosamarak** [comment]
Here is my log:
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
It took 0.02203226089477539 to load all language files
🟢 checkQueue Thread started!
🔵 Starting main application...
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
b'v1.4.10173\r\n'
None
updating winget
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
b'1.2.1\r\n'
None
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
Reactivation signal ignored: RaiseWindow_[1685788995.0414717]
{'wingetFound': True, 'scoopFound': False, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'Scoop ist deaktiviert', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
🔵 Reached main ui load milestone
Can't disconnect
🔵 Starting winget search
🔵 Starting choco search
🟢 Discover tab loaded
🟢 Found valid cache for winget!
Can't disconnect
🟢 Found valid cache for chocolatey!
Can't disconnect
🟢 Starting winget search, winget on C:\Users\XXXXXXXX\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\XXXXXXXX\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Upgrades tab loaded
Can't disconnect
🟢 Starting winget search, winget on C:\Users\XXXXXXXX\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\XXXXXXXX\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Discover tab loaded
🔵 Starting winget file update...
🟢 Starting choco search, choco on C:\Users\XXXXXXXX\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Chocolatey uninstallable packages search finished
Can't disconnect
🟢 Settings tab loaded!
🟢 Chocolatey search finished
🟢 About tab loaded!
🟢 Main application loaded...
Win32Mica Error: win32 version 19045 is not supported
50
🟢 Total packages: 14004
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Winget search finished
🟡 Package WinDirStat.WinDirStat version Unknown is ignored
🟡 Package Microsoft.VCRedist.2013.x86 version 12.0.30501.0 is ignored
🟡 Package Microsoft.VCRedist.2013.x86 version 12.0.21005.1 is ignored
🟡 Package Microsoft.VCRedist.2013.x86 version 12.0.40660.0 is ignored
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 63
🟡 package Update for  (KB2504637) failed parsing, going for method 2...
Update for  (KB2504637)                 {CFEF48A8-BFB8-3EAC-8BA5-DE4F8AA267CE}… 1 80
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 341
🟢 Winget cache rebuilt
🟢 Total packages: 14004
🟢 Chocolatey search finished
🔵 Starting winget search
🔵 Starting choco search
🟢 Found valid cache for winget!
🟢 Found valid cache for chocolatey!
🔵 Starting winget file update...
🟢 Total packages: 10270
🟢 Total packages: 14036
🟢 Winget cache rebuilt
🟢 Total packages: 14036
🔵 Copying log to the clipboard...

**Comment by Wosamarak** [comment]
And another weird piece:
I habe Ultraedit installed in the most recent version 2023.0.0.41
![2023-06-06 16_50_47- C__temp_wsl2  - UltraEdit 64-bit](https://github.com/marticliment/WingetUI/assets/82721821/7971389f-e699-470e-b905-1619c8e7000f)
However WinGetUI reports, that there is a newer Version 2023.0.41
![2023-06-06 16_50_01-WingetUI](https://github.com/marticliment/WingetUI/assets/82721821/afaada73-c6bc-4f7f-b834-b0167f29715d)
When trying to update it fails with a very cryptic information:
![2023-06-06 16_50_27-WingetUI](https://github.com/marticliment/WingetUI/assets/82721821/db55311e-6e5b-4d0d-9e0e-904721b99ed6)

**Comment by marticliment** [comment]
> When trying to update it fails with a very cryptic information:

This issue is not related with WingetUI. In this case you should follow its instructions, since this is how Winget works





> Trying to update AutoHotkey. The Installer starts, stops at 50% with the information: _**This package requires an install location**_

A fix is on its way

**Comment by Wosamarak** [comment]
> This issue is not related with WingetUI. In this case you should follow its instructions, since this is how Winget works

I see it somehow related. WinGetUI reports, that this could be updated, which is not true.

For most of the reported errors, it would be very helpful, if I could find the full command line with all parameters, which caused this error. This would be a very first step to dig deeper.  This should be part of the error description.
By long lasting errors, like that one where the installer is waiting forever for an location path, there is the possibility to find the parameters with the help of process explorer.

**Comment by marticliment** [comment]
> > This issue is not related with WingetUI. In this case you should follow its instructions, since this is how Winget works
> 
> I see it somehow related. WinGetUI reports, that this could be updated, which is not true.
> 
> For most of the reported errors, it would be very helpful, if I could find the full command line with all parameters, which caused this error. This would be a very first step to dig deeper. This should be part of the error description. By long lasting errors, like that one where the installer is waiting forever for an location path, there is the possibility to find the parameters with the help of process explorer.

There's a planned feature that will log last X done installs/updates/uninstalls, to allow better debug.

Also, processes hanging will be fixed with winget 1.5, coming with WingetUI 2.0

**Comment by marticliment** [comment]
Hello,

The issue with process hanging has been fixed (the patch will be included with the next release). The issue was that the cancel button was not actually killing the hung process.

The Installation history feature also has been implemented
