### ISSUE TITLE
[WINGET] Duplicate after update

### ISSUE THREAD

**Issue by neslekkim** [marticliment/WingetUI#1072]
I had installed "tesseract v4.0.0-beta.1.20180608" under Programfilesx86, so I guess it was 32bit at that time,
But Wingetui reported an update to "tesseract v5.3.0.20221214", so I updated it, but this was installed under programfiles, so, 64 bit version, and the old where not removed/replaced.

I guess the issue is more on winget, that winget ui, but could it be possible to check if an installed version is 32bit, and the update is 64bit, to inform that this can happen?, in Appwiz cpl it looks like this now:
![image](https://github.com/marticliment/WingetUI/assets/281342/32843238-e250-4f30-b323-17cabcfc0567)

And WingetUi shows only the newest version installed, even when both are installed.
![image](https://github.com/marticliment/WingetUI/assets/281342/2e927cc1-e0ff-4ddd-b308-6a0dab15a59b)

**Comment by marticliment** [comment]
This is an issue with Winget itself, and a fix for it is on its way.
