### ISSUE TITLE
[BUG/ISSUE] Winget sources reset not working, I do not have list since WingetUI 2.0 beta3

### ISSUE THREAD

**Issue by reddyshyam** [marticliment/WingetUI#1074]
Since installing WingetUI 2.0 beta3, I do not winget source list. Resetting not helping as the below error thrown.

<img width="553" alt="image" src="https://github.com/marticliment/WingetUI/assets/12392746/b01c0645-3891-4d91-9f83-9bcd860e6a3b">

**Comment by reddyshyam** [comment]
Switched back to stable 1.7.1 and all good now.

**Comment by JonathanPitre** [comment]
I have a similar issue with 17.1. It seems the destination path variable is not between quotes. 

![image](https://github.com/marticliment/WingetUI/assets/15003329/c1ae66ac-5ad7-4eff-8701-15f9751c3dba)
