### ISSUE TITLE
[BUG/ISSUE] Silent option not working

### ISSUE THREAD

**Issue by gustavohellwig** [marticliment/WingetUI#1077]
Hi,
Installing either by the .exe or by the winget install WingetUI doesn't prevent the Welcome UI windows from showing up, not making it possible to do a real silent installation.

Options that I did try:
`WingetUI.Installer.exe /verysilent /supressmsgboxes /norestart`

and
`winget install --silent --accept-package-agreements --disable-interactivity --override "/silent /supressmsgboxes /norestart" WingetUI`

Versions that I did try:

- 1.7.1
- 1.5.3.
- 2.0.0-beta3

Am I doing something wrong?

thank you.

**Comment by marticliment** [comment]
use `/NoAutoStart` to prevent WingetUI from running

**Comment by marticliment** [comment]
> It seems WingetGUI is totally ignoring the --override options

Those options are for winget, not for WingetUI

**Comment by scorpio200325** [comment]
/SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /LANG=deutsch zum Beispiel

**Comment by scorpio200325** [comment]
powershell (nicht als administrator) ausführen. WingetUI.exe Datei darein ziehen, /? dazu und man kriegt die ganze Liste der parameter

**Comment by scorpio200325** [comment]
run powershell (not as administrator). Drag the WingetUI.exe file into it, add /? and you get the whole list of parameters
as Example:

/SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /LANG=english
