### ISSUE TITLE
[BUG/ISSUE] Uninstall on updates page - asks about uninstalling the not-yet-updated version

### ISSUE THREAD

**Issue by LordMike** [marticliment/WingetUI#1078]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
On the updates page, if I try to uninstall a package of which I have version X (with an available update to version Y), the confirmation prompt asks about uninstalling version Y.

## To Reproduce
1. Go to Updates
2. Right click an update, select Uninstall
3. Observe the dialog on uninstalling the not-yet-installed version

## Expected behavior
I expected the prompt to ask about the installed version, in this gif - version 6.x.

## Screenshots
Note: For some reason the context menu was not captured. I right click the highlighted dotnet 6.x package, and choose "uninstall". 

![Recording 2023-05-30 at 20 05 37](https://github.com/marticliment/WingetUI/assets/1027111/e2fc2af3-76f2-49bb-b9c0-1ff1165ced46)o09

## The Log
N/A

## Additional context
I have two packages for dotnet, version 6 and 7 - both detect an update to version 7, which is weird.. but I think it's unrelated.

**Comment by marticliment** [comment]
> I have two packages for dotnet, version 6 and 7 - both detect an update to version 7, which is weird.. but I think it's unrelated.

This is actually the issue, since Winget incorrectly detects two installed versions when updating, byt only lists one of them on its _installed_ database.

This issue should be fixed soon by the Winget team, it is an open issue on their repository
