### ISSUE TITLE
[BUG/ISSUE] Prompt became Blue after the installation by winget

### ISSUE THREAD

**Issue by gustavohellwig** [marticliment/WingetUI#1080]
After the installation finishes, the prompt became blue, like you can see here:
Before:
![before](https://i.postimg.cc/Y05h7bhY/Clean-Shot-2023-06-01-at-14-13-39-2x.png)

After:
![after](https://i.postimg.cc/hPN941HC/Clean-Shot-2023-06-01-at-14-16-16-2x.png)

By the icon spinning of the terminal, it looks like something is still running in the background.

Also, even though the prompt releases, the installation is still running, as you can see. Something may still be running; that is why the blue prompt.

The problem is that the next steps of the silent installation became blue.

**Comment by gustavohellwig** [comment]
Workaround provided by ChatGPT: 
`$latestReleaseUrl = "https://api.github.com/repos/marticliment/WingetUI/releases/latest"
$latestRelease = Invoke-RestMethod -Uri $latestReleaseUrl
$assetUrl = $latestRelease.assets[0].browser_download_url
$webClient = New-Object System.Net.WebClient ; $webClient.DownloadFile("$assetUrl", "$filePath")

$taskArguments = "/SILENT /SUPRESSMSGBOXES /NORESTART /NoAutoStart"
$null = Start-Process -FilePath $filePath -ArgumentList $taskArguments -NoNewWindow -Wait > $null 2>&1
Remove-Item -Path $filePath -Force`

**Comment by marticliment** [comment]
This issue is not related with WingetUI, it happens also with other packages.

You should post this on microsoft/winget-cli
