### ISSUE TITLE
[BUG/ISSUE] Button not aligned when using translation

### ISSUE THREAD

**Issue by Ebnater** [marticliment/WingetUI#1081]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
The "Skip" button on the loading screen is not properly aligned when a translated text is longer than the original.

## To Reproduce
Steps to reproduce the behaviour:
1. Set Language for example to German
2.Restart WingetUI
43 See error

## Expected behaviour
The button should be properly aligned when the text becomes longer.

## Screenshots
![grafik](https://github.com/marticliment/WingetUI/assets/62059445/0c9cfff8-f5cb-40fd-8fc8-9a487411f992)

## The Log

<details>

```
none
```

</details>

**Comment by marticliment** [comment]
This issue was fixed in the latest beta!
