### ISSUE TITLE
[FEATURE REQUEST] further improvements to systray text/icon

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1084]
related to https://github.com/marticliment/WingetUI/issues/841

I think it would be nice if the systray text and icon showed some indication that an (un)install/update is currently under way or failed.

**Comment by marticliment** [comment]
there's actually a color code in the arrow. though I've been thinking on adding non-color icons (black/white) outlines, with color badges such as the Windows Update icon

**Comment by ppvnf** [comment]
Regarding the tooltip, I feel like instead of "everything is up to date" it would be better something like "install in progress" or "updating":

<img width="146" alt="Screenshot 2023-06-25 125545" src="https://github.com/marticliment/WingetUI/assets/73800734/2a86d3d2-935b-4087-b60f-fa0821ba1f49">

**Comment by marticliment** [comment]
Can you please open a new issue for it? Thanks!
