### ISSUE TITLE
[CHOCO] Discover Packages using included version of Chocolatey instead of system

### ISSUE THREAD

**Issue by DailenG** [marticliment/WingetUI#1088]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked that this issue is not an issue with the chocolatey utility, but rather with its implementation on WingetUI**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the issue
Trying to use WingetUI in an environment using internalized repos with less than 50 packages. When loading WingetUI says between 7,000 and 9,000 packages found (the number varies from time to time for some reason). From looking at the log it just seems to be when caching, when attempting to install an application it will use the system version.

## To Reproduce
Steps to reproduce the behaviour:
1. Disable all sources in WingetUI except chocolatey and make sure use system is enabled
2. Temporarily add an empty source to your local chocolatey, at command prompt run: choco source add --name Temporary --source C:\temp\chocolatey\
3. Remove default chocolatey source, at command prompt run: choco source remove --name chocolatey
4. Clear WingetUI chocolatey cache
5. Exit and reopen WingetUI
6. Under Discover packages the found packages should be zero
7. To remove Temporary source, at command prompt run: choco source remove --name Temporary
8. To replace original Chocolatey source, at command prompt run: choco source add --name chocolatey --source https://community.chocolatey.org/api/v2/

## The Log

<details>

🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.021941184997558594 to load all language files
🟢 checkQueue Thread started!
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🟡 Found lock file(s), reactivating...
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Reactivation signal ignored: RaiseWindow_[1686084684.8799145]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'WingetFound': False, 'WingetVersion': 'Winget is disabled', 'ScoopFound': False, 'ScoopVersion': 'Scoop is disabled', 'PipFound': False, 'PipVersion': 'Pip is disabled', 'NpmFound': False, 'NpmVersion': 'Npm is disabled', 'ChocolateyFound': True, 'ChocolateyVersion': '2.0.0\r'}
🔵 Reached main ui load milestone
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Chocolatey search for available packages
🟢 Found valid, non-empty cache file for Chocolatey!
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 6583 result(s)
Can't disconnect
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Chocolatey search for updates
🟢 Searching for string ""
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Chocolatey search for installed packages finished with 2 result(s)
🟢 Main application loaded...
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
Win32Mica Error: win32 version 19045 is not supported
50
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
🟢 Total packages: 6583
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 2 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 4
🟢 Chocolatey packages cached successfuly
🔵 Copying log to the clipboard...

</details>

**Comment by marticliment** [comment]
I see what is happening. The environment variable is still set.

**Comment by marticliment** [comment]
Hello,

Could you please test this release?: https://github.com/marticliment/WingetUI/releases/download/2.0.0-beta3/WingetUI.Installer.exe

**Comment by DailenG** [comment]
So i'm getting some bizarre behavior on this. My machine being a dev machine I think all bets are off as far as it being typical behavior. I tried resetting WingetUI's cache and leaving the preferences since to set the "use system chocolatey" setting isn't accessible until after the initial setup wizard, but even though Chocolatey was the only package manager selected it said 1000 packages were found even though my repo only has about 30.

Not sure how to test or proceed, i can setup a private chocolatey repo with a few packages in it on Artifactory if you want something to point at to test.

**Comment by marticliment** [comment]
Could you please try the latest commit?

**Comment by wrecklass** [comment]
I don't know if it is related, but today I rebooted a machine with WinGetUI on it and it automatically updated itself. In doing so it went back through the setup process, and either I missed a setting or the new version was very bad because after finishing the setup WinGetUI immediately started updating dozens of apps on my system without my telling it to, which I always had to before.

This is odd, because before WinGetUI knew that I only used Chocolatey to update software, I mainly used WinGetUI to inform me of updates being available.

I don't know what changed this behavior or why, but as I result I have Uninstalled WinGetUI from my system. After Uninstalling WinGetUI I saw that in the Windows Notices it had said it found 25 apps to update, and had updated several before I shut it down.

**Comment by marticliment** [comment]
Hello,

When you went back though the setup process, could it be that you have accidentally enabled automatic updates?
![image](https://github.com/marticliment/WingetUI/assets/53119851/2aff22ad-fbaa-497c-9de7-df5e1c4327b2)

**Comment by wrecklass** [comment]
I suppose it's possible.

Why did the update not simply use my previous settings, which would certainly not have been to Install anything by itself. That may be the real bug here. Should I enter an issue about that? 

I'll admit I was very busy when the system had to be rebooted and WinGetUI chose to update itself. I was annoyed that the software was asking me about things I had already specified on the original install.

**Comment by marticliment** [comment]
> I'll admit I was very busy when the system had to be rebooted and WinGetUI chose to update itself. I was annoyed that the software was asking me about things I had already specified on the original install

The settings asked in this wizard are introduced newly in v2.0.0 (it is true that you could enable updates on earlier versions, but the option was not quite visible to the average user.). This is why there is this new wizard that will show to everyone.
You will not see it anymore, unless you reset WingetUI.
