### ISSUE TITLE
[BUG/ISSUE] (beta 3+) discovery section placeholder doesn't disappear

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1098]
to trigger the bug you need to minimize/restore the window and go to other sections while the search is being performed:
<img width="960" alt="Screenshot 2023-06-11 223413" src="https://github.com/marticliment/WingetUI/assets/73800734/bf9b628c-4115-4201-82be-413255bb1c08">
<img width="960" alt="Screenshot 2023-06-11 222801" src="https://github.com/marticliment/WingetUI/assets/73800734/e4f450ad-2fba-426f-aa47-67d5de3e1207">

**Comment by marticliment** [comment]
For me, it happens that the placeholder does not disappear until the progressbar is hidden, could this be your issue?

**Comment by ppvnf** [comment]
> For me, it happens that the placeholder does not disappear until the progressbar is hidden, could this be your issue?

I think so, but it doesn't always happen the first time you search

**Comment by marticliment** [comment]
Can you please test the latest head?

**Comment by ppvnf** [comment]
it seems fixed to me!
