### ISSUE TITLE
[BUG/ISSUE] (Some visual issues and bugs in the Ukrainian localization)

### ISSUE THREAD

**Issue by sergd88** [marticliment/WingetUI#1101]
As seen from the first screenshot, when selecting the Ukrainian localization, the settings menu template for "Beta Features" is breaking, and in the second screenshot, there is misalignment in the first checkbox item.

Furthermore, in the following screenshots, it can be seen that the translation percentage for the Ukrainian language differs between the English and Ukrainian localizations, suggesting that the values are taken from different files.

Additionally, for some reason, the program incorrectly detects the installed system language because the computer is set to Ukrainian, but the application is using English.

Windows 11 22H2
WingetUI 1.7.1

![1_1](https://github.com/marticliment/WingetUI/assets/125032334/3a1d8e5d-24c4-47a5-bd96-370e9e35986d)

![1_2](https://github.com/marticliment/WingetUI/assets/125032334/49c8ece2-71ea-43fd-9432-196e758d78a1)

![2_1](https://github.com/marticliment/WingetUI/assets/125032334/9c5eb592-ed73-4cd0-8913-72756c1df289)

![2_2](https://github.com/marticliment/WingetUI/assets/125032334/6c8ce2e4-ac84-42c2-953a-0d196881ca6c)

**Comment by marticliment** [comment]
Changes in the translation % will be fixed on the next release.

The Misaligned strings have been fixed, but changes will take a few days to take effect

**Comment by sergd88** [comment]
> Changes in the translation % will be fixed on the next release.
> 
> The Misaligned strings have been fixed, but changes will take a few days to take effect

Wonderful news, glad to hear it. Many thanks for your promptness 😉
