### ISSUE TITLE
[BUG/ISSUE] Installed Chocolatey packages are not recognized in v. 2 rc1

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1106]
If I go back to 1.7.3 beta they (installed packages) are recognized again. I am using built in Choco.

I am not sure resetting cache button is working, because I got no feedback for clicking it

**Comment by marticliment** [comment]
Chocolatey packages, you mean the installed ones or the discoverable ones?

**Comment by marticliment** [comment]
Can you please share your log?

**Comment by ppvnf** [comment]
[log version beta 3.txt](https://github.com/marticliment/WingetUI/files/11749519/log.version.beta.3.txt)
do you also need the log from rc?

**Comment by marticliment** [comment]
yes, if possible.

**Comment by ppvnf** [comment]
[log 2 rc.txt](https://github.com/marticliment/WingetUI/files/11749724/log.2.rc.txt)

**Comment by marticliment** [comment]
Hello,

please try the latest head

**Comment by marticliment** [comment]
And please post the output on the new tab called "Package Manager Output"

**Comment by ppvnf** [comment]
I don't know how to manually upgrade while preserving my Chocolatey packages

**Comment by marticliment** [comment]
After building WingetUI into an exe file, you can just replace all the files except chocolatey ones.

P.D. After further testing, I think chocolatey 2.0.0 is misbehaving. I will downgrade it to release WingetUI 2.0.0

**Comment by marticliment** [comment]
Test this one.

If it does work I will publish WingetUI 2.0.0

https://github.com/marticliment/WingetUI/releases/download/2.0.0-rc1/WingetUI.Installer-choco1.4.0.exe

**Comment by ppvnf** [comment]
it works fine!

**Comment by ppvnf** [comment]
by the way, when are you gonna add new entries to Tolgee?

**Comment by marticliment** [comment]
As soon as possible. I am tweaking out some parts of the UI, add the strings to Tolgee and publish version 2.0.0

**Comment by ppvnf** [comment]
Should this be closed?
