### ISSUE TITLE
[BUG] Not getting notifications on Windows 11

### ISSUE THREAD

**Issue by reddyshyam** [marticliment/WingetUI#1109]
Using Windows 11 latest 22H2 and WingetUI 2.0.1.

For a few versions I do not see WingetUI on the notifications list. 

![image](https://github.com/marticliment/WingetUI/assets/12392746/ece2fa07-2d0a-4a11-bd5c-4334835f93f5)

Is there a registry hack that I can add it to the list please?

**Comment by reddyshyam** [comment]
This still is an issue with latest WingetUI 2.0.1

Resetting icon and screenshot cache under **"Experiment settings and developer options"** brings back the app under Notifications and settings section.

![image](https://github.com/marticliment/WingetUI/assets/12392746/c457326f-91a9-4fac-8fa5-7cedd191a010)

But reboot takes it off.

**Comment by MisterT87** [comment]
Since updating to WingetUI 2.0.3 also dont getting any notifications on Win11 anymore.

Before updating it worked flawlessly (using WingetUI since 2.0.1).
Im on Win11 Pro 22H2
