### ISSUE TITLE
[BUG/ISSUE] ("Trojan:Win32/Sabsik.FL.B!ml" was found in the WingetUI Updater) !!SECURITY!!

### ISSUE THREAD

**Issue by muluffel** [marticliment/WingetUI#1116]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened** --> Yep, but I want confirmation that it is safe and not a "false report"
- [x] **I have checked that I am running the latest version of WingetUI** --> no thats why it autmatically ran the updater
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again** --> will completely uninstall now
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Winget UI startet to do an auto update. It failed and immediately Windows Defender said that Threats were found. `Trojan:Win32/Sabsik.FL.B!ml`

## To Reproduce
Steps to reproduce the behaviour:
Idk, probably run the updater?

## Expected behaviour
No Trojan

## Screenshots
![image](https://github.com/marticliment/WingetUI/assets/65601356/793ffca0-bdbb-4756-9eb1-ad743419e5af)

## The Log
Can't provide, I let Defender wipe the infection

**Comment by marticliment** [comment]
This is a false positive, and should be already fixed.

Please update your virus definitions through Windows Update

**Comment by sickarm** [comment]
> This is a false positive, and should be already fixed.
> 
> Please update your virus definitions through Windows Update

Just updated windows defender definitions and still getting the same unfortunately

**Comment by GeoSimos** [comment]
Same problem with update definitions:
![image](https://github.com/marticliment/WingetUI/assets/22078536/33a9cfca-e174-482c-b12c-3683dc0bc8d9)
and in Defender's protection history:
![image](https://github.com/marticliment/WingetUI/assets/22078536/a5b7774a-5179-4c25-b6a2-ed68196d2418)

**Comment by marticliment** [comment]
I have resubmitted the false positive. We need to wait for MS Defender to reply

**Comment by marticliment** [comment]
Hello,

Please try installing version 2.0.1. It should not be flagged anymore

**Comment by GuyGuy-59** [comment]
Hello,
Same thing with version 2.0.1
![Capture d’écran 2023-06-17 124728](https://github.com/marticliment/WingetUI/assets/45609442/dd88a039-edac-4939-86a6-26f55a23b61a)
![Capture d’écran 2023-06-17 124942](https://github.com/marticliment/WingetUI/assets/45609442/b09a09e5-075b-4b4b-90f6-a17d3d5e5275)

**Comment by marticliment** [comment]
I have resubmitted the files, but in my device they aren't detected anymore, and virustotal does not report MS Dedender neither

**Comment by GuyGuy-59** [comment]
I tested it on three computers. Only one, where MS defender did not flag. MS defender definitions are updated on all three.

**Comment by CodingWonders** [comment]
The pattern in these threats, mine included, is that they end in `!ml`. The workaround, allow the "threat" on the device

**Comment by marticliment** [comment]
Please test this:
> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"

> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
