### ISSUE TITLE
[BUG/ISSUE] after updating or installing WingetUI 2.0.0 Chocolatey is activated by default

### ISSUE THREAD

**Issue by candrapersada** [marticliment/WingetUI#1118]
why after updating or installing WingetUI, Chocolatey is activated by default?
![246476257-355af2f9-ff68-4e2a-8ea1-10088b630e20](https://github.com/marticliment/WingetUI/assets/36833664/606303d8-6ac7-482c-8ca2-61b409ee39f3)

**Comment by marticliment** [comment]
Well, choosing default preferences loads the default preferences.

You should select "Customize WingetUI" and make the appropiate choices
