### ISSUE TITLE
[BUG] (Enter your description here)Truly i do know sir,

### ISSUE THREAD

**Issue by gabgab13140** [marticliment/WingetUI#1122]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [ ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [ ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## To Reproduce
Steps to reproduce the behaviour:

## The Log

<details>

```
Please paste here the log (Go to the three dots menu on the top-right corner of WingetUI -> Winget Log. 

If the issue can be reproduced, please send the log AFTER reproducing the issue (1. Launch WingetUI, 2. Reproduce the issue, 3. Paste the log)
```

</details>

**Comment by marticliment** [comment]
Hello,

could you please reply posting the issue details?

**Comment by gabgab13140** [comment]
I do not know sir, I cannot explain, if you could arrange please help me. Thank you. Envoyé depuis mon téléphone Huawei-------- Message original --------De : Martí Climent ***@***.***>Date : sam. 17 juin 2023 à 12:12À : marticliment/WingetUI ***@***.***>Cc : gabgab13140 ***@***.***>, Author ***@***.***>Objet : Re: [marticliment/WingetUI] [BUG] (Enter your description here)Truly i do know sir, (Issue #1122)
Hello,
could you please reply posting the issue details?

**Comment by marticliment** [comment]
hello,

I need to know what is happening, if not I can't fix it

**Comment by gabgab13140** [comment]
I have just followed download that is all, I can't have any knowledge about all this, please don't mind it, any have thanks a lot. Envoyé depuis mon téléphone Huawei-------- Message original --------De : Martí Climent ***@***.***>Date : sam. 17 juin 2023 à 13:45À : marticliment/WingetUI ***@***.***>Cc : gabgab13140 ***@***.***>, Author ***@***.***>Objet : Re: [marticliment/WingetUI] [BUG] (Enter your description here)Truly i do know sir, (Issue #1122)
hello,
I need to know what is happening, if not I can't fix it

**Comment by gabgab13140** [comment]
Hello, I think I have old version of  wingetui, whenever I try to install, I can't, several times I tried nothing is going on, thank you. Envoyé depuis mon téléphone Huawei-------- Message original --------De : Martí Climent ***@***.***>Date : sam. 17 juin 2023 à 13:45À : marticliment/WingetUI ***@***.***>Cc : gabgab13140 ***@***.***>, Author ***@***.***>Objet : Re: [marticliment/WingetUI] [BUG] (Enter your description here)Truly i do know sir, (Issue #1122)
hello,
I need to know what is happening, if not I can't fix it

**Comment by marticliment** [comment]
Could it be that your antivirus is blocking WingetUI?

**Comment by gabgab13140** [comment]
Yes sir probably it could be, I never thought that, I will try again and again, I am 70 years old all this algebra for me, Thanh you. Envoyé depuis mon téléphone Huawei-------- Message original --------De : Martí Climent ***@***.***>Date : dim. 18 juin 2023 à 16:43À : marticliment/WingetUI ***@***.***>Cc : gabgab13140 ***@***.***>, Author ***@***.***>Objet : Re: [marticliment/WingetUI] [BUG] (Enter your description here)Truly i do know sir, (Issue #1122)
Could it be that your antivirus is blocking WingetUI?
