### ISSUE TITLE
[BUG/ISSUE] (Setup was unable to create the directory; Error 5)

### ISSUE THREAD

**Issue by SuperFurias** [marticliment/WingetUI#1125]
## Before submitting the issue

- [ yes] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ no, 1.7.1] **I have checked that I am running the latest version of WingetUI**
- [ no] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [ yes] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [ yes] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
The autoupdate is failing with error 5 access is denied

## To Reproduce
Steps to reproduce the behaviour:
1. Open 'wingetui 1.7.1'
2. Click on 'the x, to close wingetui, and wait for the autoupdate thing'
3. See error

## Expected behaviour
The program updating without errors.

## Screenshots
![image](https://github.com/marticliment/WingetUI/assets/34806112/1b917d3d-7e4d-4d09-a513-4f18602c72e9)
## The Log

<details>

```
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.002001523971557617 to load all language files
🟢 checkQueue Thread started!
🔵 Language file up-to-date
🔵 Starting main application...
Scanning for instances...
Found lock file(s), reactivating...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
b''
None
updating winget
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates found!
b'2.0.0\r\n'
None
Reactivation signal ignored: RaiseWindow_[1687004528.8360596]
🔵 Hash:  feb1df98893e90c4264b3ed5ca78842e6a71aff13e43d9f0c65f63054d97420f
🟢 Hash ok, starting update
b"Current Scoop version:\nv0.3.1 - Released at 2022-11-15\n\n'main' bucket:\n41eeb77c9 redis@7.0.11: Fix hash (Closes #4896)\n\n"
None
{'wingetFound': False, 'scoopFound': True, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': '', 'scoopVersion': 'v0.3.1 - Released at 2022-11-15', 'chocoVersion': '2.0.0\r', 'sudoVersion': 'gsudo v2.0.10 (Branch.tags-v2.0.10.Sha.b4d8502fa00b81103afa15497adbdaccd2371b89)\r'}
🔵 Reached main ui load milestone
Can't disconnect
🔵 Starting winget search
🔵 Starting scoop search
🔵 Starting choco search
🟢 Discover tab loaded
🟢 Found valid cache for winget!
🟢 Found valid cache for scoop!
🟢 Found valid cache for chocolatey!
Can't disconnect
Can't disconnect
🔵 Starting scoop file update...
🟢 Starting winget search, winget on C:\Program Files\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on choco.exe...
🟢 Upgrades tab loaded
Can't disconnect
🟢 Starting winget search, winget on C:\Program Files\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on choco.exe...
🟢 Discover tab loaded
🔵 Starting winget file update...
🟢 Starting choco search, choco on choco.exe...
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
🟢 Chocolatey uninstallable packages search finished
0
🟢 Total packages: 12884
🟢 Searching for string ""
🟢 Winget search finished
🟢 Searching for string ""
🟡 package Update for  (KB2504637) failed parsing, going for method 2...
Update for  (KB2504637)                  {CFEF48A8-BFB8-3EAC-8BA5-DE4F8AA267CE}.… 1 82
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 271
🟢 Scoop cache rebuilt
🟢 Total packages: 12884
🟢 Winget cache rebuilt
🟢 Total packages: 12884
🔵 Copying log to the clipboard...

```

</details>

**Comment by SuperFurias** [comment]
I also tried the manual update, same error as the autoupdate.
i also tried to run the manual update with admin permissions, the error changing into this:
![image](https://github.com/marticliment/WingetUI/assets/34806112/493880a0-0e10-4e7f-a174-0eaf1574e3f4)

**Comment by SuperFurias** [comment]
> I also tried the manual update, same error as the autoupdate. i also tried to run the manual update with admin permissions, the error changing into this: ![image](https://user-images.githubusercontent.com/34806112/246608756-493880a0-0e10-4e7f-a174-0eaf1574e3f4.png)

After trying to manually uninstall WingetUI, and deleting the folder..
![image](https://github.com/marticliment/WingetUI/assets/34806112/a1ea2aa1-f34b-4e6a-ad56-e793818cbc95)
I have clue why Opera GX is using a file of another program

**Comment by marticliment** [comment]
try killing opera gx from task manager and then reinstalling

**Comment by SuperFurias** [comment]
> try killing opera gx from task manager and then reinstalling

I killed the crash reporter and manually installed the new version (2.0.1)
but its a bit annoying manually killing process to update something.. but well, as long as it works.

**Comment by marticliment** [comment]
To be honest, I don't understand why opera gx had to mess with WingetUI, but as far as I am concerned this is not related with WingetUI, but rather with opera gx, so I am going to close this issue
