### ISSUE TITLE
[BUG/ISSUE] Microsoft Windows Desktop Runtimes 7.0.7 is wrongly proposed as an update to v6.0.18

### ISSUE THREAD

**Issue by mooms06** [marticliment/WingetUI#1126]
## Before submitting the issue

- [x ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x ] **I have checked that I am running the latest version of WingetUI**
- [x ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Since today, WingetUI wants to update Microsoft Windows Desktop Runtimes 6.0.18 with version 7.0.7. 
7.0.7 is already installed on my system.
I've reset the cache of Winget and restarted WingetUI, the issue still persists.

## To Reproduce
Have both Runtimes installed.

## Expected behaviour
Dotnet Runtimes 7.0 is not an update to Dotnet Runtimes 6.0, both can be installed together.

## Screenshots
![image](https://github.com/marticliment/WingetUI/assets/25405517/6f17aca3-c0f8-489c-9256-adf36479496f)

![image](https://github.com/marticliment/WingetUI/assets/25405517/eff5a034-be76-44a6-8776-b83749ae795d)

## The Log

<details>

```
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0010006427764892578 to load all language files
🟢 checkQueue Thread started!
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
🔵 Starting update check
🔵 Language file up-to-date
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1687008980.5844684]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop est désactivé', 'PipFound': False, 'PipVersion': 'Pip est désactivé', 'NpmFound': False, 'NpmVersion': 'Npm est désactivé', 'WingetFound': True, 'WingetVersion': '', 'ChocolateyFound': True, 'ChocolateyVersion': '1.4.0\r'}
🔵 Reached main ui load milestone
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for available packages
🔵 Starting Chocolatey search for available packages
🟢 Found valid, non-empty cache file for Winget!
🔵 Starting Winget package caching
🟢 Winget search for installed packages finished with 4775 result(s)
🟢 Found valid, non-empty cache file for Chocolatey!
🔵 Starting Chocolatey package caching
🟢 Chocolatey search for installed packages finished with 8858 result(s)
Can't disconnect
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading sources...
🔵 Reloading Winget sources...
🟢 Searching for string ""
Can't disconnect
Can't disconnect
🟢 Install tab loaded successfully
🔵 Starting Winget search for installed packages
🔵 Starting Chocolatey search for installed packages
🟢 Searching for string ""
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
🟢 Chocolatey search for installed packages finished with 1 result(s)
Win32Mica Error: win32 version 19045 is not supported
50
🟢 Total packages: 7307
🟢 Total packages: 13633
🟢 Searching for string ""
🟢 Winget packages cached successfuly
🔵 Reloading Scoop sources...
🔵 Starting Winget search for updates
🟢 Winget search for installed packages finished with 125 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 126
🔵 Reloading Scoop sources...
🔵 Starting Chocolatey search for updates
🟢 Chocolatey search for updates finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for updates finished with 63 result(s)
🟠 Package CrystalArtSoftware.NewsLeecher is legacy blacklisted
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 1
🟢 Chocolatey packages cached successfuly
🔵 Loading log...
🔵 Copying log to the clipboard...

```

</details>

**Comment by marticliment** [comment]
This is an issue with winget-cli, you might want to post that issue on microsoft/winget-cli

**Comment by mooms06** [comment]
It would probably be dismissed since I'm not using winget-cli though.

**Comment by mooms06** [comment]
In the installed app tab of Winget UI, both version are seen at v6.0.18 by WingetUI (but in Windows the correct version shown, so the issue seems to be either in winget-cli or in Winget UI.


![image](https://github.com/marticliment/WingetUI/assets/25405517/fc1da74d-a61c-4597-b142-533bf6ee119f)

**Comment by marticliment** [comment]
> It would probably be dismissed since I'm not using winget-cli though.

Yes, but WingetUI uses winget-cli to retrieve updates

**Comment by mooms06** [comment]
> > It would probably be dismissed since I'm not using winget-cli though.
> 
> Yes, but WingetUI uses winget-cli to retrieve updates

I've blacklisted the packet, problem solved for now.

Where can I submit an error in the French translation of WingetUI ?

**Comment by marticliment** [comment]
> Where can I submit an error in the French translation of WingetUI ?

Email me at marticlilop@gmail.com
