### ISSUE TITLE
[BUG/ISSUE] discovery package list not being updated

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1131]
Does WingetUI regularly update the package list in the discovery section? For example, running `scoop update`. Because I have noticed that if I let WingetUI running for a long time some packages still appear outdated. Maybe the discovery package list should be updated every x minutes/hours

**Comment by marticliment** [comment]
No, but actually yes. 

The discover section is not dynamically updated, but, since the software sources are updated by the updates section (scoop update, winget source update, etc.), hitting reload a few times (to bypass the cache) should have this issue sorted

**Comment by marticliment** [comment]
every time the list is loaded the caching mechanisms start rebuliding it in the background

**Comment by ppvnf** [comment]
> hitting reload a few times (to bypass the cache) should have this issue sorted

That's good to know, but it doesn't feel like an ideal solution

**Comment by marticliment** [comment]
> > hitting reload a few times (to bypass the cache) should have this issue sorted
> 
> That's good to know, but it doesn't feel like an ideal solution

The discover packages section won't determine the version of the package you are going to install, and under very few cirumstances you would need to instantly update the packages. In this case, you could resort to resetting the caches.

I am thinking, what about Ctrl+F5 to reload without cache?

**Comment by ppvnf** [comment]
I don't mind it,but IMO the problem is that leaving WingetUI open for several days will result in packages appearing out of date in the discovery section (even if they are not in fact). So ideally they should be refreshed automatically at least once a day

**Comment by Mikey1993** [comment]
@marticliment ,
I think having some kind of mechanism for self reload without caching if the "Discover packages" tab is opened for more than X time would be a good feature to implement to avoid this issue 90% of the times.
Maybe also show the last caching/reload time somewhere at the tab would help for better visibility.

**Comment by marticliment** [comment]
All the packages will be son treated dynamically. This change is not made solely to fix this issue, but rather to speed up general loading times and resource usage. But since it will be fixed I will close this
