### ISSUE TITLE
[FEATURE REQUEST] Better "Search for package start" on the start

### ISSUE THREAD

**Issue by panther7** [marticliment/WingetUI#1133]
- [x] Auto-focus query
 - [ ] Better highlight search package query

Maybe need add button/link into text "Search for package start" for focus search input.

Search input is not good visible on bigger screen.

Btw, I don't think, that "Search for package start" is right text.

![2023-06-19 12 05 19](https://github.com/marticliment/WingetUI/assets/3808250/3149f1d0-10fd-4ab2-8b7d-d0a36d4f95e0)

**Comment by panther7** [comment]
I translated it as "Pro výpis balíčků začněte vyhledávat (v pravém horním rohu)"

> To list packages, start searching (in the top right corner)

**Comment by marticliment** [comment]
I was thinking on adding some kind of arrow that pointed there, what do you think?

**Comment by marticliment** [comment]
Yes

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/a9ba71a5-f8d1-4d8e-852d-f2766f27c844)
