### ISSUE TITLE
[BUG/ISSUE] Wingetui 2.0.1 hangs if scoop is not installed

### ISSUE THREAD

**Issue by hawkeye73** [marticliment/WingetUI#1136]
## Before submitting the issue

- [X ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X ] **I have checked that I am running the latest version of WingetUI**
- [X ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [X ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
While starting Wingetui 2.0.1 (also previous versions) I don't get pass the Starting Daemons.

## To Reproduce
Start Wingetui
Waiting on Starting Daemons
Stuck Here? skip initialization
I click on that and the program starts

## Expected behaviour
I would like it starts automatically without user input

## Additional context
I choose Dutch, System Language, English as languages on 3 different machines. 2x Windows 10 Pro 22H2 Build 19045.3086 and 1x Windows 11 Pro 22H2 Build 22621.1848 all updates installed and newest version (2.0.1) till that moment, I have this since the first version I tried.

**Comment by marticliment** [comment]
Hello,

can you please share your WingetUI log?

**Comment by hawkeye73** [comment]
[2023-06-20 Wingetui log Win11.txt](https://github.com/marticliment/WingetUI/files/11799031/2023-06-20.Wingetui.log.Win11.txt)

This is the logfile from my Win11 machine. If you also need the Win10 machine, please let me know. Thanks for looking into this issue.

**Comment by hawkeye73** [comment]
I see in the log file something with scoop. I disabled scoop and now it's working. Is this meant to work like this? Do I need extra settings for scoop?

**Comment by marticliment** [comment]
can you please run `scoop -v` and `scoop update` on a console and post here the output?

**Comment by hawkeye73** [comment]
Should I leave this open or close it?

**Comment by marticliment** [comment]
open, this shouldn't happen

**Comment by oooseun** [comment]
+1, this happened to me and a google search brought me here and the solution fixed it (which was installing scoop)

> Set-ExecutionPolicy RemoteSigned -Scope CurrentUser # Optional: Needed to run a remote script the first time
> irm get.scoop.sh | iex

**Comment by NotPuddles** [comment]
This also fixed it for me installing scoop
