### ISSUE TITLE
[FEATURE REQUEST] Push updates updates more frequently to winget (and later to choco)

### ISSUE THREAD

**Issue by MisterT87** [marticliment/WingetUI#1139]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.
No

Is it possible to push wingetui updates more frequently to winget ?
In my optinion today you dont want manually download and install per installer on a fresh win10/11 OS.
especially on newer win10/11 setups comes with newest winget, where you can just run a auto script (after win10/11 install) with "winget install wantedpackage1 wantedpackage2"

AND winget 1.5.x support (already added) .zip package install and package pinning out of the box - what is needed for example gpu drivers...

btw what I know on choco und also winget you can automate pushing updates to chocolatey packages und winget-pkgs repo.
should be easier for you because this repo already is on github :D
So nothing much todo if first time properly setup... just a tipp :)

EDIT - just want to say: In my opinion wingetUI is THE best GUI for win package management ! So big thanks for great work to all devs! :)

**Comment by marticliment** [comment]
> Is it possible to push wingetui updates more frequently to winget ?

There is an issue with the installer, which breaks continuous publishing, since the installer is reporting non-zero output codes and is failing verification. The same goes with chocolatey. I am working on fixing this though

**Comment by ppvnf** [comment]
it seems that the latest WingetUI version is available on Winget

**Comment by MisterT87** [comment]
> it seems that the latest WingetUI version is available on Winget

Yup, got it - thanks !

> There is an issue with the installer, which breaks continuous publishing, since the installer is reporting non-zero output codes and is failing verification. The same goes with chocolatey. I am working on fixing this though

Ah got it - thats why there are weird errors on the winget-pkgs Repo.
Again thanks for great work !
