### ISSUE TITLE
[ISSUE] Translations issues

### ISSUE THREAD

**Issue by panther7** [marticliment/WingetUI#1143]
1. `The classical package manager for windows. You'll find everything there.` -> `The classical package manager for Windows. You'll find everything there.`
   (w->W)
1. `Operation history` / `Package manager logs` ... I think, that this is same, it will be merged?

**Comment by marticliment** [comment]
> * `The classical package manager for windows. You'll find everything there.` -> `The classical package manager for Windows. You'll find everything there.`
>   (w->W)

Fixed (on Tolgee)



> 1. `The classical package manager for windows. You'll find everything there.` -> `The classical package manager for Windows. You'll find everything there.`
>    (w->W)
> 2. `Operation history` / `Package manager logs` ... I think, that this is same, it will be merged?

They are not exactly the same. One contains the operation history (only install/uninstall operations), and is cross-instance (logs are saved on the disk), while the other one only stores output for the current session, and provides more debugging-focused information.
