### ISSUE TITLE
[BUG/ISSUE] package list is not being refreshed if packages are checked/sorted

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1144]
Deleting with backspace or using the delete all button trigger this bug

https://github.com/marticliment/WingetUI/assets/73800734/8cb8355e-7e97-465e-936f-91ed6b0bbf1e

**Comment by marticliment** [comment]
No, this is not a bug, this is done in purpose, so you can track the packages you have selected previously if you are bulk installing packages.
