### ISSUE TITLE
[BUG/ISSUE] False updates

### ISSUE THREAD

**Issue by peter1599** [marticliment/WingetUI#1146]
## Before submitting the issue

- [ 🗸 ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ 🗸 ] **I have checked that I am running the latest version of WingetUI**
- [ 🗸 ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [ 🗸 ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [ 🗸 ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Starting from the first 2.X.X version there is a lot of false updates. Like it just says: 
Package Name: Name
Package ID: IdVersion
So just literally nothing.

Winget also behaves weird starting from the first 2 version. Its also shows a lot of false updates and when I click on the package details it shows that the details are empty no images etc...

## To Reproduce
Steps to reproduce the behaviour:
1. Just simply check for updates in any 2.X.X version and its there.

## Expected behaviour
Its not supposed to happen. It should work like in 1.7.1 which shows the updates right and not showed any false updates

## Screenshots
You can see Name IdVersion etc..
![image](https://github.com/marticliment/WingetUI/assets/25458870/bb400293-7681-4dd8-8aeb-0ecd1d7cfd6e)

![image](https://github.com/marticliment/WingetUI/assets/25458870/656b9df6-4f57-453e-ae33-7d7713c9dd19)

The manifest doesn't even exists of the discord update it shows: (1.7.1 doesn't shows discord update)
![image](https://github.com/marticliment/WingetUI/assets/25458870/0f535c85-030d-4543-be23-0f586c2ba17a)

## The Log

<details>

```
Please paste here the log (Go to the three dots menu on the top-right corner of WingetUI -> Winget Log. 

If the issue can be reproduced, please send the log AFTER reproducing the issue (1. Launch WingetUI, 2. Reproduce the issue, 3. Paste the log)
```

</details>

**Comment by marticliment** [comment]
Can you please share your package manager output log?

**Comment by peter1599** [comment]
> Can you please share your package manager output log?

Sure here: 
[P_MANAGER.txt](https://github.com/marticliment/WingetUI/files/11816469/P_MANAGER.txt)

**Comment by marticliment** [comment]
Hello,

your issue was fiixed on 4a7671befbef6405f4247516afb9b7caa359be5d, and it will be released on the next version
