### ISSUE TITLE
[BUG/ISSUE] Winget parsing issue

### ISSUE THREAD

**Issue by alexvoda** [marticliment/WingetUI#1148]
## Before submitting the issue

- [x]  I have checked that the bug is not a duplicate or, if it is, it needs to be reopened
- [x]  I have checked that I am running the latest version of WingetUI
- [x]  I have tried resetting and reinstalling WingetUI and the issue persisted or happened again
- [x]  I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [x]  I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)

## Describe the bug

On the Software Updates tab, due to I presume a parsing issue, some times the list of available updates contains garbage. It resembles a table header that instead got parsed as part of the table content. I am not using the system winget (beta) feature.  I am on WinGetUI v2.0.1 but I remember this happening before this version.

## Expected behaviour

Only details of actual package updates should appear in the table. 

## Screenshots

![Screenshot 2023-06-21 013718](https://github.com/marticliment/WingetUI/assets/790775/162cdce2-6759-4a86-998c-3e7842301a98)

**Comment by ppvnf** [comment]
this issue seems the same as https://github.com/marticliment/WingetUI/issues/1146

**Comment by marticliment** [comment]
duplicate #1146
