### ISSUE TITLE
[FEATURE REQUEST] Creation of packages using WingetUI

### ISSUE THREAD

**Issue by niceEli** [marticliment/WingetUI#1151]
I think it would be great to be able to make packages for any of the sources using a UI instead of the confusing process of making packages. I would say to put a tab, or put a button in the hamburger menu that would take you to a wizard to update or create packages.

**Comment by ppvnf** [comment]
this has been suggested for Winget in https://github.com/marticliment/WingetUI/issues/948.
I am not sure what would be an equivalent for other package managers tho

**Comment by marticliment** [comment]
duplicate of #948
