### ISSUE TITLE
[BUG/ISSUE] Update number of downloads in the README

### ISSUE THREAD

**Issue by CanePlayz** [marticliment/WingetUI#1155]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Just a very minor thing: The download number in the README should be updated to either show the downloads of the newest version or the total downloads.

**Comment by marticliment** [comment]
> ## Before submitting the issue
> * [x]  **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
> * [x]  **I have checked that I am running the latest version of WingetUI**
> * [x]  **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
> * [x]  **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
> * [x]  **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**
> 
> ## Describe the bug
> Just a very minor thing: The download number in the README should be updated to either show the downloads of the newest version or the total downloads.

Total downloads are a lie, since they count every time an user upgrades to a new version. This is why I opted to put the most downloaded release

**Comment by CanePlayz** [comment]
I see, thanks
