### ISSUE TITLE
[BUG/ISSUE] Wider text area for dropdown menus

### ISSUE THREAD

**Issue by CanePlayz** [marticliment/WingetUI#1156]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
![image](https://github.com/marticliment/WingetUI/assets/81419612/834647f0-584b-4a3b-a554-74998ec06b15)

On this button in the settings, the German text doesn't fit. BUT it's only because the text cannot fill the entire button. There would be enough space

**Comment by ppvnf** [comment]
@marticliment there are potentially a few similar cases where the text doesn't fit. Would it be possible to make the boxes automatically expandable to avoid this problem?

**Comment by CanePlayz** [comment]
Thanks :)
