### ISSUE TITLE
[FEATURE REQUEST] Display package released date (if applicable) and installed date.

### ISSUE THREAD

**Issue by reddyshyam** [marticliment/WingetUI#1157]
Can we display package _released date_ (if application) on the **Discover** tab and Package _released and installed date_ on **Installed** tab please? Also if this is possible, then I am sure sort on the dates on respective tabs please.

**Comment by marticliment** [comment]
> Can we display package _released date_ (if application) on the **Discover** tab and Package _released and installed date_ on **Installed** tab please? Also if this is possible, then I am sure sort on the dates on respective tabs please.

Most package managers don't provide this information (unless you manually query each package info, which is not an option), so only 1 out of 10 packages would have the date, and the other 9 would show _Not Available_.

**Comment by reddyshyam** [comment]
Thanks @marticliment for your prompt reply. How about installation date? That should be ok as wingetUI installs it. Won't it be helpful on the "Installed packages" tab to sort by installed date?

**Comment by marticliment** [comment]
The issue here is the same, this information is not easily provided by Package Managers
