### ISSUE TITLE
[FEATURE REQUEST] Visible download progress bar

### ISSUE THREAD

**Issue by uuc110** [marticliment/WingetUI#1164]
## Before submitting the issue

- [✓] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [✓] **I have checked that I am running the latest version of WingetUI**
- [✓] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [✓] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

It's not my problem, I just feel that marquee style progress isn't that good?, its better to know the progress on installation. it will help in knowing how much installation is left, If someone is in hurry and want to check how much it is left. it will be useful.

A clear and concise description of what the problem is. Ex. I'm always frustrated when I don't know how much download is left.

## Describe the solution you'd like

Well there should be a progress bar maybe be default windows green colour progress bar or you can set up theme to choose from.

**Comment by marticliment** [comment]
This migt not be doable due to the nature of the command-line parser, but I am going go give it a try.

**Comment by uuc110** [comment]
> This migt not be doable due to the nature of the command-line parser, but I am going go give it a try. 

Oh I see, thanks for consideration and reply but really love this software 🫶

**Comment by 2tbc1887** [comment]
+1 for this
If not possible, maybe a download speed indicator to show that progress happening?

**Comment by BartmanAbyss** [comment]
+1

**Comment by Bobrokus** [comment]
+1

**Comment by marticliment** [comment]
Hello,

Latest WingetUI Beta does include thisn feature for Package Managers that do support visual progressbars:
![image](https://github.com/marticliment/WingetUI/assets/53119851/48ce5fa8-d8fd-4e21-9c1d-b213774da764)
