### ISSUE TITLE
[BUG/ISSUE] Package description UI flickering

### ISSUE THREAD

**Issue by CanePlayz** [marticliment/WingetUI#1165]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
When I expand the installation options on a package description, the UI flickers weirdly.

## To Reproduce
Steps to reproduce the behaviour:
1. Go on a package page
2. Click on the installation options

## Screenshots

https://github.com/marticliment/WingetUI/assets/81419612/ca1ad1cf-03fe-468a-9534-ef69f229e631

**Comment by marticliment** [comment]
This is most likely a bug with Qt, rather than WingetUI, but i'll see what I can do

**Comment by CanePlayz** [comment]
Ok thanks

**Comment by marticliment** [comment]
This issue is a render issue with Qt, that has not been fixed completely but Qt 6,5,2 improves the speed and the reliability of the render, avoiding flickerings
