### ISSUE TITLE
[CHOCO] Installing Lossless-Cut does not run its choco install script

### ISSUE THREAD

**Issue by MildlyInterested** [marticliment/WingetUI#1168]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked that this issue is not an issue with the chocolatey utility, but rather with its implementation on WingetUI**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the issue
Installing `Lossless-Cut` through WingetUI using the choco repo fails to create the programm launch and shell shortcuts that the choco install offers.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to WingetUI, search for "Lossless Cut" and choose "Install as administrator"
2. Wait for install to finish, there is no obvious way to start Lossless-Cut
3. Install manually through choco using admin powershell: `choco install lossless-cut`
4. Choco asks if I want to run the install script, I confirm with "A"
5. Lossless-Cut installs and is available through the start menu.

**Comment by marticliment** [comment]
Hello, is this package on the community repository?

**Comment by MildlyInterested** [comment]
Thanks for the fast answer! Yes it is: https://community.chocolatey.org/packages/lossless-cut

**Comment by MildlyInterested** [comment]
Just tested again and it worked without hickup. Was probably user error... closing it.
