### ISSUE TITLE
[ENHANCEMENT] systray tooltip 

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1176]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Regarding the tooltip, I feel like instead of "everything is up to date" it would be better something like "install in progress" or "updating":

<img width="146" alt="Screenshot 2023-06-25 125545" src="https://github.com/marticliment/WingetUI/assets/73800734/2a86d3d2-935b-4087-b60f-fa0821ba1f49">

### Describe how this improvement could help users.

Makes it clearer that an operation is under way

related to https://github.com/marticliment/WingetUI/issues/1084

**Comment by marticliment** [comment]
fixed on bdaf7ac672912bbc4bbdb744f36d8dc9fb478a71
