### ISSUE TITLE
[FEATURE REQUEST] Overwrite Installation Source

### ISSUE THREAD

**Issue by Dornteufel1** [marticliment/WingetUI#1181]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

I would like a funktion, where you can Overwrite the source and the command of the installation. If there are packages available in multiple sources, an overwrite could help choose the correct source and packagename.
In combination with #1009 a default install order could also be established for multiple source packages (first PIP, than NPM, than ...)

### Describe how this new feature could help users.

Example: The package xurl should be installed. WingetUI automatically proposes the command "npm install xurl" and with the expert view in the options enabled you see three additional fields: "Source: NPM" (new), "Package-Name: xurl" (new) and "Custom Commandline Arguments: "
That way, you can install the PIP-Package even though it is not displayed.

Example 2: Many Chocolatey-Packages are recognised by winget. If I just update the packages with winget, I might run into file-permission errors. If I can overwrite the source, this would be a trivial problem.

**Comment by marticliment** [comment]
In this case, you need to select the package from the source you want it from.

I am aware that some chocolatey packages are missing, but from the rest of the sources all the packages are lisrted, and you should choose the one you are willing to install.

![image](https://github.com/marticliment/WingetUI/assets/53119851/db953e3a-6b42-48ef-bc60-23f620e9856c)


> Example 2: Many Chocolatey-Packages are recognised by winget. If I just update the packages with winget, I might run into file-permission errors. If I can overwrite the source, this would be a trivial problem.

In this case, just blacklist the packages you don't want winget to upgrade.


Please understand that packages with the same name but with different sources are treated as different packages, thus there's no easy way to __switch package manager_ as you are proposing.
