### ISSUE TITLE
[ENHANCEMENT] Show local installation details of detected packages in Updates tab

### ISSUE THREAD

**Issue by 2tbc1887** [marticliment/WingetUI#1185]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

The Package Details button, when on the Updates tab, could be improved by showing the location of the currently installed version of the package

### Describe how this improvement could help users.

Occasionally, I see a piece of software in the updates list that is duplicated, or may have updates managed by another application. In these cases, this feature would make it easier to determine if there's an issue, or if I should avoid updating it.

**Comment by marticliment** [comment]
Package manages don't provide this information, so this won't be really possible
