### ISSUE TITLE
[FEATURE REQUEST] Download the installation package directly and manually install it

### ISSUE THREAD

**Issue by 858622025** [marticliment/WingetUI#1201]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Winget often successfully downloads new installation packages, but there are issues with the installation process.I would like to add an option to download the installation package directly and manually install it in the foreground.

### Describe how this new feature could help users.

Frontend installation may not result in backend installation errors, and some failure messages are clearer than those generated by backend installation.

**Comment by Otiel** [comment]
👍

I also would like packages to be downloaded automatically to save some time, but I prefer to update them manually (to monitor their setup, to interactively update some of them, to choose when to update some of them...).
