### ISSUE TITLE
[ENHANCEMENT] Package installed indicator.

### ISSUE THREAD

**Issue by Pipixel** [marticliment/WingetUI#1209]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Having the installation status could help avoid confusion when installing a package without having to check whether it is already installed.

### Describe how this improvement could help users.

Knowing whether a package is already installed could save you the eventual reinstallation, or make sure it isn't already installed and can improve the accessibility. The image below gives a brief idea of what this might look like.

![wingetui_C3TYTkEZzx](https://github.com/marticliment/WingetUI/assets/66361896/47dfbf55-6fe8-4386-8481-5fc9f52db6d8)

**Comment by marticliment** [comment]
I tried a system of labeling, but it turned out to be so laggy that it was unusable. I like this approach of the icons

**Comment by Pipixel** [comment]
I use a label from Microsoft fluent icon's font

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/0c83170a-1985-4129-af24-6dc466be6b99)
Tooltips and colored icons will do the job.
