### ISSUE TITLE
Automatically refresh installed applications list after installing or updating packages

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#121]
After installing or updating a package you have to click the refresh icon near the search bar to see the new package or new version displayed under "Installed applications". I know it's not a big deal, but I think it would be easier for the user if the list were updated automatically after the installation or update. 

- [X] Uninstalled app would appear again after searching https://github.com/martinet101/WingetUI/commit/90bedb9770823e62bb51074b2a1c90a260e13a73
- [X] Refresh uninstall list when an app is installed/updated https://github.com/martinet101/WingetUI/commit/3c58efe93260dd44a636df7d21605313403b674e
- [x] Updated app appears again after searching
- [x]  Apps uninstalled with interactive uninstall will reappear in the uninstall section
- [x]  Recently installed apps appear in the uninstall section even when they shouldn't be in the search results
- [x] If you install the same app twice or more, it will also appear that number of times in the uninstall section
- [x] Refresh update list when an app is uninstalled (see [video](https://github.com/martinet101/WingetUI/issues/121#issuecomment-1258466009))
- [x] using double-click to install option doesn't add entry to the uninstall list
 - [x] Externally-installed apps not showing

**Comment by martinet101** [comment]
That might be difficult, because most of the times the uninstallers don't share the same IDs with the uninstallers, especially on Winget, but this can be studied

**Comment by ppvnf** [comment]
> That might be difficult, because most of the times the uninstallers don't share the same IDs with the uninstallers, especially on Winget, but this can be studied

What about refreshing all uninstallers like clicking the refresh icon does?

**Comment by martinet101** [comment]
Yes, but that would be excessive (like in terms of performance), and i guess not much people would install an app to right-after uninstall it. 

I don't know, honestly, i'll study this but can't guarantee anything

**Comment by ppvnf** [comment]
I agree that this issue is a low priority one, but if someday you get into it I also noticed that even after uninstalling a package its update won't disappear if you don't refresh the "software updates" list

**Comment by martinet101** [comment]
> I agree that this issue is a low priority one, but if someday you get into it I also noticed that even after uninstalling a package its update won't disappear if you don't refresh the "software updates" list

Uninstalls _should_ actually disapear. Does this happen always?

**Comment by ppvnf** [comment]
> 

It only happened once with me a few days ago when I uninstalled something (I forgot what it was) and then went to the update section in order to update everything. That's when I saw the uninstalled app in the list, then refreshed it and the uninstalled app was gone and I was able to update everything else normally. I don't know what would happen if I updated the uninstalled app, but unfortunately I forgot to take screenshots and I don't know how to reproduce it

**Comment by ppvnf** [comment]
> Uninstalls _should_ actually disapear. Does this happen always?

I just noticed that if you uninstall something then search for the uninstalled program again it will reappear and the number of packages will stay the same until you refresh the list.


https://user-images.githubusercontent.com/73800734/190901020-ff296104-727c-4dad-8ad3-2f557275e666.mp4

**Comment by martinet101** [comment]
Ok, that is not supposed to happen

**Comment by ppvnf** [comment]
> It only happened once with me a few days ago when I uninstalled something (I forgot what it was) and then went to the update section in order to update everything. That's when I saw the uninstalled app in the list, then refreshed it and the uninstalled app was gone and I was able to update everything else normally. I don't know what would happen if I updated the uninstalled app, but unfortunately I forgot to take screenshots and I don't know how to reproduce it

I forgot to make a video about this last week. Here you go:

https://user-images.githubusercontent.com/73800734/192356804-2bcbcfed-4efc-42c0-ae4d-c07517fa75bd.mp4

**Comment by ppvnf** [comment]
This issue is about 3 different things. I will try to organize them:

- [X] Uninstalled app would appear again after searching https://github.com/martinet101/WingetUI/commit/90bedb9770823e62bb51074b2a1c90a260e13a73
- [ ] Uninstalled apps appear in the update section
- [ ] Update uninstaller list when an app is installed/updated

**Comment by martinet101** [comment]
Done!

**Comment by ppvnf** [comment]
@martinet101 Thanks. I thought this feature would take a long time! Just to be sure since you received a lot of messages today/yesterday. Did you see the checklist I made yesterday https://github.com/martinet101/WingetUI/issues/121#issuecomment-1258473043?

**Comment by martinet101** [comment]
No, I did not see it. I'll take a look tomorrow

**Comment by ppvnf** [comment]
> No, I did not see it. I'll take a look tomorrow

Okay, take your time! Also, this might be related https://github.com/martinet101/WingetUI/issues/124

**Comment by ppvnf** [comment]
>     * [x]  Refresh uninstall list when an app is installed/updated [3c58efe](https://github.com/martinet101/WingetUI/commit/3c58efe93260dd44a636df7d21605313403b674e)

>     * [ ]  Uninstalled apps appear in the update section (see video above)


I realized that I could have written "Uninstalled apps appear in the update section (see video above)" as "Refresh update list when an app is uninstalled", the opposite of 3c58efe

**Comment by martinet101** [comment]
Well, worth giving it a check, right?

**Comment by ppvnf** [comment]
I think this checklist is kinda confusing. I am gonna move it to the top of the page. Also, I've noticed that recently installed apps appear in the uninstall section even when they shouldn't be in the search results (if you clear the search result and search again this problem won't happen though)

**Comment by ppvnf** [comment]
I've added to the todo:
- [ ] If you install the same app twice or more, it will also appear that number of times in the uninstall section
Like the other, this bug disappears if you refresh the list

**Comment by ppvnf** [comment]
> * If you install the same app twice or more, it will also appear that number of times in the uninstall section 

[46816ad](https://github.com/martinet101/WingetUI/commit/46816adc20a885d71ff431fdaddd10ab56ee7488) apparently fixes this task

**Comment by ppvnf** [comment]
> * If you install the same app twice or more, it will also appear that number of times in the uninstall section

On 46816adc20a885d71ff431fdaddd10ab56ee7488 Installing with double-click when you have this option checked doesn't trigger the bug:

![Captura de tela 2022-10-12 111845](https://user-images.githubusercontent.com/73800734/195367894-f812449a-7fd6-4409-aec2-1635cf10d3d4.png)

**Comment by martinet101** [comment]
> On [46816ad](https://github.com/martinet101/WingetUI/commit/46816adc20a885d71ff431fdaddd10ab56ee7488) Installing with double-click when you have this option checked doesn't trigger the bug:

Then this is a bug, since it _should_ have this behaviour.

Also, this duplication of entries neds to be fixed

**Comment by ppvnf** [comment]
> * using double-click to install option doesn't add entry to the uninstall list

@martinet101, you are right. I've added this to the task list. I'm starting to think that "Refresh uninstall list when an app is installed/updated" was a bad idea since it created so many unforeseen problems

**Comment by ppvnf** [comment]
Those seem fixed:

> * [x] Apps uninstalled with interactive uninstall will reappear in the uninstall section
> * [x]   Recently installed apps appear in the uninstall section even when they shouldn't be in the search results

**Comment by ppvnf** [comment]
This issue seems fixed, however I had a problem with one package I was testing (https://github.com/ScoopInstaller/Extras/pull/9741#issuecomment-1504099566).
Maybe because it uses a script that kills explorer it is not showing in the uninstall section after being installed

**Comment by marticliment** [comment]
It shouldn't affect. However, i will test it out and let you know

**Comment by marticliment** [comment]
It is a different issue. 

This isste requested the feature, and the feature is not working except in some specific cases (that still need test).
If the issue happens to reappear, i'll open a new issue, because the issue is not so relevant to this feature request.
