### ISSUE TITLE
[BUG] can't use after reinsall OS to win10

### ISSUE THREAD

**Issue by ted423** [marticliment/WingetUI#1221]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

```
PS D:\Program Files\WingetUI\winget-cli> .\winget.exe search git
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x800f024b : ļĹϣֵָĿ¼ļСļ𻵻򱻴۸ġ
```

but I can use windows' version
![image](https://github.com/marticliment/WingetUI/assets/7042766/e58a4204-8c6b-4c45-bc09-254ae4f00ced)

can't reset the winget sources.

```
This script will reset winget sources.
You might be asked for administrator rights up to three times during this process.
Press <ENTER> to continue or CLOSE THIS WINDOW to abort this process. Please wait...
winget path: "D:\Program Files\WingetUI\resources\..\winget-cli\winget.exe"
Performing reset...
Info: Elevation allowed for process Id 4668 and children.
Warning: Cache is a security risk. Use `gsudo cache off` (or `-k`) to go back to safety.
An unexpected error occurred while executing the command:
0x800f024b : ļĹϣֵָĿ¼ļСļ𻵻򱻴۸ġ
An unexpected error occurred while executing the command:
0x800f024b : ļĹϣֵָĿ¼ļСļ𻵻򱻴۸ġ
Resetting all sources...Done
Info: Cache session closed.
Task completed!
You can now close this window and refresh your wingetui listings
请按任意键继续. . .
```

### Steps to reproduce the issue

try 1.7.1 2.0.1 2.1.0

### WingetUI Log

```text
🟢 Winget search for installed packages finished with 0 result(s)
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🔵 Starting Winget search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Main application loaded...
Win32Mica Error: win32 version 19045 is not supported
50
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Starting Winget search for available packages
🟠 Winget cache file exists but is empty!
🔵 Starting Winget package caching
🟢 Winget packages cached successfuly
🔵 Starting Winget search for available packages
🟠 Winget cache file exists but is empty!
🔴 Could not load Winget packages, returning an empty list!
🟢 Total packages: 0
🟠 Unable to retrieve latest announcement
HTTP Error 502: Bad Gateway
🔵 Loading log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x800f024b : ļĹϣֵָĿ¼ļСļ𻵻򱻴۸ġ------------------
Failed when opening source(s); try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
0x800f024b : ļĹϣֵָĿ¼ļСļ𻵻򱻴۸ġ
```

**Comment by marticliment** [comment]
hello, does your new user directory contain non-standard characters?

**Comment by ted423** [comment]
> hello, does your new user directory contain non-standard characters?
just Priston
it's same with previous OS(win 11) account , I  override the appdata with previous one.

I had delete .wingetui after wingetUI not work

**Comment by ted423** [comment]
It seems that there is still a problem after the automatic upgrade.
I uninstall it and delete wingetui, .wingetui folder, some pythons folders , this computer has not yet installed python.
seems source reset no more garbled characters but said 系统找不到指定的路径(The system can not find the specified path)

**Comment by ted423** [comment]
seems same when I run C:\Users\Priston\AppData\Local\Programs\WingetUI\PackageManagers\winget-cli_x64\winget.exe

**Comment by ted423** [comment]
```
PS C:\Windows\system32> C:\Users\Priston\AppData\Local\Programs\WingetUI\PackageManagers\winget-cli_x64\winget.exe source reset
An unexpected error occurred while executing the command:
0x800f024b : ļĹϣֵָĿ¼ļСļ𻵻򱻴۸ġ
PS C:\Windows\system32> winget source reset
如果指定了--force 选项，则将重置以下源：
名称    参数
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
PS C:\Windows\system32> C:\Users\Priston\AppData\Local\Programs\WingetUI\PackageManagers\winget-cli_x64\winget.exe source reset --force
Resetting all sources...Done
```

**Comment by ted423** [comment]
```
C:\Users\Priston\AppData\Local\Programs\WingetUI\PackageManagers\winget-cli_x64\winget.exe -v
v1.5.1881
PS C:\Windows\system32> winget -v
v1.5.1572
```

**Comment by marticliment** [comment]
And what happens if you run the reset sources option from WingetUI settings?

**Comment by ted423** [comment]
> And what happens if you run the reset sources option from WingetUI settings?

I figure it out
I use winget settings found winget profile is C:\Users\Priston\AppData\Local\Microsoft\WinGet
and I delete it all.

**Comment by ted423** [comment]
There may be some permission issues in the profile of the previous installation system users?

**Comment by ted423** [comment]
Another possibility is that I seemed to be overridden in the middle of using wingetui at the time, and the configuration may be broken

**Comment by marticliment** [comment]
I will further study that, but this might only be a one-time only issue
