### ISSUE TITLE
[BUG] Access is Denied

### ISSUE THREAD

**Issue by SuperFurias** [marticliment/WingetUI#1222]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I started my computer. and WingetUI autoupdate started. all good up to now. but the installer gave me every time "access is denied" and i started screaming. good. after that, i started looking if some file was using the files inside wingetui, like last time #1125 but no. after some more screaming i went to the installation folder. I right-clicked, selected Properties, then Security... and I noticed that I didn't have any permissions for that folder. EVEN AS AN ADMINISTRATOR. So I said, "Well, no wonder that thing won't install, the folder has its weird shitty permissions." Then I right-clicked on the entire folder, chose "Take Ownership," and in the end... the program updated without any issues.

### Steps to reproduce the issue

i don't really know. it was a problem with the folder, not the program itself..

### WingetUI Log

```text
I cannot provide it, the program crashes (Not Responding) when I try to export the file. And the "copy to clipboard" function is not working.
```

### Package Managers Logs

```text
I cannot provide it, the program crashes (Not Responding) when I try to export the file. And the "copy to clipboard" function is not working.
```

### Relevant information

Nothing strange

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/34806112/52f7e418-a40b-4ba7-8774-fe07a7f1308c)
![image](https://github.com/marticliment/WingetUI/assets/34806112/9ceec2c9-2f95-46df-94ab-130dd10426ab)
![image](https://github.com/marticliment/WingetUI/assets/34806112/0417d9d4-a70a-40bf-ba75-32965ebb92cc)

**Comment by marticliment** [comment]
WingetUI *can't* be installed in a directory that does require administrator preferences due to the requirements of certain components of the package managers.

Please install WingetUI on the default location

**Comment by HoffmannTom** [comment]
@marticliment 
Thanks for the information. I adjusted the NTFS permissions to enable write access.
