### ISSUE TITLE
[ENHANCEMENT] Screenshots to Readme

### ISSUE THREAD

**Issue by oenu** [marticliment/WingetUI#1223]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Screenshots for readme

### Describe how this improvement could help users.

Give an idea of what the gui looks like

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/3fb91e36-2263-4b5b-8a97-cf89d0a8bdad)
![image](https://github.com/marticliment/WingetUI/assets/53119851/8513aab9-13a9-498f-a818-69c14ab528b5)
