### ISSUE TITLE
[ENHANCEMENT] automatically remove package from blacklist if it gets updated

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1224]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

suppose you block the update of a specific version but a new/different version is released and the package get updated. in this case I think it would make sense to remove it from the blacklist automatically because blocking that older version no longer makes sense.

### Describe how this improvement could help users.

<img width="960" alt="Screenshot 2023-07-19 221235" src="https://github.com/marticliment/WingetUI/assets/73800734/07fb84a2-8c5a-45da-ac28-96f37b5ae6c9">
<img width="500" alt="Screenshot 2023-07-19 221210" src="https://github.com/marticliment/WingetUI/assets/73800734/e8604fdd-73d9-454a-bfd6-00665e2454a0">

**Comment by marticliment** [comment]
makes sense to me

**Comment by kotenok2000** [comment]
Doesn't it already do that?

**Comment by marticliment** [comment]
It does inherently, but the entry is left there, since the app is not blacklisted, but rather a specific version of it
