### ISSUE TITLE
[CRASH] (Enter your description here)

### ISSUE THREAD

**Issue by TukaWarrior** [marticliment/WingetUI#1226]
Hard crash experienced

Error details : 
```
                        OS: Windows
                   Version: ('10', '10.0.23493', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
                  Language: Unknown
               APP Version: Unknown
                   Program: WingetUI
           Program section: Main script

-----------------------------------------------------------------------------------------



WingetUI Log:




Traceback (most recent call last):
  File "__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File ".\customWidgets.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File ".\genericCustomWidgets.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File ".\tools.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 64, in __call__

RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'<class 'RuntimeError'>: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

**Comment by Medard22** [comment]
I have exactly the same issue since yesterday.

**Comment by sbuethe** [comment]
Me too. Re-installing (even previous versions) did not help.

**Comment by marticliment** [comment]
Previous versions don't work? They should

**Comment by marticliment** [comment]
Hello,

do you have .NET runtimes installed?

**Comment by sbuethe** [comment]
Hi,

Yes, I have Visual Studio installed and .NET 4.8.1/.NET 7 among others… Lots of .NET runtimes installed.

Best regards

Sven



Am 29.07.2023 um 20:15 schrieb Martí Climent ***@***.***>:

﻿

Hello,

do you have .NET runtimes installed?

**Comment by marticliment** [comment]
Can you please attempt to install .net 4.7.2?

**Comment by sbuethe** [comment]
It is installed already. Not working, unfortunately.

I unistalled version 2.0.2 and reinstalled version 2.1.0 beta which was working before installing 2.0.2. It does not work anymore either. Same error log as above.

**Comment by marticliment** [comment]
Dear users, 

a pull request with a fix is coming.

Meanwhile, please install WingetUI 2.1.0 beta, that won't get autoupdated to version 2.0.2.
The link to download this release is the following: https://github.com/marticliment/WingetUI/releases/download/2.1.0-beta/WingetUI.Installer.exe

**Comment by Medard22** [comment]
Hello Marti, just to let you know, many users who speak slavic languages,
like Czechs, Slovaks and Poles make their Windows accounts name and thus
their user folder with non-ASCII characters. Moving part of the
installation to the user folder won't solve the problem and the crash will
still happen. I pointed the installation to Program Files and while the
installer required administrator privileges, it should fix the problem for
the time being.
Thank you for developing WingetUI and for the quick response and fix.

Michal.

**Comment by marticliment** [comment]
hello @Medard22 , this is how now it is supposed to work.


Wingetui will be installed to program files

**Comment by Medard22** [comment]
Ah sorry, I accidentally installed the 2.0.2 instead of the 2.1.0 beta.
Stupid me :D You are right, the installer now points to Program Files and
everything works 👍

M.
