### ISSUE TITLE
[FEATURE REQUEST] (Add the ability to select a drive to store temporary installation files)

### ISSUE THREAD

**Issue by mac4her392** [marticliment/WingetUI#1227]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Before installing or updating a program, winget first downloads the installation file/package itself, so it would be nice to be able to specify a path to download such temporary installation files to, for example, the work SSD or HDD, so as not to wear out the system SSD.

### Describe how this new feature could help users.

Will allow to increase the life of the system SSD.

**Comment by marticliment** [comment]
WingetUI does not handle the download and install process, and therefore it does not handle the temporary locations.

You will need to tweak winget/chocolatey/the package managers you are using to use your ddesired temp folder
