### ISSUE TITLE
Allow specifying installation scope in Winget

### ISSUE THREAD

**Issue by sitiom** [marticliment/WingetUI#123]
`winget install` has a parameter to specify the installation scope of the program:
```console
--scope                      Select install scope (user or machine)
```

It would be great if WingetUI has an option equivalent to this on installation.

**Comment by martinet101** [comment]
Yes, this could be a thing

**Comment by ppvnf** [comment]
I think scope will be possible using https://github.com/marticliment/WingetUI/issues/140#issuecomment-1515124085

**Comment by sitiom** [comment]
It should be built-in to WingetUI

**Comment by marticliment** [comment]
Yes, this feature will come soon
