### ISSUE TITLE
[BUG] section "Component-information" shows list index out of range

### ISSUE THREAD

**Issue by erwindon** [marticliment/WingetUI#1233]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

section "Component-information" shows `list index out of range` in the column "Version" for component "Scoop"

### Steps to reproduce the issue

Open WingetUI
Select "About WingetUI"

### WingetUI Log

```text
the wingetui logs cannot be copied (that's a different issue)
```

### Package Managers Logs

```text
the package manager logs cannot be copied (that's a different issue)
```

### Screenshots and videos

![afbeelding](https://github.com/marticliment/WingetUI/assets/3663742/2852ee54-129e-459f-858f-6ed93c27fa2b)

**Comment by ppvnf** [comment]
Do you have Scoop installed?
What happens if you type `scoop status` on cmd/pshell?

**Comment by erwindon** [comment]
scoop is not installed here and it is disabled in the settings.
`scoop status` --> `'scoop' is not recognized as an internal or external command, operable program or batch file.`
