### ISSUE TITLE
[BUG] Scoop manifest link broken

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1234]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I have encountered a few situations when this seems to be the case:

1. Packages from https://github.com/Calinou/scoop-games (scoop bucket add games)
2. Packages from custom buckets (ex: https://github.com/Zliced13/MyScoop)
3. Packages from nirsoft (https://github.com/ScoopInstaller/Nirsoft/blob/master/bucket/shmnview.json)
This seems to be an exception as the local json and the github one have different names
[shellmenuview.json.txt](https://github.com/marticliment/WingetUI/files/12138173/shellmenuview.json.txt)
4. https://github.com/marticliment/WingetUI/issues/1234#issuecomment-1696337199

### WingetUI Log

```text
n/a
```

### Package Managers Logs

```text
n/a
```

**Comment by ppvnf** [comment]
<img width="482" alt="Screenshot 2023-08-28 220810" src="https://github.com/marticliment/WingetUI/assets/73800734/47876414-0a5b-49a1-851a-6dab63908d30">
non portable has problem in manifest and source

**Comment by marticliment** [comment]
See #1325

**Comment by marticliment** [comment]
After some changes to the scoop package manager this appears to work now.
Can you please retest on the latest commit?

**Comment by ppvnf** [comment]
I am unable to click it

<img width="493" alt="Screenshot 2023-09-03 100402" src="https://github.com/marticliment/WingetUI/assets/73800734/f5d473e1-cfc5-44b1-99b8-900741382e59">

<img width="496" alt="Screenshot 2023-09-03 100017" src="https://github.com/marticliment/WingetUI/assets/73800734/a03269d8-fdfb-44f1-a050-95ed3cea3c68">

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/860f525c-cd68-41b6-a18a-4983219a5708)
For me, the nirsoft one works fine.

**Comment by ppvnf** [comment]
The problem might be that I am running the .py file directly instead of the binary because I am getting this error when trying to build it 
<img width="251" alt="Screenshot 2023-09-03 130326" src="https://github.com/marticliment/WingetUI/assets/73800734/d7315625-9256-4364-b3c1-eb56781f58f5">

**Comment by marticliment** [comment]
This issue is caused due to Python 3.11.4+ is not compatible with PyInstaller 5.9.0.

Either downgrade to Py3.11.3 or change requirements.txt to use a newer PyInstaller version (may trigger virus issues)

**Comment by ppvnf** [comment]
I managed to build, but the manifest links are still incomplete

<img width="551" alt="Screenshot 2023-09-03 234123" src="https://github.com/marticliment/WingetUI/assets/73800734/4e0221da-2be6-497a-a0ff-7c88d66d5b9c">

also for some reason I am getting a bunch of chocolatey packages wrongly appearing as installed 
<img width="959" alt="Screenshot 2023-09-03 234157" src="https://github.com/marticliment/WingetUI/assets/73800734/0ffa3f93-d115-4aca-b2b4-e068f81b6737">

**Comment by marticliment** [comment]
Can you please attach your logs?

**Comment by ppvnf** [comment]
[log package.txt](https://github.com/marticliment/WingetUI/files/12526013/log.package.txt)
[log wingetui.txt](https://github.com/marticliment/WingetUI/files/12526014/log.wingetui.txt)

**Comment by ppvnf** [comment]
> also for some reason I am getting a bunch of chocolatey packages wrongly appearing as installed

should I open a new issue for this?

**Comment by marticliment** [comment]
Yes, please

**Comment by ppvnf** [comment]
this issue also, couldn't it be because I am using latest Python/Pyinstaller?

**Comment by ppvnf** [comment]
I have installed the latest beta and the bug remains

**Comment by marticliment** [comment]
> this issue also, couldn't it be because I am using latest Python/Pyinstaller?

Latest beta does use non-latest, so this is not the issue

**Comment by ppvnf** [comment]
Maybe related. does it look the same to you?

<img width="560" alt="Screenshot 2023-09-19 182953" src="https://github.com/marticliment/WingetUI/assets/73800734/1897cc4d-c595-47b4-a4b3-a3c167b41404">

**Comment by marticliment** [comment]
no, it should not look like this

**Comment by marticliment** [comment]
please run `scoop bucket list` on a cmd window

**Comment by ppvnf** [comment]
<img width="591" alt="Screenshot 2023-09-19 212258" src="https://github.com/marticliment/WingetUI/assets/73800734/722c5fdf-8c6d-44c4-84e2-296599ff1c1e">

**Comment by ppvnf** [comment]
Replacing the ~ with the url beginning should work, right?

**Comment by ppvnf** [comment]
I realized I uninstalled git, reinstalling it fixed the problem with the tilde.

**Comment by marticliment** [comment]
> Replacing the ~ with the url beginning should work, right?

Custom buckets won't work then.


Since this would not happen under normal circumstances (scoop requires git to work, and git is installed alongside scoop), I will close this issue

**Comment by ppvnf** [comment]
about the original issue, I have tested it and the only case it doesn't work (broken link) is for this bucket (if the package is global) MyScoop                      https://github.com/Zliced13/MyScoop
<img width="491" alt="Screenshot 2023-09-19 214739" src="https://github.com/marticliment/WingetUI/assets/73800734/fd7a8092-03a1-4746-a65a-b1133271ba6a">

**Comment by marticliment** [comment]
It does work now for me, please test the latest code

**Comment by ppvnf** [comment]
In in the discovery section it works, but on the installed section I have the same problem as in https://github.com/marticliment/WingetUI/issues/1234#issuecomment-1726426797
