### ISSUE TITLE
[FEATURE REQUEST] Publish on Microsoft Store

### ISSUE THREAD

**Issue by AsciiWolf** [marticliment/WingetUI#1237]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Consider publishing WingetUI on the Microsoft Store.

### Describe how this new feature could help users.

It would make WingetUI much easier to install for regular, non-experienced users.

**Comment by AsciiWolf** [comment]
Currently, new users have to either search for and manually install the .exe file or use a command line (winget or scoop) to install WingetUI. This it not ideal and not suitable for non-experienced users.

**Comment by marticliment** [comment]
They won't allow WUI on MSStore, since it _induces to installation of third-party, untested, potentially harmful software._

I have subvmitted WUI 5 times at least. All of them with the same result

**Comment by AsciiWolf** [comment]
Ah, I did not know that. :-( Did you try to publish a WingetUI build that only supports WinGet sources? They could make an exception in that case.

**Comment by marticliment** [comment]
they did not
