### ISSUE TITLE
[BUG] chocolatey 2.1 not working

### ISSUE THREAD

**Issue by riedel** [marticliment/WingetUI#1238]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

 I am using they system chocolatey installation and it is not showing anything

In the logs I get:

```
----Chocolatey
Chocolatey v2.1
Invalid argument --locaI-onIy. This argument has been removed from the list command and cannot be used.
```

### Steps to reproduce the issue

Run update on wingetui 2.0.2 with chocolatey 2.1.0 installed

### WingetUI Log

```text
copying to clipboard does not work for me
```

### Package Managers Logs

```text
copying to clipboard does not work for me
```

**Comment by marticliment** [comment]
Hello,

For the time being please try reinstalling WingetUI. Chocolatey should get downgraded automatically.

**Comment by marticliment** [comment]
This issue will be fixed on the next version
