### ISSUE TITLE
[FEATURE REQUEST] Support for macOS and Linux (+GNU)

### ISSUE THREAD

**Issue by upintheairsheep** [marticliment/WingetUI#1241]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

This proposal is to port WinGetUI to macOS and Linux, but do not include the WinGet and MSStore source, only the pip and npm support, later adding support for apt for Linux and brew and cask for macOS.

### Describe how this new feature could help users.

This would allow macOS and Linux users to be able to manage their packages the same way as Windows users do.

**Comment by marticliment** [comment]
This looks interesting...  MacOS will be difficult due to system restrictions, but linux could work well...

**Comment by upintheairsheep** [comment]
> This looks interesting... MacOS will be difficult due to system restrictions, but linux could work well...

Additionally, the Linux package managers can be added to Windows in the form of a connection to Windows Subsystem for Linux

**Comment by marticliment** [comment]
Hello,

I am afraid this will not be part of WingetUI in the near future.

I am sorry
