### ISSUE TITLE
[BUG] (unhandled exception)

### ISSUE THREAD

**Issue by kernelplv** [marticliment/WingetUI#1250]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Hello. Today WingetUI decided to update to 2.0.3. The installation was not completed because an exception occurred. I am attaching a screenshot. 
For me, the solution is obvious and I don’t need an answer, I just decided to share the bug.

Thank you.
![wingetui_XrL78MfD99](https://github.com/marticliment/WingetUI/assets/4732036/6f1a39de-b47a-4fb1-8f29-133b5dff6c54)

### WingetUI Log

```text
                     OS: Windows
                   Version: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
                  Language: Unknown
               APP Version: Unknown
                Executable: C:\Program Files\WingetUI\wingetui.exe
                   Program: WingetUI
           Program section: Main script

-----------------------------------------------------------------------------------------



WingetUI Log:




Traceback (most recent call last):
  File "C:\SomePrograms\WingetUI-Store\wingetui_bin\__init__.py", line 2174, in <module>

ModuleNotFoundError: No module named 'win32api'
```

### Package Managers Logs

```text
The application no longer starts, I can’t get these logs.
```

**Comment by marticliment** [comment]
> For me, the solution is obvious and I don’t need an answer

I suppose you have reinstalled WingetUI, right?

As far as I can see, WingetUI is crashing due to missing files, but then the error handler is also crashing for whatever the reason.

**Comment by kernelplv** [comment]
> I suppose you have reinstalled WingetUI, right?

I did not reinstall WingetUI because you might need the program files.

**Comment by marticliment** [comment]
Then what is your solution to this issue?

**Comment by kernelplv** [comment]
I haven’t touched anything yet :) I said that I don’t need a solution because I’m sure I can solve the problem by reinstalling WingetUI, but I haven’t done it yet because the reinstallation may erase the directory hierarchy that you might need to investigate the cause of the bug.

If you don’t need any additional actions from me besides the bug report itself, then I will proceed with the reinstallation.

**Comment by marticliment** [comment]
No, you should be able to reinstall without uninstalling first, and you will not lose any data

**Comment by kernelplv** [comment]
Unfortunately, the automatic (after closing the program) update of WingetUI could not complete correctly, as I mentioned in my first message. Now I have two directories C:\Users\kerne\AppData\Local\Programs\WingetUI and C:\Program Files\WingetUI.

I have nothing to lose, I can delete both directories and install a fresh WingetUI. If no additional information is required from me, then the bug can be closed :)

**Comment by marticliment** [comment]
> Unfortunately, the automatic (after closing the program) update of WingetUI could not complete correctly

This was actually the intended result, and then when WingetUI was launched from C:\Program Files\WingetUI would take care of the duplicated files and shortcuts...

**Comment by kernelplv** [comment]
No worries, the main thing is that the error was caught.
