### ISSUE TITLE
[BUG] Lists cannot be scrolled on touch screens.

### ISSUE THREAD

**Issue by ottozumkeller** [marticliment/WingetUI#1267]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

If you have a laptop with a touch screen, unlike other apps, WingetUI does not allow you to drag your finger over a scrollable area to scroll it. Instead, only the item under the finger is highlighted, as when hovering with the mouse. The only way to scroll is to drag the bar on the side, but this is relatively difficult with one finger.

### Describe how this improvement could help users.

This improvement would obviously enhance the user experience and usability (especially on touch and mobile devices).

**Comment by marticliment** [comment]
Hi, 

Does scrolling with two fingers on the touchscreen work?

**Comment by ottozumkeller** [comment]
I actually didn't think of that at first, but it works with two fingers. Still, it would be cool if you could scroll with just one finger like in other apps.
