### ISSUE TITLE
[ENHANCEMENT] set environment variable path for chocolatey packages

### ISSUE THREAD

**Issue by candrapersada** [marticliment/WingetUI#1268]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

will there be support for automatically set path environment variable `choco-cli\bin`?

### Describe how this improvement could help users.

set path environment variable for `aria2c` `wget` `ffmpeg` and others.

**Comment by neoOpus** [comment]
I agree that this would be very useful and time saving

**Comment by marticliment** [comment]
Would this feature be useful on the installer?
