### ISSUE TITLE
[ENHANCEMENT] (Use less RAM when in the background)

### ISSUE THREAD

**Issue by mooms06** [marticliment/WingetUI#1277]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I have noticed that WingetUI use a relatively high amount of RAM, even when only launched in background (its the same when in the foreground actually).
![image](https://github.com/marticliment/WingetUI/assets/25405517/a1a5a69f-5023-4c26-a5b1-fa6ff2d3cd3e)

Since WingetUI is launched at startup, and is a resident program, can you consider using less resources when the program is in the background ? maybe not launching the UI, since it's unneeded ? The only function needed is the periodical search for updates isn't it ?

Thank you for reading.

### Describe how this improvement could help users.

Using less resources (RAM), on machines with only 4 or 8 GB of RAM can make a difference.

**Comment by marticliment** [comment]
Hello,

WingetUI has been profoundly optimized. Before, it used to require ~300mb when idling, more when active.

Optimisations are always being applied, but sometimes they are not easy do.

Of course, i will always try to improve WingetUI in terms of resource usage
