### ISSUE TITLE
[BUG] Forgetting Install options

### ISSUE THREAD

**Issue by gabriel-vanca** [marticliment/WingetUI#1291]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

After installing a winget package with certain installation options (architecture, scope etc), those options disappear when going to the "installed packages" tab and refreshing the packages. Everything goes back to "Default".

Furthermore, the installation options aren't being exported with he packages, meaning that the Export/Import feature is basically useless.

### Steps to reproduce the issue

(see above)

### WingetUI Log

```text
n/a
```

### Package Managers Logs

```text
n/a
```

### Relevant information

I am running the latest version.

### Screenshots and videos

not necessary

**Comment by marticliment** [comment]
> those options disappear when going to the "installed packages" tab and refreshing the packages

those details are not available since you cannot change them when uninstalling a package. Opening the details tab from the uninstall tab shows an option to uninstall, and therefore it does show all the available options for the uninstaller.

However, I see this makes sense
