### ISSUE TITLE
[BUG] System error DLL missing after install on fresh Win 11 Pro 22H2

### ISSUE THREAD

**Issue by ThiloL** [marticliment/WingetUI#1304]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

winget.exe - System error
CONCTR140.dll missing after installing wingetui via
`winget install wingetui`
on a fresh Win 11 Pro 22H2 installation
<img width="306" alt="image" src="https://github.com/marticliment/WingetUI/assets/2923889/1cfd2906-89b1-4a39-83f8-37b0769928ed">

### Steps to reproduce the issue

Fresh install of Win 11 Pro 22H2
installing wingtet via `winget install wingetui`
starting wingetui

### WingetUI Log

```text
no log found
```

### Package Managers Logs

```text
no log found
```

### Relevant information

VCredist seems to be missing in installation via WINGET command line

**Comment by marticliment** [comment]
hello, do you have ms visual c++ installed on your system?

**Comment by ThiloL** [comment]
It was a fresh Win 11 Pro 22H2 installation. I'm not sure, if there is a vc++ redist onboard.
If wingetui needs it, there should be a dependency in the winget manifest.

**Comment by marticliment** [comment]
The native installer does bundle vcredist. Maybe winget skips it. I am going to study this

**Comment by PedEchsing** [comment]
Yah,it skips it!
Brand new (cheap) Win11 Home tablet. Brand new install of MS Winget from store updates.
Brand new fresh install winget install wingetui.
Brand new error CONCTR140.dll not found error.
Brand new FIX of downloading installer and running that over top the winget install.
And yes, I did a winget install/uninstall cycle and it error-ed on both installs.
DIDN'T get any of the other errors, tho.
