### ISSUE TITLE
[ENHANCEMENT] (Offer more information about available packages)

### ISSUE THREAD

**Issue by andresgarcia0313** [marticliment/WingetUI#1308]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Hello, I am a WingetUI user and I would like to recommend a new enhancement that I think could enrich and improve the information about the available packages. This is to offer more data about the packages, such as size, license, release date, dependencies, etc.

The idea is that the application can obtain and display this data from repositories or package sources, as well as from other external or complementary sources, such as web pages, social networks, forums, etc. In this way, the user could have a more complete and detailed vision of the software they want to install or update.

The improvement could be implemented by adding a window or information panel that opens when a package is clicked, showing all the available data about it. The user could see the basic information such as name, version, description, etc. But you could also see additional information such as size, license, release date, dependencies, developer, official website, social networks, other users' comments, ratings, screenshots, videos , etc.

### Describe how this improvement could help users.

It would allow them to make more informed and conscious decisions when it comes to installing or updating packages, since they would be able to better understand the software and its features.
It would make it easier for them to access resources and content related to the packages, such as tutorials, guides, technical support, news, updates, etc.
It would give them a more interactive and dynamic experience with the app as they would be able to view and explore different kinds of information and media about the packages.
It would make them feel more confident and secure with the app as they would be able to check and contrast the information about the packages from different sources and perspectives.

I hope you like this idea and give me your feedback about it. Thank you for your attention and for your excellent work with WingetUI. 😊

**Comment by marticliment** [comment]
If you right-click a package and then select "Package details", you can get a preview of it.
![image](https://github.com/marticliment/WingetUI/assets/53119851/a164c68c-d29f-4be9-80cc-06733a9de969)

Is this what you meant?
