### ISSUE TITLE
[FEATURE REQUEST] (Add a cleaning and optimization function for the system after uninstalling the packages)

### ISSUE THREAD

**Issue by andresgarcia0313** [marticliment/WingetUI#1312]
### Please confirm these before moving forward

- [x] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Hello, I am a user of WingetUI and I would like to propose a new improvement that I think could improve the performance and cleanliness of the system after uninstalling the packages. It is about adding a cleaning and optimization function for the system after uninstalling the packages.

The idea is that the application can delete and free the files, records, folders or resources that remain in the system after uninstalling a package, as well as optimize the operation of the system after uninstallation. The user could choose whether to activate or deactivate this function, as well as customize the parameters or options of it.

The improvement could be implemented by adding an option in the settings or in the menu to access the cleaning and optimization function. The user could see a window or panel where they would be shown the steps and options to perform the cleaning and optimization. They could also see the progress and result of the operation.

### Describe how this new feature could help users.

It would allow them to free and recover space and resources from the system, thus improving its performance and speed.
It would facilitate the maintenance and organization of the system, thus avoiding possible conflicts, errors or incompatibilities caused by residual files or records.
It would offer them a more efficient and orderly experience with the application, as they could uninstall the packages without leaving a trace or affecting the operation of the system.
I hope you are interested in this idea and give me your opinion on it. Thank you for your attention and for your excellent work with WingetUI. 😊

**Comment by eidylon** [comment]
Not really sure this would be possible; the best it could probably do would be to delete the program's install folder, and anything left behind in that folder. 

Other than that, ... a program could write stuff literally **anywhere** on your system, in any folder, and in any location in the registry (there are some limitations, around UAC, permissions, etc., but for the sake of this conversation, we'll just call it **anywhere**). 

There's really no way for winget/winget-ui to know where any given program might've gone off and written stuff.

**Comment by andresgarcia0313** [comment]
Hello! I understand the concerns of the WingetUI developers. To address this challenge, we could consider a gradual approach: first, focus on removing files and records in specific, well-known uninstallation folders, especially the appdata folder or typical folders where various software store information, which are usually in the user folder and appdata, and cleaning the registry related to empty entries after the application is deleted. Then, over time, we could explore the option of searching for and cleaning residue in broader locations, always with due caution. This would ensure a safe and effective process. 😊👍

**Comment by eidylon** [comment]
I think if this was implemented at all, other than the install folder, it should all be behind a user prompt. 

Pop up a little dialog showing all the files WGUI _**thinks**_ should be cleaned, and let the user mark checkboxes for each one they want to delete. Anything else I think would be too risky.

**Comment by marticliment** [comment]
Hello,

I am afraid this will not be part of WingetUI in the near future.

I am sorry
