### ISSUE TITLE
[BUG] Borken html formatting chocolatey description

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1321]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

https://community.chocolatey.org/packages/open-shell
```

* = italic
** = bold
` = code
```

### Screenshots and videos

<img width="472" alt="Screenshot 2023-08-28 222538" src="https://github.com/marticliment/WingetUI/assets/73800734/f63860a1-036a-4d48-9403-4a361799fd36">

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/02f15253-d557-4040-8e18-f1f8a8a25c41)
