### ISSUE TITLE
[BUG] (can't update with wingetui source)

### ISSUE THREAD

**Issue by yangweijie** [marticliment/WingetUI#1324]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

cannot update by winget source
after search they say it because winhttps using openssl with tls1.2 
other source pip can normal update。
`openssl s_client -connect www.baidu.com:443 -tls1_2`

I don't know how to set for my windows. 
I had to open detail window right click download url to download update file manual install.

### WingetUI Log

```text
Searching for string ""
OverflowError
['- \r                                                                                                                        \r\r  █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 16.6 MB\r  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 16.6 MB\r  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 16.6 MB\r  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 16.6 MB\r  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 16.6 MB\r  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 16.6 MB\r  ████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 16.6 MB\r  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  8.00 MB / 16.6 MB\r  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  9.00 MB / 16.6 MB\r  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  10.0 MB / 16.6 MB\r  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  11.0 MB / 16.6 MB\r  █████████████████████▒▒▒▒▒▒▒▒▒  12.0 MB / 16.6 MB\r  ███████████████████████▒▒▒▒▒▒▒  13.0 MB / 16.6 MB\r  █████████████████████████▒▒▒▒▒  14.0 MB / 16.6 MB\r  ███████████████████████████▒▒▒  15.0 MB / 16.6 MB\r  ████████████████████████████▒▒  16.0 MB / 16.6 MB\r  ██████████████████████████████  16.6 MB / 16.6 MB\r                                                                                                                        \r\r   - \r                                                                                                                        \rFailed when searching source: msstore', 'An unexpected error occurred while executing the command:', 'SSL Error: WINHTTP_CALLBACK_STATUS_FLAG_SECURITY_CHANNEL_ERROR internal error.', '']
Win32Mica Error: win32 version 19045 is not supported
Exception ignored in: <function BaseWindowsToaster.show_toast.<locals>.<lambda> at 0x0000027BCF7A7EC0>
Traceback (most recent call last):
  File "windows_toasts\toasters.py", line 147, in <lambda>
  File ".\genericCustomWidgets.py", line 1087, in <lambda>
TypeError: ToastNotification.reportException() missing 1 required positional argument: 'id'
```

### Package Managers Logs

```text
no usefull log
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/1614114/4d1e319f-8411-42bd-8ad2-262420927d70)
![image](https://github.com/marticliment/WingetUI/assets/1614114/394bc229-3450-4cd4-a18b-235b92c5f20c)

**Comment by marticliment** [comment]
Try resetting sources
