### ISSUE TITLE
[ENHANCEMENT] Specify version in requirements.txt

### ISSUE THREAD

**Issue by NoPlagiarism** [marticliment/WingetUI#1328]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### First, packages are getting their updates, that can be a problem

- [PySide6](https://pypi.org/project/PySide6) stated as `>=6.4.3`, `6.5.2` is out already and what if `6.6.x` breaks GUI?
- [pywin32](https://pypi.org/project/pywin32/) has no semantic versioning (no periods ***.***), so maybe better specify it like `pywin32==306`?
- [win32mica](https://pypi.org/project/win32mica/) already has `2.0` **and** pip installs `2.0` using specification `>=1.9`. I know it the same author, but... Maybe should be updated
- [windows_toasts](https://pypi.org/project/Windows-Toasts/) is [new library](https://github.com/DatGuy1/Windows-Toasts) and only on 1.0.0. What if there will be breaking changes already on 1.2.0 that can broke code?
- [Flask](https://pypi.org/project/Flask) & [flask-cors](pip install Flask-Cors) are used very poorly, so no problems?... Except Flask-Cors can fail it's job with newest Flask version, but it's very low chance
- Can't comment [pythonnet](https://pypi.org/project/pythonnet), but version specifiers are great anyway

### Solution

- Specify versions for all dependencies in requirements.txt
	- Somewhere exact versions not needed. For example: `PySide6 >= 6.5.2, == 6.5.*`. So small fixes shouldn't change any code behavior
- Check out for updates and test them!
	- There are multiple automated ways to check new versions of dependencies to not miss any updates

**Comment by NoPlagiarism** [comment]
>  what if `6.6.x` breaks GUI?
> What if there will be breaking changes already on 1.2.0 that can broke code?
> 

It didn't solve some possible issues tho

Sth like this should go as well

```
PySide6 >= 6.5.2, == 6.5.*
win32mica>=3.0
PyInstaller==5.9.0
pywin32==306
Flask>=2.3.3
flask-cors>=4.0.0
windows_toasts==1.0.0
pythonnet>=3.0.2
```

Again

- GUI could be broken by new version of PySide6
- windows_toast is new library
- pywin32 has no semantic versioning

**Comment by marticliment** [comment]
6.5.1 does not work

**Comment by marticliment** [comment]
it's 6.5.2 or higher

**Comment by NoPlagiarism** [comment]
`PySide6 >= 6.5.2, == 6.5.*` can't install 6.5.1, but can install 6.5.3 and e.t.c. Also, it can't install `6.6`

You can run through [pep-0440](https://peps.python.org/pep-0440/#version-specifiers), there are 1 paragraph about version specifiers

**Comment by ppvnf** [comment]
I am also having problems to build with the current requirements

**Comment by NoPlagiarism** [comment]
> I am also having problems to build with the current requirements

What exact problems btw?

**Comment by ppvnf** [comment]
This https://github.com/marticliment/WingetUI/issues/1234#issuecomment-1704190278

**Comment by marticliment** [comment]
This issue is caused due to Python 3.11.4+ is not compatible with PyInstaller 5.9.0.

Either downgrade to Py3.11.3 or change requirements.txt to use a newer PyInstaller version (may trigger virus issues)
