### ISSUE TITLE
[BUG] source name cut winget pkg

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1334]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

source show as winget: tag instead of just winget

### Steps to reproduce the issue

use latest beta

### WingetUI Log

```text
n/a
```

### Package Managers Logs

```text
n/a
```

### Screenshots and videos

<img width="501" alt="Screenshot 2023-09-03 100303" src="https://github.com/marticliment/WingetUI/assets/73800734/a4f05212-9d7e-41bb-a36c-0d133a5e136f">

**Comment by marticliment** [comment]
Which winget sources have you enabled?

**Comment by ppvnf** [comment]
<img width="602" alt="Screenshot 2023-09-03 111433" src="https://github.com/marticliment/WingetUI/assets/73800734/118be13f-c574-4b49-871e-57f34a16e3f9">

**Comment by ppvnf** [comment]
I can no longer reproduce this issue, I guess it was "accidentally" fixed haha

**Comment by marticliment** [comment]
I did indeed reproduce it
