### ISSUE TITLE
[BUG] Constantly freezes while installing package updates

### ISSUE THREAD

**Issue by BullyWiiPlaza** [marticliment/WingetUI#1355]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I just downloaded this app for the first time and after queueing a lot of packages for updates, I keep getting freezes of the WingetUI which renders the app unusable for extended periods of time.

### Steps to reproduce the issue

Have many outdated apps on the PC and select 5 - 10+ of them for updating.

### WingetUI Log

```text
Probably not relevant, the app is still frozen.
```

### Package Managers Logs

```text
Not relevant.
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/7620135/b4b36dfa-97a0-48cc-a22c-ff4019784cb0)

**Comment by marticliment** [comment]
Hello,

Does this happen with all package managers?
Does WingetUI unfreeze after some period of time?
Updating only one of the outdated apps does also freeze WingetUI?
What are your system specs?

**Comment by BullyWiiPlaza** [comment]
@marticliment Hi, I've just been using `Winget: winget` as source so far. Sometimes WingetUI unfreezes but last time it never unfroze and I had to kill it with the task manager.

After restarting WingetUI again, I queued packages for updating again and it worked fine at first but then the freezing returned. It seems like it's not one specific app that causes the freezing but here's another screenshot of being frozen:
![image](https://github.com/marticliment/WingetUI/assets/7620135/9b6a000b-00b3-4dc7-9938-9defcc63aa7d)

My system specs are very good, I use a high end Dell XPS 15 laptop, that probably won't be the issue, I use many other apps without problems.

**Comment by EDM115** [comment]
why this (may) happens :  
there's 2 states for the bottom screen that shows if an app is updating or not :  
- updating (or downloading, whatever)
- Waiting for other installations to finish
  
if you click on one of the second category, you see that the message with their number in wait list is constantly being displayed every second  
  
so if you're selecting 50 apps, there will be 49 lines popping out the same line every second (and this may be the cause of lag)  
  
##### proposed workaround :
1. compare the outputs
2. if they are the same, don't print it again

**Comment by ppvnf** [comment]
related to https://github.com/marticliment/WingetUI/issues/1454
