### ISSUE TITLE
[ENHANCEMENT] Workaround for side-by-side issue reported to winget-cli

### ISSUE THREAD

**Issue by jsuddsjr** [marticliment/WingetUI#1359]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

When a package installs a side-by-side version (rather than removing/upgrading the older version), winget-cli will continue to report --upgrade-available, even though the newer version is already installed. This breaks wingetui, which fails to install the update twice, and reports some generic error. 

See https://github.com/microsoft/winget-cli/issues/3069.

![image](https://github.com/marticliment/WingetUI/assets/731998/7cbc5b97-47b1-4678-8f79-68f29adc2c38)

```cmd
PS C:\Users\User> winget list cura
Name                 Id             Version Available Source
------------------------------------------------------------
UltiMaker Cura 5.3.1 Ultimaker.Cura 5.3.1   5.4.0     winget
UltiMaker Cura 5.4.0 Ultimaker.Cura 5.4.0             winget
```

The ID is identical, and there's a clear connection between these two entries. 

**PLEASE. Can you detect this and either suppress the upgrade notification, or offer to uninstall the older version?**

### Describe how this improvement could help users.

I wish I could enable the automatic update feature in wingetui, but I cannot do it without causing unnecessary noise and churn as the same packages are upgraded over and over and over.

**Comment by marticliment** [comment]
This fature _can not_ be implemented, because some software depends on multiple installs that receive updates (let's say, you have Pyton 3.10 and Python 3.11 installed, and both do receive updates.), so disabling this behaviour would break different software.

This is an invalid (broken) package, and it needs to be fixed by maintainers/winget staff. 
Meanwhile, **you can use the _skip_ version feature** as a workaround.

P.D. If you have a suggestion on how to implement a fix that wouldn't break those other packages, let me know

**Comment by marticliment** [comment]
This is an issue with certain Packages, and ultimately with Winget. It is not caused, and therefore not fixable by WingetUI.
