### ISSUE TITLE
question about notification

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1369]
<img width="593" alt="Screenshot 2023-09-18 070451" src="https://github.com/marticliment/WingetUI/assets/73800734/79e4da51-2caa-4b4c-b6d1-46f4c49db3ec">

I want wingetUI to only show a notification when installs fail. Do I have to keep checked the 2nd option or just the 4th is enough?

I think if the 2nd option is needed for the 4th to work turning it off should disable the 4th by default

**Comment by marticliment** [comment]
You should need the 2nd and the 4th one, i will clarify this
