### ISSUE TITLE
[BUG] winget source won't appear if path has space + typo

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1376]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

bucket is used instead of source and if the path has space the sources aren't shown
<img width="723" alt="Screenshot 2023-09-19 183255" src="https://github.com/marticliment/WingetUI/assets/73800734/8e0c1816-a3a4-4150-bd4c-eb8f89bdc352">
changing the path to C:\Users\Pedro\Downloads\WingetUI\PackageManagers\winget-cli_x64\winget.exe avoids the problem. running `winget.exe source list ` from the folder of the image also shows the sources correctly

### WingetUI Log

```text
not needed I guess
```

### Package Managers Logs

```text
not needed I guess
```

**Comment by ppvnf** [comment]
Yes, the bundled one

 

De: Martí Climent ***@***.***> 
Enviada: 20 September 2023 13:53
Para: marticliment/WingetUI ***@***.***>
Cc: pedronovaes ***@***.***>; Author ***@***.***>
Assunto: Re: [marticliment/WingetUI] [BUG] winget source won't appear if path has space + typo (Issue #1376)

 

if the path has space

You mean the path where winget is located?

**Comment by marticliment** [comment]
This issue was fixed on 98647fb
