### ISSUE TITLE
[ENHACEMENT] Show the complete PM path

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1378]
I understand being able to copy the path to winget and chocolatey, but for scoop it is different. Why?
 
<img width="617" alt="Screenshot 2023-09-19 231529" src="https://github.com/marticliment/WingetUI/assets/73800734/4d48628e-d8e3-467a-92a1-b4270a835ea5">

**Comment by aaronliu0130** [comment]
By default PowerShell can restrict commands from downloading and running stuff. That command sets an exception for scoop.

**Comment by marticliment** [comment]
> I understand being able to copy the path to winget and chocolatey, but for scoop it is different. Why?
> 
> <img alt="Screenshot 2023-09-19 231529" width="617" src="https://user-images.githubusercontent.com/73800734/269097441-4d48628e-d8e3-467a-92a1-b4270a835ea5.png">

Because this reports the executable file.

I will need to fix that

**Comment by ppvnf** [comment]
also for pip, dotnet etc. I think showing the path to the executable/install folder would be better, if possible

**Comment by marticliment** [comment]
I left the used bare command to be more transparent, but i guess it makes more sense to show the path
