### ISSUE TITLE
[BUG] only bucket list should scroll 

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1379]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

currently both the settings page and the bucket list are scrolled together. It would make more sense if only the bucket list were scrolled in case the mouse is hovering it

### Steps to reproduce the issue

see video

### WingetUI Log

```text
not needed
```

### Package Managers Logs

```text
not needed
```

### Screenshots and videos

https://github.com/marticliment/WingetUI/assets/73800734/a233d250-db32-42c4-b89f-eab77ff7bed6

**Comment by marticliment** [comment]
I am aware of this behaviour, but I haven't succeeded at fixing it
