### ISSUE TITLE
[BUG] Infinite loading when querying

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1397]
- [ ] clicking a package after the query is finished: 

https://github.com/marticliment/WingetUI/assets/73800734/dd13582b-7fd3-4d63-afaa-4022306ea38e

- [ ] empty query + selected package

https://github.com/marticliment/WingetUI/assets/73800734/699753ed-904e-49d1-b030-fa2d79f1ce42

- [ ] the first time you search something this message will be shown briefly even though the query is not finished

<img width="960" alt="no packages" src="https://github.com/marticliment/WingetUI/assets/73800734/1e97b306-d585-4832-9d65-be67d518036a">

- [ ] I don't know how to reproduce this exactly, but keep clearing the query and searching and it will happen eventually

<img width="959" alt="Screenshot 2023-09-24 111338" src="https://github.com/marticliment/WingetUI/assets/73800734/566201e7-4c63-4849-825f-e7b69b3addb4">

- [ ] searching while the query is not finished will result in this (I am also not entirely sure how it happens)
<img width="960" alt="Screenshot 2023-09-24 111420" src="https://github.com/marticliment/WingetUI/assets/73800734/917c270b-8391-4149-a2cb-3d4a4a989963">

- [ ] ADDED - when unselecting source from filter option https://github.com/marticliment/WingetUI/issues/1373#issuecomment-1741973856

**Comment by ppvnf** [comment]
the two last problems might be because of the first two

**Comment by ppvnf** [comment]
> * ADDED - when unselecting source from filter option

I believe there are other elements from the interface like changing section that also trigger the behavior

**Comment by marticliment** [comment]
This issue was fixed on  a previous commit
