### ISSUE TITLE
[ENHANCEMENT] Show list of packages

### ISSUE THREAD

**Issue by BastianKamp** [marticliment/WingetUI#1403]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I fear it has been changed on purpose but never mind.
The new version no longer shows the list of all packages and forces the user to type something in the search bar.
For my use case, this is really annoying because the user now needs to know what packages are available.

### Describe how this improvement could help users.

For me who uses WingetUI with just one custom scoop bucket it is great to see the full list of available packages.

**Comment by marticliment** [comment]
Hello, @BastianKamp

This feature was removed due to increasing incompatibilities with package managers.
You can check the full details of the removal and its causes here: https://github.com/marticliment/WingetUI/issues/1365.

You may want to disable updates and downgrade to version 2.0.3.
