### ISSUE TITLE
[ENHANCEMENT] (The Impact of Administrator Permissions on Scoop Update)

### ISSUE THREAD

**Issue by Weidows** [marticliment/WingetUI#1404]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

![image](https://github.com/marticliment/WingetUI/assets/61131704/a65268a9-657a-4a3d-ab31-3fa6de9b4cf2)

When I turn on this option, whether I choose `Update/Administrator Update` will execute `scoop update -g`

### Describe how this improvement could help users.

![image](https://github.com/marticliment/WingetUI/assets/61131704/ad2a5d25-eb93-4264-b27b-e56a13d461c0)

This should be better I think

**Comment by marticliment** [comment]
Hello @Weidows,

This behaviour is expected. Attempting to install a package with administrator rights and on a non-global envionment would break scoop restrictions. Therefore, when selecting "install as administrator" the global paramater will be enforced.
When you are autoelevating scoop installations, they will be automatically performed as --global.

The application is intended to do so.
