### ISSUE TITLE
[FEATURE REQUEST] Packaged app dumping

### ISSUE THREAD

**Issue by upintheairsheep** [marticliment/WingetUI#1405]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Add a feature in the all apps list to dump packaged apps to a .appx or .msix file.
See https://github.com/Wapitiii/WSAppBak and https://gist.github.com/FusRoDah061/01f2426ad6c379d93729c8ac67f84ba2 

### Describe how this new feature could help users.

As a package manager, as it has the ability to import packages, it should also export packages.

**Comment by marticliment** [comment]
I don't think this feature would fit with all package managers

**Comment by upintheairsheep** [comment]
Correct, this would only be for UWP apps, and later Android (WSA) apps
(when implemented into WinGet).

**Comment by marticliment** [comment]
Hello,

This feature won't be implemented due to incompatiblities with the Package Managers
