### ISSUE TITLE
[BUG] missing translations

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1409]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Sources, Filters and the help menu
<img width="95" alt="Screenshot 2023-09-26 085814" src="https://github.com/marticliment/WingetUI/assets/73800734/63f44845-6c6f-48ad-bae3-1246244375b5">
<img width="242" alt="Screenshot 2023-09-26 085808" src="https://github.com/marticliment/WingetUI/assets/73800734/59054f37-5cec-4da5-8ab2-755ed6480a90">

### WingetUI Log

```text
na
```

### Package Managers Logs

```text
na
```

**Comment by marticliment** [comment]
> ### Please confirm these before moving forward
> * [x]  I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
> * [x]  I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
> * [x]  I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
> * [x]  This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))
> 
> ### Describe your issue
> Sources, Filters and the help menu <img alt="Screenshot 2023-09-26 085814" width="95" src="https://user-images.githubusercontent.com/73800734/270564740-63f44845-6c6f-48ad-bae3-1246244375b5.png"> <img alt="Screenshot 2023-09-26 085808" width="242" src="https://user-images.githubusercontent.com/73800734/270564746-59054f37-5cec-4da5-8ab2-755ed6480a90.png">
> 
> ### Steps to reproduce the issue
> _No response_
> 
> ### WingetUI Log
> ```
> na
> ```
> 
> ### Package Managers Logs
> ```
> na
> ```
> 
> ### Relevant information
> _No response_
> 
> ### Screenshots and videos
> _No response_

I am not sure if those links will stay like this, so for the moment they are not going to be translatable
