### ISSUE TITLE
[BUG] UI Breaks when switching from light to dark

### ISSUE THREAD

**Issue by marticliment** [marticliment/WingetUI#1411]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Apparently there's an incompatibility with win32mica and the current theming interface

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

**Comment by DrBlokmeister** [comment]
Is this the same problem that I have? Sometimes I open WingetUI and the text is not visible. Everything is a very similar shade of gray. After changing the theme to anything (light/dark/system default), the UI is OK again.

**Comment by marticliment** [comment]
Yes, it should be the same issue

**Comment by marticliment** [comment]
> It does seem like this issue is also resolved with a slight caveat. When the accent color or theme (light/dark) is changed, the UI does appear in a broken color state briefly, but it corrects itself after about 2 seconds. I think this would be barely noticeable and can probably be considered fixed.

This is expected, and cannot be removed. Is _part_ of the fix
