### ISSUE TITLE
WingetUI installs user setup instead of upgrading system installation on upgrade

### ISSUE THREAD

**Issue by sitiom** [marticliment/WingetUI#142]
This bug is quite annoying.

### Steps to Reproduce
1. Install an old version of VSCode in the machine scope: `winget install Microsoft.VisualStudioCode --scope machine -v <old version>`
2. Upgrade VSCode via WingetUI
3. WingetUI installs the user setup of VSCode, leaving with two installations of VSCode (user and machine wide)

Alternatively, upgrading via the commandline (`winget upgrade Microsoft.VisualStudioCode`) properly upgrades VSCode.

**Comment by martinet101** [comment]
Mhmm... Which version of winget are you running on your local machine?

**Comment by sitiom** [comment]
v1.3.2091

**Comment by Satanarious** [comment]
Same for me

![image](https://user-images.githubusercontent.com/42642682/194433193-b322d961-aa87-4982-ab04-be38af39989c.png)

**Comment by ppvnf** [comment]
I believe this was fixed by https://github.com/marticliment/WingetUI/pull/575

**Comment by marticliment** [comment]
It should. I'll test it further but it should

**Comment by sitiom** [comment]
Tested the latest commit, same thing:
![image](https://user-images.githubusercontent.com/56180050/210358833-c9040d9d-54b1-4a6f-977d-f3d6da821aa3.png)

User setup is installed.

**Comment by ppvnf** [comment]
@sitiom do you still get two separate vscode installs after using WingetUI to update?

**Comment by sitiom** [comment]
> @sitiom do you still get two separate vscode installs after using WingetUI to update?

Yes

**Comment by marticliment** [comment]
@sitiom, which version of winget are you running on your system?

**Comment by sitiom** [comment]
v1.3.2691

**Comment by marticliment** [comment]
Could you please test it now, with the latest commit?

**Comment by sitiom** [comment]
Now it works, thanks.
