### ISSUE TITLE
[BUG] export settings generates empty file

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1423]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

as reported in https://github.com/marticliment/WingetUI/issues/891#issuecomment-1739698262 by @neoOpus the export button generates an empty file

### WingetUI Log

```text
na
```

### Package Managers Logs

```text
na
```

**Comment by marticliment** [comment]
It works for me.

Can you please provide more dtails?

**Comment by ppvnf** [comment]
[tst.conf.txt](https://github.com/marticliment/WingetUI/files/12859494/tst.conf.txt)
[log.txt](https://github.com/marticliment/WingetUI/files/12859498/log.txt)

**Comment by ppvnf** [comment]
maybe it only happens in Windows 10?

**Comment by marticliment** [comment]
It shouldn't, but I will test that

**Comment by ppvnf** [comment]
my settings in case it helps
[.wingetui.zip](https://github.com/marticliment/WingetUI/files/12859588/default.wingetui.zip)

**Comment by ppvnf** [comment]
needs-author-answer can be removed I guess

**Comment by ppvnf** [comment]
the original issue has been fixed on the latest beta, however if you don't select any package and click on the export button it is still possible to export (I believe the button should be disable in this case)
![Screenshot 2023-11-30 233355](https://github.com/marticliment/WingetUI/assets/73800734/c190b9e7-c4a5-456b-86fe-08dfa6157a46)

**Comment by marticliment** [comment]
This may be a bug with the color theme, because a grey label should be visible here
![image](https://github.com/marticliment/WingetUI/assets/53119851/aae6c733-1828-4daf-b8dd-ce96dd1768c7)
