### ISSUE TITLE
[BUG] gsudo version not shown

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1424]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

also, maybe scoop version could be parsed
<img width="596" alt="Screenshot 2023-09-29 120728" src="https://github.com/marticliment/WingetUI/assets/73800734/1fb1394d-f3ba-43c7-b3df-e9f0011e87fa">

### WingetUI Log

```text
not necessary I think
```

### Package Managers Logs

```text
not necessary I think
```

**Comment by marticliment** [comment]
Possibly path in spaces is breaking the command

**Comment by marticliment** [comment]
fixed on https://github.com/marticliment/WingetUI/commit/74fda43ab73738b13f95606cdfedf404aaa2c8ca

**Comment by ppvnf** [comment]
on the scoop line, how about trimming what comes after the date. The bucket info seems out of place there

**Comment by marticliment** [comment]
I guess it is just part of the version of the program, since it reports the bucket's "version" .

I mean, it is potentially useful information that does not introduce any issues or inconveniences.

What do you think?

**Comment by ppvnf** [comment]
that makes sense, but in this case I think the output should be fully displayed (WingetUI shows only part of it)

**Comment by marticliment** [comment]
I will fix it

**Comment by ppvnf** [comment]
should I open a new issue for it?
