### ISSUE TITLE
[CRASH] UI Crash with multi-monitor setup

### ISSUE THREAD

**Issue by definfo** [marticliment/WingetUI#1425]
### Please confirm these before moving forward

- [X] I have tried deleting a folder named `.wingetui` placed on the user directory
- [X] I have tried reinstalling WingetUI
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).

### Describe your crash

The main window of WingetUI do not show up after initialisation (it seems to go out of the screen border when opening), even the program itself still works in the background and checks for update normally.

WingetUI v2.1.0

**Comment by marticliment** [comment]
did version 2.0.3 work?

**Comment by definfo** [comment]
Yes.

**Comment by marticliment** [comment]
installing v2.1.0 and deleting a folder named .wingetui located on your home directory does help?

**Comment by definfo** [comment]
No, it reproduces the problem.

**Comment by marticliment** [comment]
> it seems to go out of the screen border when opening

What do you mean?

If you alt-tab, can you see the window?

**Comment by definfo** [comment]
https://github.com/marticliment/WingetUI/assets/66514911/cd07e347-5f01-4926-bad5-ad4634b55b6f

**Comment by marticliment** [comment]
Hello, @definfo,

Are you using any kind of window manager addon/theme that could be interfiering with WingetUI?

**Comment by definfo** [comment]
I am using Powertoys, Auto Dark Mode and Mica For Everyone, but none of them seems to interfere with WingetUI ...

**Comment by newillusions** [comment]
I'm seeing the same here.
Also running PowerToys, but not the other apps mentioned above.

**Comment by marticliment** [comment]
Which Windows build are you running?

**Comment by definfo** [comment]
Windows11 22H2 22621.2283

**Comment by definfo** [comment]
When I disconnected the external screen and restart, it worked well as before, thus I doubt that it was a bug of multi-screen compability.

**Comment by newillusions** [comment]
Win 11 22H2 22621.2361 here.
I've got multiple monitors running as well.

**Comment by Ovenlade** [comment]
I'm having the same issue with a multi monitor setup. For me one of the displays is only being used as a virtual invisible display I only use to send sound from my graphics card to my receiver.

Other symptoms:
- System Tray Icon: hoover over icon (tool tip): no problem (displays 'no updates found').
- System Tray Icon: Right mouse button: No context menu is displayed.
- Workaround such shortcuts as 'Windows + Right/Left' or 'Windows + Shift + Right/Left' do not work. (These workarounds usually work when a program opens in the wrong monitor.)

Workaround:
When I go to the Windows Setting to duplicate the image to both monitors the problem goes away.

When using this workaround, I also notice that the Scaling of 225% does not apply to WinGetUi. Fonts are too small.

After Applying the workaround and changing back the Windows Setting to 'extent displays' again, sometimes the Interface works but the three dots in the right corner does not work. This is kind of similar to the behavior of the System Tray icon as described above.

**Comment by definfo** [comment]
seem v2.1.1 fixed it ?

**Comment by marticliment** [comment]
it could, some changes were introduced to the interface.

**Comment by newillusions** [comment]
No, not fixed here either [2.1.1]

**Comment by definfo** [comment]
I can't figure out how it works...... Updating to v2.1.1 did not fix it instantly, but after a few days (maybe Windows Update or sth else) it works

**Comment by Ovenlade** [comment]
I installed WingetUI 2.1.2 Beta 2 today and for me the problem is fixed.

The other thing I noticed is that scaling of 250% (a Windows setting) works much better, the text is far more easy to read now.

Maybe the issue could be closed if there are no new reports of this issue on a new version.

**Comment by newillusions** [comment]
It appears to be fixed here, too.
2.1.2 Beta 2.
