### ISSUE TITLE
[FEATURE REQUEST] (Enter your description here)

### ISSUE THREAD

**Issue by OLLI-S** [marticliment/WingetUI#1426]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Please release a portable version of [WingetUI](https://github.com/marticliment/WingetUI)
On one of my machines I am not allowed to install any applications, but I would love to use UpdateHub here too.

### Describe how this new feature could help users.

Some users prefer portable version or do not have the permission to install applications.

**Comment by marticliment** [comment]
You can install WingetUI on a custom location with the "Portable Installation" selected

**Comment by OLLI-S** [comment]
Sorry, I tested [WingetUI](https://github.com/marticliment/WingetUI) in a VM, where I just installed it.
Seems, like clicked the "Next" button too fast.
