### ISSUE TITLE
[ENHANCEMENT] Bring back the interface feature to show all packages without any search in the 'Discover Pacakges' tab

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#1429]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Please bring back this feature that was in the previous version (2.0.3)
It was possible to list the packages without providing any search query.

### Describe how this improvement could help users.

It makes discovering new packages in a glance much better, especially when you don't know what you are looking for exactly.
I was using this feature and found it very useful for me, and I am sure it was for others as well.

**Comment by marticliment** [comment]
This feature was removed due to increasing incompatibilities. 

Please see https://github.com/marticliment/WingetUI/issues/1365 for a full explanation
