### ISSUE TITLE
[BUG] Installer Has missmatch

### ISSUE THREAD

**Issue by Nawi915** [marticliment/WingetUI#1449]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Im geting hash errors a lot lately

### Steps to reproduce the issue

It appeared at some point idk.
[winget log.txt](https://github.com/marticliment/WingetUI/files/12811300/winget.log.txt)
[log.txt](https://github.com/marticliment/WingetUI/files/12811301/log.txt)

### WingetUI Log

```text
*
```

### Package Managers Logs

```text
*
```

### Relevant information

Unistalled and tried to install fresh,same error

### Screenshots and videos

https://github.com/marticliment/WingetUI/assets/133819030/7924e3b8-6609-46fc-9b7a-68db339ea70e

**Comment by dantman** [comment]
This seems like it would be an issue in winget rather than WingetUI.

**Comment by Nawi915** [comment]
Hey,

Can confirm...i havent tried that b4 im sorry.
[image: image.png]

You're right it might have something to do with winget.
If i find time ill look into that and tell you if i found a Solution..

best regards
Nawi


Am Do., 5. Okt. 2023 um 06:24 Uhr schrieb Daniel Friesen <
***@***.***>:
