### ISSUE TITLE
[ENHANCEMENT] Keep installation options for future versions

### ISSUE THREAD

**Issue by PinkSerenity** [marticliment/WingetUI#1459]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

The update installation, found under "Package details" when in the "Discover Packages" or "Software Updates" tab, currently reset for every update. I believe they should instead be saved for future versions of the same package. Of course this does not apply to the option "Version to install", but to me it seems likely that users who install a package with any of the other options selected once will likely want to do so for the next updates as well.

### Describe how this improvement could help users.

This improvement would help users because then they will not have to select these options again for every update.

**Comment by PinkSerenity** [comment]
#1291 seems similar, but it was more referencing that the install options cannot be found in the "Installed Packages" tab.

**Comment by marticliment** [comment]
They require the same implementation, so I will close this issue as duplicate
