### ISSUE TITLE
[BUG] stuck update message

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1491]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I had updates on queue for Windows Terminal and Visual Studio. Both were not recognized by WingetUI as sucessfully installed, despite they actually being so

### Steps to reproduce the issue

try updating winget pkg suck as visual studio and windows terminal

### WingetUI Log

[log1.txt](https://github.com/marticliment/WingetUI/files/12886487/log1.txt)

### Package Managers Logs

[log2.txt](https://github.com/marticliment/WingetUI/files/12886490/log2.txt)

### Relevant information

<img width="949" alt="Screenshot 2023-10-11 080928" src="https://github.com/marticliment/WingetUI/assets/73800734/cf63dbac-8fd7-4ab9-835b-6cb85b7418d7">

### Screenshots and videos

<img width="960" alt="Screenshot 2023-10-11 080659" src="https://github.com/marticliment/WingetUI/assets/73800734/fce4252d-795c-497f-98ab-8d545883565a">

**Comment by ppvnf** [comment]
related to https://github.com/marticliment/WingetUI/issues/1218

**Comment by ppvnf** [comment]
<img width="960" alt="Screenshot 2023-10-18 075536" src="https://github.com/marticliment/WingetUI/assets/73800734/9dbf6ffd-65e4-4a59-b817-5632a8d1a12c">
I had a similar problem with Chocolatey updating playnite from 10.19 to 10.20, unfortunaly I didn't save the logs.  First I updated normally, when it failed I used admin mode. It worked but I had the same situation as this issue

**Comment by marticliment** [comment]
Please test latest beta: https://github.com/marticliment/WingetUI/releases/download/2.1.2-beta/WingetUI.Installer.exe

**Comment by ppvnf** [comment]
It is somewhat hard to test this. How about closing it for now and I reopen it if it happens again?
