### ISSUE TITLE
[BUG] package in discovery section remains marked after uninstall

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1511]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

<img width="803" alt="Screenshot 2023-10-18 075551" src="https://github.com/marticliment/WingetUI/assets/73800734/c294497c-ab41-4f39-a930-a78af009b0f6">

### Steps to reproduce the issue

search for a package on the discovery section,
install it,  
uninstall it using wingetui,
return to discovery section

### WingetUI Log

```text
I accidentally deleted them
```

### Package Managers Logs

```text
I accidentally deleted them
```

**Comment by marticliment** [comment]
I shouldn't need logs for that, this must be a missing binding.

**Comment by ppvnf** [comment]
I believe this was fixed
