### ISSUE TITLE
Feature Request: Winget ui link to app

### ISSUE THREAD

**Issue by NotNullBool** [marticliment/WingetUI#152]
Be able to send uri links to the wingetui app so I can send my friends applications to install.

**Comment by martinet101** [comment]
Hard but why not

**Comment by ppvnf** [comment]
I'm not sure I understand what you want exactly, but you can share the install link with your friends by doing this:

![Captura de tela 2022-09-25 090727](https://user-images.githubusercontent.com/73800734/192142661-1a996b1a-14e8-4738-a68c-5293c7d2b7f4.png)

![Captura de tela 2022-09-25 090653](https://user-images.githubusercontent.com/73800734/192142662-5e41789c-e885-4294-b29a-7e936adb4f45.png)

It would be useful to have the option to export the scoop/winget install command tho, which would allow scoop to detect the install and also be able to share multiple apps at once. 

Tbh my friends don't even know what is powershell/cmd, so I just send them the install link. =)

**Comment by martinet101** [comment]
You mean like exporting an url such as `wingetui:package_manager#package_id` (example `wingetui:winget#Google.Chrome` or `wingetui:scoop#scrcpy`) that opened WingetUI and pointed to the app with the opened window, right?

**Comment by NotNullBool** [comment]
> You mean like exporting an url such as `wingetui:package_manager#package_id` (example `wingetui:winget#Google.Chrome` or `wingetui:scoop#scrcpy`) that opened WingetUI and pointed to the app with the opened window, right?

yes precisely I feel like it would help get my friends into using winget more instead of potential getting a virus do to their muscle memory
