### ISSUE TITLE
More intelligent ignore option (when package name change every time)

### ISSUE THREAD

**Issue by rwjdk** [marticliment/WingetUI#1530]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Package for Microsoft Visual C++ Redistributable always seems to fail installing, so I tend to ignore these but the problem is that every new version have a unique package Id (because the version number is included in the id; yes, but of MS, but here we are...)

![image](https://github.com/marticliment/WingetUI/assets/7032102/e339e3f7-5170-47e2-8e0c-f03e8d408e95)

It would be nice if we could have an "ignore by name pattern" feature so we could ignore all current and future versions

### Describe how this improvement could help users.

Cause system to intelligently know not to try and update these again and again

**Comment by marticliment** [comment]
I will try to add this ability, but please report this on [microsoft/winget-pkgs issues](https://github.com/microsoft/winget-pkgs/issues/new/choose)

**Comment by marticliment** [comment]
This is an issue with Winget. It is not caused, and therefore not fixable by WingetUI. The best efforts have been made, but this issue is unavoidable unless winget-cli fixes this.
