### ISSUE TITLE
[BUG] Wingetui installer  puts shortcut in wrong place

### ISSUE THREAD

**Issue by kotenok2000** [marticliment/WingetUI#1531]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

It puts shortcut in "C:\ProgramData\Microsoft\Windows\Start Menu"
instead of C:\ProgramData\Microsoft\Windows\Start Menu\Programs

### WingetUI Log

```text
[wigetui log.txt](https://github.com/marticliment/WingetUI/files/13198617/wigetui.log.txt)
```

### Package Managers Logs

```text
[package manager log.txt](https://github.com/marticliment/WingetUI/files/13198618/package.manager.log.txt)
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/8822292/dd5e028f-d87f-4837-b28c-2344c423bc91)

**Comment by marticliment** [comment]
This issue was fixed on a previous commit
