### ISSUE TITLE
[BUG] Splash screen and exit.

### ISSUE THREAD

**Issue by matte22ladde** [marticliment/WingetUI#1535]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Opening wingetui only shows a splash screen before exiting itself.

### WingetUI Log

```text
Seemingly not doable.
```

### Package Managers Logs

```text
Seemingly not doable.
```

**Comment by marticliment** [comment]
Is there any WingetUI icon on the taskbar?

What happens if you remove a folder named .wingetui that can can be found on your user home directory?

**Comment by matte22ladde** [comment]
It's fixed now somehow. If this is relevant, last thing I did before shutting down my PC was uninstalling W10 security update in the control panel.
