### ISSUE TITLE
Support for multiple versions of a program please

### ISSUE THREAD

**Issue by chjohans** [marticliment/WingetUI#1539]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Sometimes it's necessary to have different versions of the same program installed for different purposes, I for instance have multiple versions of Blender and Cura installed.

I suggest that this is handled the following way:
1) If the latest version of this software is installed, ignore the older versions (or give some sort of warning), I already have the latest version installed and I don't want to nor do I need to "Upgrade" the other/older versions of the same program.
2) Please implement an option to "Ignore updates for this version" (not to be confused with "Skit this version" which is already implemented. This should ignore (until un-ignored) any updates for a specific installed version of the program.

### Describe how this improvement could help users.

This will make it possible to have multiple versions of the same program installed, without being notified of unwanted updates. The existing option to "Ignore updates for this package" does not cover this use-case as it will ignore any updates for all versions of the program, which is not what I want.

**Comment by marticliment** [comment]
This is an issue with the package manages themselves, since WingetUI does not handle updates directly. 
This feature should be proposed to microsoft/winget-cli (if winget is the package manager you are using to update those packages)

**Comment by chjohans** [comment]
This is just not gonna happen if I suggest it to microsoft/winget-cli community!

And I understand what winget does.

But then the same goes for the "Skip this version" feature that you have implemented. I assume that the way you use winget you first call winget to list all available updates, and then you manually (or automatically) install updates for one or more programs by calling winget.

But you already have a list implemented (the result of users choice for "Skip this version" and "Ignore updates for this package"), and you don't call winget to update any of those. This is not something that is natively supported by winget either.

You should be able to quite easily expand that list with programs flagged as "Ignore updates for this version".

In my opinion, this functionality does not belong in winget at all either as it's a command-line utility.

I hear you loud and clear though that you don't want to implement this useful feature!

**Comment by marticliment** [comment]
What is the approach that you suggest?

While I do fetch for updates, if you try to update a package while maintaing the older version the older version will get overriden by the installer. WingetUI does not manage how updates are applied. WingetUI manages if updates are applied or not.

**Comment by marticliment** [comment]
As far as I understood, you propose something like Python3, where every Python 3.x version is a different package?

**Comment by chjohans** [comment]
Exactly, this will of course only work for programs/packages where every version is a different package. Or I would not have been able to have multiple versions installed in the first place.

Ultimaker Cura and Blender are two examples, installing a new version of either will not overwrite the older version. Unless something is done different in the installer that is downloaded by winget.

**Comment by chjohans** [comment]
Like it is now, WingetGUI suggest to update every single version of Cura and Blender I have installed, even if I have the latest version installed as well.

**Comment by chjohans** [comment]
Correct, that does not make any sense whatsoever as it will just be "installed over itself".
