### ISSUE TITLE
Progess is not shown on the status bar if older messages has not been acknowledged.

### ISSUE THREAD

**Issue by chjohans** [marticliment/WingetUI#1540]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Let's say I chose to upgrade a program, and the upgrade fails. The status bar will show a "failed" message with an "OK" button to acknowledge that message.

If I just ignore the message and proceed to update another package, the status bar will not show what WingetUI is doing (eg the upgrade progress in this case). That will only be shown if I press "OK" to acknowledge the previous message.

I would expect any current "action" to override what is currently on the status bar, currently, it will be "last in the queue" and only visible if/when all unacknowledged messages have been acknowledged by clicking "OK" for each of them.

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

**Comment by marticliment** [comment]
makes sense
