### ISSUE TITLE
[BUG] I can`t use the bundled winget.exe

### ISSUE THREAD

**Issue by Waboath** [marticliment/WingetUI#1543]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Hello,

if i start wingetui i see nothing under installed packages.

![image](https://github.com/marticliment/WingetUI/assets/37044915/9897c026-bf1c-419c-a22e-060f769e55a7)

so i used the bundled winget.exe with powershell and i get also nothing.

![image](https://github.com/marticliment/WingetUI/assets/37044915/7d7eaa47-e542-4f12-b28f-19930ab7755d)

I think something in a fresh installed windows 11 is blocking.

win ver: 22H2 Build. 22621.2428
normal user (non admin)

### WingetUI Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
🔵 It took 0.0 to load all language files
🟢 checkQueue Thread started!
🟡 Chocolatey was not found on the default location, perhaps a portable WingetUI installation?
🔵 Language file up-to-date
🔵 Starting main application...
🔵 Looking for alive instances...
🟡 Found lock file(s), reactivating...
🔵 Reloading Winget sources...
🔵 Loading WingetUI AUMID...
🔵 Starting update check
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:7058
Press CTRL+C to quit
🟢 Downloaded latest metadata to local file from url https://raw.githubusercontent.com/marticliment/WingetUI/main/WebBasedData/screenshot-database-v2.json
🔵 Loaded metadata from local file
🟢 Found valid aumid {6D809377-6AF0-444B-8957-A3773F02200E}\WingetUI\wingetui.exe
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Reactivation signal ignored: RaiseWindow_[1698846904.2268746]
{'sudoFound': True, 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r', 'ScoopFound': False, 'ScoopVersion': 'Scoop ist deaktiviert', 'ChocolateyFound': False, 'ChocolateyVersion': 'Chocolatey ist deaktiviert', 'PipFound': False, 'PipVersion': 'Pip ist deaktiviert', 'NpmFound': False, 'NpmVersion': 'Npm ist deaktiviert', '.NET ToolFound': False, '.NET ToolVersion': '.NET Tool ist deaktiviert', 'WingetFound': True, 'WingetVersion': ''}
🔵 Reached main ui load milestone
🟢 Discover tab loaded successfully
🟢 Total packages: 0
🟢 Update tab loaded successfully
🟢 Searching for string ""
🔵 Reloading sources...
🔵 Reloading Winget sources...
🔵 Reloading Scoop sources...
🟢 Uninstall tab loaded successfully
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Starting winget source search...
🟢 Starting winget source search...
🟢 Settings tab loaded!
🟢 winget source search finished
🟢 winget source search finished
🟢 About tab loaded!
🔵 Starting Winget search for updates
🟢 Winget search for updates finished with 0 result(s)
🟢 Main application loaded...
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Starting Winget search for installed packages
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Winget search for installed packages
🟢 Winget search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🔵 Loading WingetUI log...
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/wingetui.ver
🟢 Updates not found
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
 ---------Winget---------Winget

---------Winget

---------Winget---------Winget---------Winget
---------Winget
```

**Comment by marticliment** [comment]
Hello,

Have you tried reinstalling WingetUI?

How did you install wingetui in first place?

**Comment by Waboath** [comment]
Hello,

yes i reinstalled wingetui three times. 
I installed it for all users.
The funny thing is, after i installed it for the first it works after a reboot i won't work again.

**Comment by marticliment** [comment]
Do you have any antivirus that could be interfiering?

**Comment by Waboath** [comment]
I use only windows defender.

**Comment by DrStrange** [comment]
I have the same issue. Nothing in installed packages. WingetUI's winget shows no packages in PowerShell. Reset/reinstall/reset MS App Installer does not fix it. Packages showed ok for several days/reboots after installing now no packages listed. Same thing happened on my other PC. Packages show ok when using system winget in experimental settings or when in admin account. I only use Windows Defender. 

No Winget sources in Settings. Where they should be shown, it says Loading... but when I try to add them WingetUI says they already exist.

[<img src="https://onedrive.live.com/embed?resid=53711E1300D97F19%211828&authkey=%21AFIZ7IIx52b5LCQ&width=660" width="660" height="auto" />](url)

**Comment by Stibax** [comment]
I have the exact same issue,  only difference i have from DrStrange, if i select from experimental option to use system winget, the problem still exist. Only if i run wingetUI with admin privileges it seems to work. I have windows 11.

**Comment by Stibax** [comment]
Hi, i have found the solution, it's not a problem of wingetui, i have uninstall dev-home from the app store and that cause the downgrade of winget, so the system messed-up.

**Comment by redactedscribe** [comment]
@marticliment Just curious, is it possible to use the winget-cli executable already installed on the system rather than the bundled WingetUI one? It bothers me to have two possibly differing winget versions installed at the same time.

**Comment by DrStrange** [comment]
Just to report, using the fix in 1721, I now am able to view the list of installed packages using WingetUi's bundled winget instead of using the system winget. I also uninstalled WingetUI and rebooted then reinstalled it. I am using WingetUI 2.2.0 installed only in my standard user account in Windows 10 22H2.
