### ISSUE TITLE
[BUG] Wingetui breaks RPCS3 by adding itself in environment variables

### ISSUE THREAD

**Issue by kotenok2000** [marticliment/WingetUI#1547]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

It adds C:\Program Files\WingetUI\PySide6 and C:\Program Files\WingetUI to path environment variables
and making it look for         MSVCP140.dll,   MSVCP140_1.dll, VCRUNTIME140.dll and  VCRUNTIME140_1.dll at c:\Program Files\WingetUI\ instead of C:\Windows\System32\

### WingetUI Log

```text
[wingetui.log](https://github.com/marticliment/WingetUI/files/13252357/wingetui.log)
```

### Package Managers Logs

```text
[wingetuipacman.txt](https://github.com/marticliment/WingetUI/files/13252356/wingetuipacman.txt)
```

### Relevant information

I have [UAC Run all administrators in Admin Approval Mode](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-run-all-administrators-in-admin-approval-mode) disabled in secpol.msc

It happens when i run 

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/8822292/45bcd8ef-2ab3-41b1-a228-8e431ccc80a9)

**Comment by marticliment** [comment]
Can you please post your path?
The installer does not add WingetUI to path...

How did you install WingetUI?

**Comment by kotenok2000** [comment]
![image](https://github.com/marticliment/WingetUI/assets/8822292/d001d024-3028-4fdd-b29b-04d4de922a68)

**Comment by marticliment** [comment]
And how did you install WingetUI?

**Comment by kotenok2000** [comment]
ItI have installed it with WingetUI.Installer.exe

**Comment by marticliment** [comment]
Then I don't understand why WingetUI has been added to path. The installer shouldn't do that.

I will investigate this. 

Please manually remove WingetUI from path

**Comment by kotenok2000** [comment]
For some reson it happens when i run cmd.exe but not windows terminal.

**Comment by gggirlgeek** [comment]
Are we not supposed to add "WingetUI.exe" to the environment variables? What about the PATH to the folder? I just added "WingetUI.exe a few minutes ago so I haven't had a chance to see any conflicts. I didn't add its PATH yet though.

I am running a portable-mode version (through Symenu) from my P:\ internal drive. It makes life easier to add some apps' executables from that drive to my Environment variables. I also often add folder-symlinks to C:\Program Files to avoid headaches. If needed I add the folder to the PATH variable as well.

FYI: I have change my Security Policy to allow full privileges from other partitions as well.

Let me know if any of these things will cause a problem. I'll check back.

**Comment by marticliment** [comment]
Well, you are _not_ supposed to add WingetUI to path, mainly to prevent those types of issues.

**Comment by marticliment** [comment]
Please test latest beta: https://github.com/marticliment/WingetUI/releases/download/2.1.2-beta/WingetUI.Installer.exe

**Comment by kotenok2000** [comment]
What commit of 269 fixed this?

**Comment by marticliment** [comment]
Those DLLs won't be bundled anymore as of #1724

**Comment by marticliment** [comment]
Python + Qt not used anymore
