### ISSUE TITLE
[BUG] Bug with bug report template

### ISSUE THREAD

**Issue by kotenok2000** [marticliment/WingetUI#1548]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Bug report template doesn't have file upload for "WingetUI Log" and "Package Managers Logs" forms. unlike "Relevant information" form, and github doesn't accept issues with full logs pasted in.

### WingetUI Log

```text
No file upload button
```

### Package Managers Logs

```text
No file upload button
```

**Comment by marticliment** [comment]
The log entries are designed to paste your logs, not to upload them as a file.
![image](https://github.com/marticliment/WingetUI/assets/53119851/bcb4a463-cd70-4de6-9257-622e91440b48)

Github does not support file attaching from issue templates (yet)
