### ISSUE TITLE
XAMPP gets corrupted

### ISSUE THREAD

**Issue by trix1210** [marticliment/WingetUI#1550]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

PLEASE remove the xampp auto-update from your software. XAMPP cannot be updated automatically without wrecking the existing installation... I had to search the web to get the port config working again.

### Steps to reproduce the issue

let wingetui update xampp to cause the corruption

### WingetUI Log

```text
cant do that
```

### Package Managers Logs

```text
cant do that
```

### Relevant information

cant do that

### Screenshots and videos

cant do that

**Comment by trix1210** [comment]
thanks

**Comment by trix1210** [comment]
thanks

**Comment by marticliment** [comment]
You can ignore updates for XAMPP, if you don't want it to get more updates

**Comment by trix1210** [comment]
> You can ignore updates for XAMPP, if you don't want it to get more updates

But why is  xampp included in the software when it will corrupt your database?

**Comment by marticliment** [comment]
UniGetUI does not handle updates directly, instead WinGet and others are the sources of packages
