### ISSUE TITLE
[BUG] Duplicate package entries in Discover Packages's Search

### ISSUE THREAD

**Issue by hboyd2003** [marticliment/WingetUI#1553]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When searching for packages in the "Discover Packages" tab duplicate package entries are observed.

### Steps to reproduce the issue

1. In the "Discover Packages" tab begin to search for a package
2. Change your of the search query slowly. As long as the time between your change to the query is enough for it to begin to search for your query it will occur.

### WingetUI Log
Uploaded as file due to length limit
[WingetUILogs.txt](https://github.com/marticliment/WingetUI/files/13284701/WingetUILogs.txt)

### Package Managers Logs
Uploaded as file due to length limit
[PackageManagerLogs.txt](https://github.com/marticliment/WingetUI/files/13284700/PackageManagerLogs.txt)

### Screenshots and videos

![Animation](https://github.com/marticliment/WingetUI/assets/8950185/cf695e8a-602c-4f0c-b8f2-2dcdb7f1100f)

**Comment by marticliment** [comment]
I will investigate that

**Comment by ppvnf** [comment]
related to https://github.com/marticliment/WingetUI/issues/1373 I suppose

**Comment by marticliment** [comment]
Please test latest beta: https://github.com/marticliment/WingetUI/releases/download/2.1.2-beta/WingetUI.Installer.exe
