### ISSUE TITLE
[BUG] Something wrong with the name and id of  "Microsoft.Windows.Terminal"

### ISSUE THREAD

**Issue by genius-alray** [marticliment/WingetUI#1587]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [x] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

It seems that the name and package id are sperated incorrectly (Name: **Windows Terminal Mi**  ID:**crosoft.WindowsTerminal** ), and cannot update (see the log)

### WingetUI Log

```text
Package: <Package: Windows 终端 Mi;crosoft.WindowsTerminal;1.18.2822.0;Winget: winget;<PackageManagers.winget.WingetPackageManager object at 0x000001CB34E43D10>;<Interface.CustomWidgets.SpecificWidgets.UpgradablePackageItem object at 0x000001CB36873900>>
 Command-line call: "C:\Program Files\WingetUI\PackageManagers\winget-cli_x64\winget.exe upgrade --id crosoft.WindowsTerminal --exact --include-unknown --accept-source-agreements --disable-interactivity --accept-package-agreements" Output code: -1978335212
 Console output:
   | -
   | ██████████████████████████████  8.47 MB / 8.47 MB
   | -
   | No installed package found matching input criteria.
   |
```

### Package Managers Logs

```text
---------Winget
- 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 8.47 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 8.47 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 8.47 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 8.47 MB
  █████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 8.47 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  6.00 MB / 8.47 MB
  ████████████████████████▒▒▒▒▒▒  7.00 MB / 8.47 MB
  ████████████████████████████▒▒  8.00 MB / 8.47 MB
  ██████████████████████████████  8.47 MB / 8.47 MB
                                                                                                                        

   -
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/47408535/2d4adaef-64ae-40a6-b8d5-758eaed71ed6)

**Comment by rumplin** [comment]
Bug on winget side: https://github.com/microsoft/winget-cli/issues/3918

**Comment by marticliment** [comment]
in this case the issue happens due to the Chinese characters not being parsed correctly
