### ISSUE TITLE
[BUG] blacklisted packages missing

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1597]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

After using the latest beta after https://github.com/marticliment/WingetUI/commit/37ef271d42817e33ca7c4b2fb3dbb928530fd035 I had a problem of some packages being removed from the blacklist, specifically the ones that I ignored all updates. Actually only 1 package was removed after I went to the newest version, but when I went back to the stable one my blacklist was empty somehow (which was not really a problem in my case). The only package I want to keep out of date is this one (I managed to cancel the update luckily both when going to the new version and when returning to the stable one):
![Screenshot 2023-11-29 163951](https://github.com/marticliment/WingetUI/assets/73800734/1aa396b4-48f5-4ddf-8f20-16c15ea6bee5)

### WingetUI Log

```text
not sure it is necessary
```

### Package Managers Logs

```text
not sure it is necessarys
```

**Comment by marticliment** [comment]
> Actually only 1 package was removed after

Could it be that this package had both all versions ignored and a specific version skipped?

**Comment by ppvnf** [comment]
I think for most of them yes, but vmware I ignored all versions
![Screenshot 2023-11-30 170617](https://github.com/marticliment/WingetUI/assets/73800734/086329d2-1b01-4eb1-b62e-120027c1b376)
![Screenshot 2023-11-30 170330](https://github.com/marticliment/WingetUI/assets/73800734/d7cd54b0-03a3-481c-94f7-e4fc55966eab)

**Comment by ppvnf** [comment]
not sure how much of a problem this is since it only appears to happen when going back to the current version

**Comment by marticliment** [comment]
I fixed it. It just needed to change the order of how blacklisted packages are migrated
