### ISSUE TITLE
[BUG] WingetUI opens after monitor standby without content

### ISSUE THREAD

**Issue by reaseno** [marticliment/WingetUI#1598]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I have recently started using a KVM switch. Since then, my laptop, which I only use with a second screen, has been experiencing a problem from time to time. After waking up the screen from standby mode, WingetUI opens from the tray, but without any content. The window content is either completely black or white. The close button does not work, but I can use the tray icon to call up "Discover Packages", for example, which makes the content visible again and the window can be closed. I don't have this behavior with any other program that is closed in the tray (away from the taskbar).

This does not happen on my desktop computer, which is also connected to the KVM switch. So the factor is probably the laptop screen and the second screen.

I'm using Windows 10 on both systems.

### WingetUI Log

```text
No matching entry
```

### Package Managers Logs

```text
No matching entry
```

**Comment by marticliment** [comment]
Please test latest beta: https://github.com/marticliment/WingetUI/releases/download/2.1.2-beta/WingetUI.Installer.exe

**Comment by marticliment** [comment]
This does not happen anymore with the latest beta. I have tested it

**Comment by reaseno** [comment]
This still happens in 2.1.2 beta.

**Comment by fernandog** [comment]
I also have this issue. I also switch monitors.

@marticliment you can try to reproduce it by changing windows resolutions


https://github.com/marticliment/WingetUI/assets/2620870/0a3ab9d3-1481-4e0c-a1c8-378e4d91812a

**Comment by marticliment** [comment]
Thanks, now I have been able to reproduce the issue.

**Comment by fernandog** [comment]
I was able to reproduce the issue without an external monitor, just switch users on Windows. I think this is easier than connect a second monitor to debug

**Comment by olee** [comment]
Yeah this is quite the annoying issue - especially because the only way to fix it seems to be killing WingetUI right now

**Comment by reaseno** [comment]
@olee 
As written in my initial post: "I can use the tray icon to call up "Discover Packages", for example, which makes the content visible again and the window can be closed."

Hence killing is not necessary. But you can't keep WingetUI running in tray.

**Comment by olee** [comment]
Oh I skipped over that part as I saw the initial description matched my case 😀 
Thanks 👍

**Comment by jerone** [comment]
This issue happens to me when I start my laptop after waking-up from Windows hibernate mode.

I'm not using a KVM switch, but I do have a second monitor.

**Comment by feroxy** [comment]
This issue also occurs when remoting in via RDP
