### ISSUE TITLE
[ISSUE] WingetUI 2.1.2 Beta 1 detected as trojan.lazy by multiple AVs

### ISSUE THREAD

**Issue by 1aTa** [marticliment/WingetUI#1609]
WingetUI 2.1.2 Beta 1 - wingetui.exe - 20 security vendors flagged this file as malicious:

https://www.virustotal.com/gui/file/b33759faf5f9b17f684ff3b8fc8c808e0899be22b8bd4a1d2754895fa89ae0db/detection

**Comment by marticliment** [comment]
Ugh, PyInstaller again.

I will see what I can do...

**Comment by marticliment** [comment]
I will downgrade Python and PyInstaller to prevent this issue from happening
