### ISSUE TITLE
[BUG] Shortcut creation fails with permission error when installing only for current user

### ISSUE THREAD

**Issue by soredake** [marticliment/WingetUI#1623]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When installing only for current user, start menu shortcut should be created in `$env:APPDATA\Microsoft\Windows\Start Menu\Programs`, not in `C: \ProgramData\Microsoft\Windows\Start Menu\WingetUI .Ink` which requires UAC prompt.

Similar for desktop shortcut, start menu shortcut should be created in `$env:HOME\Desktop`, not in `C:\Users\Public\Desktop\WingetUI .Ink` which requires UAC prompt.

### Steps to reproduce the issue

1) Download latest installer https://github.com/marticliment/WingetUI/releases/download/2.1.2-beta/WingetUI.Installer.exe
2) Install it for current user.
3) You will see errors at the end.

### WingetUI Log

```text
IPersistFile :: Save failed; code 0x80070005.
Access is denied.
```

### Package Managers Logs

```text
IPersistFile :: Save failed; code 0x80070005.
Access is denied.
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/5204968/c8dcf413-3fab-4b6d-ac9c-4849632bb87b)
![image](https://github.com/marticliment/WingetUI/assets/5204968/a528f746-1b8e-4fe6-bcf9-98ee1f9215b0)

**Comment by marticliment** [comment]
Couls your antivirus be interfiering?

Latest beta is sometimes flagged as a virus (false-positive), could it be that Windows Defender was messing around?

**Comment by marticliment** [comment]
I will check that, inno setup shouldn't perform like that...

**Comment by marticliment** [comment]
I have re-checked the installer code and it was actually set incorrectly. I have fixed the location, and next versions should not present this issue anymore.

Thanks for reporting!
