### ISSUE TITLE
[BUG] Release notes autoshow does conflict with updates tab

### ISSUE THREAD

**Issue by marticliment** [marticliment/WingetUI#1624]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When there are updates available, release notes are not shown.

### Steps to reproduce the issue

Start newver on a computer with updates available

### WingetUI Log

```text
No errors here
```

### Package Managers Logs

```text
No errors here
```

**Comment by marticliment** [comment]
can you please share your log?
opening help does load the help pane properly?

**Comment by ppvnf** [comment]
What I mean is the beta start page that appear only once. I got a update while viewing that page and it got blank like in the picture
