### ISSUE TITLE
[BUG] Can't open help from install section

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1626]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

button doesn't work
![Screenshot 2023-12-12 221942](https://github.com/marticliment/WingetUI/assets/73800734/ce709fa1-a704-4883-b79f-082b0634db72)

### WingetUI Log

```text
na
```

### Package Managers Logs

```text
na
```

**Comment by marticliment** [comment]
The documentation or the installed section is missing. I have planned to add it before the next release.

**Comment by ppvnf** [comment]
I guess you know already the following entries can't be translated yet

![Screenshot 2023-12-12 223720](https://github.com/marticliment/WingetUI/assets/73800734/a63f5d5f-909a-4577-821e-353e129bc821)
![Screenshot 2023-12-12 223729](https://github.com/marticliment/WingetUI/assets/73800734/9f5315c7-b562-4531-ac47-14783ea82a94)

**Comment by marticliment** [comment]
yes, I do
