### ISSUE TITLE
[BUG] truncated button in options

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#1627]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Text is too big for the button, so maybe in could be truncated but show the start (instead of the middle) then ... at the end?

![Screenshot 2023-12-12 222036](https://github.com/marticliment/WingetUI/assets/73800734/c9e3c34b-b63d-42bd-a005-20da21148c3b)

### WingetUI Log

```text
na
```

### Package Managers Logs

```text
na
```

**Comment by marticliment** [comment]
Fixed on latest commit

**Comment by ppvnf** [comment]
thanks!
