### ISSUE TITLE
[BUG] Not creating announcement.png cache directory, then crasing

### ISSUE THREAD

**Issue by RonnyTNL** [marticliment/WingetUI#1629]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

WingetUI -> Settings should show a release notes screen.
First this screen is to small, or the loaded content to big, you can scroll but it's not really usable in this state.
Second is seems to be missing a image file.

[Errno 2] No such file or directory: 'C:\\Users\\<UserID>\\AppData/Local/WingetUI/CachedIcons\\announcement.png'

### Steps to reproduce the issue

Install 2.1.2-Beta2
Open settings and look above WingetUI Settings. mouse wheel in that "box" and notice there is some text showing up, including the error message.

### WingetUI Log

```text
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🟢 Winget search for installed packages finished with 165 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 168
🔵 Image URL: https://www.marticliment.com/resources/wingetui.png
🟠 Unable to retrieve announcement image
[Errno 2] No such file or directory: 'C:\\Users\\UserID>\\AppData/Local/WingetUI/CachedIcons\\announcement.png'
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
N/A
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/19427356/7ea52fca-825c-49e6-9c19-2a0241a3dae2)

**Comment by jmwoods301** [comment]
In the current release, that file is located in C:\Users\UserName\.wingetui

**Comment by marticliment** [comment]
Actually, this is not the issue. This image was moved, but WingetUI failed to download it.

**Comment by jmwoods301** [comment]
The announcement.png file exists in the path I mentioned on my system.

**Comment by marticliment** [comment]
Yes, I am aware, but this file is a leftover from an older wingetui version, since this path was changed. Now, this file should be stored in the path mentioned on the error, but looking at your log it looks as if a temporary error prevented the download of the image

**Comment by grentDRD** [comment]
@marticliment A similar issue is present in the stable WingetUI 2.2.0 Latest.

![202312270946](https://github.com/marticliment/WingetUI/assets/154965783/6b8e1ea2-91c5-4819-a6c1-d7ed1a82778e)

Prior to version 2.2.0, it was automatically updated from version 2.1.1 through the application itself, and the application itself was installed via the exe.

**Comment by marticliment** [comment]
Can you please try creating the directory on which the file should be located manually and restarting WingetUI?

Thanks!

**Comment by grentDRD** [comment]
> Can you please try creating the directory on which the file should be located manually and restarting WingetUI?
> 
> Thanks!

Yes, that solves the problem.

![202312271017](https://github.com/marticliment/WingetUI/assets/154965783/80d488ce-99a5-40b3-a94f-c50255b38c87)
