### ISSUE TITLE
[ENHANCEMENT] Suggestion for multiple parameters

### ISSUE THREAD

**Issue by CreeperKong** [marticliment/WingetUI#1643]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

![image](https://github.com/marticliment/WingetUI/assets/28486081/a7359c9d-6093-44c8-8678-eadd0bfff473)
Make this menu able to use multiple parameters.

### Describe how this improvement could help users.

Sometimes, use multiple parameters is necessary, such as hash failure and installation error.
If I can use both ignore hash and have interactive installation, it will be helpful.

**Comment by marticliment** [comment]
Hello,

You can achieve this from the installation options pane on the Package Details
