### ISSUE TITLE
[CRASH] McAfee identifies WingetUI as virus and deleting QtCore.pyd

### ISSUE THREAD

**Issue by DrMaFu** [marticliment/WingetUI#1653]
### Please confirm these before moving forward

- [X] I have tried deleting a folder named `.wingetui` placed on the user directory
- [X] I have tried reinstalling WingetUI
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).

### Describe your crash

Dear all,

yesterday I updated WingetUI to version 2.2.0 on all of my 3 Win10 machines.
But now, WingetUI is not starting any longer with a crash report.

"Your WingetUI installtion appears to have missing our corrupt components. Please reinstall WingetUI".
The reason is, that MyAfee identifies the needed file QtCore.pyd as a virus ti!064F3AE101FC and isolated the file.
So, ModuleNotFoundError: No module named 'PySide6.QtCore" occures.

The older WingetUI version are running together with McAfee and without problems.
Is this a know issue and what was changed in version 2.2.0 leading now to this effect?
Can we trust the QtCore.pyd and exclude this from real time scanning in virus software?

Merry Christmas to all of you and your families and many thanks for your help!

**Comment by marticliment** [comment]
> Can we trust the QtCore.pyd and exclude this from real time scanning in virus software?

QtCore.pyd is provided by the [Qt Company](https://www.qt.io/) and distributed to millions of users through pip, so yes, I'd say it should be pretty secure.

Please note that the way in which python applications are compiled to executables have a common part, and if an antivirus has found at some point a virus that used Qt, it may flag Qt's binaries on other applications built with the same technology (Python and PyInstaller).

However, to clear any doubts, could you please upload that binary file to https://www.virustotal.com/gui/home/upload and attach here the results?

Thanks!

**Comment by m4k2k** [comment]
@marticliment I have the same issue.
Uploaded to virustotal: https://www.virustotal.com/gui/file/064f3ae101fc1d3cf709ac28edcdedeb7414e5f9a2e438031e5301b8d6338c3f/detection
I think the next step would be to make it the issue of the lib vendor, in this case QT, so I would recommend opening a ticket at QT so they talk to mcafee (dont think wingetui is the only affected app).

**Comment by marticliment** [comment]
looking at the results (2 flags out of 70) it is clear for me that it is a false positive. Please mark it as  a false positive in McAfee and white-list it.


Thanks!

**Comment by DrMaFu** [comment]
Dear @marticliment , dear @m4k2k 
many thanks for the fast reply and the investigation. Sorry for my late response ... was on the way ;-) because of Xmas...
I'll white-list the file in McAfee to get WingetUI back into operation and additionally I'll open a ticket at QT.
Thank you and all the best for the new year!

**Comment by m4k2k** [comment]
Hello @DrMaFu, the file "QtGui.pyd" is also affected. (Maybe important for the Qt ticket, also for whitelisting)
wish you also the best for the new year.

**Comment by DrMaFu** [comment]
Hi, 

in the meantime I created a ticket at Qt but Qt is doing nothing and refering to McAfee. So, I created also a bug report at McAfee, upbloaded both files and waiting for feedback.

Will keep you updated in this thread ...

I wish you a happy new year!

**Comment by marticliment** [comment]
Thank you, and have a happy new year!

**Comment by DrMaFu** [comment]
Hi all,

happy new Year!!!!

I got feedback from McAfee :-)

_Dear Sir/Madam,
Thank you for contacting us.
We have reviewed your submission for whitelisting of your software and the submitted file named ['QtCore and QtGui.zip'] have been Whitelisted.
Regards,
McAfee Data Submission Team_ 

So, well done and issue should be solved with next McAfee data base update. Will see....

**Comment by thepro-3418** [comment]
It now occurs in 11clock
i hate mc afee i regret purchasing it
