### ISSUE TITLE
Upgrades found for Microsoft software already installed

### ISSUE THREAD

**Issue by chjohans** [marticliment/WingetUI#1660]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The Microsoft ASP .NET Runtime and Core versions WingetUI wants to upgrade have already been upgraded to the latest versions. Everything it wants to upgrade is already installed in the latest versions.

The "Microsoft Visual C++ 2005 Redistributable (x64)" in the screenshot below actually has the package ID of the x86 version, so it's trying to install a version that only exists for a different package (x86 - not x64). I have both installed in the latest version which is 8.0.61001 for the x86 version and 8.0.61000 for the x64 version.

### WingetUI Log

```text
See attachment
```

### Package Managers Logs

```text
See attachment
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/24390228/2a455bbc-7a5a-4a88-bb20-b8fd3d60f20d)
[package_manager_logs.txt](https://github.com/marticliment/WingetUI/files/13770826/package_manager_logs.txt)
[wingetui_log.txt](https://github.com/marticliment/WingetUI/files/13770827/wingetui_log.txt)

**Comment by marticliment** [comment]
.NET and Visual C++ packages tend to not be detected properly by winget, so you may need to ingore them or skip their versions. This is not WingetUI's fault, but rather winget's
