### ISSUE TITLE
[FEATURE REQUEST] Support custom portable apps.

### ISSUE THREAD

**Issue by necros2k7** [marticliment/WingetUI#1664]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Check exe version number like in SUMO app. Make some kind of versions database.

### Describe how this new feature could help users.

It will hugely increase amount of detected apps and updates not only those tied to winget , etc.

**Comment by marticliment** [comment]
This would be hard to make, not because of the implementation, but because of the compexity of implementing a package manager (web infrastructure, maintainers, security concerns, etc.). I will study this, but if it finally makes its place into WingetUI it won't be in a near future

**Comment by necros2k7** [comment]
@marticliment you can check KCsoftware`s SUMO practices to get the idea - https://www.kcsoftwares.com/?sumo

**Comment by Roseleaves** [comment]
yes, try to indicate whether the package is portable or not, and make the users to select.

**Comment by marticliment** [comment]
Hello,

I am afraid this will not be part of WingetUI in the near future.

I am sorry

**Comment by Shuunen** [comment]
SUMO is dead but I tried [UCheck](https://www.adlice.com/ucheck/) and works great ! only issue it's not OSS 😢
