### ISSUE TITLE
[FEATURE REQUEST] Customize the installation path 

### ISSUE THREAD

**Issue by Roseleaves** [marticliment/WingetUI#1667]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Add a configuration of which path the programs prefers to install, just like D:/ScoopGlobalApps or D:/Programs, and then programs will install and update into this dir.

### Describe how this new feature could help users.

If I do search and install an app by wingetUI, then the app is nearly always installed on C:/, which is really not enough size for me.

**Comment by marticliment** [comment]
You can do so only on packages that are installed from Winget. Other package managers do not support changing the installation path. (Some winget packages may still ignore the given custom location)
