### ISSUE TITLE
[BUG] Does anyone know what these packages are?

### ISSUE THREAD

**Issue by ExpertAF** [marticliment/WingetUI#1673]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I saw these today, i don't remember installing them. They seem to have been installed automatically.

![image](https://github.com/marticliment/WingetUI/assets/147683519/8cac3ec3-1b72-4fa6-8d23-35c9d9dab921)

### WingetUI Log

```text
NA
```

### Package Managers Logs

```text
NA
```

### Relevant information

NA

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/147683519/0f040efc-cd97-4874-978b-6b95f111eeaf)

**Comment by marticliment** [comment]
See here: https://github.com/chocolatey/choco/issues/1657
