### ISSUE TITLE
[BUG] defining user installing path via slash '/' instead of backslash '\' making nearly nothing installed.

### ISSUE THREAD

**Issue by Roseleaves** [marticliment/WingetUI#1684]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

![image](https://github.com/marticliment/WingetUI/assets/77195551/b1e42723-0a2a-422c-8302-9257b34e83ae)
![image](https://github.com/marticliment/WingetUI/assets/77195551/d6cd67e8-1423-45ad-8ac2-91856bf3cb86)

if using the interacive installing, then such an error occured. called "could not access network location". 
![image](https://github.com/marticliment/WingetUI/assets/77195551/b336ef0a-0383-4c77-b43e-f83293687b1e)

such matters also happens not only in installing inkscape above, but also in installing copytranslator, which no GUI takes place and reporting very well, registers added, and then cannot open the program. if try to uninstall by CCleaner, then such error occured: 
![image](https://github.com/marticliment/WingetUI/assets/77195551/efad7875-5fd0-4710-acbc-fb4ea2bcec71)
![image](https://github.com/marticliment/WingetUI/assets/77195551/1867d20e-71f4-4252-b39c-de640d94a0d6)
![image](https://github.com/marticliment/WingetUI/assets/77195551/05995c48-679e-4e63-9966-c792683fc0da)
Even though the link is repaired, there is still a bug like :
![image](https://github.com/marticliment/WingetUI/assets/77195551/8004a424-384a-4de4-bbbd-ee9d22f5baa4)
which means the / of D:/programs is never determined! 
and so that the only way is to delete the item of register.

Maybe such problems also happens when installing wolfram scripts and blender.

well, if using Scoop, nothing happened if the VPN is well connected.

### Steps to reproduce the issue

that is BECAUSE the installing path is using slash / (D:/programs) instead of backslash \ (D:\programs), and it cannot be repaired directly. 

### WingetUI Log

```text
运行安装程序...
Found Inkscape [Inkscape.Inkscape] Version 1.3.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\Rose\AppData\Local\Temp\WinGet\defaultState\WinGet-Inkscape.Inkscape.1.3.2-2024-01-05-12-13-31.371.log
```

### Package Managers Logs

```text
Found CopyTranslator [CopyTranslator.CopyTranslator]

Version: 11.0.2

Publisher: CopyTranslator

Publisher Url: https://copytranslator.github.io

Publisher Support Url: https://github.com/CopyTranslator/CopyTranslator/issues

Description: A user-frandly translation tool for PDF reading. It automaticly removes line breaks from the text you copied and then display the translation result.

Homepage: https://copytranslator.github.io

License: GPLv2

License Url: https://github.com/CopyTranslator/CopyTranslator/blob/master/LICENSE

Release Notes Url: https://github.com/CopyTranslator/CopyTranslator/releases/tag/v11.0.2

Tags:

  copy

  pdf

  translate

Installer:

  Installer Type: nullsoft

  Installer Url: https://github.com/CopyTranslator/CopyTranslator/releases/download/v11.0.2/copytranslator-setup-11.0.2.exe

  Installer SHA256: ba5f2faf04c331a2d740d3ec5c6888a7eccf70cab52b491557ef448ff15db621

  Release Date: 2023-02-27
```

**Comment by Roseleaves** [comment]
In fact, as I checked all the softwares that downloaded via winget and using the custom path, no one is installed there -- instead of fastgithub, which just installed on the path itself, instead of any subfolders like D:\Program\FastGithub, another is synthesizer V.. So that the automatications should be improved.

**Comment by marticliment** [comment]
I will fix that.

**Comment by marticliment** [comment]
This issue has been fixed on the latest PreRelease version
