### ISSUE TITLE
[ENHANCEMENT] (Some minor UI improvements)

### ISSUE THREAD

**Issue by RSM9** [marticliment/WingetUI#1704]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Currently using WIngetUI 2.2.0

1. The loading screen for WIngetUI looks a little too tall (perhaps make it slightly shorter in height whilst keeping the width the same - this would make it look more similar to the loading screen proportions for Outlook 365, etc.)

2. Under the 'software updates' tab, the search box says 'Search **on** available updates' - changing that to 'Search **for** available updates' would look better

3. Under the 'installed packages' tab, the search box says 'Search on your software' - changing that to 'Search installed software', or 'Search installed packages' would look better

4. The only other change could be to move the refresh button (next to the search and filter buttons' down, making it bigger so it is in line with the help button and pin button, etc., but justified all the way to the right

### Describe how this improvement could help users.

Making these changes will make the UI look a little better (though be careful with the last suggestion - you do not want to confuse people with the update selected packages button that is on the left) - suggestion 4 may even be counter-intuitive, as the refresh button is further from the search bar

**Comment by marticliment** [comment]
I will take them into account

**Comment by redactedscribe** [comment]
Just to chime in rather than open a whole other issue:

Confirmation dialogue pop-ups. Under Experimental settings, there is the 'Reset WingetUI and its preferences' option which doesn't provide any "Are you sure?" pop-up. This makes me concerned for options such as Scoop's 'Uninstall Scoop (and its packages)' option, which I certainly would not like to accidentally press for obvious reasons. I hope it and other WingetUI options which cause irreversible / major changes provide a UI confirmation. I'd rather not experiment myself only to shoot myself in the foot (I'm new, only downloaded WingetUI today). Thanks.

**Comment by marticliment** [comment]
Hello @redactedscribe,

I will also take your suggestions into account

**Comment by RSM9** [comment]
One more thing that can be changed: under 'WingetUI settings', the package manager preferences include options to use System WInget and System Chocolatey. Next to those options, it says in brackets 'Needs a restart'. This can be changed to 'requires restart', which would be in line with many Windows 11 settings. The r in 'requires restart' probably should be lower-case, in line with the other options in WingetUI that are enclosed within brackets.
