### ISSUE TITLE
[ENHANCEMENT] system winget - support all languages

### ISSUE THREAD

**Issue by HarryLime1120** [marticliment/WingetUI#1705]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

"use system Winget" is experimential and in my opinion the feature is only working for US-EN,
I kindly ask to complete it for all languages.

winget is written for different languages. 
Looking at https://github.com/microsoft/winget-cli/tree/master/Localization/Resources I guess there are 10 languages: de-DE, es-ES, fr-FR, it-IT, ja-JP, ko-KR, pt-BR, ru-RU, zh-CN, zh-TW

wingetui 2.2.0 is searching for the english column header.
German column headers running "winget update"
**Name                                               ID                                Version       Verfügbar     Quelle**
the english headers are
**Name                                               Id                                Version       Available     Source**

Maybe other github members with other languages can add their headers in this ticket.

I have written a prototype which works with german winget, please see https://github.com/HarryLime1120/WingetUI/tree/system_winget_all_lang
It should work for all languages if column header are single-worded.
Feedback from other github members highly welcomed.

Ideally wingetui is enhanced, so users do not need to change winget settings manually:
Executing "winget settings" will open C:\Users\abcde\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
which allows option to change to language as described here https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/winget/settings.md
Did not work for me, maybe only on next winget download.

PS: I am new to Github. appologies in advance.

### Describe how this improvement could help users.

User with other languages could use the "system winget" feature.

Finally "system winget" could become the default method in future?
Removal of the embedded english winget in WingetUI potentially reduces issues for @marticliment.

**Comment by marticliment** [comment]
System Winget is a fallback option used for error-solving, and is not a _mainstream_ feature. Furthermore, I will soon migrate Winget to PowerShell's Winget modules, and both the bundled winget and system winget will be replaced by _PowerShell_ winget.

**Comment by marticliment** [comment]
Hello,

I am afraid this will not be part of WingetUI in the near future.

I am sorry
