### ISSUE TITLE
[BUG] Automatically installed `scoop-search` detected as malware

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/WingetUI#1715]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

[`scoop-search`](https://github.com/shilangyu/scoop-search) which [WingetUI automatically installs](https://github.com/search?q=repo%3Amarticliment%2FWingetUI%20scoop-search&type=code) without asking the user is currently [being detected](https://github.com/shilangyu/scoop-search/issues/44) as malware [by some vendors](https://www.virustotal.com/gui/file/d5ab7d9d164571b21c38b137e47604b8f9785758ec6ae1b99b014bef8acca4b9/detection) and was put into my antivirus's quarantine. This could be a false positive, but if not, then not having asked the user to install this would be even worse.

### WingetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

### Relevant information

Not sure how WingetUI will behave after `scoop-search` has wrongly or rightly been removed from the system. Maybe WingetUI falls back to native (slow) Scoop searching?

Hopefully the situation resolves itself.

**Comment by shilangyu** [comment]
For visibility: https://github.com/shilangyu/scoop-search/issues/44#issuecomment-1896263779

**Comment by marticliment** [comment]
Scoop-search is the search backend for scoop.

I will try to build some backend for scoop search if the library is not present.

**Comment by redactedscribe** [comment]
@marticliment [sfsu](https://github.com/jewlexx/sfsu#benchmarks-1), although experimental, looks to be a more performant (~5x), more actively developed Scoop search (and other commands) drop-in replacement, which may be of interest. Also not currently flagged by any major AVs.

**Comment by BinToss** [comment]
Partly in response to the AV false-positives, `scoop-search`'s rewrite in Zig is done, released as v1.4.0, and is available via Scoop's main bucket as of a few hours ago.
https://github.com/shilangyu/scoop-search/releases/v1.4.0
> Done for three reasons, in order of importance:
>
> 1. Use a language without a runtime to hopefully stop being incorrectly flagged as malware by anti-viruses
> 2. I was informed there are even faster tools
> 3. Have fun rewriting in Zig
>
> scoop-search should behave exactly as before, but is now even faster.

https://github.com/ScoopInstaller/Main/commit/d65328c0cb46b9d615ed12a8f4c15b107717cbbd 
> scoop-search: Update to version 1.4.0
----
sfsu looks interesting.

**Comment by redactedscribe** [comment]
@marticliment The rewrite of scoop-search has resolved this issue. No longer flagged as malware.
