### ISSUE TITLE
[ENHANCEMENT] "Run now" button for Scoop cleanup on startup option

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/WingetUI#1716]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

There is a Startup option _Enable Scoop cleanup on launch_ which can be enabled. I'd rather have this be a manual process. It would therefore be convenient to have a "Run now" button or similar to the right of this option to trigger it at will.

### Describe how this improvement could help users.

When you know you don't need any particular old version of a Scoop-installed app, `scoop cleanup --all` (I presume) can be run via this button. Otherwise, old versions are either always deleted, or never deleted. This button gives you control over when.

**Comment by marticliment** [comment]
Check under Scoop Settings

**Comment by redactedscribe** [comment]
I presume you mean _Reset Scoop's global app cache_?

![wingetui_2024-01-18_11-32-55](https://github.com/marticliment/WingetUI/assets/25013746/61d83e2f-be75-4a4b-b354-4ff0efa6f990)

I'm not sure what "global app cache" really refers to and this is after extensive use of Scoop. I use two commands to reclaim space when using Scoop: `scoop cleanup --all` (removes old versions of updated packages) and `scoop cache rm --all` (removes the download cache). I assume the former happens on _Enable Scoop cleanup on launch_, but what happens on _Reset Scoop's global app cache_?

**Comment by redactedscribe** [comment]
I also suggest changing the option's name to something more accurate. There is no `--global` option or anything global (as far as I can tell) about removing Scoop's cache.

Scoop's help on the `cache` command says:

```
...
Scoop caches downloads so you don't need to download the same files
when you uninstall and re-install the same version of an app.
...
```
