### ISSUE TITLE
[BUG] Some packages get installed to GSudo's installation directory

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/WingetUI#1730]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Installing a package (in this case [Spotube](https://github.com/KRTirtho/spotube) via WinGet) causes the package to be installed under GSudo's installation path (_C:\Program Files\WingetUI\wingetui\components\Spotube_). If the option to use the system's (non-bundled) GSudo, the package is installed at its location instead (on my system _D:\Scoop\apps\gsudo\2.4.2\Spotube_).

I have yet to notice this happening with any package other than Spotube, but I've not installed (m)any packages since installing WingetUI.

I originally had both the options enabled which make WingetUI prefer the installed (system) versions of WinGet and GSudo and I thought this might be the problem. But after disabling these options and restarting WingetUI, using the _bundled_ WinGet and GSudo has the same result.

I also tried installing Spot*ify* via WinGet source but it installed as expected. The difference between installing Spot*ube* and Spot*ify* seems to be that only the former uses GSudo (shows a UAC prompt and inno installer). I think the bug may lie somewhere here...

### Steps to reproduce the issue

1. Download [Spotube (WingetUI link)](https://marticliment.com/wingetui/share?pid=KRTirtho.Spotube&pname=Spotube&psource=Winget:%20winget).
2. Accept UAC prompt.
    - As seen momentarily by the inno installer's path messages, Spotube is being installed to wherever GSudo is installed. Verify that is the case after installation.
4. Uninstall Spotube via WingetUI.
    - Side note: It's probably an unrelated bug, and maybe it was when using my _non-bundled_ GSudo, but Spotube didn't uninstall after uninstalling (I had to run its uninstaller executable). This only happened, maybe, twice and I've not tried to reproduce it.

### WingetUI Log

```text
🟢 Waiting for install permission... title=Spotube, id=KRTirtho.Spotube, installId=1705868376.8174021
🔵 Given package: <Package: Spotube;KRTirtho.Spotube;3.4.0;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x000002B0FFDDD810>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x000002B08105CEC0>>
🔵 Installation options: <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;CustomParameters=[];RemoveDataOnUninstall=False>
🔵 Found icon:  
🟡 Icon url empty
🟡 Icon spotube not found in json (KeyError)
🟡 Icon for KRTirtho.Spotube does not exist
🔵 Current program set to 1705868376.8174021
🟢 Have permission to install, starting installation threads...
🔵 Starting <Package: Spotube;KRTirtho.Spotube;3.4.0;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x000002B0FFDDD810>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x000002B08105CEC0>> installation with Command ['C:\\Program Files\\WingetUI\\wingetui\\PackageEngine/Managers\\winget-cli_x64\\winget.exe', 'install', '--id', 'KRTirtho.Spotube', '--exact', '--accept-source-agreements', '--disable-interactivity', '--accept-package-agreements']
['Found Spotube [KRTirtho.Spotube] Version 3.4.0', 'This application is licensed to you by its owner.', 'Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.', 'Downloading https://github.com/KRTirtho/spotube/releases/download/v3.4.0/Spotube-windows-x86_64-setup.exe', '██████████████████████████████  23.3 MB / 23.3 MB', 'Successfully verified installer hash', 'Starting package install...', 'Successfully installed', '']
```

### Package Managers Logs

```text
-
```

### Relevant information

```
 Operation: installation - Perform date 2024-01-21 22:19:37.169635
 Package: <Package: Spotube;KRTirtho.Spotube;3.4.0;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x000002B0FFDDD810>;<wingetui.Interface.CustomWidgets.SpecificWidgets.PackageItem object at 0x000002B08105CEC0>>
 Command-line call: "C:\Program Files\WingetUI\wingetui\PackageEngine/Managers\winget-cli_x64\winget.exe install --id KRTirtho.Spotube --exact --accept-source-agreements --disable-interactivity --accept-package-agreements" Output code: 0
 Console output:
   | Found Spotube [KRTirtho.Spotube] Version 3.4.0
   | This application is licensed to you by its owner.
   | Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
   | Downloading https://github.com/KRTirtho/spotube/releases/download/v3.4.0/Spotube-windows-x86_64-setup.exe
   | ██████████████████████████████  23.3 MB / 23.3 MB
   | Successfully verified installer hash
   | Starting package install...
   | Successfully installed
   | 
```

**Comment by marticliment** [comment]
This issue is caused due to the package being installed on CWD

**Comment by redactedscribe** [comment]
I just tried installing Spotube via WinGet on the CLI and it installed to the CWD as you said. Do you know if this is this a problem with WinGet or with Spotube?

**Comment by marticliment** [comment]
this is likely to be an issue with spotube's installer
