### ISSUE TITLE
[FEATURE REQUEST] In "Installed Packages" view, add ability to sort by date of installation, date of last update

### ISSUE THREAD

**Issue by shodanx2** [marticliment/WingetUI#1733]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Self explanatory

In this view

![image](https://github.com/marticliment/WingetUI/assets/10621885/2c2f2d68-8782-439e-be0b-fe3576e4b872)

How to determine when each package was first installed, last updated ? 

### Describe how this new feature could help users.

Sometimes when investigating issues, it helps to review software by order it was last updated or the recently installed software

**Comment by marticliment** [comment]
Hello,

This is not possible since not all Package Managers offer this information
