### ISSUE TITLE
[BUG] It seems WingetGUI is totally ignoring the --override options

### ISSUE THREAD

**Issue by gabriel-vanca** [marticliment/WingetUI#1737]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

It seems WingetGUI is totally ignoring the --override options

I tried:

`winget install -e --id SomePythonThings.WingetUIStore  --accept-package-agreements  --accept-source-agreements   --silent  --disable-interactivity  --override "/NoAutoStart /ALLUSERS /silent /supressmsgboxes /norestart" `

The override options are just ignored

### WingetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
Running WingetUI.Installer.exe with this parameters does work?
