### ISSUE TITLE
Icon url is wrong in Adaptive Card, which causes widgets to not load

### ISSUE THREAD

**Issue by vineeththomasalex** [marticliment/WingetUI#1738]
In the below AdaptiveCard which is for one of the Widgets, the Icon url seems to be https://community.chocolatey.org/content/packageimages/SQLite.3.41.0.png

However, this link is unreachable(404). [https://community.chocolatey.org/content/packageimages/SQLite.3.41.0.**svg**](https://community.chocolatey.org/content/packageimages/SQLite.3.41.0.svg) is reachable, so maybe that's what needs to be used. However, I can't tell where this comes from so maybe this isn't an issue relevant to this repo.
 

Adaptive Card (sorry for the bad formatting): 
`{     "type": "AdaptiveCard",     "$schema": "[http://adaptivecards.io/schemas/adaptive-card.json"](http://adaptivecards.io/schemas/adaptive-card.json%22),     "version": "1.5",     "body": [         {             "type": "Container",             "items": [                 {                     "type": "TextBlock",                     "text": "Available Updates: 1",                     "wrap": true,                     "weight": "Bolder",                     "size": "Medium"                 },                 {                     "type": "Table",                     "columns": [                         {                             "width": "32px"                         },                         {                             "width": 1                         },                         {                             "width": "34px"                         }                     ],                     "rows": [                         {                             "type": "TableRow",                             "cells": [                                 {                                     "type": "TableCell",                                     "minHeight": "2px",                                     "items": [                                         {                                             "type": "Image",                                             "url": "[https://community.chocolatey.org/content/packageimages/SQLite.3.41.0.png"](https://community.chocolatey.org/content/packageimages/SQLite.3.41.0.png%22),                                             "horizontalAlignment": "Center",                                             "width": "24px",                                             "spacing": "Padding"                                         }                                     ],                                     "backgroundImage": {                                         "verticalAlignment": "Center"                                     },                                     "verticalContentAlignment": "Center"                                 },                                 {                                     "type": "TableCell",                                     "items": [                                         {                                             "type": "Container",                                             "items": [                                                 {                                                     "type": "TextBlock",                                                     "text": "Sqlite",                                                     "wrap": false,                                                     "spacing": "None",                                                     "fontType": "Default",                                                     "size": "Small",                                                     "weight": "Bolder",                                                     "color": "Accent"                                                 },                                                 {                                                     "type": "TextBlock",                                                     "text": "From 2.0 to 2.0.0",                                                     "fontType": "Default",                                                     "size": "Small",                                                     "weight": "Lighter",                                                     "isSubtle": true,                                                     "spacing": "None",                                                     "wrap": false,                                                     "style": "default"                                                 }                                             ]                                         }                                     ],                                     "verticalContentAlignment": "Center"                                 },                                 {                                     "type": "TableCell",                                     "items": [                                         {                                             "type": "ActionSet",                                             "actions": [                                                 {                                                     "type": "Action.Execute",                                                     "title": "🡇",                                                     "verb": "updateindex0",                                                     "data": {},                                                     "tooltip": "Update this package"                                                 }                                             ],                                             "horizontalAlignment": "Center"                                         }                                     ],                                     "verticalContentAlignment": "Center",                                     "minHeight": "36px"                                 }                             ]                         }                     ]                 },                 {                     "type": "Container",                     "verticalContentAlignment": "Center",                     "items": [                         {                             "type": "TextBlock",                             "text": "\n",                             "horizontalAlignment": "Center",                             "spacing": "None",                             "weight": "Lighter",                             "isSubtle": true                         }                     ],                     "height": "stretch",                     "spacing": "None"                 },                 {                     "type": "ActionSet",                     "actions": [                         {                             "type": "Action.Execute",                             "title": "Update all",                             "verb": "updateall"                         },                         {                             "type": "Action.Execute",                             "title": "Reload",                             "verb": "reload"                         },                         {                             "type": "Action.Execute",                             "title": "WingetUI",                             "verb": "viewupdatesonwingetui"                         }                     ],                     "id": "buttons",                     "horizontalAlignment": "Center",                     "spacing": "None"                 }             ],             "height": "stretch"         }     ],     "rtl": false,     "refresh": {         "action": {             "type": "Action.Execute",             "verb": "reload"         }     } }`

**Comment by marticliment** [comment]
I have moved this issue to WingetUI since the icons are provided by WingetUI

**Comment by marticliment** [comment]
I have purged all the invalid URLs from the URL list. This issue shouldn't happen anymore after WingetUI udpates icon cache (should happen on each reboot)

**Comment by vineeththomasalex** [comment]
Can confirm this is fixed after the latest update.
