### ISSUE TITLE
Version 1.4: Suggestions to the install section

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#174]
Version 1.4 is amazing! Congratulations, it's really hard to believe you made so much in just a few months almost single-handedly! 
I think the install section is missing a few things compared to the others, so I am gonna make a few suggestions:

- [ ] select/unselect multiple packages to install at once (https://github.com/martinet101/WingetUI/issues/498)

- [ ] export packages to a file (useful if you want to install apps on another PC that you don't have installed on your own).

Edit: removed from todo an unrelated issue that has already been fixed

**Comment by martinet101** [comment]
> * export packages to a file (useful if you want to install apps on another PC that you don't have installed on your own).

You can export things from the uninstall section

![image](https://user-images.githubusercontent.com/53119851/193422216-51518af8-bb7a-40ed-b4c5-6c5684a878bb.png)

**Comment by ppvnf** [comment]
> You can export things from the uninstall section

I know. But imagine you wanna export some packages like drivers for a different hardware or programs that only work on another Windows version.

**Comment by martinet101** [comment]
Aaaaaah i get your point. 

Like creating some kind of package kit from the discover software section and then export it?

**Comment by ppvnf** [comment]
> Like creating some kind of package kit from the discover software section and then export it?

Yes, my idea initially was to create a .ps1 or .bat file or even downloading a .zip file with all the files. I changed it to export package since it's already a feature under installed applications

**Comment by ppvnf** [comment]
I believe https://github.com/martinet101/WingetUI/commit/ae72172ab6dc27158512cc6df09365722396a518 fixes icon consistency

**Comment by martinet101** [comment]
Yes, wanted to reference the issue but couldn't find which one was😅

**Comment by ppvnf** [comment]
> * export packages to a file (useful if you want to install apps on another PC that you don't have installed on your own).

I believe this idea is similar to https://github.com/martinet101/WingetUI/issues/152
