### ISSUE TITLE
[ENHANCEMENT] Allow review of own translations in Tolgee

### ISSUE THREAD

**Issue by yrjarv** [marticliment/WingetUI#1743]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Sorry if an issue is not the right way to raise this, but I propose that the translators are able to review their own translations - especially in small languages (e.g. Norwegian).

### Describe how this improvement could help users.

This would make the distinction between translated and reviewed keys much clearer, as fewer translations will be 'only' translated.

**Comment by marticliment** [comment]
Everyone has review rights now

**Comment by yrjarv** [comment]
Awesome, thanks a lot :)
