### ISSUE TITLE
How to integrate self hosted personal repository. Getting an error when trying to add the source.

### ISSUE THREAD

**Issue by JZafarr** [marticliment/WingetUI#1764]
Hi there,

I have created my own personal repostiory via Winget Pro, it gives me a link along with UniqueURL and I'm able to add the source to Winget in Powershell without any issue via the Microsoft REST API provided in the documentation of Winget Pro.

The link is something like this:
winget source add -n example.myrepo.com -a https://example.myrepo.com/uniqueurl -t "Microsoft.Rest"

However when I try to add this repository to WingetUI, I get an error as shown in the screenshot below:
![Screenshot 2024-02-03 041559](https://github.com/marticliment/WingetUI/assets/62207359/bb6adc82-44a8-4554-ba2a-bbbcddf90df8)

**Comment by marticliment** [comment]
Hello,

Try this issue https://github.com/marticliment/WingetUI/issues/1721

**Comment by JZafarr** [comment]
I tried it, deleted the folder and restarted and added via just the the address/uniqueurl but its still giving me error, normal winget repository works fine, its only when I try to add my own
![Screenshot 2024-02-03 195520](https://github.com/marticliment/WingetUI/assets/62207359/4b4aef7d-a562-40c7-bf3d-d2625c856f98)
 source, i get this error

**Comment by marticliment** [comment]
Running the command `C:\Program Files\WingetUI\wingetui\PackageEngine/Managers\winget-cli_x64\winget.exe source add sourcename url` does work?

**Comment by JZafarr** [comment]
It worked but only with the following command:

It doesnt work when i just add the name and URL, it shows the same error but in the terminal instead:
![Screenshot 2024-02-03 204428](https://github.com/marticliment/WingetUI/assets/62207359/6543ee60-ffc7-49ce-8e0b-01660a005021)

But when I use the following command, it has worked. I can now see my repo in the list and can install packages from it:
C:\Program Files\WingetUI\wingetui\PackageEngine/Managers\winget-cli_x64\winget.exe source add -n example.myrepo.com -a https://example.myrepo.com/uniqueurl -t "Microsoft.Rest"

**Comment by marticliment** [comment]
Therefore, Winget is calling the wrong command.

I will fix this

**Comment by taki-eddine-47** [comment]
Hello,
It's missing "Source type" select field in "Add source" popup, there are 2 types [Microsoft.PreIndexed.Package, Microsoft.Rest].
This should fix the issue.
![image](https://github.com/marticliment/WingetUI/assets/25118467/0ae31733-a48f-4274-9a6e-4432a73ab0f5)

**Comment by marticliment** [comment]
This issue was fixed on a previous commit.

Changes will be effective on future releases

**Comment by DantesNoWar** [comment]
Hi, I looked everywhere but i couldn't find a way to ad a specific source. Can someone explain me how to add a repository or a download page to the sources? Looking for a similar issue I ended up here.

**Comment by marticliment** [comment]
what repo do you want to add?

**Comment by DantesNoWar** [comment]
@marticliment I want to add this website https://www.wisemapping.com/it/desktop and any other download page or repository that is not automatically distributed via UniGetUI. The desktop version is new, so I guess it's normal.
I've also made an issue in their repo to ask them to be included in UGUI updates here: https://github.com/wisemapping/wisemapping-desktop/issues/6
Meanwhile, I wanted to know if there's a way to keep track of their download page via UGUI. Is there a way?

**Comment by marticliment** [comment]
@DantesNoWar, you can't just add a webpage as a source. You need to set up a server which exposes an api that package managers understand, such as winget rest or chocolatey/nuget. 

I am afraid what you are trying to do can't be done

**Comment by DantesNoWar** [comment]
Understood.
Same for repositories I immagine.
Will repos ever be supported @marticliment ?

**Comment by marticliment** [comment]
I don't know

**Comment by DantesNoWar** [comment]
I hope so 🙏 it would help with newer/smaller/testing software updates
