### ISSUE TITLE
[CRASH] (Not sure if "crash," just doesn't start)

### ISSUE THREAD

**Issue by j-6-w3n7w027h** [marticliment/WingetUI#1793]
Hard crash experienced
>WingetUI installation wizard
>set directory: D:/folder/folder/WingetUI
# Does it need to be in Sys drive? Would assume not for portable install at least? 
>portable install
>Launch WingetUI (check box from wizard)
>Crash page
>Close page
>Go to the directory in explorer
>run .exe
>Crash page
>here we are
Error details : 
```
                        OS: Windows
                   Version: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
                  Language: Unknown
               APP Version: Unknown
                Executable: D:\Programs
```

**Comment by marticliment** [comment]
> # Does it need to be in Sys drive? Would assume not for portable install at least?
> >

It should not

Can you please share the URL of the error report page? It seems as if it didn't parse properly the error message...
