### ISSUE TITLE
[CRASH] The program will exit immediately.

### ISSUE THREAD

**Issue by letrhee** [marticliment/WingetUI#1795]
### Please confirm these before moving forward

- [X] I have tried deleting a folder named `.wingetui` placed on the user directory
- [X] I have tried reinstalling WingetUI
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).

### Describe your crash

The program runs, pops up a splash window, becomes unresponsive as soon as the screen switches, and shuts down after a while.

As a result, no error logs are left behind.

It stopped immediately even before I reinstalled Windows, and it's the same after I reinstalled Windows and only installed the most essential programs for work.

This is the same symptom in WingetUI 2.2.0 and 3.0.0 Alpha 1.

![wingetui_crash](https://github.com/marticliment/WingetUI/assets/2796089/c7f6fcc2-866f-476f-b06c-9b0eb7cb5dc0)

The most informative screen was the one that showed that it was running 3.0.0 and had 3 updates right before it crashed. Strangely, the Windows Terminal app incorrectly says "Windows ?곕???" in the Korean version, when it should say "Windows 터미널".

### More details

OS: Windows 11 23H2 (22631.3007) Korean Version
CPU: AMD Ryzen 9 5950X

**Comment by marticliment** [comment]
> This is the same symptom in WingetUI 2.2.0 and 3.0.0 Alpha 1.

Please do: 
0. Disable your AV
1. Uninstall WingetUI
2. delete C:\Program Files\WingetUI
3. delete C:\Users\<user>\.wingetui
4. delete C:\Users\<user>\AppData\Local\WingetUI
5. delete C:\Users\<user>\AppData\Local\Programs\WingetUI

And install version  2.2.0.

Does it work now?

**Comment by letrhee** [comment]
Very unfortunately, I am using my computer in an environment where I should not be shutting down my AntiVirus.

If this is due to AntiVirus, I probably won't be able to solve this problem.

**Comment by letrhee** [comment]
And for some unknown reason, without a version update, WingetUI works fine for now. 

Maybe Antivius added exception handling, or maybe the Windows Terminal with the broken string was fixed with an update.
