### ISSUE TITLE
[BUG] Font sizing on screens with lesser resolution in 3.0-alpha

### ISSUE THREAD

**Issue by raghavdhingra24** [marticliment/WingetUI#1796]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Hi there,
Font sizing in the package list is quiet larger than rest of the UI causing visual inconsistencies especially noticable on screens with low resolution like mine (1366x768 on 15.6 inch display). Similar thing is also there in the filters panel.

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/106472154/8c068076-96d1-4ea7-90a0-e7a388971420)

**Comment by marticliment** [comment]
Font size has been reduced 1 point. Smaller sizes render text il·legible on some cases.
![image](https://github.com/marticliment/WingetUI/assets/53119851/328af28f-ddc3-4d09-9ebb-0b705ac45610)
