### ISSUE TITLE
[ENHANCEMENT] Don't auto update during fullscreen applications

### ISSUE THREAD

**Issue by kpd328** [marticliment/WingetUI#1797]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Probably as a toggleable setting, but it would be a great quality of life improvement to be able to specifically disable automatic updates while a full screen application like a game or fullscreen video is currently the active window.

### Describe how this improvement could help users.

I would love to use automatic updates, but as someone who often games on his computer, having auto updates initiate, and often due to the nature of some of the updaters, pull focus off of the game window and pull up a UAC prompt, it is not practical to leave automatic updates enabled.

**Comment by marticliment** [comment]
related to #1296.

I am going to move this issue there
