### ISSUE TITLE
[BUG3.0] Bad behavior with the "more details" button

### ISSUE THREAD

**Issue by aaronliu0130** [marticliment/WingetUI#1821]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Today, I tested out WingetUI 3. Two of my packages failed to update (which is routine) and both tried to get me to do more details. However, as I clicked, it never stopped: the dialog boxes that requested more details kept popping up, and I had to actually close one of them! the humanity! After that, one of the detail views finally poped up, but i was unable to cl0ose itt

### WingetUI Log

```text
uhh i immediately uninstalled it, sowwy
```

### Package Managers Logs

```text
don't think it applies
```

**Comment by marticliment** [comment]
Hello @aaronliu0130,

This is an issue I still have to figure out, since WinUI3 does not support showing multiple dialogs one on top of another. 

However, I have some ideas no how to prevent this annoying behaviour
