### ISSUE TITLE
How to locate currently installed scoop packages

### ISSUE THREAD

**Issue by vikingnope** [marticliment/WingetUI#1831]
Hi,

Sorry if this is not supposed to be here but didn't know where else to ask.

Does anyone know how I can locate already installed scoop packages within WinGetUI as they aren't showing?

**Comment by marticliment** [comment]
@vikingnope, I will need you to share your logs

**Comment by vikingnope** [comment]
[wingetuilog.txt](https://github.com/marticliment/WingetUI/files/14453381/wingetuilog.txt)

I do not have scoop installed in the user directory as default, I have it insttalled in ProgramData/Scoop.

**Comment by vikingnope** [comment]
My idiot mind didn't have scoop turned on, all sorted now sorry.
