### ISSUE TITLE
[BUG] v2.0.0 vs v2.0 CredentialManager

### ISSUE THREAD

**Issue by EdTittel** [marticliment/WingetUI#1857]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

See blog https://www.edtittel.com/blog/wingetui-throws-bogus-update-notification.html.

### Steps to reproduce the issue

Install PS gallery item credentialmanager using install-module -name credentialmanager
Run latest WingetUI (v2.2.0) against windows image to get bogus update report.

### WingetUI Log

```text
🟢 .NET Tool search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟠 Chocolatey got too few installed packages, retrying
🔵 Starting Chocolatey search for installed packages
🟢 PowerShell search for installed packages finished with 3 result(s)
🟢 Searching for string ""
🟢 Chocolatey search for installed packages finished with 0 result(s)
🟢 Searching for string ""
🟢 Winget search for installed packages finished with 272 result(s)
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 275
🔵 Loading WingetUI log...
🔵 Copying log to the clipboard...
🔵 Loading WingetUI log...
```

### Package Managers Logs

```text
Outputs from package managers on the current session:
Name                                         Id                                            Version              ---------Chocolatey
Chocolatey v2.2.2
0 packages installed.
---------

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.0.18     SpeculationControl                  PSGallery            This module provides the ability to query the speculation control settings for th...
2.0        CredentialManager                   PSGallery            Provides access to credentials in the Windows Credential Manager
1.0.11     pscredentialmanager                 PSGallery            This module allows management and automation of Windows cached credentials.---------Chocolatey
Chocolatey v2.2.2
0 packages installed.
```

**Comment by marticliment** [comment]
Please try WingetUI Beta: https://github.com/marticliment/WingetUI/releases/download/3.0.0-beta0/WingetUI.Installer.exe
