### ISSUE TITLE
[BUG] 3.0.0 Beta 1 can not be started "Run as Administrator" by a standard/limited account?

### ISSUE THREAD

**Issue by RonnyTNL** [marticliment/WingetUI#1870]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

As a standard user I can no longer WingetUI "Run as Administrator"
This does work when logged in as Admin account and allow UAC prompt, in that case it also shows "RUN AS ADMINISTRATOR" in the title bar.

### Steps to reproduce the issue

Login as standard/limited user account, right mouse -> Run as Administrator on the WingetUI desktop Icon, nothing happens.

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Relevant information

Win10, x64

**Comment by marticliment** [comment]
> Login as standard/limited user account, right mouse -> Run as Administrator on the WingetUI desktop Icon, nothing happens.

This would work on previous WingetUI versions?

**Comment by RonnyTNL** [comment]
On 2.2. for sure, not sure if I tested this on previous 3.x Beta/Alpha's.
But it's regular Windows behavior, I don't know any other application that won't launch as Admin when started from standard/limited user.

**Comment by marticliment** [comment]
So you are seeing the UAC prompt and then happens nothing?

**Comment by RonnyTNL** [comment]
No, a standard account needs elevation under a Admin userID/Password, so I get a dialog to elevate to a real admin account, no UAC involved in this use-case.

**Comment by marticliment** [comment]
This is still UAC dialog. So I undertstand the dialog still shows, but nothing happens afterwards

**Comment by RonnyTNL** [comment]
2.2. would display this;

![image](https://github.com/marticliment/WingetUI/assets/19427356/9fe7aa15-c50e-4cb0-940b-55d0c782fe94)

Just upgraded that machine to 3.x Beta1 and after the password dialog nothing happens.

**Comment by RonnyTNL** [comment]
Procmon process exit status;

![image](https://github.com/marticliment/WingetUI/assets/19427356/bd48a4d2-1329-4140-b5e3-18d1f48b65cc)

**Comment by marticliment** [comment]
Please try running PowerToys as administrator in the same way you do with WingetUI (PowerToys uses similar libraries to WingetUI). What happens?

**Comment by RonnyTNL** [comment]
That works, powertoys starts as admin when launched from a limited/standard account.

**Comment by marticliment** [comment]
Hello,

I have been doing further testing, and this issue is caused by the Windows App Sdk not being compatible with the "Run as other user". Therefore, this issue can't be fixed from WingetUI. More info here: https://github.com/microsoft/WindowsAppSDK/issues/2555

Please remember that WingetUI should not be run as administrator, and the ability to auto elevate operations is already there

**Comment by cjohn-murphy** [comment]
Not all applications are installed for all users. Before 3.0, it was possible to use WingetUI to update apps installed under the admin account from a standard user account by doing a run-as.

" the ability to auto elevate operations is already there"
Only for applications that are visible to the account being used.
The list of visible applications a standard user sees vs what an admin account see is different.

**Comment by marticliment** [comment]
I am afraid the App Sdk is simply incompatible with running as administrator from an account without administrator rights.
It was not my choice.
