### ISSUE TITLE
[BUG] (Packages are not visible)

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#1879]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Some packages were installed on my computer, which weren't shown in the Installed Packages.

### Steps to reproduce the issue

Go to Installed Packages.

### WingetUI Log

```text
https://1drv.ms/t/s!Aqq-Je19xlrfh0YzkmlUNZZn230g?e=ncyq5s
```

### Package Managers Logs

```text
https://1drv.ms/t/s!Aqq-Je19xlrfh0WGlOA6ioLAW7g2?e=ta6SO6
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/99239826/b0edac3e-7786-421c-bb1b-23fbafe0cc2e)

**Comment by skanda890** [comment]
The source called Winget wasn't found, hence the packages weren't found. This is the reason, just for information.

**Comment by skanda890** [comment]
Fixed! Just had to restart the app

**Comment by skanda890** [comment]
I tried to restart the app, but nothing changed.

**Comment by marticliment** [comment]
Please go to WingetUI Settings -> Winget -> Reset Sources

Then, please follow the steps on #1721

**Comment by skanda890** [comment]
Sure, I will try that and tell.

**Comment by skanda890** [comment]
Fixed!
