### ISSUE TITLE
[BUG] MediaInfo doesn't acknowledge the "skip this version"

### ISSUE THREAD

**Issue by EntranceJew** [marticliment/WingetUI#1884]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

![image](https://github.com/marticliment/WingetUI/assets/5711436/bb124410-5ec2-4a60-a761-264b579a54c8)
"skip this version" does not apply to this package

### Steps to reproduce the issue

install mediainfo, check for software updates, try to skip a version
it will work r/n because of something up with 24.01.1 presumably

### WingetUI Log

```text
mediainfo isn't mentioned there
```

### Package Managers Logs

```text
=========================================
[3/10/2024 9:37:43 PM] Winget - Arguments:  update --include-unknown  --accept-source-agreements
       Executable: C:\Users\ej\AppData\Local\Microsoft\WindowsApps\winget.exe
   \ 
   - 
   | 
Name                    Id                        Version     Available   Source
--------------------------------------------------------------------------------
NVM for Windows         CoreyButler.NVMforWindows Unknown     1.1.12      winget
GCFScape 1.8.6          RyanGregg.GCFScape        Unknown     1.8.6       winget
MEGAsync                Mega.MEGASync             Unknown     4.12.2.0    winget
MediaInfo 24.01         MediaArea.MediaInfo.GUI   24.01       24.01.1     winget
Blender                 BlenderFoundation.Blender Unknown     4.0.2       winget
Unity                   Unity.Unity.2020          2018.3.6f1  2020.3.48f1 winget
Unity 2019.4.39f1       Unity.Unity.2020          2019.4.39f1 2020.3.48f1 winget
Unity 2020.3.33f1       Unity.Unity.2020          2020.3.33f1 2020.3.48f1 winget
Unity 2020.3.47f1       Unity.Unity.2020          2020.3.47f1 2020.3.48f1 winget
Python 2.7.18 (64-bit)  Python.Python.3.12        < 3.12.0    3.12.2      winget
Python 3.10.11 (64-bit) Python.Python.3.12        < 3.12.0    3.12.2      winget
12 upgrades available.
The following packages have an upgrade available, but require explicit targeting for upgrade:
Name    Id              Version  Available Source
-------------------------------------------------
Discord Discord.Discord 1.0.9030 1.0.9035  winget
[3/10/2024 9:37:43 PM] Exit Code: 0
=========================================
=========================================
[3/10/2024 9:37:44 PM] Pip - Arguments:  -m pip list --outdated
       Executable: C:\Python312\python.exe
[3/10/2024 9:37:44 PM] Exit Code: 0
=========================================
=========================================
[3/10/2024 9:37:47 PM] Chocolatey - Arguments:  outdated
       Executable: C:\ProgramData\chocolatey\bin\choco.exe
Chocolatey v2.2.2
Outdated Packages
 Output is package name | current version | available version | pinned?
Chocolatey has determined 0 package(s) are outdated. 
Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare
[3/10/2024 9:37:47 PM] Exit Code: 0
=========================================
```

### Relevant information

mediainfo is a handy program, but i'd throw it in a river if wingetui makes a system toast about it every 30 minutes

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/5711436/6f45719a-d3c7-4369-b325-aa836e99d8a6)
![image](https://github.com/marticliment/WingetUI/assets/5711436/ddcebdca-77f7-473b-abec-098061c95695)
![image](https://github.com/marticliment/WingetUI/assets/5711436/549e5219-fb93-4b85-8bd1-addf68fd2353)
![image](https://github.com/marticliment/WingetUI/assets/5711436/0bd8b9fd-40f1-4b22-9e84-f2f9c2a551cd)

**Comment by philpav** [comment]
Just wanted to submit this issue. 
Same is happening here.

**Comment by marticliment** [comment]
Hello,

Which WingetUI version are you using? There was a release (3.0.0-beta0 or 3.0.0-alpha2) that had this feature broken

**Comment by EntranceJew** [comment]
the beta which prompted me to use the new UI, if there was a wingetUI
update I have yet to be prompted to upgrade

**Comment by marticliment** [comment]
> if there was a wingetUI update I have yet to be prompted to upgrade

between betas there isn't an automatic updater, you will need to update it manually; to prevent upgrading beta users to newer, potentially unstable versions

**Comment by philpav** [comment]
I have WingetUI 2.2.0 installed and get constantly the notifcation about a new MediaInfo version (24.01.1) even though it's already installed.

**Comment by marticliment** [comment]
Please install WingetUI 3.0.0 beta 1: https://github.com/marticliment/WingetUI/releases/download/3.0.0-beta1/WingetUI.Installer.exe

**Comment by EntranceJew** [comment]
![1apwFWJcPd](https://github.com/marticliment/WingetUI/assets/5711436/ed09717e-9ba8-4e41-828f-6c563509db62)
no such luck with 3.0.0-beta1

**Comment by marticliment** [comment]
But if you skip the versions of the packages do they show again?

**Comment by philpav** [comment]
Skipping the version works with the latest version of WingetUI
