### ISSUE TITLE
[BUG] Software identification error

### ISSUE THREAD

**Issue by QAQQL** [marticliment/WingetUI#1885]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When I updated my animation software(Private), it was updated to Final2x
It recognized the wrong thing

### Steps to reproduce the issue

![图片](https://github.com/marticliment/WingetUI/assets/51136763/deb0b0c7-5214-446d-a099-009d0d554eb4)

Click to update

### WingetUI Log

```text
None
```

### Package Managers Logs

```text
--------------------------------
 Operation: update - Perform date 2024-03-11 11:55:37.600020
 Package: <Package: 次元城动漫 1.0.6;Tohrusky.Final2x;1.0.6;Winget: winget;<wingetui.PackageEngine.Managers.winget.WingetPackageManager object at 0x0000024A6619A010>;<wingetui.Interface.CustomWidgets.SpecificWidgets.UpgradablePackageItem object at 0x0000024A700187C0>>
 Command-line call: "D:\Program Files\WingetUI\wingetui\PackageEngine/Managers\winget-cli_x64\winget.exe upgrade --id Tohrusky.Final2x --exact --include-unknown --accept-source-agreements --disable-interactivity --accept-package-agreements" Output code: 0
 Console output:
   | Found Final2x [Tohrusky.Final2x] Version 1.2.0
   | This application is licensed to you by its owner.
   | Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
   | Downloading https://github.com/Tohrusky/Final2x/releases/download/2024-01-02/Final2x-windows-x64-setup.exe
   | ██████████████████████████████   238 MB /  238 MB
   | Successfully verified installer hash
   | Starting package install...
   | Successfully installed
   | 


--------------------------------
```

### Screenshots and videos

![图片](https://github.com/marticliment/WingetUI/assets/51136763/82f49781-b496-487e-b37b-5ca40b42905b)

**Comment by marticliment** [comment]
> When I updated my animation software(Private), it was updated to Final2x

I will need you to provide more details

**Comment by QAQQL** [comment]
What more details do I need to provide?

**Comment by marticliment** [comment]
Which software is being updated, the names of both sotfwares, the expected behaviour, the versions of the software, what do you mean by your "private" software, etc.

**Comment by marticliment** [comment]
I undertsand what the issue is now.

However, I am afraid that this it not caused by WingetUI, but rather by Winget, the program used to fetch packages and updates. You may want to report this issue [here](https://github.com/microsoft/winget-cli/issues/new/choose).

Within WingetUI, what I can suggest you to do is to ignore updates for this package, this package does not get updated anymore
