### ISSUE TITLE
[ENHANCEMENT] (Touch screen respond)

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#1889]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

In Winget Settings, you can't scroll using touch.

### Describe how this improvement could help users.

For touch users, this would help in scrolling.

**Comment by marticliment** [comment]
Hello,

Please try the latest WingetUI Beta. It should have this issue fixed: https://github.com/marticliment/WingetUI/releases/download/3.0.0-beta1/WingetUI.Installer.exe

**Comment by skanda890** [comment]
> Hello,
> 
> Please try the latest WingetUI Beta. It should have this issue fixed: https://github.com/marticliment/WingetUI/releases/download/3.0.0-beta1/WingetUI.Installer.exe

How do I add this to my existing installation?

**Comment by skanda890** [comment]
Still doesn't work.

**Comment by marticliment** [comment]
> Still doesn't work.

I am sorry, the latest beta (the link provided) works with touch input. 
However, you will need to uninstall WingetUI and then install the file linked above

**Comment by skanda890** [comment]
> > Still doesn't work.
> 
> I am sorry, the latest beta (the link provided) works with touch input. However, you will need to uninstall WingetUI and then install the file linked above

I  did that, but still doesn't work

**Comment by marticliment** [comment]
As you can see, you are running version 2.2.0. The link I sent is for version 3.0.0. Once you have the version 3.0.0 installed touch support will work

**Comment by marticliment** [comment]
you will need to download it and install it

**Comment by skanda890** [comment]
Done!
