### ISSUE TITLE
[BUG] (When I updated WingetUI to 3.0.0 beta-1 from 2.2.0 the About page changed)

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#1897]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When I updated WingetUI to 3.0.0 beta-1 from 2.2.0 the settings page changed from this:

![image](https://github.com/marticliment/WingetUI/assets/99239826/c0a68ed2-0614-42b0-a129-8147da9d8726)

To this:

![image](https://github.com/marticliment/WingetUI/assets/99239826/d0b85a2d-6aa9-4b55-910a-f3372890881a)

### Steps to reproduce the issue

Update WingetUI from 2.2.0 to 3.00 beta-1.

### WingetUI Log

I refreshed my logs. So, it is not available.

### Package Managers Logs

I refreshed my logs. So, it is not available.

**Comment by skanda890** [comment]
The first picture looked more neat compared to the second one, which is why I created this issue. The first picture was a 2.20 settings page, while the second picture was the 3.0.0 beta-1 settings page. Is this a suggestion?

**Comment by skanda890** [comment]
> The picture you are showing in 2.2.0 is the "About" Tab, not the "Settings" Tab. The Settings tab remains mostly untouched on the update

Sorry for that. But still, the home page looks different. I can't show it because I am in 3.0.0 beta-1.

**Comment by skanda890** [comment]
Make the About page to this:

![image](https://github.com/marticliment/WingetUI/assets/99239826/c0a68ed2-0614-42b0-a129-8147da9d8726)

It looks more neat.

**Comment by marticliment** [comment]
I am sorry, but the changes introduced allow better content organization and accessibility. 
Currently Manager Information is listed on each manager's settings, and all the remaining about section has been split into 4 sections, accessible from the "About" button
Furthermore, the old version did not respond correctly to size changes, making it difficult to render on smaller displays.

Those changes do improve the accessibility and the organization of the interface, and they will not be reverted.
