### ISSUE TITLE
[ENHANCEMENT] (Change the settings page in 3.0.0 beta-1)

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#1898]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Make this settings page in 3.0.0 beta-1.

![image](https://github.com/marticliment/WingetUI/assets/99239826/c0a68ed2-0614-42b0-a129-8147da9d8726)

### Describe how this improvement could help users.

This is more neat and beautiful than the current settings page.

**Comment by skanda890** [comment]
See #1897 for more details.

**Comment by marticliment** [comment]
> This is more neat and beautiful than the current settings page.

Yes but the settings are not modifiable from here

**Comment by marticliment** [comment]
P.D. The settings page is planned to be redesigned on a future release so it is less cluttered than how it is now
