### ISSUE TITLE
[ENHANCEMENT] (Change the Suggest an improvement or an enhancement conditions)

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#1899]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

There are some mistakes in the Suggest an improvement or an enhancement conditions. For example: " This improvements refers to an existing feature. If you want to suggest a new feature, please use this template * ". 

### Describe how this improvement could help users.

The conditions won't have mistakes.

**Comment by marticliment** [comment]
Hello,

Grammarly doesn't understand YAML files and does not work with GitHub. 

I would appreciate if you could either do a PR with the corrections or if you could post here the errors and their corrections so I can fix them.

Thank you for the suggestion!

**Comment by skanda890** [comment]
> Hello,
> 
> Grammarly doesn't understand YAML files and does not work with GitHub. 
> 
> I would appreciate if you could either do a PR with the corrections or if you could post here the errors and their corrections so I can fix them.
> 
> Thank you for the suggestion!

How do I do that.

**Comment by marticliment** [comment]
Just post them here with their appropiate corrections and I will change them on the file.

**Comment by skanda890** [comment]
> Just post them here with their appropiate corrections and I will change them on the file.

Thanks.

**Comment by marticliment** [comment]
> > Hello,
> > Grammarly doesn't understand YAML files and does not work with GitHub.
> > I would appreciate if you could either do a PR with the corrections or if you could post here the errors and their corrections so I can fix them.
> > Thank you for the suggestion!
> 
> @marticliment, Open the YAML files in a text editor like Notepad or edit it in GitHub editor, and correct all the spelling mistakes using Grammarly but ignore the so-called YAML mistakes. That is what I did and it works.

Didn't work for me, but I will try again.

Thanks!

**Comment by skanda890** [comment]
Should I show you how to do it?

**Comment by marticliment** [comment]
Yes, it clearly does work now. Maybe I messed things up somewhere last time...

**Comment by skanda890** [comment]
You have to install it on your computer and the web browser.

**Comment by skanda890** [comment]
Check your email once.
