### ISSUE TITLE
Improve settings page

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#190]
- [x] Instead of deleting `.wingetui` folder in the user directory to reset settings to default, there should be a button to do that in the settings page, like ElevenClock has. 

- ~~[] Make this option default and remove it from settings (no one needs to disable this IMO):~~ I don't think we should change that, since people are now used to it

![Captura de tela 2022-10-13 181827](https://user-images.githubusercontent.com/73800734/195712859-d91c616a-56a6-4b6b-84f6-064f17bd6f5a.png)

- [x] Make the combobox greyed out (and unable to use) if the checkbox is unchecked:

![Captura de tela 2022-10-14 091213](https://user-images.githubusercontent.com/73800734/195844431-f1ebf112-9d60-4e68-be41-51045270a8f7.png)

**Comment by ppvnf** [comment]
>     [x]  Maybe scoop should be disabled by default (not my idea, but it kinda makes sense) [strange scoop messages in update tab #138 (comment)](https://github.com/martinet101/WingetUI/issues/138#issuecomment-1264340616) [85bc8f9](https://github.com/martinet101/WingetUI/commit/85bc8f965e0edf1c0cabf6b6d241a2119d3c4911)

I believe this was implemented here https://github.com/martinet101/WingetUI/commit/85bc8f965e0edf1c0cabf6b6d241a2119d3c4911

**Comment by martinet101** [comment]
> * Also, what do you think about making the option "ensure scoop is properly installed" able to fix this problem

I feel like the git unsafe directories have been made for some reason, and that external program shouldn't be _safing_ repos. I reckon this is a thing that scoop should get fixed by themselves.

**Comment by ppvnf** [comment]
> I feel like the git unsafe directories have been made for some reason, and that external program shouldn't be _safing_ repos. I reckon this is a thing that scoop should get fixed by themselves.

Okay. I would open an issue about this on Scoop, but I don't really know how to explain this problem. And it seems I am the only one affected, so it's probably not worth it

**Comment by ppvnf** [comment]
> * Make this option default a remove button (why would anyone disable this option?):

I've added this suggestion.

> * Add an option not to check for package updates when WingetUI is opened

Also, I'm removing this suggestion... Because it also seems pretty useless (you can add back if you think it's useful)

**Comment by ppvnf** [comment]
I am suggesting to have an option to not show tray icon

**Comment by martinet101** [comment]
I understand your request, but the icon is needed to throw notifications so the users would loose notifications. (WingetUI still warns about successful installs when on second-plane)

**Comment by ppvnf** [comment]
> I understand your request, but the icon is needed to throw notifications so the users would loose notifications. (WingetUI still warns about successful installs when on second-plane)

Isn't it possible to show notifications only with the regular taskbar icon?
If not, then the tray icon should always be shown
By the way, I've found a few apps that would accomplish that (hiding the tray icon), but I've still not tested if they show notifications:
https://www.raymond.cc/blog/stealth-or-hide-running-program-from-appearing-in-taskbar-or-traybar/

**Comment by martinet101** [comment]
> Isn't it possible to show notifications only with the regular taskbar icon?

Nope, on win32 apps the handler of notifications is the system tray icon.

**Comment by ppvnf** [comment]
Okay, I am gonna remove that from the task lost

**Comment by marticliment** [comment]
Fixed!

**Comment by ppvnf** [comment]
It works very well. Thanks!!
