### ISSUE TITLE
[BUG] WingetUI not updating to v3 (2.2.0 unaware of 3.0.0 release)

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/WingetUI#1904]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Perhaps it will just take some more time for the release of 3.0.0 to be picked up (it's only been an hour since), but currently, with the option "Update WingetUI automatically" enabled, I'm not getting any notice of 3's release.

### WingetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

### Screenshots and videos

About:

![wingetui_2024-03-13_16-02-42](https://github.com/marticliment/WingetUI/assets/25013746/621a1b9d-99f6-46ef-8b23-1b8923aa0304)

**Comment by marticliment** [comment]
Can you please share your log?

**Comment by redactedscribe** [comment]
It seems after a few WingetUI restarts, leaving it open for long enough solved the issue: There was a sneaky minimised UAC prompt waiting in my start bar. It has now updated.

The logs did show this however:

```
...
🟢 Searching for string ""
Exception in thread Thread-18 (updateIfPossible):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File ".\Interface\Application.py", line 557, in updateIfPossible
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\AppData\\Local\\Temp\\wingetui-updater.exe'
🟢 PowerShell source search finished with 1 sources
...
```
