### ISSUE TITLE
[BUG] Light/dark theme mixup

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#1906]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

V3.0.0 in dark theme shows a number of notifications and UI elements parly in light theme, thus rendering them illegible

### Steps to reproduce the issue

Settings: dark mode
Perform package updates
Feedback is illegible due to faulty colours

### WingetUI Log

```text
NA
```

### Package Managers Logs

```text
NA
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/10008599/d063ac68-28f8-4feb-8ede-36a2301cd821)
![image](https://github.com/marticliment/WingetUI/assets/10008599/31b9c54b-d55c-4b0d-be5f-d8f10d168151)

**Comment by marticliment** [comment]
Does restarting WingetUI fix the issue? Or the theme mixup is always there?

**Comment by Stephan-P** [comment]
After restart:
![image](https://github.com/marticliment/WingetUI/assets/10008599/16102047-800b-493a-9aad-45a8d662590a)
![image](https://github.com/marticliment/WingetUI/assets/10008599/19a126ce-88b5-459e-96f5-0c7c70371cef)

Okay, one issue less. :-)

**Comment by Stephan-P** [comment]
But another added as that Disclaimer is not translated in Dutch language ;-)

**Comment by marticliment** [comment]
I have checked and I actually forgot to mark it as translatable, so even if added to Tolgee it won't show translated.

I will fix this on the next release
