### ISSUE TITLE
[BUG] WingetUI won't open after 3.0.0 update

### ISSUE THREAD

**Issue by xsm2** [marticliment/WingetUI#1907]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

After the autoupdate installed 3.0.0 I'm unable to open WingetUI, I have also tried to reinstall it but it still doesn't work.

### Steps to reproduce the issue

Update from 2.2.0 to 3.0.0

### WingetUI Log

```text
I can't open the log from WingetUI, where are the logs located?
```

### Package Managers Logs

```text
I can't open the log from WingetUI, where are the logs located?
```

### Relevant information

I have tried to open it as admin, it makes no diference. Also the process does not appear in the task manager. I'm using W11 23H2

**Comment by Stephan-P** [comment]
Try to perform a thorough uninstall of WingetUI including removal of remaining files and folders in your user directory structure.
Then reinstall as new. 
This will obviously delete all previous settings. Alas.

**Comment by MisterXraj** [comment]
I have almost  the same problem. After3.0.0 Update, I can't open WingetUI as Administrator from a non administrative account..
Without administrative rights WingetUI opens, but doesn't schow any installed programm.

**Comment by marticliment** [comment]
> I have almost the same problem. After3.0.0 Update, I can't open WingetUI as Administrator from a non administrative account..

This is a known issue caused by the App Sdk



> Without administrative rights WingetUI opens, but doesn't schow any installed programm.

Please follow the steps on #1721

**Comment by xsm2** [comment]
There is an error in the Event Viewer, every time I try to open the app the same error appears, so it's from WingetUI:
![imagen](https://github.com/marticliment/WingetUI/assets/32161135/a93c3900-35a8-4251-9bc7-bfbf75fe84d9)

**Comment by marticliment** [comment]
This also happens when running WingetUI without administrator rights?

**Comment by xsm2** [comment]
That was without admin rights, but yes, same in error on both cases

**Comment by marticliment** [comment]
This appears to be an AppSdk Bug. Please downgrade to version 2.2.0 and disable updates until this issue can get fixed

**Comment by rumplin** [comment]
Adding more info to the issue I also have:

```
Faulting application name: wingetui.exe, version: 1.0.0.0, time stamp: 0x65a80000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3235, time stamp: 0x2b72307b
Exception code: 0xe0434352
Fault offset: 0x0000000000065b0c
Faulting process ID: 0x0x63F4
Faulting application start time: 0x0x1DA758C40C374E3
Faulting application path: C:\Program Files\WingetUI\wingetui.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 70b91cbe-acb7-44c2-bbd3-dbb5813193c0
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: wingetui.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x8001010E): The application called an interface that was marshalled for a different thread.

The application called an interface that was marshalled for a different thread.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IInfoBarMethods.set_Title(IObjectReference _obj, String value)
   at Microsoft.UI.Xaml.Controls.InfoBar.set_Title(String value)
   at ModernWindow.Structures.AppTools.UpdateWingetUIIfPossible(Int32 round) in Y:\WingetUI-Store\src\wingetui\Core\Tools.cs:line 419
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by rumplin** [comment]
Last working version for me was 3.0 Beta 1

**Comment by rumplin** [comment]
duplicate #1952

**Comment by marticliment** [comment]
I am afraid they are not the same issue

**Comment by marticliment** [comment]
@rumplin, your issue is different. Please install WingetUI 3.0.0 manually and the issue should go away

**Comment by marticliment** [comment]
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**
