### ISSUE TITLE
[BUG] (Source isn't visible)

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#1915]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I tried to install the sources of Winget, and the winget source connected, but msstore source didn't connect. 

![image](https://github.com/marticliment/WingetUI/assets/99239826/ffef58c2-2065-4481-a0f2-719f861e46dd)

### Steps to reproduce the issue

Reset Winget sources, then try to link the source msstore.

### WingetUI Log

https://1drv.ms/t/s!Aqq-Je19xlrfiB4ObjhOZMgbbEfX?e=WM6EGY

### Package Managers Logs

https://1drv.ms/t/s!Aqq-Je19xlrfiB-s-P9GO2VuoRVa?e=ML5T0U

**Comment by marticliment** [comment]
try resetting winget sources

**Comment by skanda890** [comment]
I tried that but still doesn't work.

**Comment by LM1LC3N7** [comment]
Hi!
I may have the same issue. Winget source is gone in the "installed packages" list.
It's like I don't have any apps installed using winget (all of my apps were installed using it though).

Actions tried:
* Reset winget sources (using the UI) --> Same issue
* Using the winget executable from WingetUI path, to installed apps (using CLI) --> all my packages are listed
* Adding manually winget sources in the UI --> This asks for admin rights and then exit with error "source already exists"

I don't know what to do the get WingetUI working again with my winget apps.

**Comment by skanda890** [comment]
> Hi! I may have the same issue. Winget source is gone in the "installed packages" list. It's like I don't have any apps installed using winget (all of my apps were installed using it though).
> 
> Actions tried:
> 
> * Reset winget sources (using the UI) --> Same issue
> * Using the winget executable from WingetUI path, to installed apps (using CLI) --> all my packages are listed
> * Adding manually winget sources in the UI --> This asks for admin rights and then exit with error "source already exists"
> 
> I don't know how to get WingetUI working again with my Winget apps.
> 
> **[EDIT]** Just tried also to completely remove WingetUI before reinstalling it.
> 
> 1. Uninstalled using Windows standard procedure
> 2. Force delete the C:\Program Files\WingetUI folder
> 3. Force delete the C:\Users<user>\AppData\Local\WingetUI folder
> 4. Reinstall the last version
> 5. Same issue, only packets from PowerShell and Scoop sources are listed in "installed packages"

I did this and this worked, but still, I couldn't access it.

**Comment by skanda890** [comment]
I did something, that I forgot made the Installed Apps back to normal.

**Comment by LM1LC3N7** [comment]
For the records, some answers are here:
https://github.com/marticliment/WingetUI/issues/1721

**Comment by skanda890** [comment]
Wait but the source is still missing.

**Comment by LM1LC3N7** [comment]
I found a solution: https://github.com/marticliment/WingetUI/issues/1721#issuecomment-1997441398

**Comment by skanda890** [comment]
1721#issuecomment-1997487188

**Comment by skanda890** [comment]
I replied on #1721 (comment).
(https://github.com/marticliment/WingetUI/issues/1721#issuecomment-1997487188)

**Comment by skanda890** [comment]
The source is still not being added.
