### ISSUE TITLE
[BUG] This application requires Windows App Runtime Version 1.5

### ISSUE THREAD

**Issue by rumplin** [marticliment/WingetUI#1926]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Because of issues #1907 I uninstalled WingetUI, downloaded the installer from releases and installed it from scratch.
Now when I try to start WingetUI I get a window telling me "This application requires Windows App Runtime Version 1.5"

### WingetUI Log

```text
Can't open the App, doubt logs will tell you anything more than the included screenshot will.
```

### Package Managers Logs

```text
N/A
```

### Screenshots and videos

![Screenshot 2024-03-13 222948](https://github.com/marticliment/WingetUI/assets/35449956/0af3c324-1580-44e6-88b2-37b8e77f4040)

**Comment by rumplin** [comment]
EventLog: `Package dependency criteria could not be resolved. `

**Comment by marticliment** [comment]
The installer should install AppRuntime automatically. Please download and install the version here: https://github.com/marticliment/WingetUI/blob/main/InstallerExtras/appsdk.exe

It is the one bundled with the installer, and it is the one that is supposed to work with WingetUI

**Comment by rumplin** [comment]
> The installer should install AppRuntime automatically. Please download and install the version here: https://github.com/marticliment/WingetUI/blob/main/InstallerExtras/appsdk.exe
> 
> It is the one bundled with the installer, and it is the one that is supposed to work with WingetUI

I have seen it being installed during the installation process.
But it's strange tha it's installed into a temp folder?
![Screenshot 2024-03-13 233206](https://github.com/marticliment/WingetUI/assets/35449956/41e55fc6-05c3-423d-8970-834269c90f59)

**Comment by rumplin** [comment]
I uninstalled WingetUI and deleted all the folders of WingetUI in my C:\Users\<my username>\AppData\

The installation now worked, I can start Winget 3.0.

I have another PC where I didn't try Winget 3.0 Beta 1, and there the update was smooth there.

**Comment by marticliment** [comment]
> > The installer should install AppRuntime automatically. Please download and install the version here: https://github.com/marticliment/WingetUI/blob/main/InstallerExtras/appsdk.exe
> > It is the one bundled with the installer, and it is the one that is supposed to work with WingetUI
> 
> I have seen it being installed during the installation process. But it's strange tha it's installed into a temp folder? ![Screenshot 2024-03-13 233206](https://private-user-images.githubusercontent.com/35449956/312640003-41e55fc6-05c3-423d-8970-834269c90f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTQ3NTAsIm5iZiI6MTcxMDQxNDQ1MCwicGF0aCI6Ii8zNTQ0OTk1Ni8zMTI2NDAwMDMtNDFlNTVmYzYtMDVjMy00MjNkLTg5NzAtODM0MjY5YzkwZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDExMDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5OTNhNjI0OTc2MWI1YWIwZGRkYWZjYjgyNzcxMDNiYmUzZTZmZjhjMTYwMmY3NjAyMDVmZjIyMDE0ODllZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06ehW34djWyEvuIKo5-LmQcRzJNOIX3tUOccrTcBvnw)

Dependency installers are copied to a temp folder

**Comment by MacGyverPY** [comment]
> The installer should install AppRuntime automatically. Please download and install the version here: https://github.com/marticliment/WingetUI/blob/main/InstallerExtras/appsdk.exe
> 
> It is the one bundled with the installer, and it is the one that is supposed to work with WingetUI

can i get this?
i got the same error, fresh install.

**Comment by marticliment** [comment]
Open the link and click on `View raw` to download the file

**Comment by MacGyverPY** [comment]
ok my issue must be different...
i thought, the appsdk.exe was a bad file...or outdate or something... 
i redownloaded it again...


<img src="https://media.discordapp.net/attachments/463487959606493194/1219327710598397983/image.png?ex=660ae66c&is=65f8716c&hm=7dd2c158986d883911ab5cfc48e61eeef3f865b64d65f0420aa771f99cb1ed87&=&format=webp&quality=lossless" alt="Screenshot 2024-03-13 233206" style="max-width: 100%;">

it runs and says installed with a 0x0
but then i run a script to see... 

<img src='https://media.discordapp.net/attachments/463487959606493194/1219330218234351616/image.png?ex=660ae8c2&is=65f873c2&hm=756d385c85a5d7308b5e183f072494fe68f23fbb4f8eaf689d3b8cd736bf75ec&=&format=webp&quality=lossless" alt="Screenshot 2024-03-13 233206" style="max-width: 100%;">

i guess its on my end...
