### ISSUE TITLE
[ENHANCEMENT] Installer should not always install WindowsDesktopRuntime

### ISSUE THREAD

**Issue by CanePlayz** [marticliment/WingetUI#1931]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Pretty straightforward, the installer should perform a check if the necessary runtimes are already installed. I don't know if that's possible for the Windows App Runtime, but when it comes to the .NET runtime(s), the Nuget package [here](https://github.com/Tyrrrz/DotnetRuntimeBootstrapper)  adds an interesting way of distributing software as a bootstrapped deployment. The README summarizes pretty well how that sort of deployment works and what the benefits are.

### Describe how this improvement could help users.

There would be no duplicate installations of runtimes

**Comment by marticliment** [comment]
This library sounds promising, will take a look at it!

**Comment by CanePlayz** [comment]
Thanks for the changes
