### ISSUE TITLE
[ENHANCEMENT] "Old" Winget used to start minimized.  Winget 3 doesn't seem to.

### ISSUE THREAD

**Issue by DaleWebb1** [marticliment/WingetUI#1933]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

"Old" Winget used to start minimized to the System Tray.  Winget 3 starts in a large window.  Can't find an option to start it minimized.  Is there one?

### Describe how this improvement could help users.

Obvious

**Comment by marticliment** [comment]
It should start minimized, please try reinstalling WingetUI to rebuild all the winreg links and let me know if it works.

**Comment by DaleWebb1** [comment]
Thank you.  It started minimized this morning.
