### ISSUE TITLE
[BUG] New UI is terrible

### ISSUE THREAD

**Issue by makedir** [marticliment/WingetUI#1934]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Please dont ruin this software. The new UI is terrible.

1. loads slower
2. buggy:

![image](https://github.com/marticliment/WingetUI/assets/6721083/dbaa3694-eb48-4aa1-a31b-b7228e1dc28b)

3. annoying UI, the buttons on the side are annoying compared to old style

Please give option to revert back to old design UI

### WingetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

**Comment by kajoken** [comment]
Yeah, the new ui is absolutely terribad. It doesn't even save window settings and always opens in some stretched mode with massive empty space.

**Comment by marticliment** [comment]
Let's remember the community guidelines. It is not cool to say that the interface is terrible. 

You may say you don't like it or that there are missing features, and open a bug report for them. But do not do destructive criticism.

Please do as @redactedscribe, who constructively proposed changes and explained their dislikes. If you still do destructive content you will be banned.

**Comment by marticliment** [comment]
@redactedscribe, I have moved your suggestions to #1948
