### ISSUE TITLE
[ENHANCEMENT](Remove the scroll bar)

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#1949]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Remove the scroll bar.

![image](https://github.com/marticliment/WingetUI/assets/99239826/ec57a100-44b0-4af9-89b8-751b2fd2b3da)

### Describe how this improvement could help users.

This could resolve this issue #1911.

**Comment by marticliment** [comment]
Why, wouldn't the solution be to remove the scrollbar?

**Comment by skanda890** [comment]
> Why, wouldn't the solution be to remove the scrollbar?

Check again.

**Comment by marticliment** [comment]
The scrollbar has been removed. The fix will be available with the next release
