### ISSUE TITLE
[BUG] WingetUI no longer starts after installation of 2024-03 Cumulative Update for Windows 10 (KB5035845)

### ISSUE THREAD

**Issue by pro-sumer** [marticliment/WingetUI#1952]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Since the installation of the 2024-03 Cumulative Update for Windows 10 ([KB5035845](https://support.microsoft.com/en-us/topic/march-12-2024-kb5035845-os-builds-19044-4170-and-19045-4170-24e9864f-0756-457e-bce9-3f681020d591)) WingetUI no longer starts (no GUI; errors in Event Viewer). I was still using WingetUI 2.x, but manually installing 3.x did not help either.

### Steps to reproduce the issue

Start WingetUI

### WingetUI Log

```text
Not possible; WingetUI does not start
```

### Package Managers Logs

```text
Not possible; WingetUI does not start
```

### Relevant information

Errors in Event Viewer:

```
Application: WingetUI.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFF8F29C5E4 (0x00007FFF8F110000) with exit code 0x80131506.
```

and:

```
Faulting application name: WingetUI.exe, version: 1.0.0.0, time stamp: 0x65a80000
Faulting module name: coreclr.dll, version: 8.0.324.11423, time stamp: 0x65cd500d
Exception code: 0xc0000005
Fault offset: 0x000000000018c5e4
Faulting process id: 0x85c
Faulting application start time: 0x01da763314e64616
Faulting application path: C:\Program Files\WingetUI\WingetUI.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\coreclr.dll
Report Id: <REDACTED>
Faulting package full name: 
Faulting package-relative application ID: 
```

### Screenshots and videos

N/A

**Comment by marticliment** [comment]
Hello @pro-sumer,

I am afraid this is caused by a faulty .NET runtime, as the error message suggest. Please try uninstalling all .NET 8 entries from Windows Settings and downloading the .NET 8 runtime again

**Comment by pro-sumer** [comment]
Can anyone help me with this?

I can't find any .NET entries in Windows Settings.

Instead, I manually removed `C:\Program Files\dotnet\shared\Microsoft.NETCore.App` (which only contained `8.0.3`). 
WingetUI then informs me that I should install .NET 8 and offers to download the installer.

Next, I started the downloaded installer and chose "Repair".
WingetUI gives the same errors as I reported before.

Finally, I next started the installer again and chose "Uninstall" after which I started the installer once more and chose "Install".
WingetUI gives the same errors as I reported before.

How can I fix my .NET 8 setup?

**Comment by pro-sumer** [comment]
The CLI `winget` shows these .NET entries:

```
Microsoft .Net Native Framework Package 1.2 Microsoft.NET.Native.Framework.1.2_8wekyb3d8bbwe     1.2.23231.0
Microsoft .Net Native Framework Package 1.3 Microsoft.NET.Native.Framework.1.3_8wekyb3d8bbwe     1.3.24211.0
Microsoft .Net Native Framework Package 1.6 Microsoft.NET.Native.Framework.1.6_8wekyb3d8bbwe     1.6.27413.0
Microsoft .Net Native Framework Package 1.7 Microsoft.NET.Native.Framework.1.7_8wekyb3d8bbwe     1.7.27413.0
Microsoft .Net Native Framework Package 2.1 Microsoft.NET.Native.Framework.2.1_8wekyb3d8bbwe     2.1.27427.0
Microsoft .Net Native Framework Package 2.2 Microsoft.NET.Native.Framework.2.2_8wekyb3d8bbwe     2.2.29512.0
Microsoft .Net Native Runtime Package 1.1   Microsoft.NET.Native.Runtime.1.1_8wekyb3d8bbwe       1.1.23406.0
Microsoft .Net Native Runtime Package 1.4   Microsoft.NET.Native.Runtime.1.4_8wekyb3d8bbwe       1.4.24201.0
Microsoft .Net Native Runtime Package 1.6   Microsoft.NET.Native.Runtime.1.6_8wekyb3d8bbwe       1.6.24903.0
Microsoft .Net Native Runtime Package 1.7   Microsoft.NET.Native.Runtime.1.7_8wekyb3d8bbwe       1.7.27422.0
Microsoft .Net Native Runtime Package 2.1   Microsoft.NET.Native.Runtime.2.1_8wekyb3d8bbwe       2.1.26424.0
Microsoft .Net Native Runtime Package 2.2   Microsoft.NET.Native.Runtime.2.2_8wekyb3d8bbwe       2.2.28604.0
Microsoft Windows Desktop Runtime - 8.0.3 … Microsoft.DotNet.DesktopRuntime.8                    8.0.3                         winget
```

**Comment by marticliment** [comment]
please try un installing the update that caused this issue through windows settings

**Comment by albotroz** [comment]
same problem
I don't even know which (if any) update is responsible for this.

**Comment by pro-sumer** [comment]
> please try un installing the update that caused this issue through windows settings

That update [fixes 61 CVE's](https://msrc.microsoft.com/update-guide/releaseNote/2024-Mar), so I'd rather not do that.

However, this weekend I will have access to two more PC's that most likely won't have updated yet and I will try to test WingetUI 3 before and after the updates.

On this PC I'm afraid I'll have to use the CLI until this is fixed.

**Comment by ygorigor** [comment]
For me the solution was to remove .NET 8.0.3 and install .NET 8.0.0

**Comment by pro-sumer** [comment]
> For me the solution was to remove .NET 8.0.3 and install .NET 8.0.2

Just tried that. Your workaround also works for me. Thanks for sharing!

What did change between 8.0.2 and 8.0.3 that breaks WingetUI?

**Comment by tomasz1986** [comment]
I can confirm that downgrading from NET 8.0.3 to .NET 8.0.2 allows WingetUI to start again. However, for me, the problem also affects other .NET software (e.g. https://github.com/Rem0o/FanControl.Releases), so I think that the culprit may be something more widespread and caused a problem in the new .NET version itself.

**Comment by stevemagruder** [comment]
Downgrading to .NET 8.0.2 fixed it for me on Windows 10. Note that Winget UI 3.0.1 runs fine with .NET 8.0.3 on Windows 11.

**Comment by ShayBox** [comment]
This shouldn't be closed yet, it's still an active issue preventing anyone with the latest up-to-date version of dotnet runtime 8.0.3 from using the program, I spent the last week uninstalling and re-installing dotnet runtime because the popups kept sending me to the new broken version.

Currently, this program does not launch for anyone unless they know to downgrade, and even when an update to dotnet runtime gets released nobody will have Winget UI working to update the package, again unless they know to upgrade.

It's also an issue with other programs so a linking issue to the upstream dotnet runtime repo to show them how widespread this issue is will help fix it sooner.

**Comment by marticliment** [comment]
I am afraid this is not an issue with WingetUI, but with .NET or App Sdk. The issue on App Sdk is already open, so leaving this issue open does not make sense for me. 

I will publish a post explaining how to downgrade .NET and WingetUI and pin it to the top
