### ISSUE TITLE
Quite annoying default window size

### ISSUE THREAD

**Issue by chjohans** [marticliment/WingetUI#1963]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

My display size is 3440x1440. The newest WingetUI starts with a window that is 2566x1022 pixels. The default height is not all that bad, but the width is just rediculous with lots of unused space in both sides of the window. The main content of the app does not scale very well, so anything wider than about 1438 pixels is just a waste of space. Please see the two attached screenshots, one where the window is 2566x1022 and it shows all the wasted space, and one 1where the window is 438x1022 and it shows exactly the same information, since the different elements in the app window does not scale very well.

This would not be all that bad if the app could remember it's last window size, and use that the next time it's started. But it does not, it always starts (for me) in a 2566x1022 window and it's quite annoying to have to resize that window on every restart.
![snap004004](https://github.com/marticliment/WingetUI/assets/24390228/5b1a4a89-2ab3-4eae-a2d8-1544fc3c4c55)
![snap004005](https://github.com/marticliment/WingetUI/assets/24390228/ec732749-2c34-419b-83e5-ca8b72f36249)

### Describe how this improvement could help users.

It would be a much betetr user experience if the app started with a more reasonable window size, and if it could remember it's own last size.

**Comment by marticliment** [comment]
I have widened the maximum size, but it won't be unlimited since there is a point where the text is too separated and it becomes difficult to properly read packages and not confuse the texts

![image](https://github.com/marticliment/WingetUI/assets/53119851/48781d6d-0638-4bb8-9477-2b6970c57051)

**Comment by aaronliu0130** [comment]
Would this remember the window size?

**Comment by marticliment** [comment]
No, this requires a different implementation

**Comment by chjohans** [comment]
It's a bit better, but still a lot of wasted space on each side. The real issue is the height-width ratio of the default window, that is enforced every time WingetUI is started. A better solution would be to remember the window size between restarts, a workaround would be not to open such a wide window on a widescreen monitor.

**Comment by marticliment** [comment]
> It's a bit better, but still a lot of wasted space on each side

But there is one point at which wider does not mean more content in the screen



> A better solution would be to remember the window size between restarts, a workaround would be not to open such a wide window on a widescreen monitor.

This feature has already its own support ticker

**Comment by aaronliu0130** [comment]
I think they're saying the default window size is too large

**Comment by chjohans** [comment]
Precisely, by default the window size is 2566x1022 pixels that opens up in the middle of my screen, covering most other windows. Yes, a small nuiance, but quite unnecessary. If you shring the width to about 1488 the exact same information will fit, and the window would not take up most of my screen estate. So please consider shrinking the default window size a bit. Please see the screenshots I oroginally atatched.

**Comment by marticliment** [comment]
Yes, I understand, and next version will remember your window size and position so this annoyance does not happen again

**Comment by aaronliu0130** [comment]
Was their an improvement in the default window size for 3.0? 2.0 had a very good default.

**Comment by marticliment** [comment]
> Was there an improvement in the default window size for 3.0?

WinUI3 does handle the default sizes differently than Qt.

**Comment by chjohans** [comment]
Wich in my opinion is not a good thing. The default window size was fine in v2.x, but not at all fine in v3.x.

**Comment by aaronliu0130** [comment]
I think they mean that it's a limitation with the new, native-r framework

**Comment by marticliment** [comment]
Yes

**Comment by chjohans** [comment]
Well, if WIngetUI will remember it's last windows size between restarts then this is a non-issue anyhow :)
