### ISSUE TITLE
[BUG] WinGetUI doesn't start

### ISSUE THREAD

**Issue by LennartRoeder** [marticliment/WingetUI#1966]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The UI in Version 3 does not start (2.2.0 works). The Windows Event Viewer shows this error message:
```
Windows App Runtime 
   ERROR 0x80070490: Bootstrapper initialization failed while looking for version 1.5 (MSIX package version >= 5001.70.1338.0) 
```

### Steps to reproduce the issue

start WingetUI.exe under Windows 11 

### WingetUI Log

```text
no logs
```

### Package Managers Logs

```text
no logs
```

**Comment by marticliment** [comment]
Please try uninstalling any "App Runtime" or "App Sdk" entry on Windows Settings and then reinstall WingetUI

**Comment by LennartRoeder** [comment]
@marticliment unfortunately that did not help.

**Comment by marticliment** [comment]
How are you installing WingetUI?

**Comment by LennartRoeder** [comment]
I took the binary from GitHub Releases and installed it systemwide. Tried user Install as well, which didn't change it.
SInce user Install did not work because of an `ö` in my `c:/users/<username>` I wend ahead and renamed it.

**Comment by marticliment** [comment]
Please reinstall WingetUI 2.2.0 and disable updates. I will try to fix this as soon as I can

**Comment by LennartRoeder** [comment]
thank you.
If a new release comes out, I am happy to retest it.

**Comment by Pitt-The** [comment]
I confirm the problem. On Windows logon WingetUI v.2.2.0 updated itself. 
When finished, I tried to start the new version, but it did not respond. Reboot didn’t help. 

I noticed the same error: 
```
Event ID: 1168
EventData: Windows App Runtime 
ERROR 0x80070490: Bootstrapper initialization failed while looking for version 1.5 (MSIX package version >= 5001.70.1338.0)
```

**Comment by LennartRoeder** [comment]
@marticliment @Pitt-The Version 3.0.1 fixes the issue for me.

**Comment by Tschak77** [comment]
For me it was different. I installed 3.0.1 first time at this pc and wingetui not running at all. I've got also the event id 1168
Windows App Runtime 
   ERROR 0x80070490: Bootstrapper initialization failed while looking for version 1.5 (MSIX package version >= 5001.70.1338.0) 
 
After uninstall and install 2.2 wingetui is running. But after autoupdate to 3.0.1 same error again.

**Comment by SteffenM-DE** [comment]
Same here 3.01 do not start / autostart.
