### ISSUE TITLE
[ENHANCEMENT] Clicking notification to open / focus WingetUI

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/WingetUI#1972]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

When a notification pops up to inform you of something, e.g. that there is an update available, clicking the notification should bring WingetUI to the foreground (ideally with the updates tab open if the notification was about an available update).

### Describe how this improvement could help users.

-

**Comment by marticliment** [comment]
This happens if WingetUI is closed. 

If WingetUI is open, the Window Manager does not allow an open window to get raised to the top of the other windows. Therefore the window will need to be focused manually
