### ISSUE TITLE
[ENHANCEMENT] (There is a mistake in Welcome to new WingetUI)

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#1981]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

There is a mistake in Welcome to new WingetUI.

As it is:

![image](https://github.com/marticliment/WingetUI/assets/99239826/a326ee66-3c72-457c-a9f7-b0e8cf0c01ff)

As it should be:

Welcome to New WingetUI

You are using the new WingetUI 3.0.1. I want to hear your opinion about it.
Do you have any issues or suggestions? Please post them here.

### Describe how this improvement could help users.

There are mistakes in Welcome to new WingetUI, this would correct them.

**Comment by marticliment** [comment]
I have modificed the file, but changes will take a while to be deployed due to caching
