### ISSUE TITLE
[ENHANCEMENT] (Some translations are missing)

### ISSUE THREAD

**Issue by gidano** [marticliment/WingetUI#1983]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

A fotókon megjelent angol szövegek eredetije hiányzik a Tolgee fordításnál.

### Describe how this improvement could help users.

![wingetui notranslation 1](https://github.com/marticliment/WingetUI/assets/4068977/4a1ee249-f89e-4f64-b4a8-1330a21a52bc)
![wingetui notranslation 2](https://github.com/marticliment/WingetUI/assets/4068977/9385a0bb-7550-4666-8f06-5e6d41f69d44)
![wingetui notranslation 3](https://github.com/marticliment/WingetUI/assets/4068977/129c96d0-aece-48a8-8518-588e000191d5)

**Comment by Stephan-P** [comment]
![image](https://github.com/marticliment/WingetUI/assets/10008599/3b34c4f1-a491-48c1-b180-93809eb0d058)

**Comment by Stephan-P** [comment]
In the Backup settings:

![image](https://github.com/marticliment/WingetUI/assets/10008599/200df804-ddde-4f86-a843-ff50219a85d9)

**Comment by marticliment** [comment]
This one works for me:
![image](https://github.com/marticliment/WingetUI/assets/53119851/861c1368-546e-48bc-a6d4-99e33d0317e5)

**Comment by Stephan-P** [comment]
![image](https://github.com/marticliment/WingetUI/assets/10008599/7c0cb311-bee6-4fd8-9581-eeca582a6aeb)

This wasn't translated this morning.
Is Tolgee still connected with whatever mechanism is taking care of the automated translation updates?

**Comment by marticliment** [comment]
Yes, it is, but sometimes some strings get delayed

**Comment by Stephan-P** [comment]
On another system things look differently. Here the button Open is not displayed, or - I suspect - displayed underneath the larger button Select. So, in the earlier screenshot we seem to be looking at a button Open that was actually cropped. 
I figure this is another place where flexible positioning within the available width would need improvement.

![image](https://github.com/marticliment/WingetUI/assets/10008599/934350c7-354b-4e14-bd92-71420af5583f)

**Comment by marticliment** [comment]
Fixed! (System language has been left in english to improve accessibility)

![image](https://github.com/marticliment/WingetUI/assets/53119851/93c5648c-261a-45e9-809f-6836cbc2d9b6)
![image](https://github.com/marticliment/WingetUI/assets/53119851/f4383259-59b3-4bdb-af00-b7b9e9250507)
