### ISSUE TITLE
[BUG] Systray menu shows untranslated option: Available Updates

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#1984]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The systray menu option **Available Updates** is not translated

### Steps to reproduce the issue

Setup WingetUI in non-English UI language.
Open the system tray and RMB click WingetUI.
The menu shows the option "Available Updates"  in English whilst the other menu options are properly translated in the selected language. See screenshot below.

![image](https://github.com/marticliment/WingetUI/assets/10008599/fb309a06-ba04-44ad-8880-20d1cde744d7)

### WingetUI Log

```text
NA
```

### Package Managers Logs

```text
NA
```

### Relevant information

WingetUI version 3.0.1
Windows 11

**Comment by marticliment** [comment]
Duplicate of #1983

**Comment by Stephan-P** [comment]
Also reported here: https://github.com/marticliment/WingetUI/issues/1983
