### ISSUE TITLE
FIX FOR WINGETUI NOT LAUNCHING

### ISSUE THREAD

**Issue by marticliment** [marticliment/WingetUI#2000]
## If WingetUI is not launching, do the following steps
1. Go to *Windows Settings* -> *Apps* -> *Installed Apps*
2. Uninstall the following packages (some of them may not be present on your machine):
   a) `WingetUI`
   b) `Windows App Runtime Main`
   c) `Windows App Runtime DDLM 5xxx.xx.xxxx.x`
   d) `Microsoft Windows App Runtime Singleton`
3. Download and install WingetUI from here: https://github.com/marticliment/WingetUI/releases/download/3.0.1/WingetUI.Installer.exe
4. Quit WingetUI and return to Windows Settings
5. Uninstall the following packages:
   e) `Microsoft .NET Runtime 8.0.X (x64)`
   f) `Microsoft .NET SDK 8.0.X (x64)`
6. Install .NET Desktop Runtime 8.0.2 using the following URL: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.2-windows-x64-installer

## If the steps above do not work, please downgrade to version 2.2.0:
1. Navigate to *C:\Users\<your-username>\.wingetui*
2. Right-click the folder -> *Create* -> *Text document*
3. Rename the file to  `DisableAutoUpdateWingetUI`. Make sure to remove the `.txt` extension from the file name.
6. Uninstall WingetUI from the windows settings
7. Download and install WingetUI 2.2.0 from here: https://github.com/marticliment/WingetUI/releases/download/2.2.0/WingetUI.Installer.exe

## Explanation of the issue: 
This issue mostly happens due to a bug on .NET 8.0.3 (hence the downgrade to 8.0.2) or for the Windows App Sdk not being installed properly. I am working to fix this issue, but since it is not directly caused by WingetUI, it is hard to fix it.

**Comment by stevehoek** [comment]
Unfortunately these steps did not work for me... WingetUI did not launch after installing in step 4, so I remove Desktop Runtime 8.0.3 (installed by WingetUI) and installed the linked 8.0.2 but still does not run.

Going back to v2 and blocking upgrades... this is sad because WingetUI 3.x DID work for awhile on these machines.

**Comment by stevehoek** [comment]
Still the same error in Event Viewer... access denied

```
Log Name:      Application
Source:        Windows App Runtime
Date:          4/1/2024 9:02:20 AM
Event ID:      5
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      TIGGER
Description:
Access is denied.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows App Runtime" />
    <EventID Qualifiers="32775">5</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-04-01T13:02:20.4721576Z" />
    <EventRecordID>749572</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TIGGER</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Windows App Runtime</Data>
    <Data>ERROR 0x80070005: Bootstrapper initialization failed while looking for version 1.5 (MSIX package version &gt;= 5001.70.1338.0)</Data>
  </EventData>
</Event>

```

**Comment by OniriCorpe** [comment]
> Still the same error in Event Viewer... access denied

Exact same error for me, after the first message steps

**Comment by marticliment** [comment]
Please share with me the output and exit code of installing this file:

https://aka.ms/windowsappsdk/1.5/latest/windowsappruntimeinstall-x64.exe

**Comment by stevehoek** [comment]
> Please share with me the output and exit code of installing this file:
> 
> https://aka.ms/windowsappsdk/1.5/latest/windowsappruntimeinstall-x64.exe

`
Installing license: MSIX_MAINPACKAGE_LICENSE
Install License result : 0x0
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install License result : 0x0
All install operations successful.
`

**Comment by OniriCorpe** [comment]
![image](https://github.com/marticliment/WingetUI/assets/6963387/77cc6225-5437-4ac9-9449-a69767a1c1db)

same

**Comment by jdrch** [comment]
I'm experiencing this bug too, on [this machine](https://github.com/jdrch/Hardware/blob/master/Lenovo%20L380%20Yoga%20ThinkPad%2020M7CTO1WW.md). I'm on Windows 11 Beta on an Intel Core 8th Gen with an iGPU. Anyone else with the same/similar config?

**Comment by jdrch** [comment]
Issue persists after updating to `Microsoft .NET Runtime 8.0.X (x64)`. Strangely, only the above machine is affected.

**Comment by gleib** [comment]
Same bug. WinGetUI was working fine prior to the following upgrades today:
2024-04 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5036893
2024-04 .NET 8.0.4 Security Update for x64 Client (KB5037338)
All prior Windows 11 upgrades had been performed.

Error in Event Log --> Windows Logs --> Application ...
Windows App Runtime 
   ERROR 0x80070490: Bootstrapper initialization failed while looking for version 1.5 (MSIX package version >= 5001.70.1338.0) 

Fix above did not work.

**Comment by jdrch** [comment]
@gleib Which Windows 11 channel are you on: Beta, Canary, or ... ? Asking because my non-Beta, Stable Channel Windows 11 machines are unaffected.

**Comment by jdrch** [comment]
@gleib I have that option enabled too!

**Comment by gleib** [comment]
Decided to proceed with upgrades using winget in the command line. Among the listed upgrades ...
"Microsoft Windows Desktop Runtime - 8.0.3 (x64)" with an indication the 8.0.4 (x64) was available.
Did this upgrade among others (specific user apps, not system components), then did a BIOS upgrade and re-booted.
Following re-boot WinGetUI was working!

**Comment by marticliment** [comment]
Hello, 

Please test this custom build and let me know if it works: https://drive.google.com/file/d/1NO8jhMDBPmMGvlnaW5MXv5vjYjvmFJLa/view?usp=sharing

Thanks!

**Comment by marticliment** [comment]
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**

**Comment by gleib** [comment]
As noted above ... my WinGetUI installation (3.0.1) started working when discovered and updated "Microsoft Windows Desktop Runtime - 8.0.3 (x64)" to 8.0.4. That said, installed WinGetUI 3.0.2 and that is working fine as well.
Thanks!

**Comment by jdrch** [comment]
@marticliment confirming that `3.0.2` resolves the issue. Thanks very much!
