### ISSUE TITLE
[FEATURE REQUEST] Rename WingetUI to UnigetUI

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#2004]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Rename WingetUI to UnigetUI.

### Describe how this new feature could help users.

This would help in differentiating between Microsoft WingetUI and this WingetUI.

**Comment by marticliment** [comment]
Please read https://github.com/marticliment/WingetUI/discussions/1900
