### ISSUE TITLE
[FEATURE REQUEST] Make a new type of issue called Branding issue

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#2005]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Make a new type of issue called Branding issue.

### Describe how this new feature could help users.

This new issue type can be used for branding purposes, for example, #2004

**Comment by marticliment** [comment]
This is a one-time issue, therefore it does not make sense to create a new issue type
