### ISSUE TITLE
[MANAGER] add support for portable apps

### ISSUE THREAD

**Issue by rtritto** [marticliment/WingetUI#2010]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Add support (version check, install, uninstall, update) to portable apps like apps in _PortableApps.com_ format.

### Describe how this new feature could help users.

The source (foder that contains portable apps or path of a single portable app) must be added to scan.
_PortableApps_ apps have the same tree and app info can be found in `AppInfo` folder.

**Comment by marticliment** [comment]
PortableApps does not support integrations. They currently have no public api and only allow integrations on entreprise licenses.
https://portableapps.com/node/62757

**Comment by njc888** [comment]
i have installed calibre on a seperate internal drive as my system houses two windows os, one for work and other is the oem. however  calibre needs to be updated by me manually. is it possible that you can specify a portable app location so that the app version can be montiored and updated as required
