### ISSUE TITLE
[ENHANCEMENT] Disable startup update check

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [marticliment/WingetUI#2012]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Currently whenever I start WingetUI, it automatically checks all apps for updates.

Considering that I already set in WingetUI settings to check for packages updates each 8 hours, it should a timestamp of the last check for updates event and do not trigger it unless the 8 hours have passed (unless running the update check manually which should reset the timestamp)

### Describe how this improvement could help users.

Checking updates takes a lot of time while loading (if there are lots of packages installed), spawning processes and connections. In my particular case, I use aninteractive firewall which pops up every time it checks for updates on startup (still learning the hostnames).

**Comment by marticliment** [comment]
on each app restart all loaded info is lost. therefore, on restart everything is loaded again and timers start counting again

**Comment by marticliment** [comment]
there is no way to change this behaviour

**Comment by marticliment** [comment]
because updates are loaded in the same way installed packages are

**Comment by marticliment** [comment]
yes, it does, but the way in which both lists work is the same

**Comment by marticliment** [comment]
i am sorry, it is not technically possible

**Comment by marticliment** [comment]
yes, it is _possible_, but so prone to errors and resource intensive that it wouldn't work well and would cause issues (also, the implementation would still rely on a reload, so id would fix nothing )

**Comment by andsens** [comment]
I propose reopening this.  
Windows restarts itself every now and then for forced system updates, and the first thing that happens when logging in is wingetui updating all the apps, which kind of defeats the purpose of having a periodic update check.  
Wouldn't the Windows built-in "Scheduled Tasks" be a perfect solution for this? Quite a few other apps already use this for self-updating and Microsoft has solved all the pains that come with doing things on timers for tasks precisely like this.
