### ISSUE TITLE
[BUG] cannot add winget msstore repo as source (500 error)

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [marticliment/WingetUI#2017]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

cannot readd msstore winget source
Internal server error (500)

### Steps to reproduce the issue

from wingetui settings > winget  > add source > attempting to re-add msstore repo as source for winget (was previously deleted)
mstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
result: could not add source msstore to Winget

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
Starting adding source operation for source name=msstorewith Manager name=Winget
Process Executable     : C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\Users\MyUser\AppData\Local\Microsoft\WindowsApps\winget.exe"  source add --name msstore --arg https://storeedgefd.dsx.mp.microsoft.com/v9.0 --accept-source-agreements --disable-interactivity
Working Directory      : C:\Users\MyUser
Process Start Time     : 21 March 2024 8:15:31
    | Adding source:
    |    | 
    | An unexpected error occurred while executing the command: 
    | 0x801901f4 : Internal server error (500).
Process Exit Code      : -2145844748
Process End Time       : 21 March 2024 8:15:48
```

**Comment by marticliment** [comment]
Thanks, I was not aware of this!
