### ISSUE TITLE
[BUG] settings scroll bug

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [marticliment/WingetUI#2018]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

in settings, unable to scroll until the end when package managers settings are collapsed

### Steps to reproduce the issue

collapse package managers settings
scroll

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

**Comment by marticliment** [comment]
I am sorry, but this seems to be an issue with the UI Toolkit. If the issue continues, let me know and I will open an issue on the WinUI repository
