### ISSUE TITLE
[ENHANCEMENT] remember last installation mode (admin privieges)

### ISSUE THREAD

**Issue by monger39** [marticliment/WingetUI#2025]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

for some packages I use it is not clear whether I would need to install with administrator privileges or not. Quite often I find myself first trying without, and when it fails, trying with admin privs. 
The enhancement would be where WinGetUI would remember the last (successful) mode used, and offering this for a next installation

### Describe how this improvement could help users.

this improvement would help users to make installation of updates more efficient, with less retrying

**Comment by marticliment** [comment]
If you right-click a package -> Installation options you can set permanent install/update/uninstall settings for that specific package
