### ISSUE TITLE
[BUG] lots of exceptions when parsing list of installed applications, making list very short

### ISSUE THREAD

**Issue by mbunkus** [marticliment/WingetUI#2027]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The list of installed packages is very short & doesn't contain applications installed earlier today. As an example, I installed Tabby & Alacritty with WingetUI today. Gave both of them a good try. Decided to stay with Alacritty. Had to reboot for unrelated reasons. After the reboot neither application appears in the list of installed applications, even though they're both still installed.

Refreshing the list doesn't help.

Additionally the debug log contains a massive amount of exceptions relating to parsing package names/descriptions.

### Steps to reproduce the issue

Look at the list of installed packages & the debug log. For the nothing has to be done in order to reproduce it.

### WingetUI Log

[Debug log file](https://www.bunkus.org/misc/wingetui-issue-2007/wingetui-debug-log-202403222202.txt)

### Package Managers Logs

[Package manager log file](https://www.bunkus.org/misc/wingetui-issue-2007/wingetui-package-manager-log-202403222223.txt)

### Screenshots and videos

![2024-03-22 21_57_32- BUG  Packages go missing after restarting WingetUI · Issue #2007 · marticliment](https://github.com/marticliment/WingetUI/assets/414282/c8441783-2bff-4f14-a3cf-009d79cfb104)

**Comment by marticliment** [comment]
I can see what your issue is. I will try to fix it as soon as I can

**Comment by mbunkus** [comment]
Much appreciated!
