### ISSUE TITLE
[FEATURE REQUEST] (Enter your description here)

### ISSUE THREAD

**Issue by SarreqTeryx** [marticliment/WingetUI#2029]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

If possible, I'd like for there to be an option to disallow apps from adding icons to the desktop.

### Describe how this new feature could help users.

By not cluttering the desktop.

**Comment by marticliment** [comment]
I am afraid this is an issue with how some packages are built, and it cannot be changed from WingetUI.

Please remember that wingetui is only the interface, packages are handled by Winget and other managers

**Comment by SarreqTeryx** [comment]
well, darn…
