### ISSUE TITLE
[CRASH] WingetUI fails initializing even after reinstallation!

### ISSUE THREAD

**Issue by ferociousviking** [marticliment/WingetUI#2031]
Hard crash experienced

Error details : 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.22631.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0.1
                Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: Could not load file or assembly 'System.Security.Principal.Windows, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Crash Traceback: 
   at ModernWindow.Structures.AppTools.IsAdministrator()
   at ModernWindow.MainWindow..ctor() in Y:\WingetUI-Store\src\wingetui\Interface\MainWindow.xaml.cs:line 68
   at ModernWindow.MainApp.InitializeMainWindow() in Y:\WingetUI-Store\src\wingetui\App.xaml.cs:line 123
   at ModernWindow.MainApp..ctor() in Y:\WingetUI-Store\src\wingetui\App.xaml.cs:line 64
```

**Comment by ferociousviking** [comment]
This is a comment.

**Comment by ferociousviking** [comment]
Please help.

**Comment by ferociousviking** [comment]
I uninstalled it with Revo Uninstaller and deleted all of the left over files and registry entries, but the program still crashes when it is executed.

**Comment by marticliment** [comment]
This issue has been fixed in code, and the fix will be released with the next version

**Comment by ferociousviking** [comment]
> This issue has been fixed in code, and the fix will be released with the next version

Salutations!

**Comment by ferociousviking** [comment]
WingetUI now functions as expected. I recently learned that upgrades can be installed using the Windows command winget upgrade --all

**Comment by marticliment** [comment]
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**

**Comment by ferociousviking** [comment]
Thank you sir. Keep up the good work! WingetUI rules! Nice pogram, very well made. well done.
