### ISSUE TITLE
[BUG] The Command Prompt window is coming many times

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#2036]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe the issue

Instead of having the command prompt appear multiple times during software updates, it would be more efficient to have it appear only once. This can be achieved by using a "do all at once" command or any other command that can execute all updates simultaneously, similar to how the command prompt dialog appears only once.

### Describe how this bug could affect users.

This information might be useful to users as it allows them to work without any command prompt window interruptions that can cause distractions. For instance, when typing, the command prompt window can grab attention and cause letters to be missed, or while gaming, it can block the screen and lead to losing the game. Additionally, during a meeting, the command prompt window can obstruct the window, and if there is any screen sharing, it can interfere with it.

### Steps to reproduce

Try to update a package.

### WingetUI Logs

https://1drv.ms/t/s!Aqq-Je19xlrfiCJEPHfDmHdbOT7x?e=5lGO6i

### Package Manager Logs

https://1drv.ms/t/s!Aqq-Je19xlrfiCGg_2rP9XkcB2ZY?e=lWutuJ

**Comment by marticliment** [comment]
Command prompts are not expected to be shown. Please report which packages/managers do trigger command prompt windows

**Comment by skanda890** [comment]
![image](https://github.com/marticliment/WingetUI/assets/99239826/439e4fab-ad12-4cf8-bdac-3c3ea40ce999)

Does this help? The list of packages shown in this window was updated.

**Comment by marticliment** [comment]
No. I need to know what do you exactly mean by "The Command Prompt appearing on each update", and when does this happen

**Comment by skanda890** [comment]
I have two monitors and when the update is going on that time one monitor has WingetUI other has Edge, on the monitor which has Edge the command prompt dialog pops up. I have two monitors. During updates, WingetUI appears on one monitor while Edge appears on the other. When the update is in progress, a command prompt dialog pops up on the monitor with Edge.

**Comment by skanda890** [comment]
https://1drv.ms/v/s!Aqq-Je19xlrfiCRD1M0yvttW_LtK?e=Hfldl9

Yes, every package does trigger a command prompt.

**Comment by marticliment** [comment]
I think I see what the issue is.

Note for future @marticliment: gSudo caching is interfiering

**Comment by skanda890** [comment]
> https://1drv.ms/v/s!Aqq-Je19xlrfiCRD1M0yvttW_LtK?e=Hfldl9
> 
> Yes, every package triggers a command prompt.

This is only one monitor, the other monitor there was WingetUI.

**Comment by skanda890** [comment]
Sometimes, if the update fails you have to click the 
![image](https://github.com/marticliment/WingetUI/assets/99239826/688e684a-34a6-446b-af6d-e7cfe70369e3) or 
![image](https://github.com/marticliment/WingetUI/assets/99239826/2162de36-d816-4de2-9cbe-743252fedd1e)
button to trigger the command prompt window.

**Comment by skanda890** [comment]
> Sometimes, if the update fails you have to click the ![image](https://private-user-images.githubusercontent.com/99239826/318252521-688e684a-34a6-446b-af6d-e7cfe70369e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzQ5NjUsIm5iZiI6MTcxMTg3NDY2NSwicGF0aCI6Ii85OTIzOTgyNi8zMTgyNTI1MjEtNjg4ZTY4NGEtMzRhNi00NDZiLWFmNmQtZTdjZmU3MDM2OWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA4NDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MTQzZWVjNWQ3YTNlMjU4OGI5YTI4YWZhMTNkYWEyNzgwZDM5OWMxYzAxNmYwZmFjNjA0MWZjOTU5NGU2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C2UtXrfsKv0GpmvcHB9LA5rDv9ajBuflqfrxRAkGZ7Y) or ![image](https://private-user-images.githubusercontent.com/99239826/318252586-2162de36-d816-4de2-9cbe-743252fedd1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzQ5NjUsIm5iZiI6MTcxMTg3NDY2NSwicGF0aCI6Ii85OTIzOTgyNi8zMTgyNTI1ODYtMjE2MmRlMzYtZDgxNi00ZGUyLTljYmUtNzQzMjUyZmVkZDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA4NDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMTdlNzIzMjY3YzkwZjYxNDAyNDhkNzA4MTM1MzhlNTQ2YjQ1NTNjN2Q2MDAyZDA4YmY2ODc0YWNhNTcwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nRLpUQGApn0MRGA24uHgTgLz96DlHv5HYsxnBrHp9lg) button to trigger the command prompt window.

Sometimes, when you click the 
![image](https://github.com/marticliment/WingetUI/assets/99239826/54baa4d0-a523-4af1-958e-d36bb8ed72f8) button then the User Account Control (UAC) prompt comes.
