### ISSUE TITLE
[FEATURE REQUEST] (repository based sources)

### ISSUE THREAD

**Issue by CrazyWolf13** [marticliment/WingetUI#2038]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Hi is it possible to add package based repos like this for example; https://artifacts.videolan.org/vlc/nightly-win64/

### Describe how this new feature could help users.

This would be really benefitial, as for example this is a nightly build so having an automated update would be really great!

**Comment by marticliment** [comment]
You can find those packages updated daily on Package Managers such as WinGet or Chocolatey.

Also, Adding a ftp/http location wouldn't work with WingetUI
