### ISSUE TITLE
[ENHANCEMENT] Move "Select all" box to list 

### ISSUE THREAD

**Issue by scrobbleme** [marticliment/WingetUI#2039]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

It is so confusing and not intuitive that the (de-)select all feature is not part of the list.
→ It should be part of the list instead, as this is this is how most lists work.

![image](https://github.com/marticliment/WingetUI/assets/504835/d6277790-1cfd-401a-865c-e82d628f872f)

### Describe how this improvement could help users.

Makes the application more intuitive

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/4e5b5d94-6b32-402e-a50e-9ef2d2a5895f)
