### ISSUE TITLE
[BUG] No link to "WindowsTerminal" package release notes

### ISSUE THREAD

**Issue by 7wells** [marticliment/WingetUI#2043]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Hello!

When checking information about the `Windows-Terminal` package in WingetUI (3.0.1), there is neither data nor link about the `Windows-Terminal` release notes, which are available at: https://github.com/microsoft/terminal/releases

Please accept my apologies if this is neither to be regarded as an issue nor a bug and kindly direct me where I could post this (if at all worth it). Maybe this is just a topic of missing meta data?

And thank you very much for your time that you and other collaborators spend on this great tool! ❤️

### WingetUI Log

```text
NA
```

### Package Managers Logs

```text
NA
```

**Comment by marticliment** [comment]
Hello @7wells,

I am afraid this is an issue with WinGet, since running the command `winget show Microsoft.WindowsTerminal` does not show the URL either
