### ISSUE TITLE
[FEATURE REQUEST] Make a option that says the Windows version

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#2048]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Could you make a column in 
![image](https://github.com/marticliment/WingetUI/assets/99239826/d77ea274-a569-4910-a5ed-6bb95252fafb)
like ![image](https://github.com/marticliment/WingetUI/assets/99239826/9fa8a918-df58-431a-b9fa-1d7fa1708b19)
but that says the Windows version?

### Describe how this new feature could help users.

This would be useful for users.

**Comment by marticliment** [comment]
How would thjs help?

**Comment by skanda890** [comment]
Still, for the user's info.

**Comment by skanda890** [comment]
Fine.
