### ISSUE TITLE
[BUG] lots of updates detected if no internet connection

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [marticliment/WingetUI#2050]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

lots of updates detected if no internet connection

### Steps to reproduce the issue

disconnect internet
check for updates

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Relevant information

there should be an internet connection precheck prior to checking for updates. or at least not show updates with same new version while offline

**Comment by marticliment** [comment]
Please share your logs, as well as a screenshot of the incorrect packages
