### ISSUE TITLE
[BUG] gsudo loop with hash checking disabled

### ISSUE THREAD

**Issue by Bluscream** [marticliment/WingetUI#2054]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Infinite gsudo (elevation) loop that can only be broken by logging off or shutting down when trying to update packages like 
- https://marticliment.com/wingetui/share?pid=GitHub.GitHubDesktop&pname=GitHub+Desktop+Deployment+Tool&psource=Winget%3a+winget
- https://marticliment.com/wingetui/share?pid=Ubisoft.Connect&pname=Ubisoft+Connect&psource=Winget%3a+winget

### Steps to reproduce the issue

Select apps for update
Click ignore hashes button
Enjoy being stuck forever

### WingetUI Log
[WingetUI.log](https://github.com/marticliment/WingetUI/files/14783941/WingetUI.log)

### Package Managers Logs
[WingetUI Package Managers.log](https://github.com/marticliment/WingetUI/files/14783943/WingetUI.Package.Managers.log)

### Screenshots and videos

![WingetUI_Eu0eLrJTUc](https://github.com/marticliment/WingetUI/assets/3318223/f1762f5f-0677-4eaa-beb1-46b9557c9665)

**Comment by Bluscream** [comment]
Update: Same behavior after executing `winget settings --enable InstallerHashOverride` in a admin powershell

**Comment by fabifont** [comment]
Hi, is there any workaround for that? I need to skip the hash verification but I keep getting the gsudo loop

**Comment by rodalpho** [comment]
I just had a very similar problem when trying to update Discord with root access. I did manage to get out of the loop without rebooting with ctrl-alt-del and the task manager. Pretty big bug.
