### ISSUE TITLE
[BUG] Parallel operations issue with uninstall and reinstall feature.

### ISSUE THREAD

**Issue by kifujin** [marticliment/WingetUI#2063]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When selecting the "uninstall package, then update it" feature while the option to perform operations in parallel is set, it tries to execute both at the same time instead of sequentially.

### Steps to reproduce the issue

1. Have software that doesn't update properly due to, e.g., different install technology between versions.
2. For the package manager for the software, enable the option to perform operations in parallel enabled.
3. Try to use the option "Uninstall package, then update it"
4. Watch the software uninstall at the same time that the update install fails.

Possible race condition due to having two items in queue operating on the same package trying to happen in parallel?

### WingetUI Log

```text
n/a
```

### Package Managers Logs

```text
n/a
```

**Comment by marticliment** [comment]
Yes, this is likely to be this
