### ISSUE TITLE
[BUG] WinGetUI fails to launch with no error message

### ISSUE THREAD

**Issue by stevehoek** [marticliment/WingetUI#2068]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

WinGetUI was working well after updating to v3.00, then I upgraded to v3.01 and it no longer launches.  There is no message.
I have removed the app and the app's appdata folder and reinstalled and it is the same behavior
I have removed the appruntime and singleton as directed in a similar bug and it is the same behavior
In Windows Event Viewer | Windows | Applications there is this entry at the time I launched WinGetUI

Log Name:      Application
Source:        Windows App Runtime
Date:          3/30/2024 1:05:07 PM
Event ID:      5
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      GRR-SHOEK
Description:
Access is denied.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows App Runtime" />
    <EventID Qualifiers="32775">5</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-03-30T17:05:07.6060568Z" />
    <EventRecordID>228383</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>GRR-SHOEK</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Windows App Runtime</Data>
    <Data>ERROR 0x80070005: Bootstrapper initialization failed while looking for version 1.5 (MSIX package version &gt;= 5001.70.1338.0)</Data>
  </EventData>
</Event>

### Steps to reproduce the issue

Launch the app, look at Task Manager and see it never starts

### WingetUI Log

```text
No logs, app will not run.
```

### Package Managers Logs

```text
No logs, app will not run.
```

**Comment by marticliment** [comment]
Please uninstall any "App Sdk" or "App runtime" or "XAML" entry you can find on Windows Settings.

Then reinstall WingetUI

**Comment by stevehoek** [comment]
I uninstalled 4 entries in Windows Settings | Apps... Windows App Runtime Singleton, Main, and x86/x64
There were no XAML entries
There are older App runtimes installed (3.4x and 2000.609)

NO CHANGE - fails with the same Access Denied error in Event Log

Forgot to mention I'm on Windows 10 x64 22H2

**Comment by marticliment** [comment]
Please go to Windows Settings -> Uninstall programs and find “.NET 8.0.x”. Uninstall this program.
Then, please install this package: https://download.visualstudio.microsoft.com/download/pr/a4bc7333-6e30-4e2d-b300-0b4f23537e5b/4b81af6d46a02fba5d9ce030af438c67/dotnet-runtime-8.0.2-win-x64.exe
 
Then try to launch WingetUI again. IF the issue does not work, please roll back to v3.0.0 and wait until I can fix this issue.

**Comment by stevehoek** [comment]
v3.0.0 fails with the same issue

I should also mention I have Visual Studio 2022 on this machine (as well as another one where it is working fine), and only found the .NET SDK 8.0.2 so I installed the runtime you linked and WingetUI still fails the same way

**Comment by stevehoek** [comment]
I downloaded the source code and built it release and debug, and it also fails.  

The program '[21056] WingetUI.exe' has exited with code 2147942405 (0x80070005).

I set a breakpoint at the first line of Main and AsyncMain and it didnt hit either

**Comment by stevehoek** [comment]
For now I have gone back to v2.2.0 and it is working.
I'd be happy to try debug versions or local code changes to help you in any way to diag this.

**Comment by stevehoek** [comment]
A bit more info... I have WinGetUI 3.0.1 on two other machines... one is Windows Server 2019 and it is working fine there still.  The other is similar to the first machine I reported the bug on (Visual Studio, Windows 10 22H2) and it is now not working either.  So I'm guessing an update to the WindowsAppRuntime either via the store or Visual Studio 2022 has caused the issue?  Neither Store or VS is on the Server.

**Comment by marticliment** [comment]
This is an issue with the app runtime, and therefore the entry point is not even reached, and the debugger does not reach WingetUI code.
Please try uninstalling all app runtime related packages and then reinstalling WingetUI to install the correct app runtime.

**Comment by stevehoek** [comment]
Unfortunately I have done that on both the machines that are exhibiting the problem.  Since they both have Visual Studio 2022 on them configured for C#, .NET, and Windows Desktop App development, I am hesitant to remove too much.  I have removed the latest versions of Windows App Runtime 5001 (Main, Singleton, DDLM x86/x64) that were installed/updated around March 14.  On the one machine where WIngetUI 3.x still works, those were the only versions installed, where as the other two machines have older version of the Windows App Runtime that I am hesitant to remove because other software may be dependent on them.  All machines have multiple versions of the Windows Desktop Runtime, including 8.0.3 which I believe is the new name for ".NET".  On the other two machines with Visual Studio installed there are lots of SDK's, such as the .NET 8.x SDK that comes from Visual Studio.

**Comment by Enivex** [comment]
> This is an issue with the app runtime, and therefore the entry point is not even reached, and the debugger does not reach WingetUI code. Please try uninstalling all app runtime related packages and then reinstalling WingetUI to install the correct app runtime.

This did not fix the issue for me. I uninstalled everything, and reinstalled WingetUI, and it still doesn't launch.

This was even a clean Windows install. (Curiously it did work before I reinstalled Windows.)

**Comment by stevehoek** [comment]
Yeah I feel like a big clue is that this version was working on both of my PC's until around 3/14-16 approximately.  Its hard to say for sure because I leave WingetUI running all the time.  For sure it worked after the latest Microsoft Patch Tuesday on the 12th.  I believe there was at least one Visual Studio 2022 update since then.

**Comment by Enivex** [comment]
For whatever reason it suddenly started working on my computer, even if I've seemingly made zero changes since last time I tried.

**Comment by marticliment** [comment]
Hello,

I have set a detailed guide on how to reset all WingetUI dependencies. Please follow it if WingetUI is still not working:
https://github.com/marticliment/WingetUI/issues/2000

**Comment by marticliment** [comment]
Hello,

What is the output and return code of installing this? https://aka.ms/windowsappsdk/1.5/latest/windowsappruntimeinstall-x64.exe

**Comment by Win761** [comment]
Guess what, installing that thing fixed it! WingetUI opens up now! Thanks!

**Comment by Win761** [comment]
Just a question. I used the .NET Runtime 8.02 you linked in your guide for resetting dependencies, and WingetUI shows an update for it (obviously). Should I install the update, or not?

**Comment by marticliment** [comment]
No, please do not

**Comment by Win761** [comment]
Okay. I thought not, but I just wanted to be sure. Thanks for clarifying.

**Comment by stevehoek** [comment]
> Hello,
> 
> What is the output and return code of installing this? https://aka.ms/windowsappsdk/1.5/latest/windowsappruntimeinstall-x64.exe

Unfortunately this did not help me.

**Comment by stevehoek** [comment]
> Hello,
> 
> What is the output and return code of installing this? https://aka.ms/windowsappsdk/1.5/latest/windowsappruntimeinstall-x64.exe

`Installing license: MSIX_MAINPACKAGE_LICENSE
Install License result : 0x0
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install License result : 0x0
All install operations successful.`

**Comment by stevehoek** [comment]
> Trh also running the installer as admin, please

That was from an admin command prompt

**Comment by stevehoek** [comment]
Well, after Tuesday's Windows Updates and a VS 2022 update, WingetUI 3.01 is now working again!

**Comment by marticliment** [comment]
MS haa released .NET 8.0.4, most likely fixing the issue causing the crash

**Comment by stevehoek** [comment]
Likely this issue?

https://github.com/dotnet/runtime/pull/99796

**Comment by marticliment** [comment]
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**

**Comment by Win761** [comment]
Forgot to mention: After I installed the Windows app runtime thing, WingetUI launched, but only if it was run as an admin. Just updated to 3.02, and now WingetUI launches just fine, even without admin privileges. 👍
