### ISSUE TITLE
[Feature Request] Take Inspiration from wingetUI like websites

### ISSUE THREAD

**Issue by Satanarious** [marticliment/WingetUI#209]
Check out these websites:
[winstall.app](https://winstall.app/)
[winget.run](https://winget.run/)

These websites give you the option to select 1 or more packages and then provide you with a winget-cli one-liner for the installation of those packages. Which you can copy and paste in the terminal.

They have features like:
- Featured Packages
- Popular Packages
- Favourite Packages
- Filter by Publisher (like Adobe, Microsoft, etc.)
- Tags, as well as filter by tags (like utility, reader, etc.)
- Featured Collections
- Create your own collection
- Share your collection
- Grid View
- Icons for many packages

The winget.run guy's [github](https://github.com/MehediH/winstall) is also worth a look, he explains how he gets the data there.

### How is the data obtained?

> winstall is powered by an API that I have built. The API regularly checks Microsoft's [official repository](https://github.com/microsoft/winget-pkgs) for Windows Package Manager apps. This means it always provides the latest data.
> 
> The API updates its data every 15 minutes on weekdays, and every 3 hours on weekends. I will be making the API open-source in the near-future.

I managed to get the json he is maintaining, here's the [link to the json](https://winstall.app/_next/data/68cB5G3MD-lrfN2IuU4gT/apps.json)

Here's a peek into the json:
![image](https://user-images.githubusercontent.com/42642682/194440653-c5963ff8-fa25-4004-9b42-b62766e13ebc.png)

**Comment by marticliment** [comment]
Hello,

Due to the proposed AIP's limitations, and lack of compatibility with other managers, I am afraid this will not be part of WingetUI in the near future.

I am sorry
