### ISSUE TITLE
[BUG] is it possible that the ms store version of wingetui doesn't work?

### ISSUE THREAD

**Issue by hueldoeu** [marticliment/WingetUI#2090]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

thought about switching from cmd => winget upgrade to a GUI solution. choosed wingetui (first result in google) . decided to test the ms store version too (sind 20 % of my apps are being updated through ms store, rest with winget or manually and i am satisfied). i have installed wingetui from ms store but nothing happens

### WingetUI Log

```text
no
```

### Package Managers Logs

```text
using windows 10 here. amount of windows 10 installations recently increased haha
```

**Comment by hueldoeu** [comment]
cmd => winget install SomePythonThings.WingetUIStore afterwards worked fine

**Comment by hueldoeu** [comment]
i recommend that unigetui opens maximized the first it gets opened. it has lots of settings and features, i didn't know that.

**Comment by marticliment** [comment]
WingetUI is not on Microsoft Store. WingetUI Widgets is an addon for WingetUI that can be installed from Microsoft store.

**Comment by hueldoeu** [comment]
same for windows 11.

**Comment by marticliment** [comment]
yes.

**Comment by marticliment** [comment]
Windows settings - > apps and features

**Comment by hueldoeu** [comment]
cmd => winget install SomePythonThings.WingetUIStore also installs an unneccessary desktop shortcut.
