### ISSUE TITLE
[BUG] The Retry button was black like the Close button when I was updating the packages on my computer

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#2096]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The Retry button was black like the Close button when I was updating the packages on my computer.

### Steps to reproduce the issue

Make a update fail and look ate that update's Retry button.

### WingetUI Logs

https://1drv.ms/t/s!Aqq-Je19xlrfiB4ObjhOZMgbbEfX?e=EHaMZO

### Package Managers Logs

https://1drv.ms/t/s!Aqq-Je19xlrfiCGg_2rP9XkcB2ZY?e=qfyzdR

**Comment by marticliment** [comment]
Can you please provide more details?

**Comment by marticliment** [comment]
To be able to fix this I need you to provide more details or a reproducible example

**Comment by skanda890** [comment]
I don't have any of that.
