### ISSUE TITLE
[WEBSITE ENHANCEMENT] (WingetUI website has an unloaded, broken picture)

### ISSUE THREAD

**Issue by vtonu** [marticliment/WingetUI#2099]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Not sure if it's supposed to be a logo or an icon, but I couldn't help but notice it :D 

![screenshot](https://github.com/marticliment/WingetUI/assets/56773210/21193065-6b93-49cd-ba18-cf3a12c75c5d)

The title "WingetUI A better UI for your package managers" is also off center.

### Describe how this improvement could help users.

In my opinion, it would help users like me with ADHD, OCD etc.

**Comment by marticliment** [comment]
I am aware of this issue. I am working to adress some other issues on the web, and when I have all of them fixed I will deploy the updated pages

**Comment by marticliment** [comment]
Fixed!
