### ISSUE TITLE
[BUG] unigetui opens in background

### ISSUE THREAD

**Issue by hueldoeu** [marticliment/WingetUI#2106]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

when i click on this
![image](https://github.com/marticliment/WingetUI/assets/11273667/2a3be264-eb1e-4bb2-b286-5d54bf3e2938)
unigetui opens in background. everytime i have to go to the taskbar and click on unigetui to get unigetui to the foreground.

### WingetUI Log

```text
no
```

### Package Managers Logs

```text
again no
```

**Comment by hueldoeu** [comment]
![image](https://github.com/marticliment/WingetUI/assets/11273667/77757001-a109-4433-a805-9717e0df9e2d)
would be cool to extend the context menu of tray icon. stuff like "install all updates", "settings", ...

"refresh list" is not necessary because unigetui scans all winget packages very very often especially after startup.

**Comment by hueldoeu** [comment]
![Capture+_2024-04-12-17-39-01](https://github.com/marticliment/WingetUI/assets/11273667/e50d403f-95d8-4748-87c0-85be53839cfc)
wow, thats what i call very, very, VERY ... OFTEN ... but this way everyone can see available updates. and we don't need the info-center / action-center. i try to figure out sending messages from windows pc to windows pc being displayed as notifications in the windows 10 info-center / action-center.

**Comment by marticliment** [comment]
This is an already reported bug. On the next versions, old notifications will get discarded

**Comment by hueldoeu** [comment]
> info-center / action-center

i really like it this way, our office doesn't use or doesn't need the info-center / action-center except for windows-key + shift + S (screenshot-tool)

**Comment by hueldoeu** [comment]
> ![Capture+_2024-04-12-17-39-01](https://private-user-images.githubusercontent.com/11273667/322115793-e50d403f-95d8-4748-87c0-85be53839cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTA2MTYsIm5iZiI6MTcxMzcxMDMxNiwicGF0aCI6Ii8xMTI3MzY2Ny8zMjIxMTU3OTMtZTUwZDQwM2YtOTVkOC00NzQ4LTg3YzAtODViZTUzODM5Y2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE0MzgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5N2VkMWJiNWU3OGZjZGEzYjc3ZTZmYzk3NTkwNzg0NThjNTZiODFmMmUwODViNGVhNmM4YTExNDBjMTY3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eIIdydyIQx3Zo5IkU5183Mj8XG54qCq1QXKsmm6TZRA) wow, thats what i call very, very, VERY ... OFTEN ... but this way everyone can see available updates. and we don't need the info-center / action-center. i try to figure out sending messages from windows pc to windows pc being displayed as notifications in the windows 10 info-center / action-center, but in generally we don't need the windows 10 info-center / action-center.

i really like it this way, our office doesn't use or doesn't need the info-center / action-center except for windows-key + shift + S (screenshot-tool)

**Comment by hueldoeu** [comment]
i really, really, really enjoy multiple cloned messages so that the staff wakes up and finally updates their software.

**Comment by hueldoeu** [comment]
damn bro, UnigetUI really is some nice piece of software.

**Comment by hueldoeu** [comment]
> ![image](https://private-user-images.githubusercontent.com/11273667/321247641-a84fae9a-1b08-47d3-a8a9-2e1242e4f860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTUzNDUsIm5iZiI6MTcxNjA1NTA0NSwicGF0aCI6Ii8xMTI3MzY2Ny8zMjEyNDc2NDEtYTg0ZmFlOWEtMWIwOC00N2QzLWE4YTktMmUxMjQyZTRmODYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE3NTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NWQzMGE0YmVkYjY1ZmRmZmJiODAwNmM1MDM0ODlkZjkyZWUxYjdlNzVkNjUzMTg1M2RlOTRkNmYxMjMwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dD3L7f-500LndSJVrfVX2SxaLGl8Zel5GTqPgicVCkw) a bit more options like "install updates", "skip version", ... would be nice, since it wasn't hard to program for meta in whatsapp for windows desktop ![image](https://private-user-images.githubusercontent.com/11273667/321248164-8cefc88a-38f0-4f0b-9e4e-03a04557d8bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTUzNDUsIm5iZiI6MTcxNjA1NTA0NSwicGF0aCI6Ii8xMTI3MzY2Ny8zMjEyNDgxNjQtOGNlZmM4OGEtMzhmMC00ZjBiLTllNGUtMDNhMDQ1NTdkOGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE3NTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YTMwYWEzNDQxNjE5MTliYWNiNjI1NmVkOTk4NzQxMjEzMjJkNTYxZGVkY2ViN2U5ZTcyMzNjOGE1MmJjOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fuc1wZh87-LMqYYev3Zy4qIIMZQOKfQe0ATWx0zXkis)

i'm not sure if you corrected this in the last updates but what you did is not what i meant, take a closer look. i clicked with the right mouse on whatsapp and it asks me to mute a contact. this is what i like.

**Comment by hueldoeu** [comment]
i don't know what happened but i realized on one modern PC that unigetui couldn't find updates for libreoffice 24.2.3.2. libreoffice remained on 24.2.2.2. i have upgrade libreoffice manually with cmd => winget upgrade libreoffice successfully

**Comment by hueldoeu** [comment]
> i don't know what happened but i realized on one modern PC that unigetui couldn't find updates for libreoffice 24.2.3.2. libreoffice remained on 24.2.2.2. i have upgrade libreoffice manually with cmd => winget upgrade libreoffice successfully.
> 
> maybe accidently skipped this version. but i recognized this problem on another (a bit older) PC.
> 
> no. several computer missed stuff liek 7zip, libreoffice, ... using cmd => winget upgrade showed all the missing updates.

![image](https://github.com/marticliment/WingetUI/assets/11273667/f124a90d-5379-4e70-bfd4-61403e93b462)

update for Microsoft.EdgeWebView2Runtime available. not visible in unigetui. (other updates like for Microsoft.VCRedist.2013.x86 are a mistake, already up to date and these lines can't get deleted from winget upgrade)

**Comment by hueldoeu** [comment]
the problem persist but i tried the "install packages automatically" option and it worked like a charme (for packages who can be installed). meanwhile increased the time from 10 min to 2 hours.
![image](https://github.com/user-attachments/assets/f0b5ebc0-37fd-4c7a-a439-c53827b792e4)
