### ISSUE TITLE
[CRASH] (Enter your description here)

### ISSUE THREAD

**Issue by neoOpus** [marticliment/WingetUI#2108]
Hard crash experienced

Error details : 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.26090.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0-alpha2
                Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: Cannot start process because a file name has not been provided.

Crash Traceback: 
   at System.Diagnostics.Process.Start()
   at ModernWindow.PackageEngine.Managers.Scoop.RunCleanup() in C:\SomePrograms\WingetUI-Store\src\wingetui-interface\PackageEngine\Managers\Scoop.cs:line 604
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by marticliment** [comment]
Please do upgrade to WingetUI 3.0.1, you are using an old alpha release

**Comment by marticliment** [comment]
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**
