### ISSUE TITLE
[CRASH] - App reported a crash after a system update

### ISSUE THREAD

**Issue by OnlyOnePro** [marticliment/WingetUI#2113]
Hard crash experienced

Error details : 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.26100.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0.1
                Executable: C:\Users\leona\AppData\Local\Programs\WingetUI\WingetUI.exe

Crash Message: The text associated with this error code could not be found.

Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml'. [Line: 0 Position: 0]

Crash Traceback: 

```

**Comment by marticliment** [comment]
Hello, 

Please test this custom build and let me know if it works: https://drive.google.com/file/d/1NO8jhMDBPmMGvlnaW5MXv5vjYjvmFJLa/view?usp=sharing

Thanks!

**Comment by marticliment** [comment]
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**
