### ISSUE TITLE
[CRASH] WingetUI crashed

### ISSUE THREAD

**Issue by 13regent** [marticliment/WingetUI#2122]
WingetUI crashed

Error details: 
```

                        OS: Win32NT
                   Version: Microsoft Windows NT 10.0.19045.0
           OS Architecture: True
          APP Architecture: True
                  Language: Unknown
               APP Version: 3.0.1
                Executable: C:\Program Files\WingetUI\WingetUI.exe

Crash Message: The text associated with this error code could not be found.

Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml'. [Line: 0 Position: 0]

Crash Traceback: 

```
Also tried WingetUI 3.0.2 and it wont start.

**Comment by ozkansoyturk** [comment]
same for me

**Comment by iftaras** [comment]
Had the same issue with version 3.0.1 on Windows 11 x64. After updating WinAppRuntime.Singleton & WinAppRuntime.Main.1.5 to their latest versions the issue seems to be solved.

**Comment by 13regent** [comment]
Tried 3.0.2 and WingetUI wont open. Followed instructions for downgrading to 2.2.0. It does now open, but finds zero updates....which is odd. It usually finds something?

**Comment by 13regent** [comment]
I had first tried version 3.0.2 at it would not open. 

I then went through every step at of the "GUIDE TO FIX WINGETUI NOT LAUNCHING #2000" at:
https://github.com/marticliment/WingetUI/issues/2000

As per the guide and with version 3.0.1 installed would blip open for a fraction of second and close. Downgraded to version 2.2.0....which loads...but had the message "Hooray! No updates were found!"

Just checked now and still have no updates. Will check again later to see if something populates.

**Comment by 13regent** [comment]
Tried to see if I had some WingetUI updates using version 2.2.0...and still had none. Decided to poke around and selected "Use system Winget" and that gave me updates.

![wingetui](https://github.com/marticliment/WingetUI/assets/28539673/ace200ca-71ea-4f0f-b05d-12a50c2c0a6d)

![results](https://github.com/marticliment/WingetUI/assets/28539673/7a93392b-7fd0-4b40-83a5-2a4944b3a9de)

**Comment by 13regent** [comment]
Tried installing WingetUI 3.0.2 as well as .net 8.0.4. WingetUI does not open, but I had the task manager open at the same time to see what's going on. I see that two instances of WingetUI blip in and well as Werfault.exe. Werfault is related to windows error reporting. WingetUI is crashing shortly after it starts. 

![wer](https://github.com/marticliment/WingetUI/assets/28539673/6e558e57-decf-47d0-9ca7-3e52d154c6f2)

**Comment by 13regent** [comment]
Any ideas on how to get version 3.0.2....or should I just wait?

**Comment by marticliment** [comment]
Please dowbgrade to 2.2.0 and wait

**Comment by Kim-Ko** [comment]
> Tried to see if I had some WingetUI updates using version 2.2.0...and still had none. Decided to poke around and selected "Use system Winget" and that gave me updates.
> 
> ![wingetui](https://private-user-images.githubusercontent.com/28539673/322239401-ace200ca-71ea-4f0f-b05d-12a50c2c0a6d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDM5MTEsIm5iZiI6MTcxMzgwMzYxMSwicGF0aCI6Ii8yODUzOTY3My8zMjIyMzk0MDEtYWNlMjAwY2EtNzFlYS00ZjBmLWIwNWQtMTJhNTBjMmMwYTZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMDIyMjBkMDJmZTIwMDVhNGEwZmViOTdhZjNmZWY3NmY2YjM3YmRjOGNjN2NkNWU0OWEyNzgzOGFiOWMwOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bledremJfV08XFAEl_41dyGFplbamqx8ONjWJ8KYQzs)
> 
> ![results](https://private-user-images.githubusercontent.com/28539673/322239404-7a93392b-7fd0-4b40-83a5-2a4944b3a9de.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDM5MTEsIm5iZiI6MTcxMzgwMzYxMSwicGF0aCI6Ii8yODUzOTY3My8zMjIyMzk0MDQtN2E5MzM5MmItN2ZkMC00YjQwLTgzYTUtMmE0OTQ0YjNhOWRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzY1Zjg3ZjE0MDVkNzA0ZTlmOTZjZDE4ZTRmOTNlMzUwYzRhNDJkMTI1NWZjMjk1ODBkMDU4NmFmMDk4N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c3bEaWMki3EVYbJ1peg1f1CbQhRYZmUSZsj_Oph-UnE)

**Comment by Kim-Ko** [comment]
This did improve WingetUI 3.0.2 a bit as well. 12 package updates  were found and updates proceeded. Still no Installed packages displayed, yet.

**Comment by 13regent** [comment]
Roughly when will there will be an update for those of us who have downgraded?

**Comment by marticliment** [comment]
I don't really know, since I can't really fix .NET faulting. Whenever .NET 8.0.5 gets released, I will try to publish a release which will hopefully fix the crashes

**Comment by 13regent** [comment]
Thanks for the update.

**Comment by 13regent** [comment]
.NET 8.0.5 was recently released. When will there roughly be a WingetUI update?

**Comment by marticliment** [comment]
I will try to release it this week or the next one

**Comment by marticliment** [comment]
Please try this release:
https://github.com/marticliment/WingetUI/releases/tag/3.1.0-alpha0

**Comment by 13regent** [comment]
Installed UnigetUI from the link and all appears to be working fine. Thanks.
