### ISSUE TITLE
[FEATURE REQUEST] Stop auto installing chocolatey

### ISSUE THREAD

**Issue by EDM115** [marticliment/WingetUI#2131]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Provide an option in the settings to stop auto installing chocolatey (in `%LOCALAPPDATA%\Programs\WingetUI\choco-cli`)  
Also provide a flag for the installer that stop installing it

### Describe how this new feature could help users.

I personally don't use chocolatey at all and see no use of it  
Having an environment variable constantly recreated is also not so good, as for each update of WingetUI I have to remove that folder and the env variable

**Comment by rumplin** [comment]
That is the first thing I do after Installing WingetUI, disabling chocolatey.

**Comment by marticliment** [comment]
Upgrading will not delete anything, it would be very dangerous. You will need to remove it manually, and the installer shouldn't add the files manually anymore if chocolatey is not selected as a component.

**Comment by CookieHCl** [comment]
How about uninstalling when you disable chocolatey, and installing when you enable it?

**Comment by marticliment** [comment]
New installers will allow to not install chocolatey. If Chocolatey is already installed it will NOT be removed
