### ISSUE TITLE
[BUG] "Use installed GSudo instead of the bundled one" missing in WinGetUI 3.0.2

### ISSUE THREAD

**Issue by nicerloop** [marticliment/WingetUI#2140]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I need to use a custom gsudo (https://github.com/nicerloop/ivanti-self-elevate).
In version 2.2.0 I enable "Use installed GSudo instead of the bundled one".
This option is missing in WinGetUI 3.0.2, so I stick to version 2.2.0 for now.

### Describe how this improvement could help users.

Users can elevate rights for winget actions with a custom tool tailored to their needs, in the same way it was possible in WinGetUI 2.2.0.

**Comment by marticliment** [comment]
Note for future @marticliment: Backend has been implemented on marticliment/WingetUI#2161, still requires settings entry
