### ISSUE TITLE
[BUG] Problem updating Zoom (Zoom.Zoom vs Zoom.Zoom.EXE)

### ISSUE THREAD

**Issue by Kaligula0** [marticliment/WingetUI#2163]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

WingetUI listed _Zoom_ as outdated (it was), but couldn't update (said it was updated succesfully, yet it came back to the list as outdated). Winget (CLI) also couldn't update when I copied the command showed in WingetUI (`winget.exe update --id Zoom.Zoom` without other parameters) – the response was `No installed package found matching input criteria.`.

Cmd `winget list` showed Zoom installed as `Zoom.Zoom.EXE`:
```
Zoom Workplace                           Zoom.Zoom.EXE                            6.0.0 (37205)        6.0.3 (3… winget
```
However WingeUI shows command with `Zoom.Zoom`. When I tried cmd `winget.exe update --id Zoom.Zoom.EXE` it succesfully updated:
```
Found Zoom Workplace (EXE) [Zoom.Zoom.EXE] Version 6.0.3 (37634)
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://zoom.us/client/6.0.3.37634/ZoomInstallerFull.exe?archType=x64
  ██████████████████████████████  97.9 MB / 97.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
Now `winget list` shows:
```
Zoom Workplace                           Zoom.Zoom.EXE                            6.0.3 (37634)                  winget
```

What I found so far is that there are two manifests: [_Zoom.Zoom_](https://github.com/microsoft/winget-pkgs/blob/master/manifests/z/Zoom/Zoom/6.0.37634/) and [_Zoom.Zoom.EXE_](https://github.com/microsoft/winget-pkgs/blob/master/manifests/z/Zoom/Zoom/EXE/6.0.3%20(37634)/).

### WingetUI Log

```text
For the sake of privacy it's pasted there → http://kaligula.uk/ctrlv/GitHub-WingetUI-Issue2163-WingetUIlog-1.txt
```

### Package Managers Logs

```text
For the sake of privacy it's pasted there → http://kaligula.uk/ctrlv/GitHub-WingetUI-Issue2163-PackageManagerslog-1.txt
```

**Comment by marticliment** [comment]
Hello,

Some packages sometimes fail to be detected properly by Winget, causing missing packages or mistakenly reported updates. Please use the "Ignore Updates" or "Skip this version" options within WingetUI.

Since this is an issue with Winget (not WingetUI), the error cannot be fixed from here, so my best advice is to ignore those updates
