### ISSUE TITLE
[BUG] ssh-copy-id.exe included in distribution

### ISSUE THREAD

**Issue by HimbeersaftLP** [marticliment/WingetUI#2168]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The folder AppData\Local\Programs\WingetUI\choco-cli\bin is added to PATH which includes a file named ssh-copy-id.exe that appears to have no function. Looks like this might have been used in your development environment? Because I can't find a use for it with this program.

### WingetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
Fixed!

**Comment by HimbeersaftLP** [comment]
Thanks!
