### ISSUE TITLE
[BUG] CUDA Toolkit doesn't install via WingetUI

### ISSUE THREAD

**Issue by thiagojramos** [marticliment/WingetUI#2177]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When attempting to install the CUDA Toolkit via WingetUI, the process downloads the installer and moves it to the "program files" directory but then stops without completing the installation. The program incorrectly considers the toolkit as installed.

### Steps to reproduce the issue

1. Open WingetUI.
2. Attempt to install CUDA Toolkit.
3. Process downloads but fails to install.

### WingetUI Log

```text
https://pastebin.com/e21RfVJ7
```

### Package Managers Logs

```text
https://pastebin.com/GBT3ux3d
```

### Screenshots and videos

![2024-04-27](https://github.com/marticliment/WingetUI/assets/45890502/3d840e51-8a05-44ce-8836-1d07bd1f7adf)

**Comment by marticliment** [comment]
Does installing cuda from WinGet (not WinGetUI) trigger the same behaviour?

**Comment by thiagojramos** [comment]
> Does installing cuda from WinGet (not WinGetUI) trigger the same behaviour?

I attempted to install CUDA using the WinGet (CLI), and I encountered the same issue. WinGet (CLI) downloads the CUDA installer executable but does not proceed with the installation, effectively treating the download as a completed installation. Here's the translated log from winterminal: https://pastebin.com/sZ4uKYBb

![2024-04-27 (9)](https://github.com/marticliment/WingetUI/assets/45890502/eda1eff6-366a-424d-b828-2356758557e9)

<sub>Note: Sorry I didn't put a title for the topic, but at the time I was in a hurry to go to the bathroom and forgot</sub>

**Comment by marticliment** [comment]
Therefore, I am afraid this issue is an issue with the Cuda package and not with WingetUI, so therefore this issue cannot be fixed from here
