### ISSUE TITLE
Install previous versions of Scoop apps

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#218]
It seems this feature is possible on CLI: https://github.com/ScoopInstaller/Scoop/issues/2254

However, this is not possible on WingetUI for package from Scoop source as only the latest version is shown when you click "show more info" .

For example, Firefox on scoop has many versions: https://github.com/ScoopInstaller/Extras/commits/master/bucket/firefox.json

But WingetUI only shows one: 
![Captura de tela 2022-10-08 102429](https://user-images.githubusercontent.com/73800734/194709801-aebe9fcc-34a3-4e09-9520-d9dc2fc8ce30.png)

**Comment by martinet101** [comment]
Yeah, saw that a few days ago, and i'm gonna work on it,

**Comment by ppvnf** [comment]
Do you really think this feature is possible? I thought about it and couldn't imagine a way to make it work. I don't think it's feasible to parse the Github manifest history to find older versions like in https://github.com/ScoopInstaller/Extras/commits/master/bucket/firefox.json

**Comment by martinet101** [comment]
i don't know yet, I want to properly investigate this feature request and see if it can be done or not.

**Comment by ppvnf** [comment]
I've asked in https://github.com/ScoopInstaller/Scoop/issues/5320 and it seems this feature will only be possible when https://github.com/ScoopInstaller/Scoop/issues/3045 is implemented

**Comment by marticliment** [comment]
The last time I installed a specific version of an ap`p i remember having no way to after it update the app, so we'd better wait until this is properly supported

**Comment by ppvnf** [comment]
by comparing the version in the json file with the one installed it should be possible to detect new versions, right?
And I imagine there is a way to read the github history of the json file to find old versions.
I am not sure if such a complicated thing is worth it tho

**Comment by marticliment** [comment]
Not all scoop packages are based on GitHub, so this solution wouldn't work with an important part of the available package

**Comment by marticliment** [comment]
the issue then is how to get the a list jf the available versions, I have found no way to retrieve this list.

I'm going to close this issue for now since it is scoop's architecture who is not allowing this feature to work, rather than a missing feature in WingetUI
