### ISSUE TITLE
[ENHANCEMENT] (Screen reader accessibility.)

### ISSUE THREAD

**Issue by willbilec** [marticliment/WingetUI#2188]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I wanted to provide some feedback on the accessibility of WingetUI, particularly for users like myself who rely on screen readers such as NVDA.
When attempting to read a package name in WingetUI, NVDA announces something like "ModernWindow.PackageEngine.Classes.Package," but it doesn't vocalize the actual package name unless I use more advanced screen reader techniques. While most buttons are properly labeled, this issue makes it a bit challenging to navigate through packages smoothly.
To enhance accessibility, it would be incredibly beneficial to include a keyboard shortcut that can quickly jump to the search box or the list of packages. It would also be fantastic if there were a way to bring focus directly to the list of found packages after performing a search. These adjustments could greatly improve the usability of WingetUI for screen reader users like myself.
If you're interested in testing accessibility without installing additional software, you can enable or disable the Windows built-in screen reader using the keyboard shortcut CTRL + windows+ Enter. For more information on using Narrator, you can check out Microsoft's help page: 
https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1
For further guidance on Windows accessibility standards, I recommend exploring Microsoft's accessibility resources.
https://learn.microsoft.com/en-us/windows/apps/design/accessibility/accessibility 
Additionally, if you're curious about NVDA and its capabilities, you can visit the NV Access website: .
https://www.nvaccess.org/
Thanks for considering this feedback! Feel free to reach out if you have any questions or need further clarification.

### Describe how this improvement could help users.

Improving accessibility for screen reader users.

**Comment by marticliment** [comment]
this is already an open issue
