### ISSUE TITLE
[BUG] No Option to Disable GPU Hardware Rendering

### ISSUE THREAD

**Issue by Cyber5imon** [marticliment/WingetUI#2190]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

WingetUI.exe is using GPU memory and there doesn't appear to be any option to disable hardware rendering. With a smaller GPU card I need to conserve all the GPU memory possible and do not need any speed improvements in WingetUI that would be gained by hardware rendering.

### Steps to reproduce the issue

Looks through settings for Hardware/Software Rendering option

### WingetUI Log

```text
Here is the output from NVIDIA-SMI showing the app using GPU memory:
`+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1304    C+G   C:\Windows\System32\dwm.exe                 N/A      |
|    0   N/A  N/A      1512    C+G   ...5n1h2txyewy\ShellExperienceHost.exe      N/A      |
|    0   N/A  N/A      3516    C+G   C:\Program Files\RustDesk\rustdesk.exe      N/A      |
|    0   N/A  N/A      8228    C+G   C:\Windows\explorer.exe                     N/A      |
|    0   N/A  N/A      8568    C+G   ...m Files\Mozilla Firefox\firefox.exe      N/A      |
|    0   N/A  N/A     10580    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe      N/A      |
|    0   N/A  N/A     11984    C+G   C:\Program Files\WingetUI\WingetUI.exe      N/A      |
|    0   N/A  N/A     15512    C+G   ...GeForce Experience\NVIDIA Share.exe      N/A      |
|    0   N/A  N/A     15948    C+G   ...m Files\Mozilla Firefox\firefox.exe      N/A      |
|    0   N/A  N/A     17096    C+G   C:\Program Files\RustDesk\rustdesk.exe      N/A      |
+-----------------------------------------------------------------------------------------+`
```

### Package Managers Logs

```text
N/A
```

**Comment by marticliment** [comment]
I am afraid UI Rendering is handled by WinUI3, so I have no control over this
