### ISSUE TITLE
[ENHANCEMENT] Open console windows in background so they don't steal focus.

### ISSUE THREAD

**Issue by CReich02** [marticliment/WingetUI#2198]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I've seen some other tickets that mention it for full-screen applications, but this is a problem for all updates even when not in full screen. Console windows and any update windows should open in background or minimized without taking window focus. When updating multiple applications a console window keeps popping up taking focus from what I'm trying to work on.

https://github.com/marticliment/WingetUI/issues/2030 was opened, but was closed as a duplicate of https://github.com/marticliment/WingetUI/issues/2036 which doesn't exist.

It's extremely annoying when trying to type up an email or work on some code. I'm not sure if it is only with winget or with all sources, but I know it does happen for winget and for most, if not all, packages. Auto-update is fairly useless with this happening.

### Describe how this improvement could help users.

Allow people to still use their computers while updates are happening without interruption.

**Comment by marticliment** [comment]
This issue was fixed on a previous commit
