### ISSUE TITLE
[FEATURE REQUEST] Add new option to set an auto-update time window

### ISSUE THREAD

**Issue by CReich02** [marticliment/WingetUI#2199]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Instead of just enable/disable auto-update, it would be nice to have an option to set a time of day or time window where it would perform all auto-updates.

### Describe how this new feature could help users.

This could probably be accomplished using the task scheduler, but having the settings in the app would be nice. It would also make it easier to set up for many people who don't know how to use the task scheduler.

**Comment by marticliment** [comment]
Duplicate issue

**Comment by CReich02** [comment]
> Duplicate issue

@marticliment Can you link to the original this is a duplicate of so I can follow it? I couldn't find it in my search.

**Comment by marticliment** [comment]
https://github.com/marticliment/WingetUI/issues/1294
