### ISSUE TITLE
[FEATURE REQUEST] Publish WingetUI to Microsoft Store for easy Auto-updating

### ISSUE THREAD

**Issue by NightmareWyrm** [marticliment/WingetUI#2205]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Publish WingetUI to Microsoft Store so it can be installed from there and be auto updated.

### Describe how this new feature could help users.

It will provide a centralize and easy way to find,install and update WingetUI.

**Comment by marticliment** [comment]
Can't publish on MS Store since WinGetUI does install third-party software
