### ISSUE TITLE
在安装更新时，C++更新和NET更新，一直失败，报错

### ISSUE THREAD

**Issue by manbuzhe725** [marticliment/WingetUI#2216]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

希望可以增加一个修复安装功能，解决这些更新时的失败报错。

### Describe how this new feature could help users.

Starting package update operation for package id=Microsoft.VCRedist.2005.x64with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=True;Version=;Architecture=X64;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : D:\WingetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "D:\WingetUI\PackageEngine\Managers\winget-cli_x64\winget.exe"  update --id Microsoft.VCRedist.2005.x64 --exact --accept-source-agreements --silent --disable-interactivity --accept-package-agreements --architecture x64 --force --include-unknown
Working Directory      : C:\Users\yangpu
    |    / 
    |   ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 10.5 MB
    |   █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 10.5 MB
    |   ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 10.5 MB
    |   ███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 10.5 MB
    |   ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 10.5 MB
    |   █████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 10.5 MB
    |   ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 10.5 MB
    |   ██████████████████████▒▒▒▒▒▒▒▒  8.00 MB / 10.5 MB
    |   █████████████████████████▒▒▒▒▒  9.00 MB / 10.5 MB
    |   ████████████████████████████▒▒  10.0 MB / 10.5 MB
    |    \ 
    | No installed package found matching input criteria.
Process Exit Code      : -1978335212
Process End Time       : 2024-05-16 9:41:36

**Comment by marticliment** [comment]
Please post in english.

MSVC++ Redist packages sometimes do fail, but this is caused by WinGet, not by WinGetUI
