### ISSUE TITLE
Cannot paste Package Managers Logs (body is too long (maximum is 65536 characters)

### ISSUE THREAD

**Issue by madmax2** [marticliment/WingetUI#2238]
To post bugs or issues we need to paste Package Managers Logs 

but then we get error if the log is too long
and will need to paste it into a pastebin and post the link..

**Error Package Managers Logs is too long** 
-There was an error creating your issue: body is too long (maximum is 65536 characters).

Please fix this problem.

**Comment by marticliment** [comment]
I am afraid I cannot control how GitHub limits messages.

You can also upload the log file as a txt file, you can export it directly from WingetUI
