### ISSUE TITLE
[BUG] The 'Installation options' button does nothing

### ISSUE THREAD

**Issue by Eemeli0123** [marticliment/WingetUI#2244]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [x] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The 'Installation options' button on the Discover packages, Software updates and Installed Packages tabs doesn't do anything

### WingetUI Log

[WingetUI Log.txt](https://github.com/marticliment/WingetUI/files/15415598/WingetUI.Log.txt)

### Package Managers Logs

[WingetUI Package manager Log.txt](https://github.com/marticliment/WingetUI/files/15415613/WingetUI.Package.manager.Log.txt)

**Comment by marticliment** [comment]
please upload the logs as txt files

**Comment by marticliment** [comment]
This issue was fixed on a previous commit. 

Changes will be effective on the next release
