### ISSUE TITLE
[BUG] Create UnigetUI folder in Documents only on demand

### ISSUE THREAD

**Issue by CanePlayz** [marticliment/WingetUI#2257]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I don't use package backups, so I don't need the UnigetUI folder in my Documents folder.

### Describe how this improvement could help users.

I like to keep all of the files and folders on my PC clean and since I don't need the aforementioned folder, I'd love to not have it there.

**Comment by marticliment** [comment]
Which WingetUI/UniGetUI version are you using?

**Comment by CanePlayz** [comment]
Newest alpha release

**Comment by marticliment** [comment]
This will possibly have to do with the folder migrator. 

If you delete the folder, does it reappear?

**Comment by CanePlayz** [comment]
Yep, that's the main issue I'm having. It seems to be recreated every time I start the application. UnigetUI is also creating a "WindowsPowerShell" folder with an empty folder `Scripts/InstalledScriptInfos`...

**Comment by marticliment** [comment]
This last one is created by PowerShell, so I can't do much about it, but I will fix the one on Documents

**Comment by CanePlayz** [comment]
Thanks. I wonder if there's anything I can do about the WindowsPowerShell folder... In which context of UnigetUI is it being created?

**Comment by marticliment** [comment]
Some managers (such as scoop, WinGet and Npm and PWSH Gallery are called from PowerShell for improved compatibility). 

This is unavoidable. Any program that uses powershell will face this issue

**Comment by CanePlayz** [comment]
I see, if calling them from PS requires that folder, fair, thanks

**Comment by CanePlayz** [comment]
Thanks :)
