### ISSUE TITLE
[ENHANCEMENT] Stop gsudo from flashing cache warnings when only asking once for administrator privileges

### ISSUE THREAD

**Issue by aaronliu0130** [marticliment/WingetUI#2263]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

![image](https://github.com/marticliment/WingetUI/assets/11874211/11ab70b5-6614-434c-abaa-c8d18d0f15fa)
somehow remove this screen which flashes for every package modification/update/install operation that uses gsudo

### Describe how this improvement could help users.

my eyes will be borne back ceaselessly into the past

**Comment by gerardog** [comment]
Marti, you start a cache for Process ID then every child process will have access to the cache. So you can do `gsudo cache on -p {WingetUI pid} --duration Infinite` and that will be enough. The cache will end when the PID terminates.

**Comment by marticliment** [comment]
Yes, in theory this is how WingetUI should be operating.

However, since I am not able to know whether the process has already been enabled or not, I just call `gsudo -k {WingetUI Pid}`, and if the process already had cache no UAC popup will be shown.

The fact that the command prompt is showing is likely to be an issue with how I call the executable.

**Comment by gerardog** [comment]
`-k` does not accept a `{WingetUI Pid}` argument, it ends every cache on the system.
To end a specific cache instance, `gsudo cache off` for the current caller or `gsudo cache off -p PID`

> The fact that the command prompt is showing is likely to be an issue with how I call the executable.

Yeah you can pass `Start Minimized`..

**Comment by marticliment** [comment]
I am sorry, I got confused, this is the code I use. Now I see that on certain functions it does not use the "StartInfo.CreateNoWindow" flag, which is likely to be the cause of the flashing windows issue
![image](https://github.com/marticliment/WingetUI/assets/53119851/8bc5129c-a9c7-4a04-a776-fff113ab8322)

**Comment by marticliment** [comment]
Btw, thanks for GSudo!

**Comment by gerardog** [comment]
Thanks to you too man, I'm impressed with your work 😉
