### ISSUE TITLE
[ENHANCEMENT] usage of system internal Winget

### ISSUE THREAD

**Issue by spookyfox** [marticliment/WingetUI#2277]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

if the expermimental feature "Use system internal Winget" == true, all winget sources (official and custom) don'n get considered anymore.

There is a note that the system language needs to be english, but my users are German, hence the standard language of the client machines is German.

Is this the reason why it does not work properly and if so is it supposed to be enhanced that it will work language independent?

### Describe how this improvement could help users.

Using custom data sources independent of system languages (not english) would be possible.

**Comment by marticliment** [comment]
This is why this feature is marked as Experimental, since it is half broken.
However, UniGetUI 3.1.0 has this issue fixed, you can test the alpha releases if you want
