### ISSUE TITLE
[ENHANCEMENT] A UI trigger to force a check for package updates

### ISSUE THREAD

**Issue by coinzdude** [marticliment/WingetUI#2295]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

In this screen, there appears to be no UI trigger to force a check for package updates. For example, in this case, I know there are two available package updates, and if I force quit WingetUI and restart the application, it will find the updates. Perhaps I am missing something here, but I have clicked on these UI elements but nothing appears to force a full rescan for updates

![image](https://github.com/marticliment/WingetUI/assets/58857646/ceb0317f-0001-4476-96d6-4ab035d289f6)

### Describe how this improvement could help users.

I currently find I need to close WingetUI and restart it to find package updates manually, otherwise, I need to wait some unspecified amount of time for the updates to appear

**Comment by marticliment** [comment]
This issue has actually been fixed in code, and the fix will be effective on the next release.
