### ISSUE TITLE
[BUG] Many versions for a given chocolatey package are missing and out of order

### ISSUE THREAD

**Issue by stamminator** [marticliment/WingetUI#2310]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When using UniGetUI 3.1.0-alpha1 to search for `php`, I selected the Chocolatey package with that exact id. For this package, Chocolatey reports there are 288 versions available, but UniGetUI's "Version to Install" section shows only 42 versions by my count, and they are listed out of order.

```
> choco search php --exact --all-versions

Chocolatey v2.2.2
php 8.3.8 [Approved]
php 8.3.7 [Approved]
php 8.3.6 [Approved]
php 8.3.4 [Approved]
... (shortened for brevity)
php 5.3.6.2 [Approved]
php 5.3.6.1 [Approved]
php 5.3.6 [Approved]
288 packages found.
```

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/10633170/7deababf-14a8-4459-8c06-b1361cac9426)

**Comment by marticliment** [comment]
Fixed!
