### ISSUE TITLE
Where to save the downloaded installation package

### ISSUE THREAD

**Issue by manbuzhe725** [marticliment/WingetUI#2311]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Where to save the downloaded installation package？

### Describe how this improvement could help users.

Delete used installation packages。 thank you

**Comment by marticliment** [comment]
This is done by the Package Managers themselves, WingetUI/UniGetUI does not handle directly installations/updates/uninstalls
