### ISSUE TITLE
[ENHANCEMENT] Simplify the "launch minimized upon Windows startup" experience

### ISSUE THREAD

**Issue by stamminator** [marticliment/WingetUI#2313]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

My preferred way to manage package updates is to be automatically notified shortly after logging in to Windows. I get notifications via the very nice UniGetUI widgets without needing the full UniGetUI window to launch and clutter up my screen.

Currently, I do this by putting a shortcut to WingetUI.exe in `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`, going to the shortcut's Properties, and editing the Target value to have `--daemon` at the end. This works great, but isn't intuitive for many users.

It would be nice if this startup behavior were configurable via UniGetUI's settings page. Here's an example of how Spotify's desktop app enables this, and I think their solution is quite nice.

![9fJeRPg2lX](https://github.com/marticliment/WingetUI/assets/10633170/507b0bb7-ff95-4b57-8699-6e61e2565c0f)

### Describe how this improvement could help users.

Quicker and less obtrusive startup access to the underlying UniGet goodness

**Comment by marticliment** [comment]
The fact that UniGetUI is opening itself on launch is a bug, actually. It has been fixed and UniGetUI will start minimized, as it did before

**Comment by stamminator** [comment]
Nice! I'm actually new to using this, so I didn't realize it was a regression. You're doing a great job with this project, by the way. It's very impressive.

**Comment by ROBYER1** [comment]
UnigetUI latest version as of today seems to open the full window on windows startup, I even tried uninstall, restart, install of it fresh. Can't see a start minimized option in settings?

**Comment by marticliment** [comment]
Hello @ROBYER1, which version are you running? Are you launching UniGetUI via task scheduler or similar?

**Comment by marticliment** [comment]
Hello @ROBYER1, which version are you running? Are you launching UniGetUI via task scheduler or similar?

**Comment by ROBYER1** [comment]
> Hello @ROBYER1, which version are you running? Are you launching UniGetUI via task scheduler or similar?

I'm on UniGetUI 3.1.1, I haven't done anything bespoke to open it on launch like that, I even tried reinstalling UniGetUI

**Comment by marticliment** [comment]
Yes, this is likely the cause. This shortcut shouldn't be there, the installer does not create it. Try to remove it, and see if the issue gets resolved
