### ISSUE TITLE
[BUG] Broken control for adding custom screenshot database links 

### ISSUE THREAD

**Issue by bropines** [marticliment/WingetUI#2315]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The Yandex music package shows something completely incomprehensible.

### Steps to reproduce the issue

Just search for installed Yandex package

### WingetUI Log

```text
(added file)
```

### Package Managers Logs

```text
(added file)
```

### Relevant information

[log UniGetUI.txt](https://github.com/user-attachments/files/15845978/log.UniGetUI.txt)
[PM logs UniGetUI.txt](https://github.com/user-attachments/files/15845979/PM.logs.UniGetUI.txt)

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/57861007/e1e8587a-5d0e-4a2c-9217-e6eaaa052230)

**Comment by bropines** [comment]
https://github.com/marticliment/WingetUI/assets/57861007/8d8ece38-1f80-474c-be46-4491ba4c37dd


Since my English leaves much to be desired, I’ll just attach a video (there’s another bug there). Another link in the documentation https://marticliment.com/unigetui/help/icons-and-screenshots/normalized-ids leads to nothing (error 404)

**Comment by bropines** [comment]
I also don’t understand how to add pictures to the application in the table. I did this
![image](https://github.com/marticliment/WingetUI/assets/57861007/825b4251-205a-4437-b325-167c67aca080)

But the application has not been updated. Either it's my mistake or I need to restart the application

**Comment by marticliment** [comment]
Regarding the broken characters, I am aware of it. The issue to track this is https://github.com/marticliment/WingetUI/issues/2242.

Regarding the icons, they take 24/48h to load. For what I see, you added the png correctly.

**Comment by bropines** [comment]
> Regarding the broken characters, I am aware of it. The issue to track this is #2242.
> 
> Regarding the icons, they take 24/48h to load. For what I see, you added the png correctly.

understood. there's also a bug at the end of the video with inserting its own JSON for images that slides out a lot when you enter a link.
