### ISSUE TITLE
[BUG] Package bundle does not consider the version in the bundle file

### ISSUE THREAD

**Issue by MohammedNoureldin** [marticliment/WingetUI#2322]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

The UI does not respect the version in the exported bundle.

### Steps to reproduce the issue

- In package discovery search for a package and select its version.
- Click add to bundle
- Export the bundle
- Edit the version in the exported file and set it to the targeted version.
- Make any changes or remove the the packages in the UI.
- Reimport the exported bundle.
- The UI shows though the latest version, not the one in the bundle.

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/14913147/4af8bcb7-f23c-4a18-920a-2e373dc92da2)

Here the screenshot shows the selected version of nextcloud 2.5.2, which is definitely not the latest, though the UI shows the latest.

**Comment by marticliment** [comment]
Yes, this is expected to be like this.

When you have exported a list of packages, unless you have ingored updates for that package, WingetUI understands you want the latest version, and therefore it does install the latest available version. If, however, the package had updates ignored, the version will shpw up

**Comment by MohammedNoureldin** [comment]
Oh OK. I have just tried it and this is exactly as you explained. Thanks a lot!
