### ISSUE TITLE
[ENHANCEMENT] Uninstall with PackageId instead of PackageName

### ISSUE THREAD

**Issue by teebeast** [marticliment/WingetUI#2323]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

I have two installations of Mircosoft Edge. One from WinGet and one from Microsoft store. When I want to uninstall one of them, I get an error that multiple packages were found.

![grafik](https://github.com/marticliment/WingetUI/assets/20777572/041bcc62-6971-422a-8a48-ea8f50500ceb)

Would it be better to uninstall with the PackageId instead of the PackageName to be more precise?

By the way, if the PackageId is very long, it will be shortened, even though there is enough space to display it.
![grafik](https://github.com/marticliment/WingetUI/assets/20777572/3c29457e-eb25-4379-a615-eb468fa401d0)

Best regards.

### Describe how this improvement could help users.

You can uninstall a package when there are more than one package with the same name.

**Comment by marticliment** [comment]
This behaviuour happens due to WinGet cropping the package Id. If the identifier has no ellipsis (`...`), the Id will be used.

Anyway, this issue has been fixed on the latest alpha release, so I am going to close this issue for now
