### ISSUE TITLE
[BUG] `which` unsupported by Command Prompt, leading to package managers not found: "winget.exe was not found on the system" etc

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/WingetUI#2325]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Firstly, I have not tested the lastest beta or stable. If I have additional time, I will.

The issue is, I've been using the WingetUI experimental setting "Use system Winget (System language must be set to english)" for many months, but for several weeks (not sure how long), WingetUI no longer updates any WinGet packages. WingetUI's settings reports "Winget was not found!". It also shows `B:\ThisExe\WasNotFound\InPath\winget.exe` for the path.

This setting used to work, and I believe it still worked in the first v3 version that was released. Perhaps it broke in some 3.0.x update? It definitely worked in v2 WingetUI.

Disabling the experimental setting and restarting WingetUI causes WingetUI to begin offering WinGet package updates again.

```
> where.exe winget.exe
D:\Scoop\shims\winget.exe
C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe
```

Related? #2239

Thanks.

WingetUI 3.0.2

### Steps to reproduce the issue

Didn't do anything differently. The experimental feature just stopped working one day, presumably after the latest / a recent WingetUI update.

### WingetUI Log

```text
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
```

### Package Managers Logs

-

### Relevant information

Did the experimental setting always require the system language to be English? "Use system Winget (System language must be set to english)". Mine is set to English but United Kingdom, if that matters?

### Screenshots and videos

![WingetUI_2024-06-19_22-20-11](https://github.com/marticliment/WingetUI/assets/25013746/6a22ac0c-aefe-45cf-b835-b78d28fd348f)

**Comment by marticliment** [comment]
Please test the latest alpha. WinGet component has essentially been rebuilt

**Comment by marticliment** [comment]
They are both copies of the same file, they are left as a compatibility feature with older installers

**Comment by marticliment** [comment]
How are you running WingetUI? Admin? special environment?
Where do you run the where.exe commands? Cmd, PWSH? Admin or regular user?

**Comment by marticliment** [comment]
Your paths should never contain a `!` character. Please try removing it temporarily and try again

**Comment by marticliment** [comment]
Great!
