### ISSUE TITLE
[BUG] Notification tray icon should open the available updates tab if there's any

### ISSUE THREAD

**Issue by mahmoudhossam** [marticliment/WingetUI#2333]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Currently the system tray icon shows if there are available updates but when clicking on it it just goes to the discover tab.

A more intuitive behavior would be for it to show the updates the notification is showing and only go to available software if there are no new updates available.

### Describe how this improvement could help users.

Makes it easier to get to the relevant information without too much unnecessary clicking.

**Comment by marticliment** [comment]
Oh, it should do that.

I will fix this

**Comment by marticliment** [comment]
Fixed!
