### ISSUE TITLE
[FEATURE REQUEST] Make a new column in the GitHub Suggest an Report a bug page

### ISSUE THREAD

**Issue by skanda890** [marticliment/WingetUI#2339]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Make a new column in the GitHub Suggest an Report a bug page called WingetUI Version and maybe even Windows version.

### Describe how this new feature could help users.

This could help @marticliment to know which version of WingetUI and Windows.

**Comment by marticliment** [comment]
Done!
![image](https://github.com/marticliment/WingetUI/assets/53119851/853a319e-c2cf-41f7-bd9a-b195101b1c5e)
