### ISSUE TITLE
[CRASH] Unable to launch when installed from Microsoft Store.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [marticliment/WingetUI#2367]
### Please confirm these before moving forward.

- [X] I have tried deleting a folder named `.wingetui` placed on the user directory.
- [X] I have tried reinstalling WingetUI.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).

### Describe your crash

As the undermentioned demonstrates, I am unable to invoke it from the Microsoft Store after installation:

> ![Screenshot 2024-06-23 164542](https://github.com/marticliment/WingetUI/assets/42837531/ef1531d0-adcf-43ca-b72f-0d04223838c2)

Additionally, should I attempt to invoke it from the Start Menu, it does not open.

### More details

I expect that I was using https://github.com/marticliment/WingetUI/releases/tag/3.0.1, but since you don't publish the `.MSIX` or `.MSIXBundle` here (even https://github.com/microsoft/winget-pkgs/blob/457139e28231dbaedd7111a837537f570438f065/manifests/s/SomePythonThings/WingetUIStore/3.0.2/SomePythonThings.WingetUIStore.installer.yaml#L20 uses the `.exe`, unfortunately) I can't evaluate whether it's the packaging or repository which is at fault.

**Comment by marticliment** [comment]
Hello,

You are installing **Widgets** for WingetUI. As said in the description, you need to install WingetUI separately

**Comment by RokeJulianLockhart** [comment]
> https://github.com/marticliment/WingetUI/issues/2367#issuecomment-2198541982

Ha! That's the human brain - cuts out text it doesn't want to see. I apologise - somehow during this entire process I never once saw the word "Widgets" there.

**Comment by marticliment** [comment]
Don't worrry :)
