### ISSUE TITLE
[ENHANCEMENT] Uninstalling should remove bundled Chocolatey choco.exe

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/WingetUI#2373]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

When installing, we can choose to install Chocolatey. When we uninstall, Chocolatey does not get deleted from *%LOCALAPPDATA%\UniGetUI\Chocolatey*. Therefore, when we reinstall UniGetUI and do not select to install Chocolatey, Chocolatey will still be present.

Even though I have the option to use the system Chocolatey, the one from *%LOCALAPPDATA%* was being loaded according to the logs (rather than from my PATH Scoop directory).

3.1.0 beta 1

**Comment by marticliment** [comment]
I don't agree, since it would uninstall all the packages installed to that location. I feel deleting chocolatey would be a risk
