### ISSUE TITLE
[BUG] 3.1.0 Beta 1 - Clean install issue; Missing dependency (WinGet.Client)

### ISSUE THREAD

**Issue by RonnyTNL** [marticliment/WingetUI#2384]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0 Beta 1

### Windows version, edition and architecture

Win10 x64

### Describe your issue

I did a clean install of UniGet 3.1.0 Beta 1 on a fresh VM and noticed the following.

![image](https://github.com/marticliment/WingetUI/assets/19427356/cb3c9660-2f11-4aed-a6ac-5939e81a3599)

### Steps to reproduce the issue

I have two users on this machine a standard user and an Admin user.
Logged in to the standard user account, right mouse -> Run as Admin on the UniGet installer, next, next finish etc.

Close application and start as standard user, it starts to scan and inventory and then pops with the missing dependency.
Asks to install but this fails as the current user doesn't have admin privs, so I though let's log out and login as admin.
Start the application (not elevated as not recommended) and same issue happens.

I need to run the application again as "Run as Admin" and then the Missing dependency issue can be resolved.

I think this might be a bit to complicated for the average user, so perhaps this install flow can be improved by making sure this prompts for elevation to admin privs before starting the install attempt of the dependency?

### UniGetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Relevant information

Fresh install of 3.1.0 Beta 1, this machine has never seen WinGetUI or previous Alpha/Beta's of 3.1.0

**Comment by marticliment** [comment]
fixed on https://github.com/marticliment/WingetUI/commit/c6b4fbe306e7163ce88dc13d31ae34dbd478d827
