### ISSUE TITLE
Update icon should be different from install one

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#265]
- [ ] Update icon should be different from install one

![Captura de tela 2022-10-14 225514](https://user-images.githubusercontent.com/73800734/195964111-0b942df2-73bb-48de-bed6-eaa6f55e5535.png)

Suggestions:

https://user-images.githubusercontent.com/73800734/195964106-4c82da13-c87a-43eb-8857-feaedb1bc6e6.png

https://user-images.githubusercontent.com/73800734/195964147-e77c7ad4-5787-42a3-80c5-c17ca3496d7d.png

- [ ] Also, version icon should be different from install one IMO

![Captura de tela 2022-12-27 191329](https://user-images.githubusercontent.com/73800734/209727070-10b98e80-445a-4d07-bc2c-4faffb6f3f02.png)

suggestions:
https://icons8.com.br/icons/set/version
https://user-images.githubusercontent.com/73800734/209727418-fdb16e9c-a754-4367-baa7-6a2fa8cef486.png (from first WingetUI version)

**Comment by ppvnf** [comment]
Also, version icon should be different from install one

**Comment by marticliment** [comment]
Regarding the second item, they both represent the latest instalable version, so it would make sense to leave them the same

**Comment by ppvnf** [comment]
What about new versions?
<img width="83" alt="Screenshot 2023-02-27 173933" src="https://user-images.githubusercontent.com/73800734/221650438-6022c3de-bea1-4b8d-aa23-9cf0d0321c51.png">

**Comment by marticliment** [comment]
> Regarding the second item, they both represent the latest instalable version, so it would make sense to leave them the same

**Comment by ppvnf** [comment]
I guess it is mostly a matter of personal preference, but I find a little bit confusing that these two icons are the same:

<img width="106" alt="Screenshot 2023-03-02 220036" src="https://user-images.githubusercontent.com/73800734/222551682-e83eb148-0e7e-41de-9b2e-2d87f78b6dac.png">
<img width="125" alt="Screenshot 2023-03-02 220027" src="https://user-images.githubusercontent.com/73800734/222551689-2ff2df1e-41b4-4888-a60c-b08a5f743b8d.png">

**Comment by marticliment** [comment]
Do you have any proposal for a new version icon?
It is true that it does not show quite the idea of versioning...

**Comment by ppvnf** [comment]
No, I was actually thinking about changing the install icon instead of the version one

**Comment by ppvnf** [comment]
Example https://img.icons8.com/dotty/512/software-installer.png

**Comment by marticliment** [comment]
I reckon it kind of breaks the round-line windows 11 style, doesn't it?

**Comment by ppvnf** [comment]
I didn't find a similar round icon unfortunately

**Comment by ppvnf** [comment]
> Do you have any proposal for a new version icon? It is true that it does not show quite the idea of versioning...

How about simply something like

https://icons8.com/icon/66762/circled-v
https://icons8.com/icon/66763/circled-v

**Comment by ppvnf** [comment]
i have noticed in the resources folder this icon that could be used for the version/instal,,
![performinstall_black](https://user-images.githubusercontent.com/73800734/231900440-3390ca9e-b5f3-49cf-b147-ea79dd08350e.png)
besides, there seems to be a few icons that are not used anywhere and can be removed.

**Comment by marticliment** [comment]
Honestly, I reckon it wouldbe weird, since at the end of the day this is the outline of WingetUI's logo, what do you think?
Also, On which section would you put it?

**Comment by ppvnf** [comment]
![Screenshot 2023-04-14 165926](https://user-images.githubusercontent.com/73800734/232081577-1ecdeeda-c4bb-43c2-8865-2ee86ee0487d.png)
Discovery section. I am not sure which icons to use, but I think it is not ideal to use the same icon for two different things
