### ISSUE TITLE
Add button to go to the top of the list 

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#272]
I know you can press the "Home" key, but it only works if you select a package. Example:

![Captura de tela 2022-10-15 115502](https://user-images.githubusercontent.com/73800734/195993502-40d61ed1-047f-40ae-bd01-f846a5eef777.png)

Obs: I believe this button should only appear after the user scrolled

TODO:

- [x] add return to the top button
- [x] make the button appear only when the page is scrolled

**Comment by martinet101** [comment]
Actually yes

**Comment by ppvnf** [comment]
> * make home go to the top even without selecting a package

Is this possible?

**Comment by martinet101** [comment]
Yeah, I understand you meant something like return to top button, right?

**Comment by ppvnf** [comment]
> Yeah, I understand you meant something like return to top button, right?
> 
> On the package lists, right?

That's correct. And also, if possible, make the "Home" key able to return to the top even without selecting a package

**Comment by martinet101** [comment]
Yes, I reckon an issue about keyboard navigation would be more adequate. More things like intro key binding should also be added

**Comment by martinet101** [comment]
> That's correct

Yes, this is easily doable

**Comment by ppvnf** [comment]
> Yes, I reckon an issue about keyboard navigation would be more adequate. More things like intro key binding should also be added

I've created it: https://github.com/martinet101/WingetUI/issues/275
