### ISSUE TITLE
Improve keyboard navigation

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#275]
<s>Make "Home" key go to the top of the list even without selecting a package</s>
<s>"End" key also shouldn't need selecting a package</s>
<s>"Page Up" and "Page Down" keys shouldn't return to the previously selected package if no package was selected </s> (see https://github.com/martinet101/WingetUI/issues/275#issuecomment-1283089220)
<s>"Up" and "Down" keys shouldn't return to the beginning of the list if no package is selected </s> (see https://github.com/martinet101/WingetUI/issues/275#issuecomment-1283089220)
- [x] ADDED: Enter key should trigger the double-click action
- [x] ADDED: Add keyboard navigation in the app info screenshots section
- [ ] ADDED: Hold shift to select multiple packages
- [x] Ctrl+A to select/unselect all
- [ ] Crtl+Click to select/unselect a single package

Moved from https://github.com/martinet101/WingetUI/issues/272

**Comment by ppvnf** [comment]
> "Page Up" and "Page Down" keys shouldn't return to the previously selected package if no package was selected
> "Up" and "Down" keys shouldn't return to the beginning of the list if no package is selected

I don't actually know which behavior (if any) of the two above is wrong/correct. You may remove it if you think one or both of them are correct

**Comment by ppvnf** [comment]
I've added "use shift to select more packages"

**Comment by martinet101** [comment]
The keyboard navigation in the screenshot carrousel is now a feature

**Comment by martinet101** [comment]
> * [ ]  Make "Home" key go to the top of the list even without selecting a package
> * [ ]  "End" key also shouldn't need selecting a package

This is the default Qt's behaviour, and it can't be changed

**Comment by martinet101** [comment]
I reckon that if I enabled multi-select, there would be two multi-selection methods (checkboxes and shift+click), and it would be unclear which list would be taken in account when using actions such as update selected, etc. What do you think?

**Comment by ppvnf** [comment]
Would it be possible to combine checkboxes and shift+click? For example, if you want to uninstall all dotnet runtimes, you would hold shift + click the first one's name + click the last one's name. How about making the checkboxes checked if multiple packages were selected using shift + click (even if the user don't click any checkbox)?

![Captura de tela 2022-12-23 180054](https://user-images.githubusercontent.com/73800734/209405173-2332445a-fd8e-4737-a4b4-32a2c67be84b.png)

**Comment by martinet101** [comment]
Yes, this might be a possible solution

**Comment by Mikey1993** [comment]
@marticliment 
I would also suggest to add the `CTRL + left click` on a package so that when you do that it selects/marks it with the "V" mark in the most left column

**Comment by ppvnf** [comment]
> @marticliment 
> I would also suggest to add the `CTRL + left click` on a package so that when you do that it selects/marks it with the "V" mark in the most left column

Also, I think ctrl + a should select all/select none in uninstall/update sections

**Comment by Mikey1993** [comment]
@marticliment I think that there should also be a dedicated section for changing some default hotkeys inside the Settings - should a new issue be opened for that?

**Comment by marticliment** [comment]
Yes, please open a new one, thanks!
