### ISSUE TITLE
Improve the display of Installed/new version in the info menu

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#279]
The search menu is fine, I am showing it just for reference:
![Captura de tela 2022-10-14 183622](https://user-images.githubusercontent.com/73800734/196012064-84041695-f00f-4f2d-a23c-e5214d600475.png)

However, I've pointed out in the picture below how the versions should be displayed in the info menu (**in the picture replace "current version" with "Installed version" - just a typo**):

- [ ] For Scoop packages, except in the Discovery tab, "Latest version" should be replaced with "installed version" (as an alternative you could replace "Latest version" simply with "version")

![Captura de tela 2022-10-14 142503](https://user-images.githubusercontent.com/73800734/196012067-84ec96d3-816b-469a-b624-da3010660c6f.png)

- [ ] Winget https://github.com/martinet101/WingetUI/issues/279#issuecomment-1286294772

**Comment by martinet101** [comment]
> * For Winget packages, the installed version is displayed on top. However, I think it should be displayed closer to the latest version (like Scoop packages):

This is a bug with winget, where some apps report as title their name+versions when installed. 
![image](https://user-images.githubusercontent.com/53119851/196030673-03f8813b-6f4c-43cb-a6f0-7b699e4a6e49.png)

**Comment by ppvnf** [comment]
> This is a bug with winget, where some apps report as title their name+versions when installed. ![image](https://user-images.githubusercontent.com/53119851/196030673-03f8813b-6f4c-43cb-a6f0-7b699e4a6e49.png)

I've removed it

**Comment by ppvnf** [comment]
I had an idea to be able to show both the installed version and the latest one of Winget apps in the info menu, but I don't know if it's viable: would it be possible, in addition to the information displayed when you run `winget show` + pkg name, to also show the information of `winget list` + pkg name in the info menu?

![Captura de tela 2022-10-20 210112](https://user-images.githubusercontent.com/73800734/197081772-607631aa-9189-4605-b7f8-5c18b55d6288.png)

**Comment by martinet101** [comment]
It would be pposssible, but each winget query adds up to ~two seconds or more on the overall loading time

**Comment by ppvnf** [comment]
> It would be pposssible, but each winget query adds up to ~two seconds or more on the overall loading time

It's not possible to use the info from `winget list ""`, right?

**Comment by martinet101** [comment]
it actually might...
