### ISSUE TITLE
[Feature Request] Blacklist Viewer Popup

### ISSUE THREAD

**Issue by Satanarious** [marticliment/WingetUI#284]
An interface to see all the blacklisted packages with an option to remove any/multiple packages from the list. Currently, you have to reset the blacklist to get all the blacklisted packages back on the software update page. What if I want only to remove a particular package from the blacklist? Then I will have to reset the blacklist, which will remove all other packages as well, which I still wanted on the blacklist.

I propose a simple list with all packages and a remove button right next to each one. Something like this.

![Screenshot 2022-10-16 204846](https://user-images.githubusercontent.com/42642682/196045745-632fede6-951f-441b-90d9-6e095c022b79.png)

**Comment by elliot-100** [comment]
Agree, although it seems more consistent to have an application list like the others, rather than a popup.

**Comment by ppvnf** [comment]
> Agree, although it seems more consistent to have an application list like the others, rather than a popup.

IMO a combination of popup + list would be ideal

**Comment by Bazzu85** [comment]
Hi, thx for the app!
In the meantime we wait for the feature...
are there any file that can we manually update to remove a package from the blacklist?

**Comment by ppvnf** [comment]
`%USERPROFILE%\.wingetui\BlacklistedUpdates`
