### ISSUE TITLE
Ideas to improve Scoop settings

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#286]
I have a few ideas on how to improve Scoop options in the settings:

 - [x] Unify "Remove bucket" and "Show installed" like in https://github.com/martinet101/WingetUI/issues/284:

![196062928-0d6007df-37ef-4ff4-8fe2-42f7a271796d](https://user-images.githubusercontent.com/73800734/207287135-15bd7c28-52dd-4bb0-8238-52375fc6cb9d.png)

![Captura de tela 2022-10-16 195959](https://user-images.githubusercontent.com/73800734/196062979-2bc7e832-35a8-446e-9953-8888b7b552fa.png)

- [x] this option should be greyed out if Scoop is disabled or not installed:

![Captura de tela 2022-10-16 194259](https://user-images.githubusercontent.com/73800734/196063047-caefa58a-8a05-4ab2-b48e-f65f5a005a15.png)

- [x] All options under Scoop preferences shoud be disabled if it isn't detected:

![Captura de tela 2022-12-13 070218](https://user-images.githubusercontent.com/73800734/207289083-f19fd9c9-9880-4599-9772-dd642441295e.png)

3.1 However, Install Scoop should be disabled only if it is detected

3.2 Disable Scoop should be forced to be checked if it isn't detected

**Comment by ppvnf** [comment]
1. Maybe unify "Remove bucket" and "Show installed" like in https://github.com/martinet101/WingetUI/issues/284

**Comment by luxzg** [comment]
I've got one more, unless I'm missing something. I already have scoop, and dozens of apps. How about "browse to scoop directory" or similar so it simply picks up current scoop settings (and installed apps).

**Comment by ppvnf** [comment]
I've updated this issue considering the new menu of version 1.5.1

**Comment by luxzg** [comment]
That seems as if it's per-app setting, if I'm not being confused by screenshot? I'd rather have something more global, as eg. my Scoop has close to 100 packages, going through them one by one would be... Unwelcome. It would literally be less time to delete scoop and just start with WingetUI from scratch.

I have to note, I've since made my own workflows that help me manage existing apps with very little effort (couple scripts), so I've put WinGetUI on hold indefinitely. So if it's just me, and there's no other non-trivial way to "import" all existing Scoop packages, you can ignore my idea, I won't mind.

On the other hand, if you think it's welcome feature to add, then maybe look at Scoop and its own list command and see how/where it gets list of apps. I couldn't figure out if it keeps list of installed apps somewhere centrally or it goes through install directory every time (I tried, I'm just not that good and got lost ;D ).

Anyway, thanks for considering it!

**Comment by ppvnf** [comment]
I don't know how to achieve what you want (I believe it is to backup settings for all Scoop apps). Maybe @martinet101 knows better. WingetUI has a function to import and export packages, but their settings aren't stored. I know you can use `scoop list` in PShell to see all installed scoop packages as well. There's also `scoop import` and `scoop export`, but I don't know how to use them. 

I also would like to know if there's a way to backup Scoop package settings like you propose. You could copy the folder C:\Users\ **YourUsername** \scoop\apps and the list of packages, but this would result in an unnecessarily big file. A more efficient solution would be to save only the persistant data from C:\Users\ **YourUsername** \scoop\apps\ _AppName_. That would certainly be useful IMO, but unfortunately I don't have the necessary skill...

**Comment by martinet101** [comment]
Hi @luxzg,

I don't really understand what you are requesting.

I understand an option to open where scoop installs its apps?

Regarding the scoop app exporting, you can already export lists of installed packages (including scoop ones) from the installed section, but the individual applicaton data can't be exported or copied to a backup file without moving the whole scoop folder (as @ppvnf said).

Is this what you meant?

**Comment by ppvnf** [comment]
@luxzg, there's also this file `C:\Users\your_user\.config\scoop\config.json` in case you want to backup specifically the scoop settings itself (replace your_user)

**Comment by luxzg** [comment]
Sorry all, I was away a little.

Just to clarify, what I'd like is for this UI to simply continue using my existing Scoop (together with settings and apps already installed).

To me this is logical, many UI apps, let's say fir example audio/video encoders, have such options. If you install UI it will A) ask where encoder exe is if you have it already, or B) install it's own copy of exe.

I don't see this app doing either. I installed UI using Scoop, opened UI, and it listed no Scoop apps. I tried to setup path to Scoop for it, it doesn't have the option.

Just seems like a missed opportunity. Someone installs Scoop, eventually discovers UI, installs it with Scoop, just to get basically told you can't use it without changing your setup.

IDK, am I missing here something obvious?

But as I said, I'm ok without UI. Just putting suggestion here as IMHO it would help this project and its potential users.

**Comment by martinet101** [comment]
You might need to enable scoop from the settings window. 
When installing from scoop, you won't be asked to install scoop, since the installation is done silently; so the default option will be taken: disabling it.

That's not a WingetUI's installer faullt, since this is what happens when using package managers: installers get ran silently.
The best thing you can do here is enable scoop from the settings window.

**Comment by luxzg** [comment]
Well, I' like to think I'm not that stupid :)

OK, to cover everything:

- installed Scoop
- discoevered Winget UI through scoop search
- installed WinGetUI package
- run WinGetUI
- went to "Installed packaged"
- don't see packages from scoop (both searching by names of packages, scrolling, or sorting by source, no scoop)
- go to menu, WinGetUI Settings
- scroll to "Scoop preferences" section, open it
- enable scoop, restart app, refresh, do whatever
- back to "Installed packages" - still no Scoop apps
- "Scoop preferences" offers "Install" button but I don't want to install (another) Scoop
- added random bucket (php) to scoop via WingetUI - somehow it works
- restarting and refreshing, still no scoop packages in "Installed packages"
- I do have some weird stuff in package lists marked as "+" and trying to get info seems to just be "Loading..." forever (waited a minute)
- these weird packages are:
- Package names: "+", "+", "At", "For", "+", with same respective Package ID, and Installed versions "Category info", "FullyQualifiedErrorId", "line:1", "more", "scoop"

![image](https://user-images.githubusercontent.com/9318107/208864544-48605f83-6eb4-436a-bb28-6477b9b27bba.png)

So I'd say it gets confused by my existing installation (default install, nothing weird here).

Perhaps having a Browse button and text field to enter path would fix the issue. 

![image](https://user-images.githubusercontent.com/9318107/208865577-17e5b655-0917-46b3-a00e-64761a701fe0.png)

Thus far WingetUI for me is unusable. But hey, I'm OK with that.

**Comment by martinet101** [comment]
What would happen if you tried uninstalling wingetui and installed it manually?
It is because some other people also faced issues with scoop when installing WingetUI from scoop.

**Comment by luxzg** [comment]
Uninstalled through scoop. Downloaded and installed manually, left the recommended option to not install Scoop. But - nope, still the same issue. On a side note, "scoop list" in Terminal works, both as Admin and unprivileged. But WingetUI has same errors even after reinstall, tried both as unprivileged and with "Run as Admin".
Anyway, sorry, I really shouldn't spam this thread then, in case what you say is true (and you ARE the dev) then my "Browse" idea thing isn't needed, it's different issue altogether, and I should move this to separate bug thread instead. Might be best to delete my comments from here :-/

**Comment by martinet101** [comment]
If you could open a new thread it would be great.

P.D. Try uninstalling wingetui, deleting a filder called .wingetui from your home user directory and installing again, installing scoop right from the installer. This **will not** overwrite your scoop installations or apps, but it will prepare wingetui to suport scoop from the installer, since it seems that WingetUI can't detect scoop for itself.

**Comment by marticliment** [comment]
The feature for managing scoop is implemented and will come with the next version
![image](https://user-images.githubusercontent.com/53119851/209687107-b291f6ca-0a59-4831-9604-424a11358f22.png)

**Comment by marticliment** [comment]
The items listed here have been implemented, and they will come with the next update

**Comment by ppvnf** [comment]
> 3.1 However, Install Scoop should be disabled only if it is detected
> 
> 3.2 Disable Scoop should be forced to be checked if it isn't detected

Thanks. I don't think it's really important, but would you mind explaining the reason why these suggestions were not implemented?

It's still possible to enable Scoop if it isn't detected:
![Captura de tela 2022-12-27 174325](https://user-images.githubusercontent.com/73800734/209720318-0c3b022b-fc1b-4522-9183-52f5730ae428.png)

It's still possible to install Scoop if it is detected:
![Captura de tela 2022-12-27 174516](https://user-images.githubusercontent.com/73800734/209720466-c540bd47-ba12-49f2-966a-72c1024107b0.png)

**Comment by marticliment** [comment]
> 3.1 However, Install Scoop should be disabled only if it is detected

Install scoop will also install git, a needed dependency that sometimes might lead to issues, so running the install script again may help in cases where scoop is installed but git is not



> > 3.2 Disable Scoop should be forced to be checked if it isn't detected

In the way scoop is detected, if `scoop -v` returns a non-zero value, it will report scoop not being installed (i have faced this issue).
I am working on this so I can properly locate scoop, and then implement some kind of dialog to warn the user that scoop is enabled but not installed or something.
