### ISSUE TITLE
[FEATURE REQUEST] (Scoop) Show packages notes 

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#303]
TODO LIST:

- [ ] Fix text overflow from notes to version field ([see possible explanation](https://github.com/martinet101/WingetUI/issues/303#issuecomment-1285152795))
- [ ] Add package notes to the info menu (Scoop packages)

**Is your feature request related to a problem? Please describe.**

I found out about Scoop notes because this package has a bug that doesn't allow its version to be shown: 

![Captura de tela 2022-10-19 124752](https://user-images.githubusercontent.com/73800734/196778839-2a7f805c-d70d-4bb8-8820-c76d77f91734.png)

As you can see in PowerShell, the notes are overflowing to the version field somehow:

![Captura de tela 2022-10-19 124651](https://user-images.githubusercontent.com/73800734/196779079-512e741a-8627-44ff-b58b-7bb3b03a21e0.png)

**Describe the solution you'd like**

I ended up having an idea: since many Scoop packages have notes, why not add them to the info menu? (on the other hand, I don't think Winget packages have any notes) 

Where? I don't know for sure, but maybe at the bottom. Also, maybe make it possible to hide the notes somehow.

**Comment by martinet101** [comment]
Yeah, why not

**Comment by ppvnf** [comment]
I've created a todo list and after a few more tests today I believe the reason the text overflow happens is because of the notes' size:

![Captura de tela 2022-10-20 053941](https://user-images.githubusercontent.com/73800734/196900107-acad6fc8-bfdb-429d-8055-7252be0589f1.png)

**Comment by ppvnf** [comment]
Would it be possible to implement something like trimming extra lines after the version number in order to fix the notes overflow into the version field?

**Comment by martinet101** [comment]
yes, the version and the release notes need to to be fixed

**Comment by martinet101** [comment]
Fixed!

**Comment by ppvnf** [comment]
Awesome solution. There's only one small problem left. As you can see, the release notes aren't always fully displayed for Scoop packages (only the first line is shown):

![Captura de tela 2022-12-07 185053](https://user-images.githubusercontent.com/73800734/206304198-9a11e799-6dfe-4b46-9951-7cb1fdba9f33.png)

![Captura de tela 2022-10-19 124651](https://user-images.githubusercontent.com/73800734/196779079-512e741a-8627-44ff-b58b-7bb3b03a21e0.png)

**Comment by marticliment** [comment]
This issue was fixed when I implemented the scop cat command for the command-line scoop parser. The fix will come with the next release.

Proof of fixing:
![image](https://user-images.githubusercontent.com/53119851/219976895-0b97a29d-0172-46ad-aa22-d0c37de0cc08.png)
