### ISSUE TITLE
[FEATURE REQUEST] Implement winget settings

### ISSUE THREAD

**Issue by fernandog** [marticliment/WingetUI#316]
Implement the winget settings command. I image feature with a screen with some checkboxes that creates the setting in the JSON file

For example:
```javascript
"installBehavior": {
    "preferences": {
        "scope": "user"
    }
},
```
I would be a checkbox "user" or "machine"

> The settings command of the [winget](https://learn.microsoft.com/en-us/windows/package-manager/winget/) tool allows you to customize your Windows Package Manager client experience. You can change defaults and try out experimental features that are enabled in your client. The settings command will launch your default text editor.

https://learn.microsoft.com/en-us/windows/package-manager/winget/settings

What do you think @martinet101 ?

**Comment by martinet101** [comment]
Yes, the scope thing is a thing i have ain mind, but i thought doing it through command-line so it can be easily changing without need to modify settings.json, and it could actually help with scoop global apps

**Comment by ppvnf** [comment]
I believe this is related to
https://github.com/martinet101/WingetUI/issues/123
https://github.com/martinet101/WingetUI/issues/140
https://github.com/martinet101/WingetUI/issues/81
https://github.com/martinet101/WingetUI/issues/206
https://github.com/martinet101/WingetUI/issues/142

**Comment by ppvnf** [comment]
Was this fixed with https://github.com/marticliment/WingetUI/commit/6ed9bab5fe515547e758308dc658fa7c31f952f3?

**Comment by marticliment** [comment]
Yes!
