### ISSUE TITLE
[FEATURE REQUEST] CLI interface for update-all

### ISSUE THREAD

**Issue by Bluscream** [marticliment/WingetUI#340]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.
https://github.com/microsoft/winget-cli/issues/476

I currently use https://gist.github.com/Bluscream/c1b14be52a20b54433ba46a4c26aed41#file-update-all-ps1-L54 but that also updates packages that have broken updaters so they will "re-update" everytime the command is run (Unity is an example) or straight up want to update to outdated version.

## Describe the solution you'd like
something like `wingetui.exe --update-all --auto-accept --uac` to be able to update all packages and excluding the blacklisted ones

**Comment by martinet101** [comment]
You can do that:
![image](https://user-images.githubusercontent.com/53119851/198371879-7c8ff803-95f7-4a67-bc12-ecd2777d4260.png)

**Comment by martinet101** [comment]
It will update both scoop and winget packages

**Comment by martinet101** [comment]
was this your request right?

**Comment by Bluscream** [comment]
> was this your request right?

Kind of. I need exactly that but in command line, so i can start the update from a batch script and with admin access so i dont need to accept any admin requests from installers

**Comment by martinet101** [comment]
You can also run wingetui as admin.

But I see what you want. Gonna add a button to update all with admin rights

**Comment by ppvnf** [comment]
I think this isn't exactly what OP is asking for, but IMO shortcut arguments would be a nice feature.
More info at https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/
For example a shortcut to -"C:Program Files\WingetUI.exe" -update-all would update all apps upon launching WingetUI (without the need to click on update all). What do you think? Maybe I should open another issue... if this is indeed possible

**Comment by Bluscream** [comment]
> For example a shortcut to -"C:\Program Files\WingetUI.exe" -update-all would update all apps upon launching WingetUI (without the need to click on update all). What do you think? Maybe I should open another issue... 

Yes, exactly that it what i was asking for. I hoped including the exact line of the update script im using made that clear in my initial post.
 
> @Bluscream, are you looking for a script like this https://github.com/Romanitho/Winget-AutoUpdate? 

That does indeed what i was asking for, im a little hesitant though because i dont want auto upfates happening in the background. I just want to be able to update everything without user interaction by executing one script. Im already using WingetUI to workaround a missing feature in Winget (the missing UI) and now im supposed to use a third software to workaround this missing feature in Winget *and* WingetUI. Also im using wingetui for most winget stuff except the full update so using it's blacklist that i already filled instead of yet another one that only accepts software IDs (what are those anyway, i dont see any id in wingetui) manually by changing a textfile just seems like a workaround for a workaround for a workaround.

Ideally winget itself would support blacklisting/pinning apps but microsoft made it clear in the issue i linked that theyre not interested so this is the currently best place for it.

If this feature doesnt get implemented i will just make a AutoHotkey script that starts wingetUI for me and simulates a click on update all. Thats gonna get messy af

**Comment by ppvnf** [comment]
> i dont want auto updates happening in the background

I think this discussion about Winget-AutoUpdate is a little bit off topic and you could probably get better support [there](https://github.com/Romanitho/Winget-AutoUpdate). I am not sure, but I believe you can set the update frequency to "never". It looks like there are a bunch of [install options](https://github.com/Romanitho/Winget-AutoUpdate#advanced-installation) that might be helpful to you. 

About the ID, you can see and even copy them if you open the info menu in WingetUI:

![Captura de tela 2022-10-27 205148](https://user-images.githubusercontent.com/73800734/198418524-5a6f199f-53d4-4aa9-ab00-3ca19d206684.png)

> If this feature doesnt get implemented i will just make a AutoHotkey script that starts wingetUI for me and simulates a click on update all. Thats gonna get messy af

I believe [shortcut arguments](https://github.com/martinet101/WingetUI/issues/340#issuecomment-1294038378) would be a good solution

**Comment by Bluscream** [comment]
> I believe [shortcut arguments](https://github.com/martinet101/WingetUI/issues/340#issuecomment-1294038378) would be a good solution

Thats exactly what i was asking for in the first  post

**Comment by marticliment** [comment]
This feature will come with WingetUI 1.6.1

**Comment by ppvnf** [comment]
Would this by any chance allow unattended package updates?

**Comment by marticliment** [comment]
Yes, this is a feature that will come in the next release. 

This setting can be enabled from the settings, and will allow WingetUI to start the update process after all the packages have been loaded

**Comment by marticliment** [comment]
P.D. The command-line parameter will be `--updateapps`
