### ISSUE TITLE
[BUG/ISSUE] flickering in the new settings menu

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#355]
Video: [2022-10-29 19-04-50.zip](https://github.com/martinet101/WingetUI/files/9894669/2022-10-29.19-04-50.zip)

![Captura de tela 2022-11-04 213721](https://user-images.githubusercontent.com/73800734/200092988-42394ee8-1f88-4e95-ae5e-55db4d5f04f6.png)

This seems to appear randomly (I did different actions in the picture and in the video) and it is not so common 

PS: I actually clicked remove scoop in the video, but OBSStudio didn't show it

By the way, the new menu is quite beautiful!

**Comment by ppvnf** [comment]
I believe 1.5.1 fixed this

**Comment by martinet101** [comment]
that must have been then the update to qt 6.4

**Comment by ppvnf** [comment]
I am facing this problem again on 1.5.2. Is this QT's fault?

**Comment by marticliment** [comment]
yes. it is an intermittent issue caused by the renderer.

I also faced this issue in other qt apps.
