### ISSUE TITLE
[FEATURE REQUEST] Json parsing (Scoop pkgs), enable search by description + improve info loading speed

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#397]
This would enable searching by package description and improve info menu loading speed. However, I am not sure this can be implemented since you said it's not not possible for Winget in https://github.com/martinet101/WingetUI/issues/223#issuecomment-1273551495. Is it the same case for Scoop?

This was implemented in scoop.sh official search engine, but I suppose it would be more difficult to do the same for a local app. 
Would something like this work? (sorry if it this a stupid idea)

Example:
1. Check which buckets are installed (`scoop bucket list`)
2. Download manifests (only if missing) from installed buckets and store them inside .wingetui folder (or another one)
3. Use checksum or time stamp to check for manifest updates and download newer versions of outdated manifests

**Comment by martinet101** [comment]
The issue with winget was that the time to download and read the manifests was enourmous.

I'll take a look at how would it woek with scoop

**Comment by ppvnf** [comment]
> The issue with winget was that the time to download and read the manifests was enourmous.

Only downloading missing manifests and using checksum or time stamp to check for manifest updates should reduce bandwidth utilization

**Comment by martinet101** [comment]
> > The issue with winget was that the time to download and read the manifests was enourmous.
> 
> Only downloading missing manifests and using checksum or time stamp to check for manifest updates should reduce bandwidth utilization

The issue is not bandwidth (that also it takes its time to download), but rather they come compressed and it took like 30 seconds to process the whole zip file

**Comment by ppvnf** [comment]
> The issue is not bandwidth (that also it takes its time to download), but rather they come compressed and it took like 30 seconds to process the whole zip file

Isn't it possible to individually download the JSON files?

**Comment by martinet101** [comment]
With winget not.

I have to see how scoop works

**Comment by martinet101** [comment]
Custom buckets is a possible thing, could you please open a new issue?

**Comment by ppvnf** [comment]
In this feature I asked for some sort of advanced search for Scoop
I have asked in https://github.com/marticliment/WingetUI/issues/223 for Winget
What about Chocolatey?

**Comment by marticliment** [comment]
I don't know, and honestly, I don't think advanced search will be available. 

However, i'm thinking on a way to also add the winget monikers and some other similr behaviours on scoop, so a similar approach could be done for chocolatey.

I will let you know when  have further progress on this

**Comment by ppvnf** [comment]
this feature request seems useless since there is https://github.com/marticliment/WingetUI/issues/473 and https://github.com/marticliment/WingetUI/issues/223
