### ISSUE TITLE
[FEATURE REQUEST] Ignore space when searching

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#402]
![Captura de tela 2022-11-05 135653](https://user-images.githubusercontent.com/73800734/200352208-2b7511b6-a2c4-4573-a2b0-e38747cebdbe.png)

This is only possible using Scoop Search website

**Comment by martinet101** [comment]
I don't think this will be possible. 

The search algorithm works by analyzing every single entry and checking for coincidences. 

The search algorithm is already bloated up, and adding more check for each item would mean more lag. 

I'll study that so if there's some kind of easy implementation, but i'm not sure if this won't break too much the search interface
