### ISSUE TITLE
[FEATURE REQUEST] Is there any reason not to install Scoop packages in parallel by default?

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#412]
I've seen https://github.com/martinet101/WingetUI/issues/61 and I get it that installing 2 apps from Winget could cause issues, but I don't see the same happening with Scoop packages since (I believe) Scoop doesn't support MSI installers

**Comment by martinet101** [comment]
Scoop has the `nonportable` bucket, which has some .exe installers that, at their own time, might require no other installs to be running.

However, a toggle for allowing scoop and winget apps separately to be installed in parallel could be a good idea

**Comment by ppvnf** [comment]
I think this was fixed
<img width="700" alt="Screenshot 2023-09-19 182720" src="https://github.com/marticliment/WingetUI/assets/73800734/27d2dddf-6ebb-4a0c-a8ec-7de5ef661969">
