### ISSUE TITLE
[FEATURE REQUEST] Setting for Hide Non-English Packages

### ISSUE THREAD

**Issue by hl2guide** [marticliment/WingetUI#471]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

On the "installed packages" tab I would to hide all packages that have non-English characters in their Package Names. 

## Describe the solution you'd like

Please add a setting for "hide non-English packages".

**Comment by martinet101** [comment]
I undertand what you want, but why would you want to do that?

**Comment by hl2guide** [comment]
> I undertand what you want, but why would you want to do that?

@martinet101 To clear up results that are irrelevant to me, since I don't speech the language (e.g. Chinese, Japanese).

**Comment by eidylon** [comment]
I think I would take this a step further, and rather than saying "hide all non-english packages", I'd say add an option in the settings which would allow you to hide all packages that are not in the OS you are running Windows in.

**Comment by marticliment** [comment]
You mean like showing only the installed packages?

**Comment by eidylon** [comment]
Actually, now that you bring that up, I'd say this new option should ONLY apply to the "discover"/search tab. The Updates and Installed tabs should always show all the packages you have installed/with updates (unless the user has manually hidden them). 

But in the search tab, there should be a checkbox that remembers its setting, (default would be checked I think) that would be something like this mockup... 

![image](https://user-images.githubusercontent.com/5951045/210397352-9b121cab-4760-424a-aad1-b19fefbb4865.png)

And then when searching for packages, if you have your OS configured to English it would only return packages in English, if your OS is in Chinese, it would only return packages in Chinese, etc.

**Comment by marticliment** [comment]
I see how the packages could be filtered between alphanumeric packages and non alphanumeric packages, but I don't see how the language of each package could be determined

**Comment by ppvnf** [comment]
> The package manifests in the repository don't carry the package/program language I guess?

I believe Scoop pkgs are English-only and Winget ones are most of the time available only in English (they do support other languages, but most of the time no one bothers translating them).

**Comment by eidylon** [comment]
Ah. Yeah, I guess if the manifests don't give any indication of what language the program is in, then this whole FR is dead in the water.

**Comment by ppvnf** [comment]
I think the best way to implement this idea would be to filter packages without ASCII characters https://web.fe.up.pt/~ee96100/projecto/Tabela%20ascii.htm.

**Comment by eidylon** [comment]
That would probably work for English users wanting to filter out Chinese or Russian or the like. 
But it wouldn't help any for Chinese users wanting to filter out Russian or Portuguese or the like.
Or French users wanting to filter out English and Italian.

**Comment by ppvnf** [comment]
> That would probably work for English users wanting to filter out Chinese or Russian or the like. But it wouldn't help any for Chinese users wanting to filter out Russian or Portuguese or the like. Or French users wanting to filter out English and Italian.

I don't think it's possible to filter between languages that use the same alphabet (since the package name is the only information available to figure out the package language). 

Also, Chinese is the only language besides English that has a large number of packages, but, even so, they are only a small fraction of English ones. Therefore, I am not sure Chinese people would want to filter out English packages. 

Theorically you could also create filters combining ASCII characters + another alphabet to filter out the others (for example ASCII + Russian to filter out Chinese, Korean, etc.). Again, I am not sure there's people interested on it.

**Comment by ppvnf** [comment]
the search option "ignore special characters" on the latest beta should enable what op proposed, right?

**Comment by marticliment** [comment]
yes, might actually make sense. It now ignored things like spaces and dashes
