### ISSUE TITLE
[BUG/ISSUE]  WingetUI 1.5.2 Beta is "failing" to install scoop packages from custom buckets

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#474]
The package in question is called duckstation-preview and it's in my bucket:

`scoop bucket add expert-parakeet https://github.com/ppvnf/expert-parakeet`

There are 2 problems if I try installing it using WingetUI: It is installed globally (and also locally) for some reason and the install gets stuck in WingetUI.

When uninstalling it using WingetUI I get this error (even though it was in fact uninstalled successfully in Scoop):
`ERROR 'duckstation-preview' isn't installed.`

Also, the package installed globally can't be removed by WingetUI (displays the error about using -g parameter - I believe it would also need admin privilege).

Scoop on CLI doesn't display any error/problem.

**EDIT**: that package (duckstation-preview) is now in games bucket:
`scoop bucket add games`

**Comment by ppvnf** [comment]
> **EDIT**: that package (duckstation-preview) is now in games bucket: `scoop bucket add games`

I've tested it again and the problem persists in the latest version

**Comment by marticliment** [comment]
Could you please try the latest head?

**Comment by ppvnf** [comment]
Install works, but uninstall fails

**Comment by ppvnf** [comment]
It doesn't exactly fails, but prompt gsudo UAC and then display error (but it is in fact uninstalled)
![Captura de tela 2022-12-27 163556](https://user-images.githubusercontent.com/73800734/209714534-82ccc758-5635-4b32-8a86-51d8b452adc5.png)
![Captura de tela 2022-12-27 163656](https://user-images.githubusercontent.com/73800734/209714571-44b13a9e-036b-40d5-8a56-06a8f47a8a1b.png)

**Comment by marticliment** [comment]
I see
