### ISSUE TITLE
[BUG/ISSUE] Glitch when building WingetUI 1.5.2 beta using Python 3.11.1

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#475]
I don't have the same problem if I use Python 3.10. Maybe there's something wrong with my Python install. Anyway, do you also encounter the same glitch using Python 3.11.1 or I just did something wrong?

![Captura de tela 2022-12-07 213902](https://user-images.githubusercontent.com/73800734/206328945-5be696f9-6361-4dc5-9f50-88e44d8e0dd1.png)

**Comment by martinet101** [comment]
qt 6.4.1 causes this.

For the moment, stick with at 6.4.0, i realized that yesterday while testing and im going to try to fix it.

**Comment by ppvnf** [comment]
I believe this was fixed on 1.5.2

**Comment by marticliment** [comment]
Oh, really? Version 1.5.2 still uses qt 6.4.0

**Comment by ppvnf** [comment]
Then I don't know if this could be considered a fix

**Comment by marticliment** [comment]
No, I don't think so

**Comment by marticliment** [comment]
qt 6.4.2 seems to have this issue fixed
