### ISSUE TITLE
[FEATURE REQUEST] More metadata support (Winget)

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#481]
PublisherUrl:
PublisherSupportUrl
PurchaseUrl
PrivacyUrl
CopyrightUrl

Example: https://github.com/microsoft/winget-pkgs/pull/91022/files
Full supported parameters:
https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

I am not sure if all the metadata above is relevant, maybe just up to the third is enough.
Winget also supports translating the metadata, but I'm not sure it's worth implementing it. I've not seen any in Portuguese and it seems few people bother translating overall. I've seen a few in Chinese though

Edit: there's also something called shortdescription and moniker, but I don't think it would be useful to WingetUI:

https://raw.githubusercontent.com/ppvnf/winget-pkgs/224680518424b9bf27e7e3905bff46edd38071c9/manifests/e/EaseUS/TodoPCTrans/13.2/EaseUS.TodoPCTrans.locale.en-US.yaml

Also, DocumentUrl seems useful, but feel people are aware of it when building manifests

**Comment by martinet101** [comment]
Hi @ppvnf,

do you know if those parameters are also available on scoop?

**Comment by ppvnf** [comment]
I don't think so. Maybe it's not worth adding it then

**Comment by marticliment** [comment]
After thinking about it and providing a URL to the manifest itself, I reckon there's no _real need_ for this feature, and seeing that it would collide with scoop/choco's capabilities, i would not implement that.
