### ISSUE TITLE
[FEATURE REQUEST] Release notes improvements (1.5.2 Beta)

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#484]
I've a few suggestions regarding Release Notes:

1. _ReleaseNotes_ and _ReleaseNotesUrl_ should be treated as different fields for both Winget and Scoop.
1.1. Winget **Release Notes** are in fact _ReleaseNotesUrl_ and _ReleaseNotes_ are not displayed by WingetUI.
1.2 Scoop _ReleaseNotesUrl_ could be `"checkver": { "url": " ", },`. Although it might be a little bit tricky if it is github (like WingetUI). Maybe use "autoupdate" url in this case. 

3. I think it would more accurate to say Unavailable instead of Unknown if this kind of metadata is missing

Related:
https://github.com/martinet101/WingetUI/issues/303
https://github.com/martinet101/WingetUI/issues/396
https://github.com/marticliment/WingetUI/issues/481

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/219977999-a1eccbb0-774d-40f3-ace0-e6fe0752109a.png)

**Comment by marticliment** [comment]
Done!

**Comment by ppvnf** [comment]
Firefox is showing only release notes, even tho manifest also contains release notes url
https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Mozilla/Firefox/111.0/Mozilla.Firefox.locale.en-US.yaml
<img width="494" alt="Screenshot 2023-03-23 013228" src="https://user-images.githubusercontent.com/73800734/227068942-34c836f3-03b1-402a-9efc-97d8c2b87a57.png">

**Comment by marticliment** [comment]
Yes, the release notes url was removed in favour of release notes

**Comment by marticliment** [comment]
Could you please open a new issue to re-add release notes url?
