### ISSUE TITLE
[BUG/ISSUE] Missing some keys

### ISSUE THREAD

**Issue by panther7** [marticliment/WingetUI#487]
- [x] Missing DisableLangAutoUpdater in settings. If i want test local translation, then always is downloaded from github:
https://github.com/martinet101/WingetUI/blob/d9d4deff8d5efaad3af3610aa7e2568d61ef2392/wingetui/tools.py#L355
https://github.com/martinet101/WingetUI/blob/d9d4deff8d5efaad3af3610aa7e2568d61ef2392/wingetui/tools.py#L402

 - [x] ~~Missing UseSystemWinget:~~
https://github.com/martinet101/WingetUI/blob/d9d4deff8d5efaad3af3610aa7e2568d61ef2392/wingetui/wingetHelpers.py#L10

 - [x] Missing translation key:
https://github.com/martinet101/WingetUI/blob/d9d4deff8d5efaad3af3610aa7e2568d61ef2392/wingetui/uiSections.py#L70

 - [x] Missing translation key ("{0} updates were found"):
https://github.com/martinet101/WingetUI/blob/d9d4deff8d5efaad3af3610aa7e2568d61ef2392/wingetui/uiSections.py#L1043

 - [x] Missing translation keys:
https://github.com/martinet101/WingetUI/blob/d9d4deff8d5efaad3af3610aa7e2568d61ef2392/wingetui/uiSections.py#L1826

 - [x] Missing translation key:
https://github.com/martinet101/WingetUI/blob/d9d4deff8d5efaad3af3610aa7e2568d61ef2392/wingetui/__init__.py#L285

 - [x] Missing `{0}` for format:
https://github.com/martinet101/WingetUI/blob/d9d4deff8d5efaad3af3610aa7e2568d61ef2392/wingetui/storeEngine.py#L412

 - [x] Plurar issue:
   - 0 = `0 package was found`, example for czech: `Nenalezen žádný balíček`
   - 1 = `1 packages were found` => `Nalezen jeden balíček`
   - \>1 = `5 packages were found` => `Nalezeno 5 balíčků`
   - or for all like `Found packages: {0}` => `Počet nalezených balíčků: {0}`
        https://github.com/martinet101/WingetUI/blob/15275db8d2ca1ef6b010467fbd02f336946be194/wingetui/uiSections.py#L1589

---

Translation(s) is not exists inside project:
- [x] ~~`WingetUI version {0}`~~ This one exsists:  ![image](https://user-images.githubusercontent.com/53119851/208128232-45f0f798-cb0c-4c3e-8dd6-a3b8dbf78bb7.png)
- [x] `Package managers preferences`
- [x] `Package manager specific preferences`
- [x] `Origin`
- [x] `Search for packages on Winget and Scoop`
- [x] `{} Uninstallation` -> `{0} Uninstallation`

Missing translations:
- [x] `{0} is disabled` - {0} = Scoop|Winget
- [x] `Export log`
- [x] `Select package file`
- [x] `Experimental settings and developer options`
- [x] `Beta features and other options that shouldn't be touched`
- [x] `Yes`
- [x] `No`
- [x] ~~`Unlicense`~~ This is the literal name of the license, and i recvkon it should be left as it is
- [x] `Last updated:`
- [x] `Release notes:`
- [x] `Text file` - filename for export log
- [ ] ContextMenu, probably need some translation for PySide
  ![2022-12-22 13 51 55](https://user-images.githubusercontent.com/3808250/209138516-39cf875f-07b5-4c23-8d21-b868840d4e88.png)

**Comment by panther7** [comment]
@martinet101

**Comment by martinet101** [comment]
> Missing UseSystemWinget

This one was done in purpose, since system winget is almost guarnteed to be broken, and manual tuning is needed for it to work.
Hence why is winget bundled witht the app itself

**Comment by martinet101** [comment]
Hi @panther7,

regarding the missing keys in general, i'm aware of that, but I try to post them all at once some time before releasing so translatirs don't have to be translating two or three keys per week.

**Comment by panther7** [comment]
So, if "Translation(s) is not exists inside project" then i can not translate them, because i do not known their context.

Please, check "all" my points in issue.

**Comment by martinet101** [comment]
Fixed!

**Comment by panther7** [comment]
Update issue

@martinet101

**Comment by panther7** [comment]
Update issue

**Comment by martinet101** [comment]
> * ContextMenu, probably need some translation for PySide

I don't think those ones can be translated

**Comment by martinet101** [comment]
> [ ] Plurar issue:
> 
> * 0 = `0 package was found`, example for czech: `Nenalezen žádný balíček`
> * 1 = `1 packages were found` => `Nalezen jeden balíček`
> * >1 = `5 packages were found` => `Nalezeno 5 balíčků`
> * or for all like `Found packages: {0}` => `Počet nalezených balíčků: {0}`

I don't understand this part

**Comment by panther7** [comment]
> > * ContextMenu, probably need some translation for PySide
> 
> I don't think those ones can be translated. They are part of the Qt's native context menus

I think, that Qt/PySide have some solution for translation "native" elemenets

> > [ ] Plurar issue:
> > 
> > * 0 = `0 package was found`, example for czech: `Nenalezen žádný balíček`
> > * 1 = `1 packages were found` => `Nalezen jeden balíček`
> > * > 1 = `5 packages were found` => `Nalezeno 5 balíčků`
> > * or for all like `Found packages: {0}` => `Počet nalezených balíčků: {0}`
> 
> I don't understand this part

You have translation ONLY for "not one" and "other number", see in code: https://github.com/martinet101/WingetUI/blob/15275db8d2ca1ef6b010467fbd02f336946be194/wingetui/uiSections.py#L1589

But, some languages have plurar for zero (0), one (1), five (5),... (check my examples). If we ignore plurar isses over languages, I can translate `{0} packages were found` and `{0} packages was found` like `Found packages: {0}` that it is neutral.

**Comment by panther7** [comment]
Update issue

**Comment by martinet101** [comment]
> translate `{0} packages were found` and `{0} packages was found` like `Found packages: {0}` that it is neutral

I think this is the best solution for this particular issue. If you face this issue in some other string and you see that this neutral solution could be applied, feel free to do it without posting/reporting.



> I think, that Qt/PySide have some solution for translation "native" elemenets
> 
> > >

I'll further look at this

**Comment by panther7** [comment]
> - ~`Unlicense`~ This is the literal name of the license, and i recvkon it should be left as it is

Is not "truth"... `MIT License` is translated...
See:

https://github.com/marticliment/WingetUI/blob/936490e42b53dfb653521017ab431004655d0dba/wingetui/uiSections.py#L2034-L2035

**Comment by marticliment** [comment]
but since the fixed name is MIT, the _license_ part can be translated. In catalan it would look like _Llicència MIT_

**Comment by marticliment** [comment]
Done!

(The contxet menu will be worked on in the future)

**Comment by panther7** [comment]
* all keys in tolgee translated
* updated this issue
* contextmenu moved to separate issue #527

**Comment by marticliment** [comment]
Done!
