### ISSUE TITLE
[FEATURE REQUEST] Add context menu option to browse to scoop directory

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#489]
![Captura de tela 2022-12-13 071545](https://user-images.githubusercontent.com/73800734/207290848-dcf6c026-446b-4dbb-ae44-40746c8e65d8.png)

The new option would open _C:\Users\USERNAME\scoop\apps\duckstation\current_. 

I don't know if it would be possible to have this option in the case of global packages, however. 

Also, I am not sure how to handle Scoop installed on a custom directory.

Maybe have this option on the Update section as well.

**Comment by marticliment** [comment]
Honestly, after looking carefully at this, I think it would colide with other package managers, since they don't provide this functionality, and it wouldn't also work neither with global nor with custom scoop installation paths
