### ISSUE TITLE
Multiple Package

### ISSUE THREAD

**Issue by ifelixculpa** [marticliment/WingetUI#498]
Hi this is a gem of a program but how can i install various programs at a single time ?

**Comment by ppvnf** [comment]
Hello, it is not possible yet (see https://github.com/martinet101/WingetUI/issues/174). However, you can export/import multiple packages

**Comment by martinet101** [comment]
If by at the same time you mean if you can stack program installations, yes, you can queue any install/update/uninstall and it will be queued until previous jobs finish.

If by at the same time you mean importing, this is what @ppvnf said. You can export lists of already installed packages, and import that list on a newer machine to get the same lit of packages installed.

**Comment by ifelixculpa** [comment]
> Hello, it is not possible yet to selected multiple packages to be installed at the same time (see #174). However, you can export/import multiple packages
> 
> Edit: as [martinet101](https://github.com/martinet101) said, you can queue any install/update/uninstall and it will be queued until previous jobs finish

yes sir thankyou thats what i ment selecting and installing multiple programs at once....hope the best for this software , what a wonderwork this is

thankyou so much for this @martinet101 sir
