### ISSUE TITLE
Eliminate unused translation keys (Tolgee)

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#504]
Would it be possible to implement a scan to check if there are unused Tolgee translation strings?

https://tolgee.io/blog/taking-localization-to-i18next-level#additional-tools-for-i18next
https://www.i18next.com/how-to/extracting-translations

**Comment by martinet101** [comment]
I suppose the files can be analyzed for any occurrences of the string...

**Comment by ppvnf** [comment]
@panther7 sorry for tagging you. Did you use some script to find missing keys in https://github.com/martinet101/WingetUI/issues/487? If so I believe it would be possible to apply it for this issue as well. Thanks!

**Comment by martinet101** [comment]
no need to worry, I'm already working on it and it will work

**Comment by marticliment** [comment]
The unused keye have been removed from the repostory and from Tolgee.
Also, there's a new utility that anlyses the whole code to detect unused tolgee keys
