### ISSUE TITLE
Feature Request: Update selected packages with administrator privileges

### ISSUE THREAD

**Issue by AbitFishy** [marticliment/WingetUI#520]
Since most windows program installers need administrator privilege to access the "Program Files" folder, when updating a selection of packages, it would be nice to give administrator privileges just once, instead of the UAC prompt opening for program.

If I run the wingetUI as administrator, I can use the existing "Update selected packages", but the program warns me on opening that it's not designed to run as admin and that Swoop stuff won't work correctly.

So I propose a "Update selected packages with administrator privileges" or maybe a "Update selected packages with administrator privileges if needed" option.

**Comment by martinet101** [comment]
the only option right now is to run wingetui as administrator.

however, I'll further study that.

**Comment by ALERTua** [comment]
You could just `gsudo cache on -d duration -p pid`, and `gsudo -k` before exit. It seems secure.
```
gsudo cache {on | off} [-p {pid}] [-d {time}]   Start/stop a gsudo cache session.
  -p | --pid {pid}            Specify which process can use the cache. (Use 0 for any, Default=caller pid)
  -d | --duration {hh:mm:ss}  Max time the cache can stay idle before closing.
                              Use '-1' to keep open until logoff (or `cache off`, or `-k`).
                              Current idle duration is: Infinite

gsudo -k                       Stops all active cache sessions.
```

**Comment by marticliment** [comment]
Yes, this seems as a good idea

**Comment by marticliment** [comment]
From next version and beyond, users will have the ability to choose between some options regarding how administrator rights are treated.
![image](https://user-images.githubusercontent.com/53119851/232163195-57c83768-60a1-4069-bed2-c37b422f8466.png)
