### ISSUE TITLE
[FEATURE REQUEST] invert checkboxes

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#523]
![Captura de tela 2022-12-23 182823](https://user-images.githubusercontent.com/73800734/209408097-7784407d-a7ba-46f9-ab1b-5b55721d1ea8.png)
Example from https://github.com/Klocman/Bulk-Crap-Uninstaller

Tbh I am unsure if this feature is actually useful (so feel free to ignore it), but I've created an example so you can easily understand how it can be used (although it's possible to achieve the same result without this feature):

<details>

![Captura de tela 2022-12-23 184837](https://user-images.githubusercontent.com/73800734/209408341-9292ee92-7ab4-45fb-913f-304f581a1c96.png)
![Captura de tela 2022-12-23 184915](https://user-images.githubusercontent.com/73800734/209408344-28eff78f-9997-45fe-a458-efbcbce943d8.png)
![Captura de tela 2022-12-23 184945](https://user-images.githubusercontent.com/73800734/209408346-0353c5a2-587b-44b6-934b-b32522a8dd7a.png)
</details>

**Comment by martinet101** [comment]
I thought on adding it, but i didn't thought of a scenario where it would be useful.

**Comment by ppvnf** [comment]
> I thought on adding it, but i didn't thought of a scenario where it would be useful.

I don't think it's actually useful if you think before acting. For example, in the example above you could unselect everything and select just the packages you want instead of inverting the selection
