### ISSUE TITLE
[BUG/ISSUE] Show info glitch when alternating between Winget and Scoop packages

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#533]
For example:

1- Show info of main/win32yank 
2- Quickly click show info of Winamp.Winamp
3 - It will then briefly show info of win32yank, then the info Winamp.Winamp and maybe win32yank again afterwards

A possible fix would be to kill the PShell module when closing the info menu

Video
https://user-images.githubusercontent.com/73800734/209722466-564e1880-70ce-43c9-ad90-a2e775e5e092.mp4

**Comment by marticliment** [comment]
Yes, or simply giving an identifier to each program, and then, before loading more info, check if the indetifier is still the same.
