### ISSUE TITLE
[FEATURE REQUEST] Improve systray context menu 

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#535]
- [X] I believe `No updates are available` would be better if `self.availableUpdates == 0`:

![Captura de tela 2022-12-27 213144](https://user-images.githubusercontent.com/73800734/209742828-9e0bdcba-51cb-4931-97e1-4cde0c2658b6.png)

- [x] Grey out/disable `No updates are available` (I've no idea how to do that):

![Captura de tela 2022-12-27 223508](https://user-images.githubusercontent.com/73800734/209744017-b27b64f8-d707-4e1e-b228-fca49d95836d.png)

Related to https://github.com/marticliment/WingetUI/issues/446 and https://github.com/marticliment/WingetUI/issues/447

**Comment by ppvnf** [comment]
Maybe I should've used the bug label

**Comment by marticliment** [comment]
Done!
![image](https://user-images.githubusercontent.com/53119851/209790387-9f1be5fa-eeb1-4e40-930c-8a1f59d9960b.png)

**Comment by ppvnf** [comment]
Thanks! It will be possible to translate the keys "1 update was found" and "No updates are available" after a new version is released, right?

**Comment by marticliment** [comment]
it will be possible when I add the key in tolgee, which I'll probably do soon
