### ISSUE TITLE
[FEATURE REQUEST] Show installer download size

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#537]
I suppose it's possible to do that after seeing https://stackoverflow.com/questions/55226378/how-can-i-get-the-file-size-from-a-link-without-downloading-it-in-python, but I have no idea which method is the best. Also, I'm worried this might slow down WingetUI since you would need to get the download link first...

**Comment by rumplin** [comment]
Maybe this will give more context/info: https://forum.qt.io/topic/71971/qnetworkaccessmanager-get-file-size-before-download/11

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/232144390-15851390-31bc-4197-baa2-665bfde40895.png)
