### ISSUE TITLE
[BUG/ISSUE] don't boot and stuck at 'running daemon'

### ISSUE THREAD

**Issue by alfus5** [marticliment/WingetUI#552]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**

- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**

## Describe the bug
WingetUI don't boot even after 20 min and get stuck at "runing daemon"

## To Reproduce
Steps to reproduce the behaviour:
1. Run WingetUI
2. Wait until it show "running daemon" (it can be different because i use it in french)
3. It don't continue to load

## Expected behaviour
I expected WingetUI to boot even after a while but it' not happening ( it's been 20 min I'm waiting for it)

## Screenshots
![image](https://user-images.githubusercontent.com/63202698/209988931-79176bdf-5aaa-4c6b-8490-89abab5c0c80.png)

**Comment by ppvnf** [comment]
Are you running version 1.5.3?

If not you can download it in https://github.com/marticliment/WingetUI/releases/download/1.5.3/WingetUI.Installer.exe

**Comment by alfus5** [comment]
I'm running the version 1.5.3.

After a reboot the issue solved itself
