### ISSUE TITLE
[BUG/ISSUE] I didn't translate Dutch

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#554]
For some unknown reason I appear as Dutch translator in the about section

![Captura de tela 2022-12-29 201245](https://user-images.githubusercontent.com/73800734/210019926-438fdfdb-07b5-46a3-ba7c-7f2878550bf9.png)

**Comment by marticliment** [comment]
Yes, I noticed that, but I don't understand why.

However, the last PR that panther7 pushed fixed this issue.

**Comment by Stephan-P** [comment]
I can explain: this 1st string in tolgee is unclear. It says to ADD your names. And so I added my name to the two already mentioned in the original text. Also note that it is unclear if this string about contributors to the app in general or the translation in particular.
