### ISSUE TITLE
[FEATURE REQUEST] Identify GoG packages

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#555]
I've noticed that GoG games IDs have a certain pattern. It's certainly more complex than https://github.com/marticliment/WingetUI/issues/202, so I don't think I have the skill to implement it myself (I'm willing to try, however):

![Captura de tela 2022-12-29 204627](https://user-images.githubusercontent.com/73800734/210021803-bc8a080f-f3d0-4b18-9334-7da9ea887553.png)

In the image above only the first two packages are from GoG so it will be harder than just spliting _is1. It would also need to find if GOG is present on the ID or count if there are 10 numbers on it (I believe it's possible using https://docs.python.org/3/library/re.html).

Also, I've no idea which icon could be used. Is this a complete waste of time?

What do you think, @marticliment? 

Edit: about the icon, I don't think there's any problem using the GoG logo since their games are DRM-Free. Also, I think any icon from https://icons8.com.br/icons/set/gog could be used as a placeholder

**Comment by marticliment** [comment]
I think, again it is like the steam ones.
I guess steam ones were easier, and steam is much more popular than GoG.
I honestly think that if this is much complicated and involves regex, it won't be a big deal to just leave them as local pc.
