### ISSUE TITLE
[BUG/ISSUE] Blacklisting app won't refresh count of updates

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#559]
Available updates shouldn't be shown as 1

![blacklist](https://user-images.githubusercontent.com/73800734/210026822-f239f101-502a-49a3-804e-2abe312ec3bd.png)

**Comment by marticliment** [comment]
If yiu refresh your list, the number goes back to zero, right?

**Comment by ppvnf** [comment]
yes, but shouldn't it be refreshed automatically like when you blacklist?
The way it is now I think some user could, for example, blacklist a package, close WingetUI window and then use the systray context menu to update all packages

**Comment by marticliment** [comment]
It should, but i have my doubts it really does

**Comment by ppvnf** [comment]
Instead of refreshing the update list after blacklisting another solution would be to decrease the amount of available updates by the number of recently blacklisted packages

**Comment by marticliment** [comment]
No, i did not meant refreshing the list itself, but rather the count of updates. There's a function that does that, i just need to call it after the blacklist function

**Comment by marticliment** [comment]
Whops, i was supposed to tag #599
