### ISSUE TITLE
will there be Chocolatey in WingetUI

### ISSUE THREAD

**Issue by candrapersada** [marticliment/WingetUI#56]
will there be [Chocolatey](https://community.chocolatey.org/packages)?

**Comment by martinet101** [comment]
It was my plan, but i'm waiting to have all pending things.

Also, Chocolatey is based on admin rights, so it needs to be studied correctly and can't be made in a rush

**Comment by marticliment** [comment]
It seems like it could work...
![image](https://user-images.githubusercontent.com/53119851/212130618-20d1433b-fb5f-4b44-a58d-56ec8335c850.png)


(It is still not 100% sure that it will come to WingetUI, but latest commits regarding choco can be found on the branch chocolatey-testing)

**Comment by marticliment** [comment]
Chocolatey support is already on the main branch.

I'll release a beta soon so you can test it out!

**Comment by candrapersada** [comment]
is there any information how to set chocolatey path environment variable in WingetUI?

**Comment by adripo** [comment]
@marticliment  I am getting different errors when installing packages from Chocolatey.
How did you managed the Admin rights? Shouldn't all installations for Chocolatey be executed as Admin?

If you want to check one package that gives error without admin you can try for example `amd-ryzen-master`.

**Comment by adripo** [comment]
Logs:

```

Chocolatey v1.2.1
Chocolatey detected you are not running from an elevated command shell
(cmd/powershell).
You may experience errors - many functions/packages
require admin rights. Only advanced users should run choco w/out an
elevated shell. When you open the command shell, you should ensure
that you do so with "Run as Administrator" selected. If you are
attempting to use Chocolatey in a non-administrator setting, you
must select a different location other than the default install
location. See
https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
for details.
For the question below, you have 20 seconds to make a selection.
Do you want to continue?([Y]es/[N]o):
Timeout or your choice of '' is not a valid selection.
 ```

**Comment by marticliment** [comment]
Those logs are expected.
Chocolatey is ran from a location where admin rights are not required, so this part shouldn't be the issue.
The timeout just defaults to the [Y] action (I am working on how to remove it)
Are there more logs?

**Comment by ylefebvre** [comment]
I just installed wingetUI for the first time, bring most interested by the Chocolatey integration. I was already using ChocolateyUI. Now, while it was able to load a list of apps to install, the Software Updates section and Installed Packages section are not showing me the apps that I've installed with Chocolatey. Am I doing something wrong? Do I need to uninstall from Chocolatey and reinstall with wingetUI to be able to see apps in these sections?

**Comment by ylefebvre** [comment]
I think I found my own answer. I set to use the system chocolatey and then all of my installed applications showed up!

**Comment by adripo** [comment]
@marticliment opened #671

**Comment by roman6078** [comment]
https://community.chocolatey.org/packages?q=wingetui will it become available there?

**Comment by marticliment** [comment]
@roman6078 i plan to

**Comment by shumafuk** [comment]
> Logs:
> 
> ```
> 
> Chocolatey v1.2.1
> Chocolatey detected you are not running from an elevated command shell
> (cmd/powershell).
> You may experience errors - many functions/packages
> require admin rights. Only advanced users should run choco w/out an
> elevated shell. When you open the command shell, you should ensure
> that you do so with "Run as Administrator" selected. If you are
> attempting to use Chocolatey in a non-administrator setting, you
> must select a different location other than the default install
> location. See
> https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
> for details.
> For the question below, you have 20 seconds to make a selection.
> Do you want to continue?([Y]es/[N]o):
> Timeout or your choice of '' is not a valid selection.
> ```

I have same issue. I can browse packages of choco in WingetUI, I have allowed choco in settings, however when I write "choco" in cmd, it's not there: "The term 'choco' is not recognized as the name of a cmdlet...." Should I install chocolatey outside of WingetUI?

**Comment by marticliment** [comment]
chocolatey is not added to path, you will need to add chocolatey manually to path

**Comment by shumafuk** [comment]
What path?

**Comment by marticliment** [comment]
You need to add to the system environment variable path the path where chocolatey is installed (`C:\Users\yoursername\AppData\Local\Programs\WingetUI\choco-cli`)

Se how to add a path to windows here: https://www.mathworks.com/matlabcentral/answers/94933-how-do-i-edit-my-system-path-in-windows

**Comment by candrapersada** [comment]
is there any information how to set chocolatey path environment variable in WingetUI wiki or readme?
https://github.com/marticliment/WingetUI/issues/56#issuecomment-1407518563

**Comment by marticliment** [comment]
No, because the idea is not to actually use wingetui's chocolatey install as a machine-wide installation.
