### ISSUE TITLE
[BUG/ISSUE] Software Updates wrong after refresh

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#567]
WingetUI version 1.5.3

- WingetUI finds packages to update
- I give the command to update the packages
- The packages are successfully updated (interactively)
- Refresh the tab Software Updates
- Presto: the packages that just have been updated are listed again

![image](https://user-images.githubusercontent.com/10008599/210138467-02341717-7bec-4ac7-bf28-efa416ff5c79.png)

![image](https://user-images.githubusercontent.com/10008599/210138483-3d6c06f9-7305-48cd-b639-5d95846365ad.png)

**Comment by marticliment** [comment]
This is a known issue with winget. Please right-click them -> ignore this packages.

This is winget's fault and is up to them to fix that

**Comment by Stephan-P** [comment]
Ooooh, I wasn't aware of this. My apologies. 
I fear there will be many reports like this.
Is there a way to warn new users of this existing issue?

**Comment by marticliment** [comment]
Not really, but if you are using wingetui you have probably used winget, which shows the same issue...
