### ISSUE TITLE
[FEATURE REQUEST] Button to filter source

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#584]
## Is your feature request related to a problem? Please describe.

I think it would be useful to have a button that allows only a certain source to be shown (Scoop, Winget, Local PC, etc.)

## Describe the solution you'd like

Examples:

1. In the discovery section, selecting the option to filter Winget (possibly using a combo box) would hide all pkgs from Scoop (instead of having to go to settings and disable Scoop). EDIT: maybe selecting the scoop bucket would be useful as well.

2. For the update section I thought about having an option to update all Scoop / all Winget packages separately, but I personally just update everything regardless, so I don't think I would use it.

3. In the uninstall section it would be useful for seeing all packages from MSStore or from a specific bucket.

The button could be similar to https://github.com/marticliment/WingetUI/issues/223 and https://github.com/marticliment/WingetUI/issues/339

Edit:
If you think it is useful/easy to implement (I'm not sure actually) this button could also enable/disable case-sensitive search
Maybe you could also include instant search and show unknow version (update section) inside of it as well to optimize space utilization

Icon suggestion (a simple arrow pointing down, not necessarily this one):

<details>

![long-arrow-down](https://user-images.githubusercontent.com/73800734/210634183-00035687-7c8e-490d-9f7a-be01bf5dc621.png)

</details>

**Comment by marticliment** [comment]
you can just sort by source. it should do the job, shouldn't it?

when winget 1.4 gets released with tags, I was planning some kind of refine results section.

**Comment by ppvnf** [comment]
Yes, it probably makes sense to wait for Winget 1.4.  Sorting by source does the job most of the time, but being able to filter out a certain source would be cleaner/easier for the user and it would allow sorting packages by name/id/version

**Comment by ppvnf** [comment]
I guess this also depends on https://github.com/marticliment/WingetUI/issues/712

**Comment by ppvnf** [comment]
I think this feature is more important now that so many package managers are supported

**Comment by neoOpus** [comment]
I concur, this feature is more important than many other requests.

**Comment by ppvnf** [comment]
it looks pretty good, just a small suggestion. What do you think about opening the panel on the right side since the button is on that side?

**Comment by marticliment** [comment]
Well, I did put it on the left side because panels similar to it tend to show on the left side of the window:
 - Any online website (amazon for example) show their filtering options on a panel positioned on the left.
 - Windows explorer has a similar layout: sub-pane on the left and main window on the right.
It made sense for me to show it on the left side. I think otherwise it would be a little bit counter-intuitive

**Comment by olee** [comment]
It looks like it is not possible to filter out "Local PC" right now - would it be possible to add that to the filter?

**Comment by marticliment** [comment]
> It looks like it is not possible to filter out "Local PC" right now - would it be possible to add that to the filter?

They are currently tied to Winget, since Winget is the Package Manager in change of loading them.

However, I will take this suggestion into account

**Comment by ppvnf** [comment]
how about having an expandable submenu like this
![Screenshot 2024-01-14 134840](https://github.com/marticliment/WingetUI/assets/73800734/70a8a65d-b8a7-4a52-9f50-3d74f555e551)

**Comment by marticliment** [comment]
Yes, this could be it.
