### ISSUE TITLE
[BUG/ISSUE] Translation list

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#587]
![Captura de tela 2023-01-04 063732](https://user-images.githubusercontent.com/73800734/210526432-8a64538c-634c-4000-b877-177e7815c309.png)

The languages of the first and last translators aren't properly identified. 

Besides, i've found a few translators missing the link to their Github pages (I don't know if you should mention them, contact them or add yourself their usernames to Tolgee):

https://github.com/BUGProtectionAssociation - Simplified Chinese
https://github.com/gidano - Hungarian
https://github.com/aaronliu0130 - Simplified Chinese and Traditional Chinese
https://github.com/Satanarious - Hindi
https://github.com/maicol07 - Italian
https://github.com/MisterEvans78 - French
https://github.com/sklart - Russian

Maybe (found Googling):
https://github.com/sho9029 - Japanese
https://github.com/JanecekPetr - Czech
https://github.com/krokodilerian - Bulgarian
https://github.com/cololi - Simplified Chinese
https://github.com/daVinci13 - Serbian 
https://github.com/nilavra - Bangla
https://github.com/Kryeker - Ukranian
https://github.com/yrctw - Traditional Chinese
https://github.com/henoya - Japanese

Edit: Arabic has two translators, but I think they refer to the same person:

![Captura de tela 2023-01-04 234409](https://user-images.githubusercontent.com/73800734/210689969-d21b06cc-a8c7-4ef1-ae4e-ac0cbcc86565.png)

Also, how about adding an entry in the Wiki reminding translators to add their names

**Comment by Stephan-P** [comment]
typo in description: comma is not in coma

Also, best to add specific note to description NOT to copy the names from the English team

**Comment by marticliment** [comment]
The key can't be changed, because it would break compatiblity with already existing wingetui versions.

However, i'll add a comment to the comments section explaining better this section

**Comment by marticliment** [comment]
I have fixed the missing languages and removed the duplicate arabic ccredit, but regarding the untagged translators, i think is their choice to add or not the @ before their username
