### ISSUE TITLE
[BUG/ISSUE] Missing translation

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#588]
I've noticed in the "beta" version that differently from https://github.com/marticliment/WingetUI/pull/561/files and https://github.com/marticliment/WingetUI/pull/576/files and https://github.com/marticliment/WingetUI/pull/595/files that haven't been added to Tolgee yet, the strings below are unstranslated despite being added to Tolgee (with semicolon). I believe you could solve this problem by also adding these strings without semicolon to Tolgee:

![Captura de tela 2023-01-04 085539](https://user-images.githubusercontent.com/73800734/210556394-37020c9d-23e5-4ed6-976d-c9526673561e.png)
![Captura de tela 2023-01-04 094403](https://user-images.githubusercontent.com/73800734/210557777-30708fde-e3ba-45c0-99c5-1381430c3ce9.png)
![Captura de tela 2023-01-04 094557](https://user-images.githubusercontent.com/73800734/210558038-6024a0eb-0f58-49f4-8c3d-560e632a67ea.png)

**Comment by marticliment** [comment]
Yes, i'll fix that
