### ISSUE TITLE
[BUG/ISSUE] Description is not fully shown if it has more than 1§ (Winget)

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#590]
I was thinking about commenting on https://github.com/marticliment/WingetUI/issues/481 about the missing manifest parameter in Winget called "ShortDescription", but I don't think it's necessary since you have regular "Description". However, while doing that I've noticed that description isn't completely displayed if it has more than 1§.

See https://github.com/microsoft/winget-pkgs/blob/master/manifests/e/EaseUS/TodoBackup/2022.1/EaseUS.TodoBackup.locale.en-US.yaml

Screenshot:

![Captura de tela 2023-01-04 162321](https://user-images.githubusercontent.com/73800734/210633262-2b8e8047-1cbd-4b7a-8e9f-5c9016268c94.png)

**Comment by marticliment** [comment]
Thanks to the update to Winget 1.4, and the changes done on `5d177fc`, it now works as expected:
![image](https://user-images.githubusercontent.com/53119851/214647235-ad8067ce-a4e4-4b5c-b95c-a63fb1198f35.png)
