### ISSUE TITLE
[BUG/ISSUE] Show info menu isn't able to uninstall packages

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#599]
Currently show info menu is able to install/update packages:

<details>

![Captura de tela 2023-01-05 190315](https://user-images.githubusercontent.com/73800734/210970559-e86aafb8-2aec-45a9-9754-716c193ace4b.png)
![Captura de tela 2023-01-05 190257](https://user-images.githubusercontent.com/73800734/210970570-3667feb0-61ac-4161-8e41-1d9bf7fcbb87.png)

</details>

However, in the uninstall section it shows install instead of the expected uninstall:

<details>

![Captura de tela 2023-01-06 062442](https://user-images.githubusercontent.com/73800734/210971457-56b8943c-4db9-404b-8604-bd2165c62de6.png)
![Captura de tela 2023-01-05 190315](https://user-images.githubusercontent.com/73800734/210971138-bb3d1ca2-2957-4ad5-b0f1-15a2449ed94b.png)

</details>

**Comment by marticliment** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/53119851/221288977-911d94eb-939d-4e21-9145-1420f41baed0.png)
