### ISSUE TITLE
[BUG/ISSUE] Replace updater by the Winget/Scoop fallback

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#601]
Discussed in https://github.com/marticliment/WingetUI/discussions/452

Also, maybe Scoop needs `CloseApplications=force` to be able to uninstall/upgrade? 
Edit: I think Scoop ignores the kill WingetUI command. See https://github.com/ScoopInstaller/Scoop/issues/3947

![Captura de tela 2023-01-06 082820](https://user-images.githubusercontent.com/73800734/211098370-f56b02fa-f93b-47dd-9076-979e6c424cd1.png)

**Comment by marticliment** [comment]
Is not that scoop ignores the command, but I reckon the installer is never launched from scoop itself, since scoop checks if the app is running.

Do you think is a good idea to open an issue on the scoop repo to add a parameter that prevents this checks from happening?

**Comment by ppvnf** [comment]
yes, I am not sure either if https://github.com/ScoopInstaller/Scoop/issues/3947 is the same issue, so it might be worth it to open a new one

**Comment by marticliment** [comment]
It would also work, tbh. Not the approach of skipping the check, but rather their (better than mine) approach to fixing this issue

**Comment by marticliment** [comment]
The built-in updater has been fixed, so having this issue open makes no sense anymore
