### ISSUE TITLE
[BUG/ISSUE] Translations percentage for language is not updated in other languages

### ISSUE THREAD

**Issue by KamilZielinski** [marticliment/WingetUI#604]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Recently I updated translations in Tolgee for Polish language from 38% to 99%. The app downloaded the newest translation from Github but the percentage didn't update in all places.
When I checked the app in English, translation for Polish language in app settings seems to be 38%. After switching to Polish, languages list shows that Polish is translated in 99% (which is correct).
I checked that in Czech language as well, still shows 38% instead of 99%.
I reinstalled the app but it didn't help.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to settings, set language to English
2. Check languages list, look for Polish and check its translation percentage - it's 38%
3. Switch to Polish language
4. repeat step 2 but this time it's 99%

## Expected behaviour
Language translation percentage is the same in all languages

## Screenshots
![language](https://user-images.githubusercontent.com/6136794/211171556-d2608aad-3ee7-4163-8553-1d8a5bccecf3.png)

**Comment by marticliment** [comment]
This is an intended issue, since there's no point on updating each single language if the user does not use them.

Once the user changes its lang, the percentage will be updated
