### ISSUE TITLE
[BUG/ISSUE] Edge apps are categorized as Microsoft Store apps

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#607]
WingetUI version 1.5.3

Maybe this cannot be solved in WingetUI, but I noticed that websites that i've installed as [Edge Apps](https://pureinfotech.com/install-website-app-edge-chromium/) are categorized as coming from Microsoft Store.

![image](https://user-images.githubusercontent.com/10008599/211275189-49cf190d-840f-46ab-a1d0-f2d47c405e00.png)

(Edit: updated screen capture)

**Comment by marticliment** [comment]
Yes, MS edge installs PWA apps as if thgey were ms apps, and in fact, they are treated in the same way by the OS. They are installed through MSIXs and can be reetted and uninstalled using the settins or the X-AppxPackage command

**Comment by marticliment** [comment]
This is an expected behaviour. If you check chrome apps, they don't appear like this
