### ISSUE TITLE
[BUG] Announcement image error

### ISSUE THREAD

**Issue by panther7** [marticliment/WingetUI#608]
Replace URL to image to marticliemnt.com, because ssl error.

![Image-2023-01-09 20 22 19](https://user-images.githubusercontent.com/3808250/211390785-8c53b00d-9eaa-4b68-b726-5ad5b79c7e04.png)

**Comment by marticliment** [comment]
I know.

My old domain got lost becauseof some freenom issues, i am working on it to restore services. Next version already has marticliment.com, but the update can't be rolled out without the old infrastructure working

**Comment by marticliment** [comment]
fixed
