### ISSUE TITLE
BUG: Chocolatey installed packages appearing in installed list with Winget as source

### ISSUE THREAD

**Issue by AbitFishy** [marticliment/WingetUI#612]
### **The Problem:**
It seems a number of packages I have installed using Chocolatey are being found by WingetUI, but in the "Source" column, it shows up as "Winget".  It should show up as either "Local PC" or as "Chocolatey".

With it being marked as "Winget", WingetUI tries to update these packages, but it often incorrectly identifies the exact package and version number and often fails to actually update the program.

Some notable example packages:

### **Amazon Corretto 8 and 11:**

**Choco Packages:** corretto8jdk and corretto11jdk
**Both Detected as**: Amazon.Corretto
with version numbers 8 and 11, it said version 18 was available as an update.  Update of course failed as 18 was already instead.
**Note:** Amazon Corretto is a distribution of Java, the major versions 8, 11, 17, 18, 19 are not interchangeable.  I uninstalled the Chocolatey packages and installed via winget and now they are fine.

### **Microsoft Visual C++ 2008 SP1 Redistributable Package:**

**Choco:**  vcredist2008 9.0.30729.616104  (includes both 32- and  64-bit versions)
**Detected as:** Microsoft.VCRedist.2008.x86 and Microsoft.VCRedist.2008.x64 
**Version:** 9.0.30729
**with version:**  9.0.30729.616 available for both as update

**After update:** both versions (9.0.30729 and 9.0.30729.6161) are installed via "Winget" and WingetUI wants to update them again.  Unable to uninstall from ChocolatelyGui.  Versions 9.0.30729.17 (yes .17) and 9.0.30729.6161 appear in Windows' installed program list.

### **Others:**

- Mp3tag
- WindirStat
- Wireshark
- WinSCP
- XnCovert
- vlc
- virtualbox
- veracrypt
- Steam
- Skype
- Qalculate!
- PuTTY
- and many more

 It seems almost every (but not every) package that both have will result in this bug.

I don't know if this problem is with WingetUI or winget

**Comment by marticliment** [comment]
since chocolatet registers software as if they were installed as usual, this is an issue that, at the moment, can't be fixed.(there's no way to differentiate them) 

however, I'm studying how to implement chocolate support, so thjs might get fixed then

**Comment by marticliment** [comment]
Hence, since programs are installed as regular software, winget detects them and attempts to update them as well
