### ISSUE TITLE
[FEATURE REQUEST] Paging display app list

### ISSUE THREAD

**Issue by Weidows** [marticliment/WingetUI#618]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/61131704/212496020-f270c2de-1ac8-4c3b-b55b-470ee4a9f8a0.png)

Cause there's `a large number` of apps in my scoop bucket (over 10K), so printing out the whole list spend a lot of time.

## Describe the solution you'd like

In addition, searching doesn't need so much time, its quickly. So the performance of paging output should be better.
Thanks!

**Comment by marticliment** [comment]
Part of the slow performance of the page is slow mainly because of the qt's slow times, so this can't be really fixed. However, I will try to optimize. 

However, you need to understand that loading 14k packages is a heavy task, and it is usual for it to struggle

**Comment by ppvnf** [comment]
Try typing `scoop search ""` in terminal. I believe it will also take a long time to show all packages

**Comment by Weidows** [comment]
> Try typing `scoop search ""` in terminal. I believe it will also take a long time to show all packages

![image](https://user-images.githubusercontent.com/61131704/212538587-92484c69-02bf-4c19-a271-106cd5278d6c.png)

searching in terminal not spends too much time, printing 48K lines takes 2s

![image](https://user-images.githubusercontent.com/61131704/212538813-845e737d-becc-47de-a733-d86bafb622f9.png)

and I try to search "7" in wingetUI, searching + printing = total 1s (result app list not many)

![image](https://user-images.githubusercontent.com/61131704/212538849-40231266-aa5e-453a-afd7-9f2fc39530fa.png)

when trying to search empty, searching + printing whole list = about 10s, surely over 5 seconds

so i think printing out the app list spends most time

**Comment by marticliment** [comment]
Instead of adding pages, items will be dynamically loaded.

I am testing this and it seems to work very well

**Comment by marticliment** [comment]
the fix for this iwwue will come with the next version
