### ISSUE TITLE
[FEATURE REQUEST] Disable the creation of desktop icons during updates

### ISSUE THREAD

**Issue by reaseno** [marticliment/WingetUI#624]
When updating programs via winget, it often happens that desktop icons are created. I would like to be able to switch this off. Otherwise I have to delete the icons manually with every update, which is a bit annoying.

WingetUI 1.5.3

**Comment by marticliment** [comment]
This is an issue with how winget works, since it runs the installer again without removing icons.
Note that this does not happen with scoop packages

**Comment by reaseno** [comment]
Are you sure there is no parameter for this? I imagine I've seen something like that before.

**Comment by marticliment** [comment]
you can do this, for example, with chocolatey, but not with winget (at least not yet).

if you want, you can open an issue on Microsoft/Winget-cli

**Comment by reaseno** [comment]
Oh, too bad. Thank you for the info and your time 👍

**Comment by reaseno** [comment]
That's the Issue:
https://github.com/microsoft/winget-cli/issues/1545

Since it will probably take even longer for Microsoft to do something, a small workaround would help: Scanning the desktop before the update and deleting new shortcut icons when the update is ready. The only danger would be that you should not create a new shortcut on the desktop during an update. Therefore, the option should be provided with a note.

**Comment by marticliment** [comment]
I will check that

**Comment by quickfold** [comment]
I would also like this option. I like to keep the desktop clean. Scanning the desktop shortcuts before installs and deleting new icons after install would be a workable solution. If you are worried that users might manually create a new shortcut during installs and would be unhappy to see it deleted, you could also show a list of new shortcuts before deleting them and giving the user a chance to unselect any they want to keep. 

Thanks for this great program!
