### ISSUE TITLE
WingetUI dark theme uses white titlebar

### ISSUE THREAD

**Issue by LoranRendel** [marticliment/WingetUI#632]
WingetUI dark theme uses white titlebar.

![image](https://user-images.githubusercontent.com/7853801/213941129-0b24b9bd-c0cd-477c-95a8-f38971d0331f.png)

**Comment by marticliment** [comment]
Hi @LoranRendel,

I'm afraid that the API that controls the color of the titlebar is only available on Windows 11, so this can't be changed on Windows 10 (at least as far as I know).

I'll check this again, but I don't think this can really be fixed

**Comment by LoranRendel** [comment]
> Hi @LoranRendel,
> 
> I'm afraid that the API that controls the color of the titlebar is only available on Windows 11, so this can't be changed on Windows 10 (at least as far as I know).
> 
> I'll check this again, but I don't think this can really be fixed

I use some other apps on Windows 10, which changes native titlebar to black. Maybe it also is possible for WingetUI.

**Comment by marticliment** [comment]
I will investigate this

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/214845571-3c142929-2fc7-4a6a-99c9-ed67421f66ff.png)

Fixed!
