### ISSUE TITLE
[BUG/ISSUE] WingetUI unexpectedly deletes scoop cache upon first start without asking

### ISSUE THREAD

**Issue by kevin-stuart** [marticliment/WingetUI#635]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Starting WingetUI deletes scoop cache without asking.

This is very bad, because I choose to keep older versions there to rollback, but now they are all gone on this machine I used.

## To Reproduce
Steps to reproduce the behaviour:
1. Start WingetUI
2. See that it says that it is deleted scoop cached
3. Check scoop cache
4. Be sad

## Expected behaviour
Just starting WingetUI does not unexpectedly delete scoop cache or at least asks for behavior

</details>

## Additional context
There seems to be an option for this in the settings, but it is disabled if scoop is disabled. Maybe you should also allow setting this independantly from enabling scoop in case you enable scoop.

**Comment by marticliment** [comment]
By scoop cache, you mean `scoop cache rm *` or `scoop cleanup --all`?

**Comment by kevin-stuart** [comment]
I assume; I hurrier to $USERPROFILE/scoop/cache and it was empty :-(

**Comment by marticliment** [comment]
yes, Wingetui deletes scoop cache, though this can be disabled from the settings (under startup options).


however, this should be enabled by default

**Comment by kevin-stuart** [comment]
I saw the option, the problem was that it deleted the cache right on the first start and I did not have the chance to disable it. Even then, it should be opt in to delete and not be the default if you ask me. Before I first started it, I had no idea it could also manage scoop and WingetUI seems to very good, this was not a good experience.

**Comment by marticliment** [comment]
This issue shouldn't happen anymore, and this option will be disable by default

**Comment by candrapersada** [comment]
how to enable cache cleaner in WingetUI 1.6.0?

**Comment by marticliment** [comment]
By enabling "enable scoop cleanup" under startup options:
![image](https://user-images.githubusercontent.com/53119851/219968369-75c6e49c-ce0e-4ba6-bb57-70539b3729df.png)

**Comment by candrapersada** [comment]
what I mean is cache cleaner not working
![gambar](https://user-images.githubusercontent.com/36833664/219968649-8602b8db-9019-4f3d-9fd3-1b4a3fa3ecb0.png)

**Comment by marticliment** [comment]
Can you then please open a new issue?
