### ISSUE TITLE
[BUG/ISSUE] Weird update packages (named "Everything is OK!")

### ISSUE THREAD

**Issue by shumafuk** [marticliment/WingetUI#645]
## Describe the bug
Update list shows wired packages. Like this named "Everything is OK!" showed in screenshot. Or those + +.

## To Reproduce
I have no idea. It just appear after while.

## Expected behaviour
More explanation about what it is.

## Screenshots
![Screenshot (1)](https://user-images.githubusercontent.com/62727484/215067301-3f58fa15-7b39-471c-95e3-ccdabec26c9a.jpg)

**Comment by marticliment** [comment]
Can you please go to WingetUI settings -> Scoop preferences -> install scoop?

**Comment by shumafuk** [comment]
It writes: Scoop is already installed.

**Comment by marticliment** [comment]
running scoop status on the command line does work?
