### ISSUE TITLE
[FEATURE REQUEST] More time intervals for update checking

### ISSUE THREAD

**Issue by adripo** [marticliment/WingetUI#647]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

It would be useful to add more options for `Check for updates every:` section.
At the moment the options are:

- 30 minutes
- 1 hour
- 2 hours
- 4 hours
- 8 hours

I would like to be able to check even once a day, once a week or once a month, for example.

## Describe the solution you'd like

Add more options to choose from:

- 30 minutes
- 1 hour
- 2 hours
- 4 hours
- 8 hours
- 12 hours
- 1 day
- 1 week
- 2 weeks
- 1 month
- 3 months

**Comment by marticliment** [comment]
WingetUI checks for updates on launch, and the time starts counting after the start of WingetUI on the system tray, so more than 8 hours does not make sense for me.

What do you think?

**Comment by adripo** [comment]
Okay, so I misunderstood that setting. It indicates the interval between update checks when wingetUI is opened.
I would still add a couple of options:
- 12 hours
- 1 day

**Comment by adripo** [comment]
What I would like to have as an option is to automatically check for updates even when the GUI is closed. So without keeping WingetUI running all the time, but only do an update check once 1/2/3 weeks/months. For example by running silently a scheduled task and open and notify the user if there are updates, otherwise remain closed.

**Comment by marticliment** [comment]
I am not sure if that las part will be possible, since the main application is built into the GUI

**Comment by reaseno** [comment]
> WingetUI checks for updates on launch, and the time starts counting after the start of WingetUI on the system tray, so more than 8 hours does not make sense for me.

It is useful if the computer is not restarted every day. I primarily use the hibernation mode, because this way the computer is booted faster and also all programs are open again. You can simply continue working where you were last when you turned off the computer. With WingetUI in the tray.
