### ISSUE TITLE
[BUG/ISSUE] WingetUI installer v1.6.0 is painfully slow

### ISSUE THREAD

**Issue by o-l-a-v** [marticliment/WingetUI#650]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug

For extracting < 90 MB to `%LOCALAPPDATA%\Programs\WingetUI`, the WingetUI installer is painfully slow.

This is on a relatively fast computer (i7-9750H, 32GB RAM) to fast storage (Corsair MP510 960gb).

## To Reproduce

Install WingetUI v1.6.0, it takes several minutes to complete.

## Expected behaviour

Seconds.

**Comment by marticliment** [comment]
The issue here are the snall files. chocolaty and winget are bundled with WingetUI, and this enlarges the amount of small files.

However, I also noticed that, and I am working on a solution

**Comment by tastypear** [comment]
For me, only 400 files, it takes almost 1h.

**Comment by marticliment** [comment]
@tastypear, are you running on an hdd?

**Comment by tastypear** [comment]
> @tastypear, are you running on an hdd?

No, on a Samsung ssd.

It takes extremely long time even on the ramdisk.

Every time a file is extracted, it takes a few seconds(>10s) to delay.

**Comment by Xetrill** [comment]
Its got nothing to do with any amount of small files. Its just a broken installer.
For every file it executes and waits (!) for `"taskkill.exe" /f /im "winget.exe"`.

**Comment by o-l-a-v** [comment]
> Its got nothing to do with any amount of small files. Its just a broken installer.
> For every file it executes and waits (!) for `"taskkill.exe" /f /im "winget.exe"`.

If winget is bundled with the installer, it shouldn't even try to kill winget.exe before checking if the path of the process matches install path IMO.

**Comment by marticliment** [comment]
that seems to explain it's slowlyness

**Comment by marticliment** [comment]
This issue has been fixed. Newer versions will have a way faster installer
