### ISSUE TITLE
[BUG/ISSUE] (v1.6.0) At least when installed through Scoop, upon first start, the app gets stuck at the 'Clear Scoop cache' step

### ISSUE THREAD

**Issue by RavenMacDaddy** [marticliment/WingetUI#653]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Upon the first start of the app, once installed through Scoop, the app gets stuck on the step for clearing the Scoop cache.

Manually deleting the contents of the cache dir and then relaunching WingetUI restores normal operation.

## To Reproduce
Steps to reproduce the behaviour:

1. Start the app after installation through Scoop - with the cache of Scoop populated.
2. Observe how things run as normal until the app tries to clear the cache (though no files are seemingly deleted).
3. Manually clear the cache by for example deleting the contents through the File Explorer.
4. Close and then re-open WingetUI.

## Expected behaviour
For the cache to be successfully cleared accordingly through the step upon startup, and for all the steps to proceed without issues.

## The Log
(Since the problem doesn't persist after the first run, the log was retrieved upon the next startup, which was successful)

<details>

```
F:\Backup\Scoop\apps\wingetui\current\sudo\gsudo.exe
F:\Backup\Scoop\apps\wingetui\current\sudo
🟢 checkQueue Thread started!
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 410, in <module>

🔴 Exception: Value not found for ['sv_SE', 'sv']

🔴 Note this traceback was caught by reporter and has been added to the log (Value not found for ['sv_SE', 'sv'])
🟡 Using bundled lang file (forced=False)
🔴 Unknown language
🟡 Using bundled lang file (forced=True)
It took 0.002004861831665039 to load all language files
🔵 Starting main application...
Scanning for instances...
🔵 Starting update check
Found lock file(s), reactivating...
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
b'v1.4.10173\r\n'
None
updating winget
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
b'1.2.1\r\n'
None
b"Current Scoop version:\nv0.3.1 - Released at 2022-11-15\n\n'extras' bucket:\nc155560a2 netron: Update to version 6.5.0\n\n'games' bucket:\n1d19b475 yuzu-pineapple: Update to version EA-3340\n\n'java' bucket:\nbbb0ca60 temurin8-nightly-jre: Update to version 8.0.362-9.0.202301271816\n\n'main' bucket:\n839c14873 micronaut: Update to version 3.7.6\n\n'nirsoft' bucket:\n28db834 Excluded two pad files that require a password. They need to be updated manually.\n\n'nonportable' bucket:\na4d244e musicbee-np: Add version 3.4.8033 (#139)\n\n'rasa' bucket:\na3496d9 ltrdata: Update to 2022.12.23\n\n'rmd' bucket:\nf469f0d Delete usb-tree-view.json\n\n'sysinternals' bucket:\ne34b938 zoomit: Update to version 6.12\n\n'versions' bucket:\n2f8e2fd3e r-patched: Update to version 4.2.2-r83711\n\n"
None
Reactivation signal ignored: RaiseWindow_[1674900347.1784828]
{'wingetFound': True, 'scoopFound': True, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'v0.3.1 - Released at 2022-11-15', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
🔵 Is Dark
🟢 Starting winget search, winget on F:\Backup\Scoop\apps\wingetui\current\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Discover tab loaded
🟢 Starting winget search, winget on F:\Backup\Scoop\apps\wingetui\current\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on F:\Backup\Scoop\apps\wingetui\current\choco-cli\choco.exe...
🟢 Upgrades tab loaded
🟢 Starting winget search, winget on F:\Backup\Scoop\apps\wingetui\current\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on F:\Backup\Scoop\apps\wingetui\current\choco-cli\choco.exe...
🟢 Discover tab loaded
🟢 Starting scoop search...
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Chocolatey uninstallable packages search finished
🟢 Main application loaded...
🟢 Chocolatey search finished
🟢 Searching for string ""
🟢 Searching for string ""
No installed package found matching input criteria.
🟢 Winget search finished
🟢 Searching for string ""
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Scoop bucket search finished
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 216
None
🟢 Winget search finished
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Scoop search finished
🟢 Total packages: 15580
🔵 Copying log to the clipboard...

```

</details>

## Additional context
In case it makes any difference, the path for Scoop isn't the default, but on another drive for persistence.

The manifest for the app doesn't persist any data, and I believe I didn't have any old data in AppData or corresponding which would possibly conflict with the newer version of WingetUI.

**Comment by marticliment** [comment]
Can you please clean-install wingetui from scoop, copy the install directory to another part of your HDD and then install wingetui with the installer, open the install path and compare both folders with winmerge?

I suspect there might be file issues with scoop

**Comment by RavenMacDaddy** [comment]
![image](https://user-images.githubusercontent.com/67732686/215316291-9f97f32e-59f2-4ade-a764-3855825f025a.png)

It does seem to be the same.

**Comment by marticliment** [comment]
Yes, those files are irrelevant.

I will further study that

**Comment by marticliment** [comment]
I have not found the root of the issue, but I have added a bypass mechanism to prevent infinite waits on the initialization window.
There will be a button that will pop up after 15 seconds of _stuckness_.
