### ISSUE TITLE
[BUG/ISSUE] Chocolatey Uninstall as Administrator

### ISSUE THREAD

**Issue by adripo** [marticliment/WingetUI#659]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Uninstall as Administrator not working for Chocolatey packages.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to Installed packages
2. Right click on Chocolatey package and select `Uninstall as administrator`
3. Check logs
4. See error `Chocolatey detected you are not running from an elevated command shell`

## Expected behaviour
Execute uninstall as admin

## Screenshots
![image](https://user-images.githubusercontent.com/26493496/215302662-d372181e-4575-4fa7-a116-8120f9199d90.png)

## The Log

<details>

```
Chocolatey v1.2.1 Chocolatey detected you are not running from an elevated command shell (cmd/powershell). You may experience errors - many functions/packages require admin rights. Only advanced users should run choco w/out an elevated shell. When you open the command shell, you should ensure that you do so with "Run as Administrator" selected. If you are attempting to use Chocolatey in a non-administrator setting, you must select a different location other than the default install location. See https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install for details. For the question below, you have 20 seconds to make a selection. Do you want to continue?([Y]es/[N]o): Timeout or your choice of '' is not a valid selection. Uninstalling the following packages: amd-ryzen-chipset
```

</details>

**Comment by Giggigx** [comment]
The issue occurs also when uninstalling any package from WingetUI. The option to uninstall as administrator just doesn't work

**Comment by marticliment** [comment]
This issue is now fixed on the latest commit, and the fix will come with the next release
