### ISSUE TITLE
[BUG/ISSUE] V1.6.0 - First run dialogue partially not translated

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#661]
Version 1.6.0 - First run dialogue
All strings have been properly and timely translated in Tolgee, yet the dialogue looks like this:
![image](https://user-images.githubusercontent.com/10008599/215313290-1f3063c7-3e99-4c59-995f-22df1a3da74b.png)

**Comment by marticliment** [comment]
added the missing code to translate those sections
