### ISSUE TITLE
[BUG/ISSUE] v1.6.0 - Settings - 4 untranslated strings

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#662]
![image](https://user-images.githubusercontent.com/10008599/215313642-ff227b0c-4be3-48a2-8764-6fab13b514d3.png)

![image](https://user-images.githubusercontent.com/10008599/215313718-701dadcf-95f7-4612-8778-5b62cdcc8d80.png)

![image](https://user-images.githubusercontent.com/10008599/215313761-f246156c-55e0-4685-bb70-10603d34556a.png)

**Comment by Stephan-P** [comment]
Found another: the Windows notification.
Or is this one not WingtUI's?
![image](https://user-images.githubusercontent.com/10008599/215433821-c37ad25c-9fef-4118-b747-893f4862291d.png)

**Comment by marticliment** [comment]
I have added them to Tolgee for translators to translate them
