### ISSUE TITLE
[BUG/ISSUE] v1.6.0 - quite some updates not found

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#663]
After updating WingetUI v1.60 (beta) to v1.6.0 final this morning, I ran into a situation that I have not encountered before.
SuMo was able to find quite a few updates that are not discovered by WingetUI.

Can it be that the detection mechanism is failing somehow?

![image](https://user-images.githubusercontent.com/10008599/215318790-ebc19bd0-78b9-47aa-a1b1-91f1c65ab538.png)

**Comment by marticliment** [comment]
winget.exe does show any updates?

**Comment by Stephan-P** [comment]
It did show two updates for Windows Terminal and that Visual C runtime lib that keeps showing up, yeah

**Comment by Stephan-P** [comment]
Meanwhile, I've updated those apps manually. We'll have to wait for the next opportunity

**Comment by Stephan-P** [comment]
Vidcoder got another update yesterday: [8.23 (official release)](https://vidcoder.net)
Both Winget and Chocolatey are enabled and this is what they can find for Vidcoder
Same picture after resetting Winget sources and Chocolatey caches
![image](https://user-images.githubusercontent.com/10008599/215425811-035fd9d4-6db7-400b-b674-2067f93001cb.png)

**Comment by Stephan-P** [comment]
Here's an image of Vidcoder in "Installed packages"
![image](https://user-images.githubusercontent.com/10008599/215427693-9d000f47-afa3-4805-95f7-3d93dfe78e8e.png)

**Comment by Stephan-P** [comment]
And Software Updates says: Hooray
![image](https://user-images.githubusercontent.com/10008599/215427916-fe492ab3-6bbd-4eb1-b6ba-eae6c622657d.png)

**Comment by Stephan-P** [comment]
[WingetUI-log.txt](https://github.com/marticliment/WingetUI/files/10533905/WingetUI-log.txt)

**Comment by Stephan-P** [comment]
And I'm having the same experience on two PC's

**Comment by marticliment** [comment]
This is then an issue with the package managers. When an update is released, package managers take a while before they reflect the changes.

This will happen you also with wingetui, which is still on v1.5.3 on winget while version 1.6.0 is the latest one

**Comment by marticliment** [comment]
If you still face this issue but the chocolatey and winget cli do show the correct updates, please let me know.

Also note that some packages are left unmaintained
