### ISSUE TITLE
Uninstall problem

### ISSUE THREAD

**Issue by ozky84** [marticliment/WingetUI#664]
Try to uninstall package it says ok but it doesn't really remove anything app still shows in Windows start menu.....
Windows 10 home x64 22h1 version....
I have try both Wingetgui winget and system winget....
Here is link to dropbox loaded video.
tinyurl.com/4cbvc2w4

`C:\Users\ozky\AppData\Local\Programs\WingetUI\sudo\gsudo.exe
C:\Users\ozky\AppData\Local\Programs\WingetUI\sudo
🟢 checkQueue Thread started!
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 410, in <module>

🔴 Exception: Value not found for ['fi_FI', 'fi']

🔴 Note this traceback was caught by reporter and has been added to the log (Value not found for ['fi_FI', 'fi'])
🟡 Using bundled lang file (forced=False)
🔴 Unknown language
🟡 Using bundled lang file (forced=True)
It took 0.015624523162841797 to load all language files
🔵 Starting main application...
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
b'v1.4.10173\r\n'
None
updating winget
b'1.2.1\r\n'
None
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
Reactivation signal ignored: RaiseWindow_[1674989608.6792767]
{'wingetFound': True, 'scoopFound': False, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'Scoop is disabled', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
🟢 Starting winget search, winget on winget.exe...
🟢 Discover tab loaded
🟢 Starting winget search, winget on winget.exe...
🟢 Starting choco search, choco on C:\Users\ozky\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Upgrades tab loaded
🟢 Starting choco search, choco on C:\Users\ozky\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Starting winget search, winget on winget.exe...
🟢 Starting choco search, choco on C:\Users\ozky\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Discover tab loaded
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
🟢 Chocolatey uninstallable packages search finished
🟢 Searching for string ""
🟢 Chocolatey search finished
🟢 Searching for string ""
An unexpected error occurred while executing the command:
database is locked
0x87af0005 : Tietokantatiedosto on lukittu
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 56
2276392965
🟢 Starting winget search, winget on winget.exe...
No installed package found matching input criteria.
🟢 Winget search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
None
🟢 Winget search finished
🟢 Total packages: 11264
🟢 Chocolatey search finished
🟢 Starting winget search, winget on winget.exe...
None
🟢 Winget search finished
🟢 Total packages: 11195
🟢 Found reactivation lock file...
Win32Mica Error: win32 version 19045 is not supported
50
Win32Mica Error: win32 version 19045 is not supported
50
Win32Mica Error: win32 version 19045 is not supported
50
Win32Mica Error: win32 version 19045 is not supported
🔵 Uninstalling Microsoft.Microsoft3DViewer_8wekyb3d8bbwe
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=3D-katseluohjelma, id=Microsoft.Microsoft3DViewer_8wekyb3d8bbwe, installId=1674998458.564937
🔵 Uninstalling Microsoft.ZuneVideo_8wekyb3d8bbwe
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=Elokuvat ja TV, id=Microsoft.ZuneVideo_8wekyb3d8bbwe, installId=1674998458.5989473
🔵 Uninstalling Microsoft.Wallet_8wekyb3d8bbwe
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=Microsoft Pay, id=Microsoft.Wallet_8wekyb3d8bbwe, installId=1674998458.6299393
🔵 Uninstalling Microsoft.YourPhone_8wekyb3d8bbwe
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=Puhelinlinkki, id=Microsoft.YourPhone_8wekyb3d8bbwe, installId=1674998458.6569455
🔵 Current program set to 1674998458.564937
🟢 Have permission to install, starting installation threads...
🟢 winget installer assistant thread started for process <Popen: returncode: None args: []>
0
🔵 Current program set to 1674998458.5989473
🟢 Have permission to install, starting installation threads...
🟢 winget installer assistant thread started for process <Popen: returncode: None args: []>
0
🔵 Current program set to 1674998458.6299393
🟢 Have permission to install, starting installation threads...
🟢 winget installer assistant thread started for process <Popen: returncode: None args: []>
0
🔵 Current program set to 1674998458.6569455
🟢 Have permission to install, starting installation threads...
🟢 winget installer assistant thread started for process <Popen: returncode: None args: []>
0
Win32Mica Error: win32 version 19045 is not supported
50
🟢 Starting winget search, winget on winget.exe...
🟢 Starting choco search, choco on C:\Users\ozky\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Chocolatey uninstallable packages search finished
🟢 Searching for string ""
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 56
Win32Mica Error: win32 version 19045 is not supported
🔵 Uninstalling Microsoft.Microsoft3DViewer_8wekyb3d8bbwe
Win32Mica Error: win32 version 19045 is not supported
🟢 Waiting for install permission... title=3D-katseluohjelma, id=Microsoft.Microsoft3DViewer_8wekyb3d8bbwe, installId=1674998522.6685143
🔵 Current program set to 1674998522.6685143
🟢 Have permission to install, starting installation threads...
🟢 winget installer assistant thread started for process <Popen: returncode: None args: []>
0
Win32Mica Error: win32 version 19045 is not supported
50
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Saving log...
`

**Comment by marticliment** [comment]
if you have tested system winget and it does still not work, there's not much we can do here :/.

Please open an issue on microsoft/winget-cli

**Comment by marticliment** [comment]
Can you please test the command-line winget?

**Comment by ozky84** [comment]
Yes cli works but not gui......
`PS C:\Windows\system32> winget remove 9NBLGGH42THS
Found 3D Viewer [9NBLGGH42THS]
Starting package uninstall...
  ██████████████████████████████  100%
Successfully uninstalled`

**Comment by marticliment** [comment]
could you please send a screenshot of the package you are willing to uninstall?

**Comment by ozky84** [comment]
All Windows x packages groove music or 3d app  not Winget installed apps...
Sorry i forgot whole answer...

**Comment by ozky84** [comment]
Thanks for fix this.....when can expect release this fix is included?

**Comment by marticliment** [comment]
versión 1.6.1 was released yesterday.

You can either install it manually, update from the automatic updater (if enabled) or wait until the last version gets published to winget
