### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by ylefebvre** [marticliment/WingetUI#665]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
With both winget and chocolatey activasted as sources, packages are appearing twice in Software Updates page when the applications were installed with chocolatey.

## To Reproduce
Steps to reproduce the behaviour:
1. Install an application using chocolatey
2. When an update becomes available for the application, it will appear twice in the list
3. If you just select all items in the list, each of these duplicate applications will get uninstalled and reinstalled twice.

## Expected behaviour
Only show each update once in the Software Updates list, perhaps showing both sources in the last column.

## Screenshots
![image](https://user-images.githubusercontent.com/8749791/215335281-946b8bff-a444-4b5b-8a72-1db74b67daaa.png)
As can be seen in this screenshot, handbrake, hwinfo32 and imageglass are all appearing twice.

**Comment by marticliment** [comment]
As you can see, this is due to the fact that each entry is detected by a different package manager.

Much can't be done, since this is the expected result.

It is in my plans to handle duplicate packages, but meanwhile, this is how it is supposed to work
