### ISSUE TITLE
[BUG/ISSUE] Chocolatey packages show id as package name instead of title

### ISSUE THREAD

**Issue by adripo** [marticliment/WingetUI#666]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Name of Chocolatey packages is the same as their id. The real name can be viewed in the package info.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to Discover
2. Search chocolatey package, for example 'ddu'
3. See name equals id
4. If you right-click on package and `Show info` the correct name(title) will be showed

## Expected behaviour
View package title, as it happens for winget

## Screenshots
![image](https://user-images.githubusercontent.com/26493496/215348698-3a772354-1642-4811-92aa-227592766a9c.png)

![image](https://user-images.githubusercontent.com/26493496/215348678-cd23462a-6ccb-4bdb-ac9f-a0f45e203738.png)

**Comment by marticliment** [comment]
This is due to how chocolatey uses the search command.

The package name is never shown, so it can not be shown.
