### ISSUE TITLE
[FEATURE REQUEST] Button contrasts and font weight

### ISSUE THREAD

**Issue by aaronliu0130** [marticliment/WingetUI#670]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

Across the entire app, the text colors on buttons don't care about the theme color. This leads to poor contrast on dark themes.
![image](https://user-images.githubusercontent.com/11874211/215353728-e401a301-6ba4-4f0e-93cb-ee36bf4bb614.png)
Additionally, in this picture, it might just be me, but the text weights next to checked boxes appear to be bolder than normal (see below reset button for reference). Also, the icons appear to have more weight than the "Enable" headers, which is distracting.
![image](https://user-images.githubusercontent.com/11874211/215353901-e3ee2fd8-f008-41ab-895c-3875e26a2ae6.png)

## Describe the solution you'd like

Make the buttons adjust color according to the theme, make the text weights normal if they aren't, and decrease the icon weights.

**Comment by marticliment** [comment]
The weight of the icons can't be changed.

However, it is true that buttons appear to have a lighter weith than expected, and I'm going to change that asap

**Comment by aaronliu0130** [comment]
Could the color of the text be changed according to the theme color?

**Comment by marticliment** [comment]
Yes, but it is in black where it gives the best contrast.

The color schemes for the theme are the same used in UWP, so readability shouldn't be an issue
