### ISSUE TITLE
[BUG/ISSUE]There is no running effect after using wingetui to import the installation package

### ISSUE THREAD

**Issue by Alexzz96** [marticliment/WingetUI#673]
0 0
 🔴 Traceback (most recent call last):  
🔴   File ".\uiSections.py", line 381, in importPackages  
🔴 AttributeError: 'dict' object has no attribute 'text'  
🔴 Note this traceback was caught by reporter and has been added to the log ('dict' object has no attribute 'text') 

Both computers do not work, is it a system problem? win11 professional workstation version.

**Comment by marticliment** [comment]
Whoops, this appears to be a code crash...
