### ISSUE TITLE
[FEATURE REQUEST] Feedback upon pressing "Reset" button

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#674]
v1.6.0
There are a number of buttons that do not provide any feedback when pressed, which is quite confusing.

- Settings - Package Manager - Chocolatey - Reset cache
- Settings - Experimental - Reset WingetUI Icon cache
- WingetUI Log - Copy log to clipboard
- WingetUI Log - Reload log

One can press these buttons, but one will never know if anything happened

**Comment by marticliment** [comment]
Reload log does update the text, but if the log hasn't changed nothing will happen.
The other ones, it is true that they could do something

**Comment by marticliment** [comment]
this actually happens, but it is so instantaneous that it does not show as a noticeable change

**Comment by Stephan-P** [comment]
Gone are the days that computers were slower than the blink of an eye.  😉
