### ISSUE TITLE
[BUG/ISSUE] sign this program with a valid digital signature

### ISSUE THREAD

**Issue by HotCakeX** [marticliment/WingetUI#675]
None of the bug/issue categories apply because can't even run this program since it doesn't have a valid digital signature.

[Sign your app for Smart App Control compliance
](https://learn.microsoft.com/en-us/windows/apps/develop/smart-app-control/code-signing-for-smart-app-control)

[Smart App Control](https://learn.microsoft.com/en-us/windows/apps/develop/smart-app-control/overview)
<br>

![image](https://user-images.githubusercontent.com/118815227/215457885-bda50155-7e0a-425d-aa75-d963943b29da.png)

**Comment by marticliment** [comment]
Signing cerficicates are really expensive ($200-$300 a year), and I can't afford one. When the installer gets downloaded a little bit more it will be recognized as safe.

**Comment by Poopooracoocoo** [comment]
Why would anyone use Smart App Control?! Sounds like user/Microsoft error here. It's ridiculous to expect FOSS to pay for signing certificates.

**Comment by Poopooracoocoo** [comment]
I know ;)
