### ISSUE TITLE
Github: Contact detailed changelog

### ISSUE THREAD

**Issue by panther7** [marticliment/WingetUI#677]
Concat "Detailed changelog" pull request into one message, if have duplicates, example:

```
Update translations from Tolgee by @github-actions in #615
Update translations from Tolgee by @github-actions in #617
Update translations from Tolgee by @github-actions in #619

-- >

Update translations from Tolgee by @github-actions in (#615, #617 and #619)
```

https://github.com/marticliment/WingetUI/releases/tag/1.6.0

I did not found "release script" inside this project.

@marticliment

**Comment by marticliment** [comment]
There's no release script, I use the release notes generator from the releases tab.

I will take this in account for future releases, and update v1.6.0
