### ISSUE TITLE
[BUG/ISSUE] Issue with installation path including space characters

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#679]
wingetUI v.1.6.0
My home path is C:\Users\Stephan Paternotte\ and includes a space character.
Apparently WingetUI is not prepared for this. See screenshot after issuing the command "Reset winget sources"
I guess some quotes need to be applied here.

![image](https://user-images.githubusercontent.com/10008599/215815387-2d673e4a-c042-416c-8d60-e08d2cfe231b.png)

**Comment by derula** [comment]
Can confirm, this is a problem in multiple places. No chocolatey packages listed (unless I switch to system chocolatey), no WinGet packages listed, no real error reported except for the one in the screenshot above. WinGet updated itself and became rendered itself completely inoperational :(

**Comment by sbuethe** [comment]
I can confirm that too: No installed packages found on a system with a space in home dir, no updates either. Wingetui working fine on other computers. Only obvious difference seems to be the space character in the home dir.

This may be related: After switching to system winget plenty of installed packages are found, but results look like this:
![grafik](https://user-images.githubusercontent.com/38316191/229299258-ca78b62a-9bf8-4211-ae4c-fd4840ed82d8.png)

Meanwhile, winget cli shows the correct results.

**Comment by marticliment** [comment]
System winget is quite broken due to localisation.

I am aware of this issue, but I can't find any fix for it.
