### ISSUE TITLE
[FEATURE REQUEST] Set "Use system Chocolaty" by defualt 

### ISSUE THREAD

**Issue by AbitFishy** [marticliment/WingetUI#683]
## Before submitting the issue

- [*] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [* ] **I have checked that I am running the latest version of WingetUI**
- [ *] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [* ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

Have the Chocolaty setting  "Use system Chocolaty" set by default by the installer if it detects Chocolaty is already installed.  I was very confused why my Chocolaty installed packages weren't showing up.  Turns out WingetUI was using it's own Chocolaty, something I had no idea it would do.

## Describe the solution you'd like

During install, when it asks what sources you want to use and you select Chocolaty, detect if Chocolaty is already installed, and if so, automatically check a box to use installed Chocolaty.

**Comment by marticliment** [comment]
Yes, it seems like a good idea

**Comment by marticliment** [comment]
Done!
(This check will be done only on the welcome window, when setting up the package managers)
