### ISSUE TITLE
[FEATURE REQUEST] Support automatic update of selected apps

### ISSUE THREAD

**Issue by siewers** [marticliment/WingetUI#686]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.
Certain apps has a high frequency of updates, which makes it a bit tedious to always manually having to update them. For instance, [Oh My Posh](https://github.com/JanDeDobbeleer/oh-my-posh) has daily releases, and updating every day is a bit of a drag.

## Describe the solution you'd like
I'd love if WingetUI could update certain packages automatically, similar to how it is done in [Winget-AutoUpdate (WAU)](https://github.com/Romanitho/Winget-AutoUpdate).
In the WingetUI interface, it would be great if I could mark certain apps to auto update, and then get a notification when WingetUI starts up, that it will update the apps I've selected.

I don't find it necessary with an option to automatically update all apps, but some are updated so often that it would be simpler to just let it happen automatically.

In case a major version update is detected (or minor, depending on the app - configurable perhaps), it might be important to warn the user to do a manual approval. Especially if the app has configuration which might be breaking, which could be the case for Oh My Posh for instance.
A link to the release notes would also be awesome in such cases, but I know I'm asking for a lot already :)

**Comment by siewers** [comment]
Sorry, I see this might have already been discussed in #44, but it doesn't seem to have been addressed (https://github.com/marticliment/WingetUI/issues/44#issuecomment-1184657617).
Personally, I don't mind being interrupted, as long as I'm notified about there's an app about to be updated.

**Comment by marticliment** [comment]
What I plan to do with the implementation of #680, is to add a shortcut to directly update all apps.

However, this could be a possibility

**Comment by marticliment** [comment]
This feature will come with WingetUI 1.6.1
