### ISSUE TITLE
[BUG/ISSUE] Chocolatey: App installation always has a 20 sec selection timeout before proceeding

### ISSUE THREAD

**Issue by RavenMacDaddy** [marticliment/WingetUI#690]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Any app with Chocolatey as the source has a 20 sec selection timeout before the installation proceeds, as can be seen in the screenshot below.

This is the stock behaviour when running through WingetUI.

Maybe this shouldn't technically be cat as a bug, but it's clearly not the desired default operation.

## To Reproduce
Steps to reproduce the behaviour:
1. Install any app with Chocolatey as the source
2. Notice how the installation gets stuck with a 20 sec timeout - and this is for every app. (Which I confirmed by installing another app.)

## Expected behaviour
Default should both detect the requirement for admin (#671), and proceed effectively with the installation process; no unnecessary halts, whether an app needs it or not.

Seemingly, Chocolatey is just really grumpy without admin and might need some adjustment to its stock config to not give users this unoptimal experience.

## Screenshots
![image](https://user-images.githubusercontent.com/67732686/216675695-940a364a-947b-4a90-a290-683e85050aa1.png)

![image](https://user-images.githubusercontent.com/67732686/216675790-65bebee3-2be1-4da6-b3fb-16ac68248642.png)

## The Log

[Log.txt](https://github.com/marticliment/WingetUI/files/10581621/Log.txt)

**Comment by marticliment** [comment]
I am aware of it, but i have still found no way to disable this question.

**Comment by marticliment** [comment]
For whatever the reason, the y is not read by the executable.

**Comment by vexx32** [comment]
I've done this from PowerShell before. You need to emit the input _and_ a line feed character for it to read it as "y", "enter" and continue.

So yeah sending ``"y`n"`` (from PS) or `"y\n"` (from C# or most other langs) or equivalent will generally work.

**Comment by marticliment** [comment]
That actually could make sense. I will test this out
