### ISSUE TITLE
[BUG/ISSUE] Skip Hash Check option not working

### ISSUE THREAD

**Issue by Giggigx** [marticliment/WingetUI#697]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Selecting the "skip hash check" option doesn't actually skip the check
## To Reproduce
Steps to reproduce the behaviour:
1. Search for bandizip (the hash check fails on this package)
2. Click on skip hash check
3. Click on install

## Expected behaviour
The installation should go ahead after skipping the hash check

## The Log

<details>
C:\Users\Giggig\AppData\Local\Programs\WingetUI\sudo\gsudo.exe
C:\Users\Giggig\AppData\Local\Programs\WingetUI\sudo
🟢 checkQueue Thread started!
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.020138263702392578 to load all language files
🔵 Starting main application...
🔵 Language file up-to-date
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
b'v1.4.10173\r\n'
None
updating winget
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
Reactivation signal ignored: RaiseWindow_[1675959553.510757]
b'1.2.1\r\n'
None
b"Current Scoop version:\nv0.3.1 - Released at 2022-11-15\n\n'main' bucket:\n71e258065 clipboard: Add version 0.3.1 (#4431)\n\n"
None
{'wingetFound': True, 'scoopFound': True, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'v0.3.1 - Released at 2022-11-15', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
🔵 Is Dark
🟢 Starting winget search, winget on C:\Users\Giggig\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Discover tab loaded
🟢 Starting winget search, winget on C:\Users\Giggig\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on C:\Users\Giggig\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Upgrades tab loaded
🟢 Starting winget search, winget on C:\Users\Giggig\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting scoop search...
🟢 Starting choco search, choco on C:\Users\Giggig\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Discover tab loaded
🟢 Starting scoop search...
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
🟢 Searching for string "b"
🟢 Searching for string "ba"
🟢 Searching for string "ban"
🟢 Searching for string "band"
🟢 Searching for string "bandi"
🟢 Searching for string "bandiz"
🟢 Searching for string "bandizi"
🟢 Searching for string "bandizip"
No installed package found matching input criteria.
🟢 Chocolatey uninstallable packages search finished
🟢 Searching for string ""
🟢 Winget search finished
🟢 Searching for string ""
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Scoop bucket search finished
🟢 Chocolatey search finished
🟢 Searching for string ""
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 50
🟢 Scoop search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
None
🟢 Winget search finished
🟢 Scoop search finished
🟢 Total packages: 12425
🟢 Searching for string "bandizip"
🟢 Starting get info for id Bandisoft.Bandizip
🟢 Loading versions for Bandizip
['C:\\Users\\Giggig\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'show', '--id', 'Bandisoft.Bandizip', '-e', '--versions', '--source', 'winget', '--accept-source-agreements']
🟢 Starting installation of package Bandizip with id Bandisoft.Bandizip
🟢 Waiting for install permission... title=Bandizip, id=Bandisoft.Bandizip, installId=1675960632.7317069
🔵 Current program set to 1675960632.7317069
🟢 Have permission to install, starting installation threads...
['C:\\Users\\Giggig\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'install', '-e', '--id', 'Bandisoft.Bandizip', '--source', 'winget', '--accept-source-agreements', '--force', '--silent']
🟢 winget installer assistant thread started for process <Popen: returncode: None args: ['C:\\Users\\Giggig\\AppData\\Local\\Programs...>
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

</details>

**Comment by RavenMacDaddy** [comment]
https://user-images.githubusercontent.com/67732686/219455496-3aac9ac1-78da-44bd-b7a1-86edf4a81b8b.mp4

This still seems to be an issue.

**Comment by marticliment** [comment]
Are you running the latest heads?

**Comment by RavenMacDaddy** [comment]
That explains it, thanks for the info.
