### ISSUE TITLE
[FEATURE REQUEST] List of programs ignored by updates with the possibility to unignore them

### ISSUE THREAD

**Issue by oxFilla** [marticliment/WingetUI#699]
I missed the possibility to see which programs I put on the Ignore Updates list and the possibility to allow some of them again.

I would like to have an additional view where all ignored programs are listed with the possibility to unignore them.

**Comment by marticliment** [comment]
This will be done on #284.

Please subscribe to that thread, since I am going to close this as duplicate

**Comment by oxFilla** [comment]
Oh, I didn't search for blacklist 🙈
