### ISSUE TITLE
[FEATURE REQUEST] Make "manifest" property of packages display URL

### ISSUE THREAD

**Issue by aaronliu0130** [marticliment/WingetUI#715]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

Oftentimes I want  to go directly to the scoop manifest on github before I realize that the manifest points to a local location.
![image](https://user-images.githubusercontent.com/11874211/218910104-b1da11d7-900d-4543-894b-e635d6efed26.png)

## Describe the solution you'd like

Make the "manifest" property show the online URL of the manifest instead.

**Comment by marticliment** [comment]
This feature will come with WingetUI 1.6.1
