### ISSUE TITLE
[FEATURE REQUEST] check for updates every 24h or once a week

### ISSUE THREAD

**Issue by reaseno** [marticliment/WingetUI#716]
## Before submitting the issue
- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**

Some of my installed packages seem to get an update twice a day, which annoys me with the update notifications. So it would help me if I could set update checks to 24h or once a week.

**Comment by marticliment** [comment]
duplicate of #647

**Comment by reaseno** [comment]
I have not found this. Sorry 🙈
