### ISSUE TITLE
[FEATURE REQUEST] Change Blacklist Feature to pin package

### ISSUE THREAD

**Issue by xIUPITERx** [marticliment/WingetUI#718]
## Before submitting the issue

- [ x ] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [ x ] **I have checked that I am running the latest version of WingetUI**
- [ x ] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [ x ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the solution you'd like

For consistency, switch from the custom blacklist feature to Winget's new pin package feature when using system-integrated Winget.

**Comment by marticliment** [comment]
System winget is translated, what will cause issues when it comes to parsing the console output.
The blacklisting feature is going to get a needed improvement soon, but I am not sure up to what point this is going to be changed as you say.

**Comment by marticliment** [comment]
Package pinning is not goping to be integrated with Winget, but it has been improved and has new useful features, such as tje ability to skip single versions or an interface to manager the blacklisted packages
