### ISSUE TITLE
[BUG/ISSUE] Add button to scoop cleanup -g

### ISSUE THREAD

**Issue by candrapersada** [marticliment/WingetUI#727]
I cannot cleanup a global app:
![gambar](https://user-images.githubusercontent.com/36833664/219117163-56c8ccdc-3fdf-4119-be2b-324137479253.png)
![gambar](https://user-images.githubusercontent.com/36833664/219117457-84754b03-7a5e-4eb5-98ae-3d5c048c3fba.png)

**Comment by marticliment** [comment]
Could you please test the latest commit?

**Comment by candrapersada** [comment]
not working
![image](https://github.com/marticliment/WingetUI/assets/36833664/fab24f3e-7943-43aa-bc3b-0a964db74ac2)
[WingetUI 2.0.0 beta 3](https://github.com/marticliment/WingetUI/releases/tag/2.0.0-beta3)

**Comment by marticliment** [comment]
Yow would need to grant WingetUI administrator rights on launch, which could be really annoying for users.

This would need to be a manual task

**Comment by candrapersada** [comment]
then will there be an option or button to Clean old versions from Cache in `scoop global`?

**Comment by marticliment** [comment]
Yes

**Comment by neoOpus** [comment]
scoop cleanup -a -g -k
