### ISSUE TITLE
[FEATURE REQUEST] readd update all

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#729]
Update all was removed because it was useless, however I think the last QT version made packages unselected by default. So update selected no longer equals update all. 

But I think just the update all icon is enough as there's already a lot of text in the toolbar

**Comment by marticliment** [comment]
On the updates section they should be selected by default. That's a bug!

**Comment by ppvnf** [comment]
How about adding to the context menu an option to update all packages from each pkg manager individually besides updating everything like it is now? There would be options of updating all scoop, chocolatey or winget separately. I don t think it would be necessary for the toolbar since it I think it will be possible to do this kind of selecting when advance search is implemented

**Comment by marticliment** [comment]
but to do this you can just manually select the packages you want from the context menu, can't you?

**Comment by ppvnf** [comment]
Yes, but I think https://github.com/marticliment/WingetUI/issues/584 would achieve what I want easier

**Comment by marticliment** [comment]
Yes, this will come with the advanced search/filtering
