### ISSUE TITLE
[BUG/ISSUE] Install global scoop apps and differentiate them from regular ones

### ISSUE THREAD

**Issue by candrapersada** [marticliment/WingetUI#732]
- I don't see an option to install an app globally
- I cannot uninstall a global app:
![image](https://user-images.githubusercontent.com/56180050/206353644-9feb034e-d7d7-4a71-a903-ab6837526786.png)
- I cannot differentiate between a local and global app:
![image](https://user-images.githubusercontent.com/56180050/206355281-59825554-372f-4023-a228-6f122e167dcc.png)

**Comment by marticliment** [comment]
Could you please test the latest heads again? Thanks!

**Comment by candrapersada** [comment]
I don't see an option to install an app global and I cannot differentiate between a local and global app in [WingetUI 1.6.2 (release 2)](https://github.com/marticliment/WingetUI/releases/tag/1.6.2-r2)

**Comment by ppvnf** [comment]
this issue seems the same as https://github.com/marticliment/WingetUI/issues/81

**Comment by marticliment** [comment]
Apps can be installed globally from the info window

**Comment by candrapersada** [comment]
can `scoop cleanup *` be used to automatically clean old versions from cache in global scoop on WingetUI?
