### ISSUE TITLE
[FEATURE REQUEST] Add ability to add custom sources for WinGet. Aka Add the REST API

### ISSUE THREAD

**Issue by AwesomeKalin** [marticliment/WingetUI#734]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

I believe it would be useful to be add custom sources to use for Winget, just like you can add scoop buckets

**Comment by marticliment** [comment]
Winget sources do not work as goood as I'd want, at least for now. Until they get them improved, that won't be really possible. 

If I get the COM api to work, this could be also more easily implemented
