### ISSUE TITLE
[BUG/ISSUE]  Bundled Winget list command can't distinguish between VCRedist 2010 x64/x86 

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#735]
So, for some reason the bundled version of Winget CLI and consequently WingetUI has this bug where Microsoft.VCRedist.2010.x64 and Microsoft.VCRedist.2010.x86 are both treated as Microsoft.VCRedist.2010.x64. However, system Winget correctly distinguishes both packages

**Comment by marticliment** [comment]
What system winget are you using?

**Comment by ppvnf** [comment]
v1.4.10173, the same as WingetUI I believe

**Comment by ppvnf** [comment]
This issue seems to also affect Microsoft.VCRedist.2015+ in the same way, and it hinders the ability to update the package (since it is not correctly identified)

**Comment by ppvnf** [comment]
This seems related to https://github.com/microsoft/winget-cli/issues/2448 and https://github.com/microsoft/winget-cli/issues/2995, however I do not get it why the problem happens only with the bundled WingetCLI
