### ISSUE TITLE
[BUG/ISSUE] "No package found matching input criteria" beta version winget pkg

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#736]
I get this error when trying to install any Winget pkg using the latest [commit ](https://github.com/marticliment/WingetUI/commit/a846d2028896faa2c691eb8315f5c96c7c1916f3) (doesn't matter if building or running the .py file). The latest stable version works fine though. I am on Windows 10, Python 3.11.2

**Comment by marticliment** [comment]
Any package? There's not any package that works?

**Comment by ppvnf** [comment]
I don't think so. I have tried gsudo, firefox and pdf-xchange

**Comment by marticliment** [comment]
However, installing form the context menu works, right?

**Comment by ppvnf** [comment]
that is correct
