### ISSUE TITLE
how to select InstallerType and Scope on winget in WingetUI

### ISSUE THREAD

**Issue by candrapersada** [marticliment/WingetUI#739]
how to select firefox InstallerType: `wix` or `exe` and how to select firefox Scope: `user` or `machine`

**Comment by marticliment** [comment]
The scope choose is a feature that had been requested somewhere in the issues list.

Could you please explain more the wix/exe installer?

**Comment by candrapersada** [comment]
![gambar](https://user-images.githubusercontent.com/36833664/220477266-b10e1529-9d79-4d0a-aa3f-cbfc0688304b.png)

**Comment by ppvnf** [comment]
selecting installerType is not supported yet https://github.com/microsoft/winget-cli/issues/1166
scope will be possible using https://github.com/marticliment/WingetUI/issues/140#issuecomment-1515124085

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/233397238-895f3f22-31ca-4c3a-8238-d3808509fcc5.png)

**Comment by marticliment** [comment]
This will come with the next version
