### ISSUE TITLE
[FEATURE REQUEST] Retain Local Copy Of Installer

### ISSUE THREAD

**Issue by adrianmmiller** [marticliment/WingetUI#742]
I service a number of machines, with exact SOE, while WingetUI is a great tool for knowing WHEN software has updated, it is practically useless in my usage case because you cant even grab a local copy of the installer, because once its installed, that installer is removed.

This seems INSANE to me 

I dont want to install WingetUI on 10 PC's and download the same software 10 times...maybe in your country data is so readily available its a non-issue, but thats not universal...

This seems like a total no-brainer feature, please add, or at least leave the installer until the next update so those of us with more than one PC to look after AND data restrictions can re-use the installer......

What would be handy would be to use one PC as a local repo for all others, and point other PCs at it as an option in their WingetUI, as in a first preference for update source, and if not found THEN download from the original source.

**Comment by marticliment** [comment]
I am sorry, but this is how winget/chocolatey/scoop work, and this behaviour can't be changed. 
WingetUI is only an interface, a fontend, and does not manage the actual sotware downloads and installs.

You may post that  on microsoft/winget-cli, which is the repository in charge of developing the package manager itself.
