### ISSUE TITLE
[BUG/ISSUE] Error 5 When updating chocolately (WingetUI v1.6.0)

### ISSUE THREAD

**Issue by adrianmmiller** [marticliment/WingetUI#746]
WingetUI attempted to updated itself upon loging. IT failed **badly**, throwing error 5 (permission denided) when reaching the point of trying to replace chocolately, no amount of Try Again would work at this point, and cancelling removed WingetUI

Sub ideal....

**Comment by cwt515** [comment]
same issue, wingetUI was removed from my application list but if I try to uninstall (either with winget or Windows11) it says it's not available. So I dont have a way to re-install WingetUI either.

**Comment by marticliment** [comment]
For now, please install wingetui again from github.

do you run any chocolatey auto updater or anything similar that runs chocolatey in the background?

**Comment by cwt515** [comment]
> 

Unfortunately I can neither install or uninstall, see below. I had one chocolatey app installed, all other applications were winget.

![image](https://user-images.githubusercontent.com/65136219/221421110-dda8f7c6-39a3-4b47-865a-b4a715a56ecf.png)

**Comment by adrianmmiller** [comment]
> For now, please install wingetui again from github.
> 
> do you run any chocolatey auto updater or anything similar that runs chocolatey in the background?

Hi, i did manually install the latest

I have never used chocolately, not once.....

**Comment by ppvnf** [comment]
Today WingetUI successfully update from 1.6 to 1.6.1. It asked me to restart the PC though

**Comment by adripo** [comment]
It also happened to me. I had to manually taskkill `wingetui.exe` and press `Retry` to complete the update without `Error 5`. For some reason winget was still running during the update.

**Comment by marticliment** [comment]
> Today WingetUI successfully update from 1.6 to 1.6.1. It asked me to restart the PC though

This is from vcredist

**Comment by adrianmmiller** [comment]
Leaving open from my end as a placeholder warning to any 1.6.0 users...hopefully most will manually install later versions in the next few days

Technically closed as a bug from my perspective anyways

Close when you feel is appropriate @marticliment and thanks.

**Comment by marticliment** [comment]
This issue (should) have been fixed in version 1.6.2
