### ISSUE TITLE
[BUG/ISSUE] v1.6.1 wiped all chocolatey packages during update

### ISSUE THREAD

**Issue by adripo** [marticliment/WingetUI#747]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [ ] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [ ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Automatic update to v1.6.1 wiped all chocolatey packages that were installed with version 1.6.0

**Comment by marticliment** [comment]
Dit update to v1.6.2 also do that?

**Comment by adripo** [comment]
I have disabled Chocolatey since last update so I couldn't check, sorry.

**Comment by marticliment** [comment]
Then the introduced changes worked
