### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by mimimass16** [marticliment/WingetUI#750]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [ ] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [ ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## To Reproduce
Steps to reproduce the behaviour:

## The Log

<details>

```
Please paste here the log (Go to the three dots menu on the top-right corner of WingetUI -> Winget Log. 

If the issue can be reproduced, please send the log AFTER reproducing the issue (1. Launch WingetUI, 2. Reproduce the issue, 3. Paste the log)
```

</details>

**Comment by marticliment** [comment]
This issue has been fixed, and a nwew version will be released soon with the fix
