### ISSUE TITLE
[BUG/ISSUE] (Add the ability to change the folder for installing programs)

### ISSUE THREAD

**Issue by mimimass16** [marticliment/WingetUI#754]
Hello, add the ability to change the folder for installing the program, that is, the autoruns program, which is not installed and it just opens after the jump, then it installs in an unknown folder for me to look for it, but I never found it and deleted it

**Comment by marticliment** [comment]
Hi @mimimass16,

I don't understand you. Could you please provide more details?

**Comment by marticliment** [comment]
Now I see what you mean.

This issue is not related with winget, but rather with the package manager used to install the program., Could you please tell me the source of the package you are willing to install?

**Comment by marticliment** [comment]
the source, you will. find it in the right column of the package list. it will be. winget, scoop or chocolatey

**Comment by marticliment** [comment]
If right-clicking -> packatge info, and then you copy the shown command and run it on a cmd window, does it do the same thing?
![image](https://user-images.githubusercontent.com/53119851/221681336-c20e97c2-6fe6-46a8-9057-31b3651754c3.png)

**Comment by marticliment** [comment]
Yes?

**Comment by marticliment** [comment]
> > If right-clicking -> packatge info, and then you copy the shown command and run it on a cmd window, does it do the same thing?
> > ![image](https://user-images.githubusercontent.com/53119851/221681336-c20e97c2-6fe6-46a8-9057-31b3651754c3.png)
> 
> no, since I can specify a bunch and even if I don’t specify the path, it will install where the folder path is by default

what do you mean when saying _I can specify a bunch_?

**Comment by marticliment** [comment]
Ah, I see what you mean. 

However, this is winget's fault, not wingetui. 
Winget is (one of) the tools that wingetui uses to install software. And it is winget who is in charge to install software and generate icons/shortcuts. 

I'm sorry, but this can't be fixed here.
