### ISSUE TITLE
[BUG/ISSUE] WingetUI 1.6.2 (release 2): Overwriting the existing installation with this version changes the language to German

### ISSUE THREAD

**Issue by RavenMacDaddy** [marticliment/WingetUI#766]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Upon overwriting the existing installation (cause the Discover section was just looping; i.e., simple troubleshooting), suddenly the language of the installations was changed to German, which I noticed as the app made its initial boot (see the pic below).

## To Reproduce
Steps to reproduce the behaviour:
1. Overwrite the existing installation with version WingetUI 1.6.2 (release 2) 
2. Start the app

## Expected behaviour
As English is (I presume?) the default language for the app – and the one that's used by the existing installation, it ought to still be the active language.

## Screenshots

![image](https://user-images.githubusercontent.com/67732686/222218002-d1125d58-d7fd-435b-be99-77aa222a1fed.png)

## The Log

[Log.txt](https://github.com/marticliment/WingetUI/files/10863874/Log.txt)

**Comment by marticliment** [comment]
You don't happen to have your system in german, right?

**Comment by RavenMacDaddy** [comment]
> You don't happen to have your system in german, right?

All in English.

![image](https://user-images.githubusercontent.com/67732686/222224499-5e85e009-a194-40e1-99e7-10970d3a7352.png)

**Comment by marticliment** [comment]
Reinstalling version 1.6.2 does reproduce the issue?

**Comment by marticliment** [comment]
In version 1.6.1, which language have you set?

**Comment by RavenMacDaddy** [comment]
> In version 1.6.1, which language have you set?

Always English – never had a reason to change it.

**Comment by marticliment** [comment]
in the .wingetui folder in your user profile there's a file called Preferred Language.

please post both the 1.6.1 and 1.6.2 file contents

**Comment by RavenMacDaddy** [comment]
Both had default, and overwriting the app again, reproducing the case in this issue (i.e., 1.6.1 > 1.6.2), doesn't reproduce the changed language phenomenon – so if you aren't able to figure it out, we can close the issue for now.

**Comment by marticliment** [comment]
I will try to reproduce it, but i have never faced that issue and I don't have any other report about this happening

**Comment by marticliment** [comment]
This issue hasn't appeared again, right?

**Comment by RavenMacDaddy** [comment]
Closing for now as I'm currently not using the app.

**Comment by HulkSmashBurgers** [comment]
I have this issue after an update to 1.7.0
