### ISSUE TITLE
[BUG/ISSUE] Info menu (sha256 field) should show only numbers

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#771]
<img width="488" alt="Screenshot 2023-03-02 143339" src="https://user-images.githubusercontent.com/73800734/222552210-52de53c0-8138-49a4-86ef-813cdd031da8.png">

**Comment by marticliment** [comment]
Which package manager shows that?

**Comment by ppvnf** [comment]
winget pkgs (all of them probably)

**Comment by marticliment** [comment]
This issue was fixed in a previous commit
