### ISSUE TITLE
[BUG/ISSUE] (Getting and showing manifest file by local search is better)

### ISSUE THREAD

**Issue by Weidows** [marticliment/WingetUI#774]
I prefer to use third party scoop buckets, but when i search and show the manifest which not in official github buckets, I'll get a wrong manifest url (404)

![image](https://user-images.githubusercontent.com/61131704/222717555-a93cf122-1fbb-401a-81d0-9fd1dc1bb671.png)

the manifest below belongs to `apps` bucket above, the following is wrong:

https://github.com/ScoopInstaller/apps/blob/master/bucket/wpsoffice-cn.json

![image](https://user-images.githubusercontent.com/61131704/222717463-29261087-4f98-47f3-82d6-5a6c07f66e3b.png)

**Comment by marticliment** [comment]
Fixed on https://github.com/marticliment/WingetUI/commit/15401afaeb1ea71659dfa2318165288de00b5824

The fix will be available on the next release
