### ISSUE TITLE
[BUG/ISSUE] updating apps that require restart do not make them disappear from the update list

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#776]
Unfortunately I forgot the name of the app so I can not test it again :astonished:, but I remember that it was from Winget last month and it would remain on the update list until I refreshed it. I was gonna test it today to make it sure it was still a problem, but I do not know any app that requires restart 

related to https://github.com/marticliment/WingetUI/issues/121

**UPDATE** https://github.com/marticliment/WingetUI/issues/776#issuecomment-1502260694

**Comment by marticliment** [comment]
for this, I would need the output code of the installer.

it is winget who should standardize output codes, since every app has a different output code when restarted.

chocolatey has its own one, so it is their job to fix that.

**Comment by ppvnf** [comment]
I really can not remember the name of the app, or any that requires restart in fact. However, I believe this problem do not happens with only a specific package, since WingetUI was able to detect that a restart was needed, but did not remove it from the update list immediately

**Comment by marticliment** [comment]
So it happens always or only sometimes?

**Comment by ppvnf** [comment]
It happened just once, but I do not think it was specific to that package

**Comment by ppvnf** [comment]
maybe close this since we do not know how to test it

**Comment by ppvnf** [comment]
Could this be reopened ? This problem just happened again to me
<img width="960" alt="Screenshot 2023-04-10 220854" src="https://user-images.githubusercontent.com/73800734/230988837-41b22cb7-7948-4bf5-80bd-45fada4a2673.png">
