### ISSUE TITLE
[BUG/ISSUE] Recently installed packages appear incorrectly in the install section

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#781]
1. Install/update a package
2. Check this package on the install section
3. See error (the package below is from Winget. I have not tested with Scoop/Chocolatey)

<img width="920" alt="Screenshot 2023-03-09 142404" src="https://user-images.githubusercontent.com/73800734/224037235-c5590a2e-52e0-4ae7-91bc-c55d940aa16f.png">

**related to https://github.com/marticliment/WingetUI/issues/121**

**Comment by marticliment** [comment]
this might be the actual cause. for a reported issue where some packages wouldnt show properly in the install section
