### ISSUE TITLE
[FEATURE REQUEST] Export packages on a timer

### ISSUE THREAD

**Issue by marticliment** [marticliment/WingetUI#786]
Backup package list on a file every x time.

Sent Through mail by a translator.

**Comment by umarabdullah23** [comment]
+1
A Backup option will be great. And sending by email will not need a database either.

**Comment by ianalexis** [comment]
MVP = :icecream:
MMP = :shaved_ice:
MLP = :ice_cream:

Trigger :gun::
- _**X Time**_ :clock4: :icecream: :
- - Trigger or Check if X time passed.
- - For those whit 24/7 background WinGetUI
- **_Every time WinGetUI open/closes_**  :shaved_ice:: 
- - Must read last export for changes to avoid useless export.
- - For those without background WinGetUI

Where :open_file_folder::
- **_Custom directory_** :file_folder: :icecream:: 
- - Easy task and easy to sync with onedrive or sftp.
- **_Email_** :e-mail: :ice_cream::
- - Harder and risky :bangbang: but nice idea.

Files:
- Last :page_facing_up: :icecream::
- - Name = [PcName]-WingetUi-AutoExport.json
- - - Content: Last export with date YYMMDD HHMMSS
- Historic file :book: :shaved_ice::
- - Name = [PcName]-WingetUi-History.json
- - - Content: Last X versions with changes.
- - - Need to check
