### ISSUE TITLE
[BUG/ISSUE] Labels in updates all out of alignment

### ISSUE THREAD

**Issue by eidylon** [marticliment/WingetUI#795]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Packages are not displaying properly. Hard to really explain, as they say, a picture is worth a thousand words. The screenshot shows it all. Lines 2 and 3 are completely fubared.

## To Reproduce
Steps to reproduce the behaviour:
1. Launch UI
2. Click on `Software Updates`
3. Look at the list.

## Expected behaviour
The packages with updates should display properly.

## Screenshots
![image](https://user-images.githubusercontent.com/5951045/225026141-6c0edfe4-cff4-4c4b-b532-10ac80bd1199.png)

## The Log

<details>
C:\Users\aabdi\AppData\Local\Programs\WingetUI\sudo\gsudo.exe
C:\Users\aabdi\AppData\Local\Programs\WingetUI\sudo
🟢 checkQueue Thread started!
🟡 Using bundled lang file (forced=False)
🟡 Using bundled lang file (forced=True)
It took 0.01000070571899414 to load all language files
🔵 Starting main application...
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
b'v1.4.10173\r\n'
None
updating winget
Reactivation signal ignored: RaiseWindow_[1678313466.8525567]
{'wingetFound': True, 'scoopFound': False, 'chocoFound': False, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'Scoop is disabled', 'chocoVersion': 'Chocolatey is disabled', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
🔵 Is Dark
Can't disconnect
🟢 Starting winget search, winget on C:\Users\aabdi\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Discover tab loaded
Can't disconnect
🟢 Starting winget search, winget on C:\Users\aabdi\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Upgrades tab loaded
Can't disconnect
🟢 Starting winget search, winget on C:\Users\aabdi\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Discover tab loaded
{'System language': 'default', 'Arabic - عربي\u200e (95%)': 'ar', 'Bulgarian - български (88%)': 'bg', 'Bangla - বাংলা (25%)': 'bn', 'Catalan - Català': 'ca', 'Czech - Čeština (95%)': 'cs', 'Danish - Dansk (47%)': 'da', 'German - Deutsch (88%)': 'de', 'English - English': 'en', 'Spanish - Castellano': 'es', 'French - Français': 'fr', 'Hindi - हिंदी (76%)': 'hi', 'Hungarian - Magyar': 'hu', 'Italian - Italiano': 'it', 'Indonesian - Bahasa Indonesia (22%)': 'id', 'Japanese - 日本語 (82%)': 'ja', 'Korean - 한국어 (92%)': 'ko', 'Dutch - Nederlands (95%)': 'nl', 'Polish - Polski (95%)': 'pl', 'Portuguese (Brazil) (95%)': 'pt_BR', 'Portuguese (Portugal) (95%)': 'pt_PT', 'Russian - Русский (76%)': 'ru', 'Serbian - Srpski (20%)': 'sr', 'Turkish - Türkçe (79%)': 'tr', 'Ukranian - Yкраї́нська (79%)': 'ua', 'Simplified Chinese (China) (95%)': 'zh_CN', 'Traditional Chinese (Taiwan) (95%)': 'zh_TW'}
['System language', 'Arabic - عربي\u200e (95%)', 'Bulgarian - български (88%)', 'Bangla - বাংলা (25%)', 'Catalan - Català', 'Czech - Čeština (95%)', 'Danish - Dansk (47%)', 'German - Deutsch (88%)', 'English - English', 'Spanish - Castellano', 'French - Français', 'Hindi - हिंदी (76%)', 'Hungarian - Magyar', 'Italian - Italiano', 'Indonesian - Bahasa Indonesia (22%)', 'Japanese - 日本語 (82%)', 'Korean - 한국어 (92%)', 'Dutch - Nederlands (95%)', 'Polish - Polski (95%)', 'Portuguese (Brazil) (95%)', 'Portuguese (Portugal) (95%)', 'Russian - Русский (76%)', 'Serbian - Srpski (20%)', 'Turkish - Türkçe (79%)', 'Ukranian - Yкраї́нська (79%)', 'Simplified Chinese (China) (95%)', 'Traditional Chinese (Taiwan) (95%)']
en
{'default': 'System language', 'ar': 'Arabic - عربي\u200e (95%)', 'bg': 'Bulgarian - български (88%)', 'bn': 'Bangla - বাংলা (25%)', 'ca': 'Catalan - Català', 'cs': 'Czech - Čeština (95%)', 'da': 'Danish - Dansk (47%)', 'de': 'German - Deutsch (88%)', 'en': 'English - English', 'es': 'Spanish - Castellano', 'fr': 'French - Français', 'hi': 'Hindi - हिंदी (76%)', 'hu': 'Hungarian - Magyar', 'it': 'Italian - Italiano', 'id': 'Indonesian - Bahasa Indonesia (22%)', 'ja': 'Japanese - 日本語 (82%)', 'ko': 'Korean - 한국어 (92%)', 'nl': 'Dutch - Nederlands (95%)', 'pl': 'Polish - Polski (95%)', 'pt_BR': 'Portuguese (Brazil) (95%)', 'pt_PT': 'Portuguese (Portugal) (95%)', 'ru': 'Russian - Русский (76%)', 'sr': 'Serbian - Srpski (20%)', 'tr': 'Turkish - Türkçe (79%)', 'ua': 'Ukranian - Yкраї́нська (79%)', 'zh_CN': 'Simplified Chinese (China) (95%)', 'zh_TW': 'Traditional Chinese (Taiwan) (95%)'}
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Main application loaded...
Win32Mica Error: win32 version 19045 is not supported
Name                                            Id                                  Version       Available
Piriform.CCleaner was blackisted
Ultimaker.Cura was blackisted
ShiningLight.OpenSSL was blackisted
ElectronicArts.EADesktop was blackisted
🟢 Winget search finished
, was blackisted
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 3
🟡 package Entity Framework 6.1.3 Tools  for Visual S… failed parsing, going for method 2...
Entity Framework 6.1.3 Tools  for Visual S… {2A56910C-69C8-495D-8ED8-9080F0A14E58}      14.0.41103.0 88
🟡 package Update for  (KB2504637) failed parsing, going for method 2...
Update for  (KB2504637)                     {CFEF48A8-BFB8-3EAC-8BA5-DE4F8AA267CE}.KB2… 1 88
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 332
None
🟢 Winget search finished
🟢 Total packages: 4314
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Announcement URL: https://www.marticliment.com/resources/wingetui.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🟢 Starting winget search, winget on C:\Users\aabdi\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
Name                                            Id                                  Version       Available
🟢 Winget search finished
Piriform.CCleaner was blackisted
Ultimaker.Cura was blackisted
ShiningLight.OpenSSL was blackisted
ElectronicArts.EADesktop was blackisted
, was blackisted
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 3
🔵 Copying log to the clipboard...
</details>

**Comment by eidylon** [comment]
Interesting.... fwiw, this issue seems to have automatically corrected itself today. There's only one update (I did some via CLI yesterday) and it has its labels looking fine. 

![image](https://user-images.githubusercontent.com/5951045/225402212-882ae11d-2455-48d0-aedb-e375a85c518f.png)

So not sure if this was just a fluke on the winget catalog backend or something? (although it didn't occur in the winget CLI).

**Comment by marticliment** [comment]
It might just be that for whatever the reason winget parsing got bugged...

Anyway, I will close this, but if the issue reapers, make sure to post back here and i'll reopen this
