### ISSUE TITLE
[FEATURE REQUEST] Import/Export capability of apps

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#800]
I saw that there is an open issue already for backing up a list of apps every X time with #786, but I would like to be more specific in this feature request and see if it aligns or not with that request.

I would like to have the following backup (export) / restore (import) capabilities with WingetUI as follows:
1) Export - be able to export all the currently installed apps to a file with all the details that WingetUI knows such as: Name, package ID, Installed Version, Soruce and etc.).
2) Import - be able to import the apps from point 1 with a granular selection of which apps to install or not based on parameters such as:
 * Only specific source(s).
 * Specific version of a given package and not always the latest that is currently available.

Subsequent imports of the same app list should handle the current state of the installations and ask for each package what the user wants to do:
* For already installed package: Revert to the specific version from the app list, update it to latest or do nothing.
* For apps that are not installed: Install the app with the specific version from the app list, install the latest version or do nothing.

Hope it was clear enough 🙂

**Comment by marticliment** [comment]
could you please repost this comment on the original issue?

it is to not have duplicate trackers for a same feature request.

Thanks!

**Comment by Mikey1993** [comment]
> could you please repost this comment on the original issue?
> 
> it is to not have duplicate trackers for a same feature request.
> 
> Thanks!

I don't think they are the same, this is why I opened this new one.
I think #786 needs to be migrated to this one as this one is more detailed and not the other way.
What do you think?

### Posting here the additional feature from #786:
Backup package list on a file every x time.

**Comment by marticliment** [comment]
Feature number 1 won't be implemented for the time being.
Feature number 2 will come in the next release:
![image](https://github.com/marticliment/WingetUI/assets/53119851/3ac42ed3-b1c0-48af-b886-1439ce6571ef)
![image](https://github.com/marticliment/WingetUI/assets/53119851/112fe3b7-ae07-46e8-a0cb-d3249118f1d8)
