### ISSUE TITLE
[BUG/ISSUE]  Badly parsed update

### ISSUE THREAD

**Issue by AbitFishy** [marticliment/WingetUI#805]
## Before submitting the issue

- [X ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ X] **I have checked that I am running the latest version of WingetUI**
- [X ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [ X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [ X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
There is an update available via winget source called "The following packages have an upgrade available, but" that looks like an obvious parsing error of winget's output.
![image](https://user-images.githubusercontent.com/5720804/225939827-6a630002-60bf-472a-a957-4b0fb69a0076.png)
![image](https://user-images.githubusercontent.com/5720804/225940038-f8402813-c813-4a08-abb0-9545afc334c1.png)
![image](https://user-images.githubusercontent.com/5720804/225940119-80764cba-6460-4978-9690-fa24d9d8006d.png)

now when I try to update it, it obviously fails with the no package found error: 
![image](https://user-images.githubusercontent.com/5720804/225940387-0c78fb9d-4b47-43c5-bce8-ccb5e6c00800.png)

## To Reproduce
Steps to reproduce the behaviour:
1. Open or freshly install or reset WingetUI
2. Look at updates

## Expected behaviour
A package that actually exists to show up under updates

## Screenshots
see above

## The Log

[winget log.txt](https://github.com/marticliment/WingetUI/files/11002616/winget.log.txt)

## Additional context
I'm using the built-in winget
The "loading" in the info screen never seems to finish

**Comment by marticliment** [comment]
Does this _always_ happen, or reopening the info windows helps?

Because winget has issues with the info command sometimes

**Comment by Heart1010** [comment]
I hang in here... updated to v1.6.3 and also have a 'strange upgradable package' in the list now:

![image](https://user-images.githubusercontent.com/1481680/225986056-4f51e006-58ec-4c6f-8637-7e12311e10f0.png)

**Comment by marticliment** [comment]
Yes, it is also not good. I will try to fix that.

**Comment by marticliment** [comment]
Meanwhile you can disable the updater and sticik with 1.6.2

**Comment by Nereithr** [comment]
> I mean, it actually makes sense, since v1.6.3 does not introduce changes to the winget engine, so it might just have been a coincidence

Can confirm the issue began for me in 1.6.2, [here is a link to a comment](https://github.com/marticliment/WingetUI/issues/369#issuecomment-1472011694) in issue #369 with a bit more info on how I encountered the bug.

**Comment by Mikey1993** [comment]
Yup, also got bad parsing for  this one here with the latest 1.6.3 version:
![image](https://user-images.githubusercontent.com/8223772/226209395-0800bee3-4185-4f64-8283-11e662a2bb30.png)

**Comment by AbitFishy** [comment]
> Does this _always_ happen, or reopening the info windows helps?

Sorry for the delay, yes, the loading the dialog box always happens with this "package" even after following all the troubleshooting steps the checkboxes had me do

**Comment by ppvnf** [comment]
was this fixed by https://github.com/marticliment/WingetUI/commit/188560473e30ebc8f7ace91b606df3d91df7d7d8?

**Comment by marticliment** [comment]
Yep
