### ISSUE TITLE
[BUG/ISSUE] Typo in WingetUI Settings

### ISSUE THREAD

**Issue by ciaranchen** [marticliment/WingetUI#807]
## Before submitting the issue

- [*] **I have checked that I am running the latest version of WingetUI**
- [*] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [*] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug - Just a typo

![image](https://user-images.githubusercontent.com/19751193/226094913-6175d51d-d208-44b3-939c-fbb038d92ab1.png)

![image](https://user-images.githubusercontent.com/19751193/226095049-eff0e942-b0c6-41ae-bd3d-6b736974edfc.png)

This option is "Directly install when double-clicking an item on the **Discover Software** tab (instead of showing the package info)". But the text on the tab page is **"Discover Packages"**.

**Comment by marticliment** [comment]
The issue has been fixed, but effects will take one day or two to be applied
