### ISSUE TITLE
[FEATURE REQUEST] ICU format in translations

### ISSUE THREAD

**Issue by flatron4eg** [marticliment/WingetUI#808]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

For now in translations we are not able to use ICU message format, which is very usefull when translating context dependent strings. For example, now for russian/ukranian/lot of slavic languages [we cannot translate line "{0} updates are available" properly](https://app.tolgee.io/projects/1205/translations/single?id=1003412489) cause word "updates" in this cause depends on number value (I think you already saw my translations, so it should be clear).

## Describe the solution you'd like

There is [PyICU package](https://gitlab.pyicu.org/main/pyicu) that I found which wraps C++ implementation of ICU.

**Comment by rumplin** [comment]
Translations are done in Tolgee.io, there It would help to have screenshots of where the text is used.

**Comment by marticliment** [comment]
I will take a look at this, it looks promising

**Comment by marticliment** [comment]
Hello,

I am afraid this will not be part of WingetUI in the near future.

I am sorry
