### ISSUE TITLE
Properly handle global and local Scoop apps

### ISSUE THREAD

**Issue by sitiom** [marticliment/WingetUI#81]
WingetUI does not differentiate between global and local Scoop apps, see this example:
![image](https://user-images.githubusercontent.com/56180050/179127954-ef1a0ad0-4771-4003-9d35-7884e2b3e2a9.png)
![image](https://user-images.githubusercontent.com/56180050/179127963-9aea7695-a4c3-4db3-83f7-a89eb410f38a.png)

Right now, I can't update global Scoop apps, as this error appears:
![image](https://user-images.githubusercontent.com/56180050/179126389-09bf8513-c2b6-403f-b15e-102218704359.png)

The ability to install and uninstall Scoop apps globally is also essential. When installing, uninstalling, or updating an application globally, "run as admin" **needs** to be checked.

### Checklist
- [x] Updates
- [x] Uninstallation
![image](https://user-images.githubusercontent.com/56180050/206353644-9feb034e-d7d7-4a71-a903-ab6837526786.png)
- [x] Specify installation scope
- [x] Differentiate between a local and global app:
![image](https://user-images.githubusercontent.com/56180050/206355281-59825554-372f-4023-a228-6f122e167dcc.png)
It would be great if the global app had something like `(Global)` suffixed or similar to an `info` column in Scoop:
![image](https://user-images.githubusercontent.com/56180050/206355590-e2cf22d8-cd82-4348-8327-9ee8033d115e.png)

**Comment by martinet101** [comment]
I see

**Comment by candrapersada** [comment]
will there be support for installing, updating and removing packages as admin+global?

**Comment by sitiom** [comment]
WingetUI cannot detect the difference between global and local apps in both [Scoop](https://github.com/martinet101/WingetUI/issues/81) [and](https://github.com/martinet101/WingetUI/issues/142) [Winget](https://github.com/martinet101/WingetUI/issues/123). This is the biggest problem for me from using this GUI. I have a bunch of global and local apps, and WingetUI cannot manage them properly.

**Comment by martinet101** [comment]
Yes, this is a pending thing.

**Comment by martinet101** [comment]
Hi @sitiom, 

could you please test the latest head? Because this issue should be fixed by now.

**Comment by sitiom** [comment]
> Hi @sitiom,
> 
> could you please test the latest head? Because this issue should be fixed by now.

Doesn't work? And I don't see an option to install an app globally:
![image](https://user-images.githubusercontent.com/56180050/206353644-9feb034e-d7d7-4a71-a903-ab6837526786.png)

**Comment by aaronliu0130** [comment]
i think the needsauthoranswer tag can be removed for now

**Comment by ppvnf** [comment]
I believe this is related to #474

**Comment by candrapersada** [comment]
I cannot cleanup a global app:
![gambar](https://user-images.githubusercontent.com/36833664/219117163-56c8ccdc-3fdf-4119-be2b-324137479253.png)

**Comment by marticliment** [comment]
@candrapersada, could you please open a new issue?

Thanks!

**Comment by ppvnf** [comment]
I think this issue and https://github.com/marticliment/WingetUI/issues/732 were partially fixed by https://github.com/marticliment/WingetUI/commit/6ed9bab5fe515547e758308dc658fa7c31f952f3

**Comment by marticliment** [comment]
Yes, it is only missing the part of detection

**Comment by sitiom** [comment]
Added a checklist to complete on the first comment: https://github.com/marticliment/WingetUI/issues/81#issue-1305463914

**Comment by marticliment** [comment]
Yes!
