### ISSUE TITLE
[FEATURE REQUEST] Currently installed packages should have their rows marked on the "Discover Packages" tab

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#810]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

When I am looking for an app in the "Discover Packages" tab, I am often forgetting that I already have this app installed, and need to check back in the "Installed Packages" tab to make sure about it.
More visibility in this tab would be great.

## Describe the solution you'd like

- It would be much better if the rows of the currently already installed packages would have their background be highlighted green (or something in this matter) to indicate I already have this app installed and it's the latest version of this package.
- Moreover, I also suggest highlighting a row orange if there is a pending update for this package in the "Software Updates" tab for more clarity.

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/745ff338-2812-4056-8a56-d568f8143edb)

**Comment by marticliment** [comment]
Will come with the next release
