### ISSUE TITLE
[BUG/ISSUE] "Installed Packages" tab is not being updated until a manual refresh

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#811]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
After installing the Git package manually outside of Winget/WingetUI, it's not being reflected in the "Installed Packages" tab.
See pic:
![image](https://user-images.githubusercontent.com/8223772/226144221-ecd4b79a-148f-4f87-b246-087371c01b04.png)

After manually refreshing (F5) the tab, it shows correctly.
* Note: I have waited for a long time for the tab to refresh itself, but it didn't, so I guess there is no mechanism to refresh it automatically?

## To Reproduce
Steps to reproduce the behaviour:
1. Go to "Installed Packages" tab
2. Search for a package in the search
3. Note the current version in the UI
4. Update the package to a new version **not** via WingetUI/Winget
5. Get back to WingetUI and specifically to the "Installed Packages" tab
6. It still shows the old version from step 3 no matter how long you wait
7. ONLY after refreshing the UI (F5) it does show the correct version. The user should not be doing this manually.

## Expected behaviour
Package version should be updated to the latest in the UI

## Suggested ways to correct this
I would suggest WingetUI to try and have the following features to remedy that:
1. Refresh the "Installed Packages" tab according to external installs, e.g. if the user installed new app not via the app, and its name is the same as the package name/ID, try to refresh these packaged in WingetUI to have the updated versions in the UI.
2. Maybe also a good way would be: When searching for an app in the "Installed Packages" tab (and also if bringing WingetUI to the front when still in the search results screen), and after maybe 2 seconds of no new input in the search textbox, try to fetch info about the packages that came in the search results, and update the UI - this way the UI will always have the latest updated info possible.

**Comment by Mikey1993** [comment]
I guess it's somewhat related to #121, but this should be better handled by WingetUI I think, and so I suggest doing both of the suggestions here.

**Comment by marticliment** [comment]
Yes, i will track this issue on #121 as well.

**Comment by ppvnf** [comment]
I think the solution for this issue would be to make the install section be refreshed after x minutes together with the update section when check for updates periodically is enabled

**Comment by marticliment** [comment]
Or maybe just refresh it when showing the WingetUI Window.

I'm in the way of studying it
