### ISSUE TITLE
[BUG/ISSUE] Discover packages tabbar buttons need to be on the context menu

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#814]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
When selecting multiple package from the "Discover Package" tab, then hitting the install package (which is also an error and show be renamed to "Install packages" when multiple selections are selected), it will install the marked/highlighted package, and not the ones which are selected with the "V" mark.

## To Reproduce
Steps to reproduce the behaviour:
1.  "Discover Package" tab
2. Select multiple packages to install (select the V in the most left column)
3. Hit the "Install package" (should be changed to "Install packages" IMO when multiple packages are selected)
4. See that it's only installing the package that is marked in blue and not the packages that are selected by the "V" in the most left column which is erroneous.

## Expected behaviour
The packages which are selected with the "V" should be installed and not the one which is highlighted (last selected via mouse).

See the screenshot:
![image](https://user-images.githubusercontent.com/8223772/226148372-441c3f8c-43a6-4316-874a-3eed815d0149.png)

**Comment by Mikey1993** [comment]
By the way, this also applies for the other buttons such as the "Show package info", this behavior should probably be fixed for them as well.

**Comment by marticliment** [comment]
You should click on "Install selected packages"

**Comment by marticliment** [comment]
THis might need to be added on the context menu, actually

**Comment by Mikey1993** [comment]
> You should click on "Install selected packages"

I don't think I should do that.
I already have the "install package" button which I know installs a package, it's redundant to have the "Install selected packages" text to use that when selecting multiple apps in the UI and not intuitive at all. it's confusing.

I want that when you click on the "install package" button, that everyone know installs a package, it will install all the packages that are selected, that's all, simple as that.

One button to rule them all named "Install selected package(s)". 
I don't know about the context menu.

**Comment by ppvnf** [comment]
this was fixed on beta, right?
