### ISSUE TITLE
[FEATURE REQUEST] Be able to select all or deselect all packages in the tables via a checkbox in the title row

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#815]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

I would like to select multiple packages to install for example, but I need to select them one by one.
For example a scenario where I would like to install all of these and a "select all" checkbox would be helpful here:
![image](https://user-images.githubusercontent.com/8223772/226149392-af1bca80-f5cc-46fd-abe8-19ac24d039f5.png)

## Describe the solution you'd like

It would be helpful to add a "select all" checkbox on the title row to select the visible packages that are currently in view. Do it for all the tables on all the three tabs.

**Comment by marticliment** [comment]
This can't be done on qt. 

However, you have those buttons:
![image](https://user-images.githubusercontent.com/53119851/226203252-3ebd8a8f-07e9-4650-80b5-c62935dd06bb.png)

**Comment by Mikey1993** [comment]
> This can't be done on qt.
> 
> However, you have those buttons: ![image](https://user-images.githubusercontent.com/53119851/226203252-3ebd8a8f-07e9-4650-80b5-c62935dd06bb.png)

What a joke.. :(
So why can't we put them at the top row in the table?

**Comment by marticliment** [comment]
I don't think Qt supports widgets on QHeaderItems. At least i couldn't find how to do that.

Sometimes, when developing we need to adapt to toolkits, languages and libraries limitations.

**Comment by Mikey1993** [comment]
@marticliment,
https://stackoverflow.com/questions/71342916/pyqt6-how-to-check-a-checkbox-within-table-view-when-selecting-an-item
Do this helps?

Unfortunately I have no experience with coding with PyQt6, so I don't really know what works and what's not.
I guess you need to implement it yourself and that it's not that straightforward as you've said with PyQt6.

Thanks for trying though.
