### ISSUE TITLE
[FEATURE REQUEST] Better first time usage for automatic updates

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#816]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

The auto update feature is hidden pretty well in the settings under the tray options, it should be more visible and reachable for the simple user.

## Describe the solution you'd like

I suggest adding the setting of "Update packages automatically" to:
1. The "Software Updates" tab somewhere above the table
2. To the tray icon options to be selected on deselected easily (also maybe add the "Check for updates every" to here as well as I think it's appropriate)

**Comment by ppvnf** [comment]
Another thing to make the automatic update option more easy to notice would be to rename 'notification options' to 'update options' ('close to tray' would be moved to general settings in this case):
<img width="620" alt="Screenshot 2023-04-24 192526" src="https://user-images.githubusercontent.com/73800734/234079701-ffabe25b-1225-4042-85ec-0e4a1de04422.png">

**Comment by ppvnf** [comment]
1.7 fixed this, right?

**Comment by marticliment** [comment]
No, since I plan to add some kind of Welcome Wizard
