### ISSUE TITLE
[BUG/ISSUE] Selecting a package should highlight its row, but it doesn't

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#817]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
When selecting a package it's not being highlighted (taking focus from the previously selected package).

## To Reproduce
Steps to reproduce the behaviour:
1. Go to "Discover Packages" tab
2. Click on package 1 from the list via mouse click, see that it's being highlighted.
3. Select a different package (check the V in the checkbox)
4. The package is not being highlighted (the row is not highlighted and the previous package is still being highlighted)

## Expected behaviour
After selecting a package, its row should be highlighted and the previous highlighted package should not be highlighted.

See the issue below with the screenshot:
![image](https://user-images.githubusercontent.com/8223772/226150425-8b51ef98-3553-41a1-bad8-d0712f61a42c.png)

**Comment by marticliment** [comment]
This issue was fixed on the lates commit. You will be able to experience the fix once a next version is released
