### ISSUE TITLE
[FEATURE REQUEST] Show a breakdown of how many apps are shown in the table from each source in the UI

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/WingetUI#822]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the solution you'd like

I suggest adding a breakdown of the packages by source like so:
1. In the "Discover Packages" and "Software Updates" tab breakdown the packages to the sources that are currently loaded from the table (Winget/Chocolatey/Scoop) something like that:
![image](https://user-images.githubusercontent.com/8223772/226207282-2f324590-1e0f-4bf4-a785-8f97515a2c06.png)

2. In the "Installed packages" do the breakdown the same for all the sources (even for the Local PC/Steam/Microsoft Store ones for better visibility).
![image](https://user-images.githubusercontent.com/8223772/226207466-4b993f85-ade5-431a-9db3-cdfb723ad2c1.png)

**Comment by ppvnf** [comment]
This breakdown could be shown when hovering the number of packages found or the text
