### ISSUE TITLE
[BUG/ISSUE] (-\|  No installed package found matching input criteria.)

### ISSUE THREAD

**Issue by neoOpus** [marticliment/WingetUI#828]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
-\| 
No installed package found matching input criteria.

## Screenshots
![wingetui_ua4O4knNxy](https://user-images.githubusercontent.com/1388336/226592440-588781c4-515b-4a0d-bfa5-1e9ad726d483.png)

![wingetui_YQK5cvoYfa](https://user-images.githubusercontent.com/1388336/226592464-a9a49b32-d359-4dd0-a29d-ea1400d5acd3.png)

![TxyhVXNSI3](https://user-images.githubusercontent.com/1388336/226592508-3d0c4891-9f94-4962-892d-7d78789e2a8b.png)

## The Log

[Winget Bug Log.txt](https://github.com/marticliment/WingetUI/files/11027735/Winget.Bug.Log.txt)

<details>

```
Please paste here the log (Go to the three dots menu on the top-right corner of WingetUI -> Winget Log. 

If the issue can be reproduced, please send the log AFTER reproducing the issue (1. Launch WingetUI, 2. Reproduce the issue, 3. Paste the log)
```

</details>

**Comment by marticliment** [comment]
Does this happen when using winget console client?

**Comment by neoOpus** [comment]
This happens for this package, I didn't test with CLI and did the update by manually downloading the files from the links and installing them regularly.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/DotNet/DesktopRuntime/6/6.0.15/Microsoft.DotNet.DesktopRuntime.6.installer.yaml

**Comment by marticliment** [comment]
please test it with the cli, since this package tends tok give issues in general

**Comment by ppvnf** [comment]
I think this could be the same issue as https://github.com/marticliment/WingetUI/issues/735

**Comment by marticliment** [comment]
it might well be

**Comment by neoOpus** [comment]
> please test it with the cli, since this package tends tok give issues in general

![image](https://user-images.githubusercontent.com/1388336/226782827-f29b57ea-5f24-4c26-b751-5d8f9b74c387.png)

**Comment by marticliment** [comment]
IT might be or it might not, since VCRedists nd .NET, with their propretary installers tend to give errors with winget cli, and there

**Comment by Jamisonfitz** [comment]
Happened for me today for Discord Winget

No installed package found matching input criteria.

https://marticliment.com/wingetui/share?pid=d.Discord&pname=Discord%20Discor

**Comment by marticliment** [comment]
> Happened for me today for Discord Winget
> 
> No installed package found matching input criteria.
> 
> https://marticliment.com/wingetui/share?pid=d.Discord&pname=Discord%20Discor

Hello,

In your case, you happen to have a malformed URL. Can you please check if names or IDs in your system show properly or are cut out?

**Comment by CodersPlayground** [comment]
I'm having the same issue, and yes it appears the ID is cut out. Tested on WingetUI 2.0.0 b2 and 1.7.0

Name: Discord Discord.Disc   ID: ord   Installed Ver: 1.0.9012   New Ver: 1.0.9013   Source: Winget

I also have this unknown package that showed up

Name: The following packag   ID: es   Installed Ver: have   New Ver: an   Source: Winget

**Comment by marticliment** [comment]
This isseue has been fixed, coming with the next release

**Comment by ShowMeBillyJo** [comment]
@marticliment Thank you for resolving this! Out of curiosity, which commits and/or PRs fix this bug? I didn't see this issue's ID number referenced anywhere, so I'm guessing it ended up being a side effect of another reported issue.

**Comment by marticliment** [comment]
I just forgot to mention it, i think it was c900cbcaade2b41e7b7f2a02c9d42a10207e453d

**Comment by marticliment** [comment]
Hello, @PCAssistSoftware,

if the cli also has this issue you might want to report that on https://github.com/microsoft/winget-cli
