### ISSUE TITLE
[CHOCO] Install parameters

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#835]
similar to https://github.com/marticliment/WingetUI/issues/140, but for Chocolatey.

Example:
`choco install virtualbox --params "/NoDesktopShortcut /ExtensionPack"`

To find out about parameters you can look at the description: https://community.chocolatey.org/packages/virtualbox#description

**Comment by marticliment** [comment]
Since it is basically the same feeature, i will mark this as a duplicate and post the progress there
