### ISSUE TITLE
[CHOCO] Publish WingetUI on Chocolatey repository

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#840]
I think it is always good to have another way to install WingetUI :smiley:

I have no idea how to do it though

**Comment by marticliment** [comment]
I don't understand what are you referring to

**Comment by ppvnf** [comment]
simply being able to install WingetUI by running `choco install wingetui`

**Comment by marticliment** [comment]
ah yes, choco installation is a work in progress

**Comment by marticliment** [comment]
Pending approval!

https://community.chocolatey.org/packages/wingetui/1.7.1

**Comment by marticliment** [comment]
Approved!

**Comment by ppvnf** [comment]
quite an old version though. Is it gonna be automatically updated when a new version is released?

**Comment by marticliment** [comment]
next version of WingetUI will be published there. I am working on a beta rn.

Autopublish is a thing i am working on
