### ISSUE TITLE
[FEATURE REQUEST] improve WingetUI systray icon hover text

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#841]
when starting WingetUI you get this icon:

<img width="15" alt="Screenshot 2023-03-23 170005" src="https://user-images.githubusercontent.com/73800734/227267569-a1b880b7-f98e-4a3c-960b-fcd8eac8eac2.png">

however, its hover text is 
<img width="44" alt="Screenshot 2023-03-23 170753" src="https://user-images.githubusercontent.com/73800734/227267703-b83e4d3b-701a-4e4c-976b-3fcfccd48da9.png">

which is the same for the no updates available icon
<img width="16" alt="Screenshot 2023-03-23 171753" src="https://user-images.githubusercontent.com/73800734/227267915-1dac5258-83cd-46d6-be1f-0ba283564119.png">

so I suggest changing the hover text for the initialization icon to "WingetUI - initializing". You could also change the hover text of the grey icon to "WingetUI - no updates available"

**Comment by marticliment** [comment]
Yeah, why not

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/228896545-dd4f73fd-76c2-4211-bc9d-82bd1b710f36.png)
![image](https://user-images.githubusercontent.com/53119851/228896705-f9ca5ff8-2fc1-44cb-b669-83fe1ce76f5d.png)
