### ISSUE TITLE
[BUG] Share functionality has no translation tags

### ISSUE THREAD

**Issue by rumplin** [marticliment/WingetUI#856]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

The Share functionality, which was added recently to version 1.6.4 is missing translations tags in Tolgee.

**Comment by marticliment** [comment]
Now they are
