### ISSUE TITLE
[CHOCO] Uninstall fails without admin privileges / Option to launch Chocolatey as admin

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#857]
Today I tried to uninstall vlc-nightly without using the admin privileges. It returned the following message:

`ERROR: Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"`

Of course, it is easy to simply uninstall as admin. However, in order to improve the user experience, could not this be done automatically or have an option to always perform Chocolatey operations as admin (which would also solve https://github.com/marticliment/WingetUI/issues/690)?

Related to https://github.com/marticliment/WingetUI/issues/671 and https://github.com/marticliment/WingetUI/issues/659

**Comment by marticliment** [comment]
it should elevate itself automatically, but it is not doing it
