### ISSUE TITLE
[WINGET] Package not listed

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#859]
voidtools.Everything is not being shown for some reason (but it appears on CLI), while voidtools.Everything.Alpha and voidtools.Everything.Lite appear normally on both WingetUI and CLI

<img width="872" alt="Screenshot 2023-03-31 010207" src="https://user-images.githubusercontent.com/73800734/228983508-fa528bac-32a9-4b37-971e-e1e2efe56e76.png">
<img width="605" alt="Screenshot 2023-03-31 010130" src="https://user-images.githubusercontent.com/73800734/228983510-2f774019-d89b-4eed-917c-a473a2a1fe0d.png">

**Comment by unwillinglyawesome** [comment]
I confirm the app does not list `voidtools.Everything` from Winget.
![image](https://user-images.githubusercontent.com/129231322/229232850-6bceba5e-55ea-4d6f-a0e8-231bbec17f28.png)
```
PS C:\Users\Sergey> winget search everything --source winget
Name               Id                           Version     Match
-----------------------------------------------------------------------------------
Everything         voidtools.Everything         1.4.1.1022  ProductCode: everything
EverythingToolbar  stnkl.EverythingToolbar.Beta 0.8.0.1     Tag: everything
EverythingToolbar  stnkl.EverythingToolbar      1.0.3       Tag: everything
Everything Lite    voidtools.Everything.Lite    1.4.1.1022
Everything (Alpha) voidtools.Everything.Alpha   1.5.0.1339a
```

Furthermore, it does not list `everything`, `everything.install`, `everything.portable` and `es` (Everything Command Line) from Chocolatey.
https://community.chocolatey.org/packages?q=%22everything%22

![image](https://user-images.githubusercontent.com/129231322/229235346-f0b28d5b-3d4e-4716-885e-384db49c64e2.png)

**Comment by ppvnf** [comment]
I think Everything was blacklisted https://github.com/marticliment/WingetUI/commit/f1ca2774b9faed899f18d9a827f370a6d905e5ba

**Comment by marticliment** [comment]
True.

I will add a trailing space on the id, in a way that it does not skip the everythingXXX packages
