### ISSUE TITLE
[FEATURE REQUEST] Ask for admin privileges if needed when installing WingetUI

### ISSUE THREAD

**Issue by alexolog** [marticliment/WingetUI#860]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

When trying to install WingetUI into a subfolder in `C:\Program Files` (or any other privileged location), the installer fails with "insufficient privileges", even when the installing user is a member of the Administrators group.

Re-running the installer with "Run as administrator" works, but it's an extra step when installing updates:
1. Download installer from the "releases" page
2. Run it from within the browser
3. Click through all the dialogs, confirming existing settings
(WinGetUI was originally installed to `C:\Program Files\WingetUI`, leave as is)
4. Installer cannot continue because of insufficient privileges
5. Utter your choice of expletives (optional step, but rarely skipped)
6. Close installer
7. Open the folder that the installer was downloaded into
8. Right click on the installer, select "Run as administrator"
9. Continue installation
10. Close folder

## Describe the solution you'd like

Many installers of other programs pop up a UAC prompt to continue instead of failing.
I'd like the WingetUI installer to do the same.

The workflow now becomes:
1. Download installer from the "releases" page
2. Run it from within the browser
3. Click through all the dialogs, confirming existing settings
(WinGetUI was originally installed to `C:\Program Files\WingetUI`, leave as is)
4. Installer pops up a UAC screen
5. Accept and continue installation

**Comment by marvnl** [comment]
Yes indeed. After every reboot, the process gsudo also keeps asking for admin approval. Obviously, if you publish something like this, make sure that it is a systems app. But if installed as user app, then have something in place for this to solve the admin rights issue.

**Comment by marticliment** [comment]
Yes, administrator rigths are not expexted to be maintained across reboots. This is explained on the welcome wizard
