### ISSUE TITLE
[WINGET] Hyphen shouldn't affect search results

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#862]
I had reported this issue regarding Scoop in https://github.com/marticliment/WingetUI/issues/350. It seems Chocolatey never uses hyphen. The problem is with Winget (both regular CLI and WingetUI). For example 7-zip will not be shown if typed 7zip or 7 zip. Could this be improved like you did with Scoop?

**Comment by marticliment** [comment]
Fixed on 608e78c8d0b89c021b4d1fe23f3b2ffc0e377f30
