### ISSUE TITLE
[SCOOP] Incorrect powershell 7 execution policy

### ISSUE THREAD

**Issue by PhantomGamers** [marticliment/WingetUI#867]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked that this issue is not an issue with the scoop utility, but rather with its implementation on WingetUI**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the issue

After installing Scoop through WingetUI I am unable to install packages due to the following error:
> scoop.ps1 cannot be loaded because running scripts is disabled on this
system.

I have tried to uninstall Scoop through WingetUI but uninstalling gives me this error:
```
Running uninstaller script...
You cannot call a method on a null-valued expression.
At line:1 char:1
+ $arch = $architecture.SubString(0,2)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Users\username\scoop\apps\scoop\current\lib\core.ps1:455 char:27
+     if (!(Test-Path -Path $dir)) {
+                           ~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
   PathCommand

Convert-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Users\username\scoop\apps\scoop\current\lib\core.ps1:458 char:24
+     Convert-Path -Path $dir
+                        ~~~~
    + CategoryInfo          : InvalidData: (:) [Convert-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Conv
   ertPathCommand
   ```

and trying to click the install button results in the install script reporting that Scoop is already installed.

I have also tried manually running `Set-ExecutionPolicy Unrestricted` in an elevated powershell window but after all of these steps the issue remains.

**Comment by ppvnf** [comment]
That seems to be the case. You could try to manually remove Scop as explained in https://github.com/ScoopInstaller/Scoop/issues/4701#issuecomment-1028336117 and then reinstall it from CLI following the instructions from scoop.sh

**Comment by marticliment** [comment]
Did the solution provided by @ppvnf work?

**Comment by ppvnf** [comment]
I don't think it is possible to fix Scoop uninstall through WingetUI (since even on CLI you can't uninstall it in this case), however I think being unable to properly install Scoop is an important thing to fix

**Comment by PhantomGamers** [comment]
Sorry I forgot to reply to this but I wound up solving it by running `Set-ExecutionPolicy RemoteSigned` specifically in `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`, prior I was just running it in PowerShell under terminal which uses PowerShell 7, which has different permissions from the default Windows PowerShell 5 installation.

I'll leave this issue open as I think WingetUI should be properly setting this permission and that I shouldn't have had to manually correct it but if you think it should be closed feel free to do so.
