### ISSUE TITLE
[BUG] ModuleNotFound

### ISSUE THREAD

**Issue by Devopsik404** [marticliment/WingetUI#873]
OS: Windows
                   Version: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: Unknown
                   Program: WingetUI
           Program section: Main script

-----------------------------------------------------------------------------------------

WingetUI Log:

Traceback (most recent call last):
  File "__init__.py", line 11, in <module>

ModuleNotFoundError: No module named 'PySide6.QtGui'<class 'ModuleNotFoundError'>: No module named 'PySide6.QtGui'

**Comment by rumplin** [comment]
Did you use the 1.6.5 version when this issue happened?

**Comment by marticliment** [comment]
This is likely to have happened due to a broken installation.

Please try reinstalling WingetUI and try again

**Comment by ppvnf** [comment]
@Devopsik404 Link to the latest version: https://github.com/marticliment/WingetUI/releases/latest/download/WingetUI.Installer.exe

**Comment by ppvnf** [comment]
I have been able to reproduce this issue accidentally. It happened after I closed the installer in the middle of the install. Reinstalling fixed the issue. I am not sure if there is any way to improve the installer to prevent this from happening though.

**Comment by marticliment** [comment]
When the application is not installed correctly WingetUI will crash, since required components would not be present.
The installer is Inno setup, so it can't be modified, but you are not supposed to kill an installation, right?
