### ISSUE TITLE
[BUG/ISSUE] Package names are winget messages

### ISSUE THREAD

**Issue by Dixet** [marticliment/WingetUI#874]
Winget 1.6.5

In the list of updatable packages there are two that look more like headers/messages than packages. Their install of course fails with no package available
"The following packages have an upgrade available, but r"
"Name   Id    Version     Avail"

## Screenshots
<img width="965" alt="Schermafbeelding 2023-04-05 131935" src="https://user-images.githubusercontent.com/8961696/230069546-72b12888-f848-4915-b1ce-412abf7416a9.png">

## The Log
[wingetlog.txt](https://github.com/marticliment/WingetUI/files/11158197/wingetlog.txt)

**Comment by kirashi3** [comment]
Same here. Either something gone done broke in the last couple of days, or WinGetUI installed a strangely named "Name Id Version Availab" software on my system without my consent.

![image](https://user-images.githubusercontent.com/5917227/230539853-120b7539-0799-4dce-92bc-497bc2c0903d.png)
