### ISSUE TITLE
Fast feedback (chat)

### ISSUE THREAD

**Issue by panther7** [marticliment/WingetUI#879]
Is posible create chatroom for fast feedback, like on [gitter.im](https://app.gitter.im) or [discrod](https://discord.com/app)? For "all" projects.

Example for fast report:
```
Missing translation string:
- `We could not {action} {package}. Please try again later. Click on \"{showDetails}\" to get the logs from the installer.`
```

**Comment by marticliment** [comment]
please email me at marti@marticliment.com to discuss that

**Comment by panther7** [comment]
Missing string is relevant issue, sorry, if it was not clear.

```
We could not {action} {package}. Please try again later. Click on \"{showDetails}\" to get the logs from the installer.
```

@marticliment

**Comment by marticliment** [comment]
ah that was real, I thought it was an example

**Comment by marticliment** [comment]
please email me so. I can give you my telegram, I don't want to post it here publicly

**Comment by panther7** [comment]
> please email me so. I can give you my telegram, I don't want to post it here publicly

Check your email, my telegram sent. Thanks
