### ISSUE TITLE
[BUG/ISSUE] interactive uninstall button is not working

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#880]
nothing happens when clicking this option (context menu still works tho, except for Scoop). For Scoop I guess the button should display an error message similar to what the more info button does for local pc packages, saying it is unavailable or simply uninstall.
<img width="341" alt="Screenshot 2023-04-06 153552" src="https://user-images.githubusercontent.com/73800734/230397943-cc0fe1c0-2239-44cd-9179-05321e3d1216.png">

**Comment by marticliment** [comment]
Fixed in c00d0a418b2006ea044d6e61e0d785bc20c5dbd1
