### ISSUE TITLE
[BUG/ISSUE] "The following packages have an upgrade available but require explicit targeting" shows up as a package

### ISSUE THREAD

**Issue by aaronliu0130** [marticliment/WingetUI#882]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
See the screenshot. This is the message in `winget upgrade` for reference:
```
11 upgrades available.

The following packages have an upgrade available, but require explicit targeting for upgrade:
Name                         Id              Version      Available   Source
----------------------------------------------------------------------------
Microsoft Teams              Microsoft.Teams 1.5.00.28361 1.6.00.6754 winget
Teams Machine-Wide Installer Microsoft.Teams 1.5.0.4689   1.6.00.6754 winget
```

## To Reproduce
Steps to reproduce the behaviour:
1. Install old version of package that needs explicit upgrading
2. Scan for packages that need upgrade

## Expected behaviour
Winget ignores the message.

## Screenshots
![image](https://user-images.githubusercontent.com/11874211/230498612-19d0514b-b0aa-4826-b885-7f274cf7ec48.png)

## The Log

N/A

**Comment by ShayBox** [comment]
Same here 
![image](https://user-images.githubusercontent.com/9505196/230538307-0128293d-17f5-4bab-a4ef-53033e60358f.png)

**Comment by kirashi3** [comment]
Same here. Either something gone done broke in the last couple of days, or WinGetUI installed a strangely named "Name    Id       Version  Availab" software on my system without my consent.

![image](https://user-images.githubusercontent.com/5917227/230539671-0b6aaf30-11ba-412b-a2f2-fcc85da54c09.png)

**Comment by marticliment** [comment]
yes, it is

**Comment by aaronliu0130** [comment]
oops, sorry

**Comment by marticliment** [comment]
no worries, the one here lists unlisted packages in the other one

**Comment by marticliment** [comment]
Fixed!
Fix coming with the next version
