### ISSUE TITLE
[FEATURE REQUEST] Disable UAC with autoupdate feature on

### ISSUE THREAD

**Issue by mikekuzak** [marticliment/WingetUI#885]
Hi 

I have WingetUI running in the tray and it will check for new packages every day. When it finds a package to upgrade a UAC prompt comes up. Is there a way to omit this? I want it to be silent update in the background, no prompts on nothing. 

Thanks

**Comment by marticliment** [comment]
I am aware of this, and I'm in the ways of smirking this out

**Comment by marticliment** [comment]
the best approach for it, however, will be for it to ask once for administrator rights and then "cache" the administrator rights

**Comment by ppvnf** [comment]
Like it was described in https://github.com/marticliment/WingetUI/issues/520#issuecomment-1407374740 I assume

**Comment by marticliment** [comment]
probably yes, in the same way

**Comment by marticliment** [comment]
From next version and beyond, users will have the ability to choose between some options regarding how administrator rights are treated.
![image](https://user-images.githubusercontent.com/53119851/232163195-57c83768-60a1-4069-bed2-c37b422f8466.png)
