### ISSUE TITLE
[FEATURE REQUEST] Import/export WingetUI settings

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#891]
## Before submitting the issue

- [X] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

If you want to have the same WingetUI settings in 2 machines you can manually copy the files from the .wingetui folder to a new computer, but It would be easier if WingetUI could do this for the user.

## Describe the solution you'd like

A button to export settings and another to import them in the configuration tab. Exporting would create a ZIP with the configuration files and the import would replace the current settings with the ones from the ZIP.

**Comment by DailenG** [comment]
Where is this config? Is it a file that can be parsed? I was looking at creating a GPO ADMX for managing each client's settings. If it's in the registry this is pretty easy, but an INI might require a login script. Didn't see an INI or anything in registry.

**Comment by ppvnf** [comment]
%UserProfile%\.wingetui

**Comment by marticliment** [comment]
> Where is this config? Is it a file that can be parsed? I was looking at creating a GPO ADMX for managing each client's settings. If it's in the registry this is pretty easy, but an INI might require a login script. Didn't see an INI or anything in registry.

The configuration is represented by indivisual files, where if the file exists the setting is enabled, and if not it is disabled. Some files might store values inside

**Comment by DailenG** [comment]
Maybe this will help. I don't write Python but I'm pretty fluent in PowerShell, so I wrote it in PowerShell then converted it. Let me know if there's some other way I should submit this.

Convert Config To Single File: https://gist.github.com/DailenG/40db87032199c579a08c211f529f264a
Convert Single File to Config: https://gist.github.com/DailenG/bcee5f20fbc1f6866312096e8e878837


Same Scripts Converted to Python using ChatGPT (Please verify!)
Convert Config to Single File: https://gist.github.com/DailenG/487cab0a9c3d56737dcfc9a955c171c3
Convert Single File to Config: https://gist.github.com/DailenG/7c06b6ef10c9845745807455958b2080

**Comment by vanbang9710** [comment]
May I ask if all files in %UserProfile%\.wingetui are settings? Because I want to use some script to automate the process of backing-up the settings.

**Comment by marticliment** [comment]
yes, they are there

**Comment by neoOpus** [comment]
For some reason, the export generates an empty file. Could someone please perform a test to confirm this?

**Comment by ppvnf** [comment]
> For some reason, the export generates an empty file. Could someone please perform a test to confirm this?

same for me

**Comment by vanbang9710** [comment]
> `%UserProfile%\.wingetui`

This doesn't exist anymore?

**Comment by marticliment** [comment]
now it is under %localappdata%\UniGetUI
