### ISSUE TITLE
[BUG/ISSUE] (pag) down keys are unable to properly scroll the package list

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#894]
related to https://github.com/marticliment/WingetUI/issues/275

Currently the pag down and also the regular down keys are not able to scroll down the package list past the last loaded package (in the Discovery section). Only by using the mouse wheel/scroll bar it is possible to continuously scroll down the package list

**Comment by ppvnf** [comment]
I didn't study the code, but would it be possible to do something like when the last package is selected more are shown?

**Comment by marticliment** [comment]
I'm not sure, since the issue is that when triggering the pag-down keys scrollEvents are not properly called by Qt

**Comment by ppvnf** [comment]
A partial fix happened maybe? the scroll will continue past the cached list indefinitely if you use the scrolling wheel to load more packages once. This behavior happens on 1.7 beta, but not on 1.6.5

**Comment by marticliment** [comment]
possibly caused by the smooth scrolling mechanism
