### ISSUE TITLE
[FEATURE REQUEST] issues coming from error reports should include log

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#895]
there are issues such as https://github.com/marticliment/WingetUI/issues/820 where people don't type anything. I think I have found out why they do that. When in the page https://www.marticliment.com/error-report/ they click on "Open a new issue" and submit it thinking the log is already included. I am not sure how to solve it, but you could change the link to https://github.com/marticliment/WingetUI/issues/new?assignees=&labels=bug&template=bug-report--something-is-not-working-as-expected-.md&title= so they at least have to type a title before creating it

**Comment by marticliment** [comment]
Oh, I see this could work very well. Thanks!

**Comment by ppvnf** [comment]
how about modifying the issue templates to something like https://github.com/JosefNemec/Playnite/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
https://github.com/microsoft/winget-pkgs/blob/master/.github/ISSUE_TEMPLATE/package_issue.yml
?

**Comment by marticliment** [comment]
> there are issues such as #820 where people don't type anything. I think I have found out why they do that. When in the page https://www.marticliment.com/error-report/ they click on "Open a new issue" and submit it thinking the log is already included. I am not sure how to solve it, but you could change the link to https://github.com/marticliment/WingetUI/issues/new?assignees=&labels=bug&template=bug-report--something-is-not-working-as-expected-.md&title= so they at least have to type a title before creating it

This has been implemented. You can test it here:
https://www.marticliment.com/error-report/?appName=WingetUI&errorBody={s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}OS:{s}Windows{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Version:{s}(%2710%27,{s}%2710.0.22631%27,{s}%27SP0%27,{s}%27Multiprocessor{s}Free%27){l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}OS{s}Architecture:{s}AMD64{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Architecture:{s}64bit{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Language:{s}Unknown{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Version:{s}2.01{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Program:{s}WingetUI{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Program{s}section:{s}Main{s}script{l}{l}-----------------------------------------------------------------------------------------{l}{l}{l}{l}WingetUI%20Log:{l}{l}{l}{l}{l}Traceback{s}(most{s}recent{s}call{s}last):{l}{s}{s}File{s}%22c:\SomePrograms\WingetUI-Store\wingetui\__init__.py%22,{s}line{s}78,{s}in{s}%3Cmodule%3E{l}{s}{s}{s}{s}from{s}customWidgets{s}import{s}*{l}{s}{s}File{s}%22c:\SomePrograms\WingetUI-Store\wingetui\customWidgets.py%22,{s}line{s}12,{s}in{s}%3Cmodule%3E{l}{s}{s}{s}{s}from{s}PackageManagers.pip{s}import{s}Pip{l}{s}{s}File{s}%22c:\SomePrograms\WingetUI-Store\wingetui\PackageManagers\pip.py%22,{s}line{s}14,{s}in{s}%3Cmodule%3E{l}{s}{s}{s}{s}class{s}PipPackageManager(DynamicLoadPackageManager):{l}{s}{s}File{s}%22c:\SomePrograms\WingetUI-Store\wingetui\PackageManagers\pip.py%22,{s}line{s}39,{s}in{s}PipPackageManager{l}{s}{s}{s}{s}raise{l}{l}RuntimeError:{s}No{s}active{s}exception{s}to{s}reraise%3Cclass{s}%27RuntimeError%27%3E:{s}No{s}active{s}exception{s}to{s}reraise

**Comment by marticliment** [comment]
I have renewed the templates, @ppvnf

**Comment by ppvnf** [comment]
Nice, there is a small typo in the new label you have created "enha<b>n</b>cement".
 Also, please check Telegram.
