### ISSUE TITLE
[BUG/ISSUE] Sharing isn't working for Portuguese

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#897]
Try changing the language to Portuguese (BR and PT) and then click the share icon. The share menu won't open for me. Changing the language to English seems to fix the problem. I have tried French and it also works.

**Comment by ppvnf** [comment]
I translated the string... It should be fixed

**Comment by marticliment** [comment]
Yes, on next lang update this will get fixed. 

Those strings can never be changed, otherwise Python fails to parse the string and therefore crashes. 

In this case it is a minor crash, but it can get worse if it happens on the main script
