### ISSUE TITLE
[BUG/ISSUE] another untranslated string

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#899]
I accidentally found this when reporting the bug of https://github.com/marticliment/WingetUI/issues/776 lol

'Restart your PC to finish installation'
<img width="960" alt="Screenshot 2023-04-10 220854" src="https://user-images.githubusercontent.com/73800734/230990829-32f537ec-43b1-4235-beae-72f3cf215578.png">

**Comment by marticliment** [comment]
I will add it right now.

p.d. @ppvnf, can you please send me an email at marti@marticliment.com?
