### ISSUE TITLE
[FEATURE REQUEST] Ability to blacklist/pin packages when installing

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#902]
similar to https://github.com/marticliment/WingetUI/issues/889, but for the install section

Suppose you have to install a package that you want in a specific version, however you have autoupdate enabled. This will make it pointless to install an old version, since it will instantly try to install the newest one. I suggest having an option in the settings menu, in the context menu or in the info menu that installs and pin/blacklist the package you want to install in a specific version

**Comment by marticliment** [comment]
This will probably go with the install options in the details/more info window.

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/233404686-65d2a22d-6548-4c03-87ba-a0f11927e057.png)
