### ISSUE TITLE
[BUG/ISSUE] Lower version advertised as update

### ISSUE THREAD

**Issue by Khaos66** [marticliment/WingetUI#903]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
I have installed the product `Stardock Fences 4`. WinGetUI is showing an update for the product, even though the version number is lower.

![image](https://user-images.githubusercontent.com/4013009/231144581-152ba69b-8030-4930-8e90-c65832681296.png)

## To Reproduce
Steps to reproduce the behaviour:
1. Install `Stardock.Fences` (Current Version 4.1.0.6) from [their website](https://www.stardock.com/products/fences/)
2. Search for updates
3. Find update to version (4.07.02) which is lower

## Expected behaviour
Only show newer version as updates

## The Log
Neighter `stardock` nor `fences` is mentioned in the logs. I can provide you the logs, but I don't see how that'll be helpfull

**Comment by ppvnf** [comment]
what is the result of running `winget upgrade` on Command Prompt?

**Comment by Khaos66** [comment]
@ppvnf 
![image](https://user-images.githubusercontent.com/4013009/231163412-d0e5def8-075a-4dcd-8cf4-35c2401e21d2.png)

**Comment by ppvnf** [comment]
yes, it seems like that specific Winget package has a problem. Stardock.Fences's manifest (https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/Stardock/Fences/4.07.02/Stardock.Fences.installer.yaml) seems out of date. You could either fix it yourself or open an issue in that repo

**Comment by marticliment** [comment]
Yes, this is an issue related to winget-cli.
