### ISSUE TITLE
[FEAT/ISSUE] wingetui clutters home directory

### ISSUE THREAD

**Issue by daephx** [marticliment/WingetUI#907]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug

I really don't like when programs dump files in the root of the user's home directory.
Is there a reason the path `$HOME\.wingetui` was chosen over some flavor of `$APPDATA\WingetUI`?

I looked through the docs/issues and didn't see any other mention of this.
Scoop had a similar problem some time ago due to path string length limits on windows, but the location can be changed using a user environment variable named `SCOOP`.

Assuming there is a strong reason behind keeping the default location, could this be changed in a similar fashion?

**Comment by marticliment** [comment]
I set this choice as it is more transparent for the end user. Different software uses this scheme, only because in linux it works the same and because it is more transparent for the user, therefore being easier to debug.

What you can do is to set your .wingetui folder hidden.

**Comment by daephx** [comment]
That's fair point regarding onedrive. Powershell keeps it's user profile and modules in `~\Documents\WindowsPowerShell` but I have had the sync feature generate some problems files due to mismatching. Think: `profile_{HOSTNAME}.ps1`, because it is built to not override files it can't confidently resolve. Though this has only happened once when I disabled syncing and reenable it on another device.

Looking through my documents I see a number of things, Project files, log/crash dumps, a few configs, database and presets, game saves. I'd say mostly things that are accessible to the user and either static or updated at a slower interval.

Realistically, how often do you expect people to interact with the files in `~\.aptgetui` by hand?
It looks more like cache, language configs and a few feature flag files.
Given the information below, I'd recommend `LOCALAPPDATA`.

---

I haven't personally tested the differences between the appdata folders, but they do cause some confusion.
Here's some quotes regarding `Local`, `LocalLow` and `Roaming`.

- "These folders were introduced in Vista with a view to making management of user profiles easier."

- "In certain network settings, profiles roam with the user regardless of what computer they are on.",
- "Any data in the Roaming folder would follow a user if they logged into another domain-connected PC at their company... Thus, the Roaming folder doesn't do much for a home user..."

- "Windows uses the Local and LocalLow folders for application data that does not roam with the user. Usually this data is either machine specific or too large to roam.",
- "Local stores data only on one PC. It's up to the developers what goes where, but generally data in the Local folder is too large to sync or not worth syncing. For instance, you don't need to sync the giant thumbnails file or browser cache to a new PC -- it's just a waste of space and time."

- "LocalLow stays on one PC like Local, but has a lower level of access. It's not too common now. One example is Internet Explorer's Protected Mode."

**Comment by marticliment** [comment]
Interesting finds about the differences...

I will take this into consideration, thanks!

**Comment by ppvnf** [comment]
So `.wingetui\cacheddata` and `.wingetui\lang` would go to `Local` (because it doesn't make sense to sync it), and the settings files would go to `Roaming`. Also, should't `.wingetui\cachedmeta` be move to the temp folder to save disk space?

An interesting fact is that Linux has something called XDG Base Directory Specification but many developers choose to ignore it for several reasons resulting in cluttering of home directory.

**Comment by ppvnf** [comment]
> Also, should't `.wingetui\cachedmeta` be move to the temp folder to save disk space

@marticliment what do you think about this? or  maybe just delete this folder's content when WingetUI is started

**Comment by lostmsu** [comment]
> Different software uses this scheme

Yes, sometimes even Microsoft ones. But it is wrong, and the other software should also consider not using designated directories to be a bug.

On Windows using user home folder for your software can only be justified if you have some configuration files that can only be modified by the user directly. Given WingetUI is a UI application, it should not do that.

**Comment by marticliment** [comment]
All cache and data files will be moved to AppData on the next update.
Regarding settings, I prefer to save them under ~/.wingetui for the time being.
