### ISSUE TITLE
[BUG/ISSUE] Blacklisted package still updates

### ISSUE THREAD

**Issue by Luatan** [marticliment/WingetUI#915]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
If a package or in the "Software Update" tab is selected (not checkbox but clicked on the item itself), and then blacklisted, it is still selected, meaning if the button "Update Package" is clicked, the package is updated.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to Software Updates
2. Select one or multiple updates to blacklist (checkbox)
3. Click on one of the selected updates (not the checkbox but on the item itself)
4.5 (Optional) klick somewhere else in the GUI to unselect the package (darker background) 
5. Click Blacklist packages
6. Click Update Package

In my case I have two Microsoft 365 Apps for Enteprise packages which are not possible to update, even with wingui directly. That's why I noticed this.
After a restart of WingetUI the packages are not selected anymore and the issue is resolved. But it took me some time to figure out what went wrong.

## Expected behaviour
Packages are ignored, even if selected previously.

## Screenshots
You can see, I get the error (which is not the issue here), even though the package is blacklisted.
![Screenshot_2023-04-14_22-30-10](https://user-images.githubusercontent.com/74045606/232149044-137ddb81-099b-4265-8438-ff5f920ed531.png)

## The Log
Don't think the log will help, but here it is:

🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
Reactivation signal ignored: RaiseWindow_[1681499882.3589315]
{'wingetFound': True, 'scoopFound': False, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': 'v1.4.10173\r', 'scoopVersion': 'Scoop is disabled', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
Reached main ui load milestone
🔵 Is Dark
Can't disconnect
🟢 Starting winget search, winget on C:\Users\luatan\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🔵 Starting choco search
🟢 Discover tab loaded
🟢 Found valid cache for chocolatey!
Can't disconnect
🟢 Starting winget search, winget on C:\Users\luatan\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\luatan\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Upgrades tab loaded
Can't disconnect
🟢 Starting winget search, winget on C:\Users\luatan\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\luatan\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Discover tab loaded
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Chocolatey uninstallable packages search finished
🟢 Main application loaded...
Win32Mica Error: win32 version 19045 is not supported
🟢 Chocolatey search finished
🟢 Searching for string ""
🟢 Searching for string ""
Name                                      Id               Version          Available
🟢 Winget search finished
Microsoft.Office was blackisted
Microsoft.Office was blackisted
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🟢 Winget uninstallable packages search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 113
None
🟢 Winget search finished
🟢 Total packages: 11209
🟢 Starting winget search, winget on C:\Users\luatan\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\luatan\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Chocolatey search finished
🟢 Searching for string ""
Name                                      Id               Version          Available
🟢 Winget search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 2
🟢 Starting winget search, winget on C:\Users\luatan\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\luatan\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Chocolatey search finished
🟢 Searching for string ""
Name                                      Id               Version          Available
🟢 Winget search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 2
Win32Mica Error: win32 version 19045 is not supported
args
🟢 Waiting for install permission... title=Microsoft 365 Apps for Enterprise - de-de, id=Microsoft.Office, installId=1681504115.063178
🔵 Current program set to 1681504115.063178
🟢 Have permission to install, starting installation threads...
[]
['C:\\Users\\luatan\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'upgrade', '-e', '--id', 'Microsoft.Office', '--include-unknown', '--source', 'winget', '--accept-source-agreements', '--silent', '--force']
🟢 winget installer assistant thread started for process <Popen: returncode: None args: ['C:\\Users\\luatan\\AppData\\Local\\Programs\...>
-1978335212
Win32Mica Error: win32 version 19045 is not supported
🔵 Sending cancel signal...
🟢 Starting winget search, winget on C:\Users\luatan\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\luatan\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Chocolatey search finished
🟢 Searching for string ""
Name                                      Id               Version          Available
🟢 Winget search finished
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 2
Win32Mica Error: win32 version 19045 is not supported
args
🟢 Waiting for install permission... title=Microsoft 365 Apps for Enterprise - de-de, id=Microsoft.Office, installId=1681504202.649611
🔵 Current program set to 1681504202.649611
🟢 Have permission to install, starting installation threads...
[]
['C:\\Users\\luatan\\AppData\\Local\\Programs\\WingetUI\\winget-cli\\winget.exe', 'upgrade', '-e', '--id', 'Microsoft.Office', '--include-unknown', '--source', 'winget', '--accept-source-agreements', '--silent', '--force']
🟢 winget installer assistant thread started for process <Popen: returncode: None args: ['C:\\Users\\luatan\\AppData\\Local\\Programs\...>
-1978335212
Win32Mica Error: win32 version 19045 is not supported
🔵 Copying log to the clipboard...

## Additional context
If you need more information or screenshots, let me know.

**Comment by marticliment** [comment]
This issue has been fixed, and the fix will be available once a new release is published
