### ISSUE TITLE
[FEATURE REQUEST] Add buckets via URL

### ISSUE THREAD

**Issue by trymeouteh** [marticliment/WingetUI#918]
## Before submitting the issue

- [x ] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [ x] **I have checked that I am running the latest version of WingetUI**
- [ x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [ x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.

WingetUI does not allow for adding any scoop bucket and your limited to selecting official scoop buckets.

## Describe the solution you'd like

An option to add a bucket by pasting the URL of the repo. Weather it is a github repo, gitlab repo, gitea repo or forgejo repo.

**Comment by marticliment** [comment]
From the next version, the user will have the ability to choose to add a custom bucket, and it will be asked to insert the bucket's name and url.
![image](https://user-images.githubusercontent.com/53119851/232241893-ab472cd9-2640-4fdf-a962-956d6b2db5ac.png)
![image](https://user-images.githubusercontent.com/53119851/232241899-3f6c35c8-9e7f-4a3f-8af7-436a2421d652.png)

**Comment by trymeouteh** [comment]
Excellent! Will users be able to deleted custom buckets that they added?

**Comment by marticliment** [comment]
Yes, they will behave in the same way as official buckets

**Comment by trymeouteh** [comment]
Thank you for adding this feature. I really appreciate that.
