### ISSUE TITLE
[CHOCO] Incorrect parsing of package description

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#927]
similar to https://github.com/marticliment/WingetUI/issues/921
It seems that the description of packages containing special html characters is incorrectly parsed

<img width="509" alt="Screenshot 2023-04-18 184303" src="https://user-images.githubusercontent.com/73800734/232847344-a13e3d9d-22e3-4794-a00e-8c783ffe1acf.png">
<img width="528" alt="Screenshot 2023-04-18 184336" src="https://user-images.githubusercontent.com/73800734/232847350-c1fe914c-3f4a-44d9-be28-e36681702026.png">

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/WingetUI/assets/53119851/b94e4e92-8971-415c-978d-e397d7f993c6)
