### ISSUE TITLE
[FEATURE REQUEST/ISSUE] Add missing string to translation files

### ISSUE THREAD

**Issue by kwiateusz** [marticliment/WingetUI#933]
## Before submitting the issue

- [x ] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x ] **I have checked that I am running the latest version of WingetUI**
- [x ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [x ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.
When you right-click on a package in the menu that shows up is the "Show info" string. It is not in the translation files so it is always in English.

Here I found the use of this string:
https://github.com/marticliment/WingetUI/blob/c19f8d8d79b21b2d26ead3592472779b2a4a2c2f/wingetui/uiSections.py#L250

## Describe the solution you'd like
Need to add this string to the translation file. I would love to do it myself, but unfortunately I don't know python and how to develop translations in it.

**Comment by ppvnf** [comment]
I think `show info` appear as `package details` and is now translated

**Comment by marticliment** [comment]
yes, but I deleted the old show jnfo by accident, so it will show in English.

However, versión 1.7.0 is close, so for one or two weeks I don't think it is worth to re-add those missing strings to Tolgee

**Comment by ppvnf** [comment]
now that 1.7 was released it got fixed, right?

**Comment by marticliment** [comment]
Yes!

**Comment by kwiateusz** [comment]
That went fast, thanks.
