### ISSUE TITLE
[CHOCO] SHA512 info menu -  add a break after :

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#937]
hash starting with / should have a break before it (in order to fully display it in one line)

<img width="458" alt="Screenshot 2023-04-20 184622" src="https://user-images.githubusercontent.com/73800734/233437217-d4f352fa-9e14-4344-bef5-b3f2cb64e587.png">

Also similar:

<img width="449" alt="Screenshot 2023-04-21 012003" src="https://user-images.githubusercontent.com/73800734/233506538-69a0bc3e-bd3c-402c-befb-626e3e11a31f.png">

**Comment by ppvnf** [comment]
I have tested the new beta and the problem still happens (same outputs as first post)

**Comment by marticliment** [comment]
![image](https://user-images.githubusercontent.com/53119851/235160371-303e3fbf-a55a-4fb9-9ad6-d521b04f45b6.png)
Now it is. I had to replace \n with <br>
