### ISSUE TITLE
[FEATURE REQUEST] Android Emulator (WSA, Google Play Games, BlueStacks, etc) Support via adb

### ISSUE THREAD

**Issue by upintheairsheep** [marticliment/WingetUI#946]
## Before submitting the issue

- [ ] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [ ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.
Please add support for Android package management, just to manage them for now, sources come later.

## Describe the solution you'd like

ADB can connect to any running Android emulator’s ADB port you set, and then the android emulator will be part of the PC’s package list. Since it would be easy to implement, an “other device” function to manage the packages of phones and smart TVs that run Android would be a nice addition.

**Comment by upintheairsheep** [comment]
Unrelated, but I wonder if Microsoft will ever perfect WinObjC and add support for iOS apps.

**Comment by marticliment** [comment]
in fact, you can currently uninstall android apps from WingetUI, because winget provides this feature by default

**Comment by ppvnf** [comment]
see https://github.com/microsoft/winget-cli/issues/1625

**Comment by MesterPerfect** [comment]
@upintheairsheep 
Have you tried to install APK files using this tool on android emulators?
It works great on Windows Subsystem For Android.

https://github.com/alesimula/wsa_pacman

**Comment by marticliment** [comment]
Yes, and also, there's no way to list all the available apps. This feature is not going to be part of WingetUI, because there's no package manager for WSA

**Comment by upintheairsheep** [comment]
> Yes, and also, there's no way to list all the available apps. This feature is not going to be part of WingetUI, because there's no package manager for WSA

adb shell pm: am I a joke to you?

**Comment by upintheairsheep** [comment]
You could fix this WinGet issue to solve the problem: https://github.com/microsoft/winget-cli/issues/1625
