### ISSUE TITLE
[FEATURE REQUEST] WinGet Create Support (and other PMs too)

### ISSUE THREAD

**Issue by upintheairsheep** [marticliment/WingetUI#948]
## Before submitting the issue

- [ ] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [ ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.
WinGetCreate.exe is harder to use in command line form, as it’s both time consuming and difficult to edit multiple fields, and especially stuff like fixing typos. Additionally it would be nice to get more people on board making app manifests.

**Comment by ppvnf** [comment]
you can also use https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1 to create Winget manifests. I don't know which one is better though

**Comment by aaronliu0130** [comment]
(Also Komac)

**Comment by marticliment** [comment]
Hello,

I am afraid this will not be part of WingetUI in the near future.

I am sorry
