### ISSUE TITLE
[FEATURE REQUEST] Add a Download Count to every package

### ISSUE THREAD

**Issue by upintheairsheep** [marticliment/WingetUI#949]
## Before submitting the issue

- [ ] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section**
- [ ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.
Download counts are a neat thing on app stores, they tell you how many people downloaded your app, and can be useful for seeing analytics and sorting apps by most downloaded, a neat feature would be to add a download count and counter to every package on WinGet to determine how many people downloaded the program, and shows the history of download counts, and uninstall counts would be neat as well.

**Comment by marticliment** [comment]
I'm gonna check of there's any way to get the download count of a package but I don't think this is doable

**Comment by flatron4eg** [comment]
Chocolatey has this info (just installs), but winget and scoop doesn't

**Comment by marticliment** [comment]
And in the way Scoop works, there's no existing way to manually retrieve it.

**Comment by ppvnf** [comment]
don't you think it is worth adding it to Chocolatey packages?

**Comment by marticliment** [comment]
But it is really package-manager dependant, and you can just open the online package manifest and see the download count

**Comment by upintheairsheep** [comment]
WinGet doesn’t
