### ISSUE TITLE
[BUG/ISSUE] error when installing dependency

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#952]
PS C:\Users\Pedro> pip install zroya
Collecting zroya
  Using cached zroya-0.2.4.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: zroya
  Building wheel for zroya (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for zroya (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\zroya
      copying zroya\dismiss_reason.py -> build\lib.win-amd64-cpython-311\zroya
      copying zroya\template_enums.py -> build\lib.win-amd64-cpython-311\zroya
      copying zroya\version.py -> build\lib.win-amd64-cpython-311\zroya
      copying zroya\__init__.py -> build\lib.win-amd64-cpython-311\zroya
      running build_ext
      building '_zroya' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for zroya
Failed to build zroya
ERROR: Could not build wheels for zroya, which is required to install pyproject.toml-based projects
PS C:\Users\Pedro>

**Comment by marticliment** [comment]
you might need to have ms visual studio with cpp build tools on your system.

I do, and it builds and runs (the library) without issues.

**Comment by ppvnf** [comment]
More than 3gb doesn't seem ideal when you don't have a large hard drive
<img width="266" alt="Screenshot 2023-04-24 122705" src="https://user-images.githubusercontent.com/73800734/233970716-991fd191-6801-4e1a-9f44-da3a5baba186.png">

**Comment by marticliment** [comment]
I will try to send you a precompiled version of the module to see if it works

**Comment by marticliment** [comment]
BTW, in theory you need only the build tools core feature

**Comment by marticliment** [comment]
[zroya.zip](https://github.com/marticliment/WingetUI/files/11312457/zroya.zip)

Try extracting this folder to `C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages`
