### ISSUE TITLE
[BUG/ISSUE] newly blacklisted packages are not properly capitalized

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#953]
<img width="491" alt="Screenshot 2023-04-23 233221" src="https://user-images.githubusercontent.com/73800734/233867454-70e86dd3-59f4-4f94-8d8a-565d0e2d9b6e.png">

**Comment by marticliment** [comment]
This issue has been fixed here: https://github.com/marticliment/WingetUI/commit/7a05154fb5d2011c63b9d3b73f25ef624555aae5

You will need to clear your list to see the changes
