### ISSUE TITLE
Untranslated: Ignore selected packages

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#967]
V1.7.0

In the tab Software Updates
- The toolbar icon "Ignore selected packages" is not translated (in Dutch)

![image](https://user-images.githubusercontent.com/10008599/235289427-7f2fde4b-b32e-40e3-ac45-72f58ba02234.png)

**Comment by marticliment** [comment]
For me, they works fine:
![image](https://user-images.githubusercontent.com/53119851/235295688-7dead75e-f70d-4431-b754-a13ed4b4c408.png)

**Comment by marticliment** [comment]
The same thing as #969
