### ISSUE TITLE
[BUG/ISSUE] Systray right click context menu should appear on top of the systray icon when pinned

### ISSUE THREAD

**Issue by rp1231** [marticliment/WingetUI#968]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
If you pin the systray icon to the taskbar,
the Systray right click context menu appears in the extreme right regardless of the position of the icon in the tray.

## To Reproduce
Steps to reproduce the behaviour:
1. Pin the systray icon to the taskbar
2. Right click on the systray icon

## Expected behaviour
The context menu should appear above the icon

**Comment by marticliment** [comment]
this has been done in purpose, so it does not overlay the Taskbar.

**Comment by marticliment** [comment]
ah, I see
