### ISSUE TITLE
Untranslated: new notification options

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/WingetUI#969]
V1.7.0

I discovered two missing translations in Settings - Options for Notification area
After checking Tolgee, it became clear that these had been introduced very recently. So I dug in.
- In Tolgee I completde the outstanding translations and exported the file as lang_nl.json
- I used notepad to check that it contained the newly added sttrings with their proper translations
- copied the json file to ...\AppData\Local\Programs\WingetUI\lang
- quit and restarted WingetUI
- the two new Notification options remain untranslated (see screenshot)

Faulty pointer or failure to read updated language file?

![image](https://user-images.githubusercontent.com/10008599/235294973-4fe5ee34-97a5-4413-8c8a-4928bd4edb3b.png)

**Comment by marticliment** [comment]
For me, they works fine:
![image](https://user-images.githubusercontent.com/53119851/235295651-90b21d8d-923e-454e-9cba-83857324dd09.png)


Please note that the used json is not actually under AppData\Local\Programs\WingetUI\lang, but rather under .wingetui\lang
Try updating that one.

Also, strings translated in tolgee might take a day or two before changes being actually noticeable

**Comment by marticliment** [comment]
If the issue persists please let me know, and I'll reopen this

**Comment by Stephan-P** [comment]
Okay, I corrected my "copy to" folder link to .wingetui\lang. 
So, what's up with the folder AppData\Local\Programs\WingetUI\lang then?


But in  .wingetui\lang the file lang_nl.json that I copy there appears to be immediately overwritten by WingetUI upon starting.
So I cannot test the lang_nl.json that I updated on Tolgee.

**Comment by marticliment** [comment]
So, WingetUI has the base translation files under AppData\Local\Programs\WingetUI\lang

However, at startup, WingetUI downloads latest translations from GitHub and stores them under .wingetui\lang. You can disable this behaviour from here:
![image](https://user-images.githubusercontent.com/53119851/235298890-d583554c-f36c-4483-859a-63e5f39cf505.png)

**Comment by Stephan-P** [comment]
Confirmed!
Updated translations are coming through now.
