### ISSUE TITLE
[BUG] "Stuck" button is slim for some translations

### ISSUE THREAD

**Issue by panther7** [marticliment/WingetUI#971]
Example:

| EN | CZ |
| --- | --- |
| ![Snímek obrazovky 2023-04-29 121845](https://user-images.githubusercontent.com/3808250/235297752-111135ca-6b82-4b2f-96fb-68f1e8ccc1eb.png) | ![Snímek obrazovky 2023-04-29 121626](https://user-images.githubusercontent.com/3808250/235297750-8a76a20a-7fed-417c-96d7-496ded1facb1.png) |

Probably solution: Text [Button], like
```
Stuck initialization here? [Skip] 
```

**Comment by panther7** [comment]
v2.0.0-beta2

Still...

![Uploading 2023-05-16 09 06 47.png…]()

**Comment by marticliment** [comment]
Ah, they are the same. I didn't check and thought #991 was in the beta issue list.
