### ISSUE TITLE
[BUG/ISSUE] text cut out welcome screen

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#973]
<img width="562" alt="Screenshot 2023-04-29 130656" src="https://user-images.githubusercontent.com/73800734/235300677-66a69d00-bf21-4ef9-a286-0ad1c455b85e.png">

**Comment by ppvnf** [comment]
I guess this got fixed by https://github.com/marticliment/WingetUI/pull/1043

**Comment by marticliment** [comment]
Yes
