### ISSUE TITLE
[FEATURE REQUEST] Saving apps updated by winget ui

### ISSUE THREAD

**Issue by MesterPerfect** [marticliment/WingetUI#979]
I suggest that there should be an option to allow the user to keep the files of updates that winget ui downloads
Ex: I have 20 apps that need to be updated
I want to have the ability to download and save these files to install manually or automatically at a later time
Or even keep it in case I have more than one computer in the same house or I have limited internet connection

**Comment by marticliment** [comment]
WingetUI does not download the installers manually, this part is handled by the package managers, so a feature like this can't really be implemented
