### ISSUE TITLE
[BUG/ISSUE] WingetUI Crashes immediately upon startup

### ISSUE THREAD

**Issue by brimwats** [marticliment/WingetUI#983]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- Deleted it and reinstalled it 
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
Crahses immediately after loading. Here's a gif. 
![explorer_qk9FQptO5s](https://user-images.githubusercontent.com/73113656/235355659-9b0b4249-9b0f-47c1-a58e-4bb1cc90a56e.gif)

I can't access the log to see what is happening. Where is the log stored?

**Comment by marticliment** [comment]
This issue has already been reported on #980.
When wingetui closes, can you try opening wingetui from the system tray?
Could you please provide details about your system?

**Comment by marticliment** [comment]
Could you please run this build and send me the console output?
https://we.tl/t-phkAxfhwJe

**Comment by marticliment** [comment]
WingetUI 1.7.1 has this issue fixed!
