### ISSUE TITLE
[BUG/ISSUE] Some Program is already updated and still showing!

### ISSUE THREAD

**Issue by khaledmndev** [marticliment/WingetUI#984]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
I'm updating programs for example (Microsoft Teams and MEGA Cloud Storage) but' it's still asking for them to be updated!
Here's an example of MEGA Cloud Desktop App: 
![image](https://user-images.githubusercontent.com/9519494/235360268-cec8edc6-9688-49b9-9ac8-d072136fc692.png)
![image](https://user-images.githubusercontent.com/9519494/235360340-cacd5293-9f57-4ce3-b15d-bca06322c6b1.png)

**Comment by marticliment** [comment]
Please update it, wingetui will register it as updated and won't show it again until a new version is available

**Comment by khaledmndev** [comment]
i did! multiple times..

**Comment by khaledmndev** [comment]
> Please update it, wingetui will register it as updated and won't show it again until a new version is available

i did! multiple times..

**Comment by marticliment** [comment]
Then try right-click -> skip this version

**Comment by khaledmndev** [comment]
I already did as well, but wanted to ask if there's a fix for it, thank you very much anyways :)

**Comment by ppvnf** [comment]
@marticliment what do you think about automatically skipping the next version if a package with unknown version is updated?
I also think that in this case a message should be shown to inform the user about a package being temporarily added to the blacklist

**Comment by marticliment** [comment]
> what do you think about automatically skipping the next version if a package with unknown version is updated?

That what it is supposed to do, with every package I tested it worked flawlessly. I will continue studying this

**Comment by ppvnf** [comment]
I wonder what might cause this issue, because it seems to be working fine if you upgrade a package with an unknown version to the latest. What would happen if you upgraded again? Would the blacklist be updated replacing the old latest version with the new one?

**Comment by marticliment** [comment]
> I wonder what might cause this issue, because it seems to be working fine if you upgrade a package with an unknown version to the latest. What would happen if you upgraded again? Would the blacklist be updated replacing the old latest version with the new one?

No, they should just stack on the ignored list

**Comment by marticliment** [comment]
@khaledmndev, Is this issue still happening with WingetUI 2.0.1?

**Comment by khaledmndev** [comment]
> 

sadly, I'm having this error almost all of the updates now!

- 
   \ 
   | 
   / 
   - 
   \ 
                                                                                                                        

    1024 KB / 14.9 MB
    2.00 MB / 14.9 MB
    3.00 MB / 14.9 MB
    4.00 MB / 14.9 MB
    5.00 MB / 14.9 MB
    6.00 MB / 14.9 MB
    7.00 MB / 14.9 MB
    8.00 MB / 14.9 MB
    9.00 MB / 14.9 MB
    10.0 MB / 14.9 MB
    11.0 MB / 14.9 MB
    12.0 MB / 14.9 MB
    13.0 MB / 14.9 MB
    14.0 MB / 14.9 MB
    14.9 MB / 14.9 MB
                                                                                                                        

   - 
   \ 
   | 
                                                                                                                        
Found EA app [ElectronicArts.EADesktop] Version 12.208.0.5465
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe
- 
   \ 
   | 
   / 
   - 
   \ 
   | 
   / 
   - 
                                                                                                                        

                                                                                                                        

     381 KB / 2.37 MB
    1.37 MB / 2.37 MB
    2.37 MB / 2.37 MB
Installer hash does not match; to override this check use --ignore-security-hash

**Comment by marticliment** [comment]
Hello @khaledmndev , 

This issue is caused by the publisher of the program providing dynamic links to the installer, so the package manager (microsoft/winget-cli, not marticliment/WingetUI) can't validate its integrity.

If you still want to install that software, you should right-click the failing package ->Skip hash check

**Comment by khaledmndev** [comment]
> Hello @khaledmndev ,
> 
> This issue is caused by the publisher of the program providing dynamic links to the installer, so the package manager (microsoft/winget-cli, not marticliment/WingetUI) can't validate its integrity.
> 
> If you still want to install that software, you should right-click the failing package ->Skip hash check

alright thanks for the info.. I will be back here, and will update you more about the main issue..

**Comment by marticliment** [comment]
Hello,

was this issue fixed?
