### ISSUE TITLE
[WINGET] Packages with version " unknown" are listed in updates

### ISSUE THREAD

**Issue by aaronliu0130** [marticliment/WingetUI#985]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked that this issue is not an issue with the winget utility, but rather with its implementation on WingetUI**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the issue
Apps with "unknown" version are shown in the "Updates" tab.

## To Reproduce
Steps to reproduce the behaviour:
1. Install package with unknown reported version, such as Algodoo.
2. Check for updates.

## The Log

My Log functionality is also not working. "Export to file" freezes the app and "Copy" just doesn't work, including the selection copy.

## Additional context
![image](https://user-images.githubusercontent.com/11874211/235360578-c3f80544-b01e-4117-b6da-28d67fabee2f.png)

**Comment by marticliment** [comment]
If you update them, they will get registered as updated and won't show again. One of the new changes in the support for managing unknown apps

**Comment by aaronliu0130** [comment]
How do I register them as updated without actually updating them?

**Comment by aaronliu0130** [comment]
And how about the logging issue?

**Comment by marticliment** [comment]
> How do I register them as updated without actually updating them?

right click - > skip this version

**Comment by marticliment** [comment]
> And how about the logging issue?

which issue?

**Comment by aaronliu0130** [comment]
1. Pressing any "copy" button related to the logs doesn't work.
2. "Export log as file" hangs the entire app.

**Comment by marticliment** [comment]
Can you please open a new issue for this? Thanks!
