### ISSUE TITLE
[BUG/ISSUE] WingetUI stops responding, when I click on "export selected packages to a file"

### ISSUE THREAD

**Issue by gokberkgs** [marticliment/WingetUI#988]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that I am running the latest version of WingetUI**
- [ ] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [ ] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [ ] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
When I click on "export selected packages to a file" WingetUI stops responding.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Installed Packages'
2.  Click on 'Select all'
3. Click on 'Export selected packages to a file'
4. See error 'WingetUI not responding'

## Expected behaviour
I would expect the program not to stop responding and the export to occur.

## Screenshots
![WingetUI not responding](https://user-images.githubusercontent.com/77885700/235376082-b17e3b74-2d66-45bb-addb-4f69d3942bf8.png)

## The Log
WingetUI stops responding even when I I click on "export log to a file".

<details>

```
After reproducing the problem, I cannot go to the log tab because the program stops responding.
```

</details>

## Additional context
There is no other context. Except for this problem, the program works perfectly and I love it

**Comment by marticliment** [comment]
Can you please test this release now?

It does not have a library that could potentially cause the crashes:

https://we.tl/t-8AOyJMCSxh

**Comment by mirronake** [comment]
This test release works well, I was able to export the applications without problems, but in Release version 1.7.0 I have problems.

**Comment by gokberkgs** [comment]
Yes, no problem with this version, it can do the export. Also, the log runs in the background as a command line instead of the application window.

**Comment by marticliment** [comment]
WingetUI 1.7.1 has this issue fixed!
