### ISSUE TITLE
[BUG/ISSUE] text cut out start screen

### ISSUE THREAD

**Issue by ppvnf** [marticliment/WingetUI#991]
https://github.com/marticliment/WingetUI/commit/6424762d74c43a3d25047b764088aea822666d50 causes this to me
<img width="470" alt="Screenshot 2023-05-01 150219" src="https://user-images.githubusercontent.com/73800734/235455220-a6d927ac-39e0-41ea-a98d-989f56775488.png">

**Comment by marticliment** [comment]
Move to #971
