### ISSUE TITLE
[BUG/ISSUE] 'Software Updates' and 'Installed Packages' are empty. ( winget-cli\winget.exe is missing from WingetUI's folder )

### ISSUE THREAD

**Issue by darkred** [marticliment/WingetUI#998]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
'Software Updates' and 'Installed Packages' are empty. Also winget-cli\winget.exe is missing from WingetUI's folder.

## To Reproduce
1. Install WingetUI 1.7.1 on win11 x64 (use default settings)
2. Launch WingetUI
3. Switch to either 'Software Updates' or 'Installed Packages' tabs
4. Notice that they are both empty.

## Expected behaviour
Both lists should be populated with available updates and installed packages, just in winget CLI (see screenshots below) .

## Screenshots
<details>
<summary>The two empty tabs, 'Software Updates' and 'Installed Packages':</summary>

![2023-05-03_233546](https://user-images.githubusercontent.com/723651/236043746-248313c5-65b8-42ee-aec8-4bcc551deac4.jpg)
![2023-05-03_233552](https://user-images.githubusercontent.com/723651/236043757-681f1b85-d212-433a-83b4-392766255bb1.jpg)
</details>

<details>
<summary>Output of winget CLI (<code>winget list</code> and <code>winget upgrade</code>)</summary>

[`winget list` (too long to display)](https://user-images.githubusercontent.com/723651/236044504-439ebc27-f42d-44f6-ab69-4169476b7277.jpg)
![2023-05-03_233810](https://user-images.githubusercontent.com/723651/236044556-e129cc56-ffc3-45af-9015-1f3f08bcf82d.jpg)

</details>

## The Log

<details>

```
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0009751319885253906 to load all language files
🟢 checkQueue Thread started!
🔵 Starting main application...
Scanning for instances...
Found lock file(s), reactivating...
🔵 Starting update check
 * Serving Flask app 'WingetUI backend'
 * Debug mode: off
b''
None
updating winget
🔵 Version URL: https://versions.marticliment.com/versions/wingetui.ver
🟢 Updates not found
b'1.2.1\r\n'
None
🔵 Language file up-to-date
Reactivation signal ignored: RaiseWindow_[1683145611.3217254]
🟢 Downloaded latest metadata to local file
🔵 Loaded metadata from local file
{'wingetFound': False, 'scoopFound': False, 'chocoFound': True, 'sudoFound': True, 'wingetVersion': '', 'scoopVersion': 'Scoop is disabled', 'chocoVersion': '1.2.1\r', 'sudoVersion': 'gsudo v2.0.4 (Branch.tags-v2.0.4.Sha.506efa024af0cef6e4b0cfec42e0c8c5d0b1472c)\r'}
🔵 Reached main ui load milestone
🔵 Is Dark
Can't disconnect
🔵 Starting winget search
🔵 Starting choco search
🟢 Discover tab loaded
🟢 Found valid cache for winget!
🔵 Starting winget file update...
🟢 Found valid cache for chocolatey!
Can't disconnect
Can't disconnect
🟢 Starting winget search, winget on C:\Users\Kostas\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\Kostas\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Upgrades tab loaded
Can't disconnect
🟢 Winget cache rebuilt
🟢 Starting winget search, winget on C:\Users\Kostas\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Starting choco search, choco on C:\Users\Kostas\AppData\Local\Programs\WingetUI\choco-cli\choco.exe...
🟢 Discover tab loaded
🟢 Winget uninstallable packages search finished
Can't disconnect
🟢 Settings tab loaded!
🟢 About tab loaded!
🟢 Chocolatey uninstallable packages search finished
🟢 Main application loaded...
🟢 Chocolatey search finished
1
🟢 Starting winget search, winget on C:\Users\Kostas\AppData\Local\Programs\WingetUI\winget-cli\winget.exe...
🟢 Winget search finished
🟢 Total packages: 9234
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Total packages: 0
🟢 Searching for string ""
🟢 Searching for string ""
🟢 Searching for string ""
🟡 Can't get custom interval time! (got value was '')
🟢 Total packages: 0
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
```

</details>

## Additional context
As I see it, the issue is that there's no `winget-cli` folder at all in `C:\Users\Kostas\AppData\Local\Programs\WingetUI` (only a `choco-cli`) :
[WingetUI folder](https://user-images.githubusercontent.com/723651/236045188-a392d122-404b-40c1-8195-de8496a6ef6f.jpg)

Winget for me is installed at `C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.19.10173.0_x64__8wekyb3d8bbwe`:
[winget folder](https://user-images.githubusercontent.com/723651/236045848-75855084-bc94-4817-80f4-15d51abf2fcc.jpg)

So, should I somehow install/copy a separate winget version inside WingetUI's folder?
Also, I'd like to note that WingetUI should warn that it winget-cli\winget.exe is missing.

**Comment by marticliment** [comment]
> As I see it, the issue is that there's no `winget-cli` folder at all in `C:\Users\Kostas\AppData\Local\Programs\WingetUI` (only a `choco-cli`) :
If you install version 1.7.0 and then update, does it get fixed?

**Comment by darkred** [comment]
Yes, that fixes the issue, thank you 👍
So, the latest 1.7.1 installer is missing the winget files.
